### ISSUE TITLE
Ubuntu 18.04 PAM BUG 

### ISSUE THREAD

**Issue by jfrazee216** [neutrinolabs/xrdp#1406] opened 2019-09-06 20:36 UTC
We have discovered that there is a bug with PAM in Ubuntu 18.04 when using xrdp. 

If you kill your xrdp session instead of logging out properly then it registers as a failure in /etc/pam.d/common-auth 

If you do this 5 consecutive times then you lock yourself out.

Our workaround was to change deny=5 to 50000 in /etc/pam.d/common-auth

**Comment by evanlinde** [comment] 2019-09-07 05:36
This may be a duplicate of #262

**Comment by metalefty** [comment] 2019-09-09 01:54
Yes, it is already reported and on the ToDo List.

**Closed** 2023-06-15 09:55 UTC
