### ISSUE TITLE
Make fail if we are in a directory with comma

### ISSUE THREAD

**Issue by antoinetran** [neutrinolabs/xrdp#335] opened 2016-02-25 12:50 UTC
Hi,

I tried to compile xrdp 0.8 branch today. At the make step, it fails because I have a comma in my directory name, at:
gcc -shared  .libs/vnc.o   -Wl,-rpath -Wl,/shared/trana/2015,04,20-xrdp-0.8/xrdp-0.8/common/.libs -Wl,-rpath -Wl,/usr/local/lib/xrdp ../common/.libs/libcommon.so -lcrypto -lssl -lpthread    -Wl,-soname -Wl,libvnc.so.s -o .libs/libvnc.so.0.0.0

There should be quote around the long path, or it will fail asking where is 04 file, in this example.

Thank you.

**Comment by proski** [comment] 2016-02-27 02:42
Quotes won't help. Some other way of passing arguments to the linker would be needed. Just don't compile in such directories. If you have a good reason to use such directories, try talking to libtool developers. The devel branch doesn't use "-rpath", but it still fails in a directory with a comma.

Even if the source needs to be in a directory with a comma, you can build outside the source tree in a directory without a comma, and the build would work.

I would say "WONTFIX".

**Comment by antoinetran** [comment] 2016-02-29 10:04
Hi, you're right. It's just that someone who just follow the README may use comma without knowing this (eg: I used it to put a date 2016,02,29). Maybe this should be put in the README, unless it is a general rule not to use comma when using make.

**Comment by proski** [comment] 2016-02-29 16:45
That really affects every program that uses libtool. Accumulating random facts about other software in xrdp documentation is unlikely to be effective. Those facts can also get out-of-date quickly. I will contact libtool developers about the issue.

**Comment by proski** [comment] 2016-02-29 17:20
It turns out Libtool fixed that issue in version 2.4.3. I guess you are using an older Libtool.

**Comment by proski** [comment] 2016-02-29 19:38
I was able to reproduce the problem even with the latest libtool and even with the current xrdp. So I reported the problem to the libtool maintainers.

**Comment by proski** [comment] 2016-02-29 22:31
Reported: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22857

**Comment by metalefty** [comment] 2016-06-29 08:28
Not an xrdp issue. Reported to upstream.

**Closed by metalefty** 2016-06-29 08:28 UTC
