### ISSUE TITLE
Pasting text from Windows to xrdp session has double line breaks

### ISSUE THREAD

**Issue by jedis00** [neutrinolabs/xrdp#2450] opened 2022-12-07 15:58 UTC
Basically, having the same issue as this SO post: https://superuser.com/questions/1156974/double-new-line-when-copy-to-konsole-on-xrdp

However, the suggested fixes do not work. They break using Enter key on the keyboard when trying to use things like sudo, I cannot hit enter to send my password.

> xrdp 0.9.20

**Comment by matt335672** [comment] 2022-12-08 10:06
Duplicate of #1746.

I'm pretty sure this is a bug on our side rather than anything to do with terminal settings. I've not had the time to look at it yet though.

**Comment by matt335672** [comment] 2023-01-24 09:41
Closing, as a duplicate.

**Closed as completed by matt335672** 2023-01-24 09:41 UTC
