### ISSUE TITLE
lag on password entry

### ISSUE THREAD

**Issue by pwn0r** [neutrinolabs/xrdp#2295] opened 2022-06-28 16:50 UTC
Hi there, I have been using xrdp (different versions) in different linux configurations, both VM and physical, test and production and I'm generally very happy. It does work very well if you know how to configure it 👍 

One thing that drives me nuts though. Whenever it is a debian, or ubuntu, 20.04 or 22.04, physical or VM, when you have to enter a password it is a massive lag.  One VM has a LUKS encrypted partition. Password prompt window generates insane lag, like 10-15 seconds (between typing your password and seeing dots on screen).  Root privileges prompt is less laggy but still takes a few seconds to complete. 

So when having a LUKS partition, I have to enter passwords *three times*. And three times lag (once partition password, and *twice* for your root password, for unknown reason). 

VM specs for example are Debian12, xrdp 0.9.19.1 on gnome but similar stuff happens with any  other setup I have. They all are either debian or ubuntu and running on gnome. So I guess this is a gnome issue? Any workaround for this?

**Comment by matt335672** [comment] 2022-06-28 19:49
Hi @pwn0r 

I'm not following you. Where are you seeing the lag when you enter a password?

**Comment by andreasplesch** [comment] 2022-06-28 22:26
Since I just managed to get xrdp to run on Ubuntu server with xfce4, let me add that both krdc and the windows rdp client let you enter the user and password on the client, and then directly launch into the rdp desktop session without going through the display manager. Assuming the lag occurs logging in from a DM.

**Comment by pwn0r** [comment] 2022-06-29 08:26
> 

Nah, I was not specific enough I guess with my description. 
The password prompt *inside* ubuntu or debian. A GUI prompt to enter your credential.

For starters, I'm attempting a privileged operation in doublecmd.  (like editing a file in /etc/... folder or copying stuff to restricted folders etc). This triggers a GUI prompt like gksudo in the past or something.  This is slow.

However when I want to unlock an encrypted partition, this triggers a password prompt and now it is a whole new level of lag. 
You can type your password and then wait like 10-15 sec *before symbols appear in the prompt window*

**Comment by pwn0r** [comment] 2022-06-29 08:34
> 

The only problem with xrdp login I have is the inability to change keyboard layout :((((( this is a very old issue but not fixed yet. There is zero lag when logging from xrdp window. 

Just in case my normal scenario is using win10 rdp and connecting (usually over WAN) over xrdp directly to VMs or physical machines running ubuntu or debian.  The lag problem is reproducible 100%, independent from which exact version of kernel the machine is running, if it is a physical or virtual, if xrdp is .19, .17 or even .12 (like for 20.04 the latest official release btw), They all run on gnome though, again different versions (like 20.04 on .40 i think, and 22.04 and debian12 on .42 now).

**Comment by matt335672** [comment] 2022-06-29 10:54
That's not something I can reproduce here, and based on the information we have so far it doesn't sound like it can be anything that xrdp is doing either. xrdp is unaware that you're trying to unlock a partition - it just reproduces what's happening on the screen. Also 10-15 seconds is an enormous delay and would be likely to cause the session to drop out.

What tool are you using the enter the LUKS password? Do you get the same delay on the command line?

**Comment by pwn0r** [comment] 2022-06-29 11:18
> That's not something I can reproduce here, and based on the information we have so far it doesn't sound like it can be anything that xrdp is doing either. xrdp is unaware that you're trying to unlock a partition - it just reproduces what's happening on the screen. Also 10-15 seconds is an enormous delay and would be likely to cause the session to drop out.
> 
> What tool are you using the enter the LUKS password? Do you get the same delay on the command line?

Even for VMs I have console access from the host. I.e. I can RDP *to host* and then doing same things in a console session does not cause any serious lag. 

Just restarted that VM to measure more accurately. First password prompt on encrypted partition -- about 8 seconds lag. Then each credential prompt about 4 seconds lag. Again, it is not really something that breaks things, just a serious annoyance. 

I made a screenshot of the password prompt just in case, not entirely correct but good for illustration
and you can see that the rest of the screen is made black, covering all other windows. I think this is the real issue here, such "secure prompt" causes this lag. 

![deb12](https://user-images.githubusercontent.com/19326623/176424678-d9f7ed3e-67b5-46a3-8209-ced80c316fef.png)

**Comment by matt335672** [comment] 2022-06-30 08:46
Are you able to try this with the Xvnc backend instead of Xorg?

**Comment by matt335672** [comment] 2022-09-08 08:55
No more info from OP - closing

**Closed as completed by matt335672** 2022-09-08 08:55 UTC
