### ISSUE TITLE
Authentication dialog not shown when running pi-packages on the Raspberry Pi over RDP

### ISSUE THREAD

**Issue by DMW007** [neutrinolabs/xrdp#2000] opened 2021-09-19 18:35 UTC
Hello,
I'm using xrdp to connect from my main workstation to the Raspberry Pi (RPI 4 Model B). This works well, until I tried to install software using the graphical `pi-packages` interface provided in the Raspberry Pi OS Desktop distribution. After setting a tick on the software I'd like to install, I got a popup to confirm and then nothing happens. The operation (install/uninstall) is not performed, even after waiting some time.

![pi-packages_rdp](https://user-images.githubusercontent.com/21245043/133938557-a8843761-0f94-49ef-af5c-22f0d37eeb96.gif)

First I thought that I was [affected by this bug](https://www.raspberrypi.org/forums/viewtopic.php?t=132620), since the language was set to German. But even with `en_GB` the same behavior. After trying different things out, it seems to be an issue of xrdp: Using physical connected screen + keyboard + mouse, it works well. Here you can see a screenshot without xrdp, after confirming with _OK_ an authentication popup appears (which is never visible using xrdp):

![pi-software_local](https://user-images.githubusercontent.com/21245043/133938709-34b4dd2f-a9f5-4f15-9527-831f014b324b.png)

When running `pi-packages -v` it shows a more verbose log, containing the following entry:

> GnomePackageKit    failed to install packages: Failed to obtain authentication.

This issue only occurs when using `pi-packages` together with `xrdp`. However I cannot say which of those packages needs to fix it.

### More details about the used software/platform
I'm using the latest stable versions avaliable in the RapsberryPi OS repos.

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ xrdp --version
xrdp 0.9.9
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=arm-linux-gnueabihf
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/arm-linux-gnueabihf
      --libexecdir=${prefix}/lib/arm-linux-gnueabihf
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/var/run/xrdp/sockdir
      build_alias=arm-linux-gnueabihf
      CFLAGS=-g -O2 -fdebug-prefix-map=/build/xrdp-q47Nhl/xrdp-0.9.9=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-q47Nhl/xrdp-0.9.9/pkgconfig

  Compiled with OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by matt335672** [comment] 2021-09-20 17:18
Hi @DMW007 

I take it your using Raspbian (based on Debian)?

I believe this is a PolicyKit issue. Because you're running a remote session rather than a local one, PolicyKit is refusing to allow you to do some privileged operations.

I'm running out of time today to give you a complete answer. In short, if this is the case, the fix is to find the 'polkit action' which you need to authorize, and then add a `.pkla` file to authorize the action.

Have a look at #1568 where we work through a similar problem with XFCE. Please come back to me if it doesn't make any sense.

In any case, let us know how you get on.

**Comment by matt335672** [comment] 2021-09-21 08:26
Hi @DMW007 

Please accept my apologies - I've re-read your post with more time on my hands, and I see you've already made it clear you're using Raspbian.

I don't have suitable hardware to hand to reproduce this, but I'll try getting a VM set up this morning using [this repo](https://github.com/dhruvvyas90/qemu-rpi-kernel). I'm hoping I can reproduce this.

**Comment by matt335672** [comment] 2021-09-22 10:57
Having successfully set up a (very slow) emulated PI, I'm unable to reproduce this as reported.

I note however that by default the PI logs the user in on the console. I've disabled that. Maybe that's the reason.

@DMW007 - are you using the same user on the console as on the xrdp session? That's going to cause you problems as this version of Raspbian uses `systemd --user` so the two sessions will collide with each other. I can't say for sure that this is the problem here though.

If that is the case, can I ask you us the PI configuration utility to disable auto login, reboot the PI and try again?

**Comment by matt335672** [comment] 2021-10-07 09:33
No updates for two weeks - closing.

**Closed as completed by matt335672** 2021-10-07 09:33 UTC
