### ISSUE TITLE
error compiling on OS X

### ISSUE THREAD

**Issue by Bllacky** [neutrinolabs/xrdp#243] opened 2015-05-21 20:02 UTC
Not sure if I misconfigured something or it's something wrong with the code.
Feel free to close it, if you consider so.

I am trying to build xrdp-devel on OS X 10.10 using MacPorts.
This error is not present on 0.8.0 release version.

Basically on make, I get this:

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in common
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_LOG_PATH=\"/var/log\" -m32 -mmacosx-version-min=10.6 -MT os_calls.lo -MD -MP -MF .deps/os_calls.Tpo -c -o os_calls.lo os_calls.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_LOG_PATH=\"/var/log\" -m32 -mmacosx-version-min=10.6 -MT os_calls.lo -MD -MP -MF .deps/os_calls.Tpo -c os_calls.c  -fno-common -DPIC -o .libs/os_calls.o
os_calls.c:2981:12: error: expected expression
    environ[0] = 0;
           ^
1 error generated.
make[2]: **\* [os_calls.lo] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

**Comment by Bllacky** [comment] 2015-05-21 21:12
Figured it's because I added this recommended patch:
Code:
--- ../xrdp-v0.6.0/common/os_calls.c 2012-02-21 11:00:55.000000000 -0800
+++ ../xrdp-environ/common/os_calls.c 2014-08-17 23:54:53.000000000 -0700
@@ -67,6 +67,9 @@

/* for clearenv() */
#if defined(_WIN32)
+#elif __APPLE__
+#include <crt_externs.h>
+#define environ *_NSGetEnviron();
#else
extern char** environ;
#endif
@@ -2113,7 +2116,7 @@
void APP_CC
g_clearenv(void)
{
-#if defined(_WIN32)
+#if defined(_WIN32) || defined(__APPLE__)
#else
environ = 0;
#endif

**Comment by Cyclic** [comment] 2015-05-24 16:27
@Bllacky do you have a fork somewhere to test/debug?

**Comment by Bllacky** [comment] 2015-05-24 20:57
No, but I can try and make on. Do you think that might be helpful ?

**Comment by Bllacky** [comment] 2015-06-02 20:58
I have made a fork here, will soon add the changes to it:
https://github.com/Bllacky/xrdp/tree/OSX

**Comment by Bllacky** [comment] 2015-06-02 22:12
This is version of devel branch that will compile. But make install still fails with:
https://github.com/Bllacky/xrdp/tree/OSX

chmod 755 /etc/xrdp/xrdp.sh
if [ -f /etc/init.d/xrdp ]; then \
		chmod 755 /etc/init.d/xrdp; \
		sed -i 's|__BASE__|/usr|' /etc/init.d/xrdp; \
	fi
sed: 1: "/etc/init.d/xrdp": command i expects \ followed by text

**Comment by metalefty** [comment] 2015-06-03 00:16
OS X have BSD sed, not GNU sed. We have to be aware of differences between two sed implementations. 

Please see also:
https://github.com/metalefty/xrdp/blob/freebsd/instfiles/instfiles/Makefile.am

**Comment by Bllacky** [comment] 2015-06-18 20:09
Thank you metalefty.

I used your repo to build a OS X version of XRDP. 
After some tinkering, compilation and installation went through.

The service is up and running and allows me to connect, but I am unable to login into XRDP.

Console reports:
<CODE>18/06/15 23:04:29,195 XRDP-sesman[40899]: in openpam_read_chain(): /etc/pam.d/xrdp-sesman(2): invalid facility '@include' (ignored)

18/06/15 23:05:05,238 XRDP-sesman[40899]: in openpam_read_chain(): /etc/pam.d/xrdp-sesman(2): invalid facility '@include' (ignored)
</CODE>

**Comment by metalefty** [comment] 2015-06-19 00:12
Yes, authentication system in OS X a little different from FreeBSD. It may fails.  Could you please try remove `pam.d/xrdp-sesman` and make a symbolic link to `pam.d/sshd` like this? I haven't confirmed but I think it works.

```
yourosx$  (cd /etc/pam.d; rm -f xrdp-sesman && ln -s sshd xrdp-sesman)
```

I'm working on merging fixes for BSDs (also yours) to upstream neutrinolabs devel branch.  However, my work is sometimes helpful for OS X but  not always since I specially looking at FreeBSD.

Please see also  my post in mailing list:
http://sourceforge.net/p/xrdp/mailman/message/34220409/


I have no ideas for `libvnc.dylib` now.

**Comment by Bllacky** [comment] 2015-06-25 20:29
Thank you very much metalefty.

The above link worked great, unfortunately is not enough.

<code>
Jun 25 23:16:45 Mac.local sudo[3890]:   Silviu : TTY=ttys000 ; PWD=/private/etc/xrdp ; USER=root ; COMMAND=/bin/bash xrdp.sh
Jun 25 23:16:45 Mac.local XRDP-sesman[3902]: (3902)(-1604337196)[WARN ] [init:46] libscp initialized
Jun 25 23:16:45 Mac.local XRDP-sesman[3903]: (3903)(-1604337196)[CORE ] starting sesman with pid 3903
Jun 25 23:16:55 Mac.local opendirectoryd[73]: MIG demux failed. This message ID is invalid: 0x76
Jun 25 23:17:05 --- last message repeated 20 times ---
Jun 25 23:17:05 Mac.local XRDP-sesman[3906]: (3906)(-1604337196)[ERROR] X server for display 10 startup timeout
Jun 25 23:17:05 Mac.local XRDP-sesman[3905]: (3905)(-1604337196)[ERROR] X server for display 10 startup timeout
Jun 25 23:17:05 Mac.local opendirectoryd[73]: MIG demux failed. This message ID is invalid: 0x76
Jun 25 23:17:35 --- last message repeated 1 time ---
</code>

It seems it is now passing the login phase, but it doesn't initialise the connection with the desktop environment. I have no idea why...

I would gladly reply to your letter if I knew how.

Thing is, there are lots of softwares to connect from OS X to Windows or Linux desktops, but only one for Windows to OS x (which is ridiculously expensive).

I use xrdp and SSH for my Linux environments and it works absolutely great. So I am trying to make a working version of xrdp for OS X. There is one here, but it's outdated and works very very slow: http://forums.macrumors.com/threads/how-to-control-your-mac-using-win-rdp-client-xrdp-compiling-guide-on-osx.1770325/

**Comment by Bllacky** [comment] 2015-06-25 20:41
I think this might be a lot more helpful:

<code>

[20150625-23:16:55] [INFO ] starting Xvnc session...
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 8
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: 127.0.0.1:56916 - socket: 7
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 8
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 7
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 6
[20150625-23:16:55] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 7
[20150625-23:16:55] [ERROR] env_set_user: error creating .vnc dir
[20150625-23:16:55] [INFO ] Xvnc :10 -geometry 1920x1200 -depth 16 -rfbauth /Users/Silviu/.vnc/sesman_Silviu_passwd -bs -ac -nolisten tcp -localhost -dpi 96  
[20150625-23:16:55] [CORE ] error starting X server - user Silviu - pid 3907
[20150625-23:16:55] [DEBUG] errno: 2, description: No such file or directory
[20150625-23:16:55] [DEBUG] execve parameter list size: 16
[20150625-23:16:55] [DEBUG]         argv[0] = Xvnc
[20150625-23:16:55] [DEBUG]         argv[1] = :10
[20150625-23:16:55] [DEBUG]         argv[2] = -geometry
[20150625-23:16:55] [DEBUG]         argv[3] = 1920x1200
[20150625-23:16:55] [DEBUG]         argv[4] = -depth
[20150625-23:16:55] [DEBUG]         argv[5] = 16
[20150625-23:16:55] [DEBUG]         argv[6] = -rfbauth
[20150625-23:16:55] [DEBUG]         argv[7] = /Users/Silviu/.vnc/sesman_Silviu_passwd
[20150625-23:16:55] [DEBUG]         argv[8] = -bs
[20150625-23:16:55] [DEBUG]         argv[9] = -ac
[20150625-23:16:55] [DEBUG]         argv[10] = -nolisten
[20150625-23:16:55] [DEBUG]         argv[11] = tcp
[20150625-23:16:55] [DEBUG]         argv[12] = -localhost
[20150625-23:16:55] [DEBUG]         argv[13] = -dpi
[20150625-23:16:55] [DEBUG]         argv[14] = 96
[20150625-23:16:55] [DEBUG]         argv[15] = (null)
[20150625-23:17:05] [ERROR] X server for display 10 startup timeout
[20150625-23:17:05] [ERROR] X server for display 10 startup timeout
[20150625-23:17:05] [INFO ] starting xrdp-sessvc - xpid=3907 - wmpid=3906
[20150625-23:17:05] [ERROR] another Xserver might already be active on display 10 - see log
[20150625-23:17:05] [DEBUG] aborting connection...
[20150625-23:17:10] [INFO ] A connection received from: 127.0.0.1 port 56917
[20150625-23:17:10] [INFO ] scp thread on sck 7 started successfully
[20150625-23:17:10] [INFO ] ++ reconnected session: username Silviu, display :10.0, session_pid 3905, ip 192.168.254.206:53678 - socket: 8
[20150625-23:17:10] [INFO ] An established connection closed to endpoint: 127.0.0.1:56917 - socket: 7
[20150625-23:40:19] [INFO ] A connection received from: 127.0.0.1 port 57406
[20150625-23:40:19] [INFO ] scp thread on sck 7 started successfully

</code>

**Comment by metalefty** [comment] 2015-06-26 00:38
Don't worry.  Nothing's going wrong.  It is almost working!  Let's see your xrdp source directory and execute `sesman/tools/xrdp-sestest`.   Now you should be able to authenticate.

```
[20150626-09:35:52] [WARN ] [init:46] libscp initialized
001 - send connect request
ERR: resend credentials - Wrong username and/or password
     username:
```

**Comment by metalefty** [comment] 2015-06-26 00:45
```
[20150625-23:16:55] [INFO ] Xvnc :10 -geometry 1920x1200 -depth 16 -rfbauth /Users/Silviu/.vnc/sesman_Silviu_passwd -bs -ac -nolisten tcp -localhost -dpi 96

[20150625-23:16:55] [CORE ] error starting X server - user Silviu - pid 3907
[20150625-23:16:55] [DEBUG] errno: 2, description: No such file or directory
```

Ah, at your latter post, the problem is quite simple.  You just forget to install VNC or xrdp couldn't find the VNC. If you want to use VNC backend, never forget to install VNC.  There's a lot of variants, RealVNC, TigerVNC, TightVNC, and more.  Whatever is OK if it has Xvnc.

If you could solve the issue, please don't delete your fork of xrdp.  I'll look at it and merge OS X specific changes after you solve the issue.

**Comment by Bllacky** [comment] 2015-06-26 20:06
OS X comes with a standard VNC server: http://coolestguidesontheplanet.com/connect-2-macs-using-vnc-os-x-screen-sharing/

So probably xrdp has trouble to connect to OS X native VNC server. I will need to investigate further.

**Comment by Bllacky** [comment] 2015-06-26 20:31
Maybe it's related to the fact that the folder it's trying to create is .vnc - OS X as far as I know doesn't accept the creation of folders with a dot in front.

**Comment by Bllacky** [comment] 2015-06-27 10:13
<b>SUCCESS!</b>

There seems to be a pathing issue with xrdp. Not sure why.

In xrdp.ini
Found in /etc/xrdp/

You need to set:
[global]
max_bpp=24

for the connection you need to change in xrdp.ini the first entry to

[xrdp1]
name=sesman-Xvnc
lib=libvnc.0.dylib
username=na
password=<Remote Management password you set on the native OS X VNC server> 
ip=127.0.0.1
port=5900

Now, you need to go to 
/usr/lib/xrdp and copy

libvnc.0.dylib

to /usr/lib

start xrdp from /etc/xrdp with
sudo bash xrdp.sh

enjoy!

My problem was that I've set 

lib=/usr/lib/xrdp/libvnc.0.dylib
and for some reason, xrdp couldn't access the files from that folder... strange.

**Comment by metalefty** [comment] 2015-06-28 15:49
> OS X comes with a standard VNC server

That's exactly true but I thought you don't want to use OSX's VNC because you were trying to use Xvnc. Your log says.


```

```

**Comment by metalefty** [comment] 2015-06-28 15:54
```
[20150625-23:16:55] [DEBUG] errno: 2, description: No such file or directory
[20150625-23:16:55] [DEBUG] execve parameter list size: 16
[20150625-23:16:55] [DEBUG] argv[0] = Xvnc
```

This means xrdp couldn't find Xvnc executable in your PATH and you're trying to use Xvnc. 
If you want to connect to OSX VNC, you should use vnc-any instead of Xvnc-sesman.  Anyway, it seems you're already enjoying xrdp. Good work.

**Comment by Bllacky** [comment] 2015-06-28 19:37
That is correct. It was a problem from my settings in xrdp.ini .
Thank you

@metalefty If you do incorporate my changes in your version, let me know so I can test it.

Thank you very much for you help and support.

---> This reply was written on OS X via xrdp connection from Windows 8.1. :-)

**Comment by zchinac** [comment] 2015-10-23 06:04
Hi @Bllacky, 

Thanks for the great work. I used your repo https://github.com/Bllacky/xrdp/tree/OSX and I was able to build and start xrdp on Mac. But I encountered a few problems and wondering if you saw the same thing. 

1) cannot contro the mouse after connecting to mac vnc... I am stuck on login screen. (biggest issue)
2) cannot restart xrdp with xrdp.sh (have to kill process and restart)
3) xrdp creates multiple instances and takes 99% of the cpu. (makes my fan loud... )

Have you seen any of these issues? Do you have any update on your repo or should I use @metalefty 's repo? 

Thank!

**Comment by Bllacky** [comment] 2015-10-23 07:14
1) I sometimes have this issue, but I just need to hit the keyboard (enter , or some other key ) and then the mouse comes up
2) I can restart the process, I never had an issue
3) I never had this issue either

Yes, I should make some updates to that repo, but I have been very busy lately and I couldn't find the time to deal with this project.

**Comment by zchinac** [comment] 2015-10-26 06:57
@Bllacky  i got it compiled and working based on xrdp 0.8. But some times I have to tried multiple (3 -4 )times to get to the Mac login screen. Dont know why... do you have this issue?

Also, it is hard to tell if there improvement (in terms of latency) on 0.8 compare to 0.6.  Maybe I am missing some configuration.

**Comment by StSimmons** [comment] 2016-02-21 00:47
@metalefty - has the latest OSX support made its way over to this repo. Or is it best to use @Bllacky repo?

**Comment by metalefty** [comment] 2016-02-22 01:15
I think It is still best to use bllacky's repo.

**Comment by proski** [comment] 2016-12-29 18:56
Can we close this issue? I see it's drifting from one actual issue to another. Mac OS is still not supported, but it's better to have small well defined issues that can be resolved.

**Comment by moobyfr** [comment] 2016-12-29 21:02
currently xrdp, xorgxrdp and X11rdp are building on latest OSX. But xorgxrdp and X11rdp don't work on OSX (can't open framebuffer) I didn't have time to test Xvnc.

**Comment by proski** [comment] 2016-12-29 22:44
I haven't had success with xorgxrdp or Xvnc (x11vnc). X11rdp did not compile last time I tried. The PAM files installed by default is wrong. But those are separate issues. We can have a master ticket (fix Mac OS) and simple resolvable issues.

**Comment by Vraiment** [comment] 2018-02-01 08:15
pull request #1021 adds PAM for Mac OS

**Comment by metalefty** [comment] 2018-03-22 06:54
This issue seems to be solved by Vraiment's effort.

**Closed by metalefty** 2018-03-22 06:54 UTC
Labels: compiling
