### ISSUE TITLE
RDP sessions opened with xrdp are not listed in system tools like `who`

### ISSUE THREAD

**Issue by pktiuk** [neutrinolabs/xrdp#2676] opened 2023-05-16 10:13 UTC
I would like to have universal way of checking list of active sessions on my machine and I use universal linux tools to track it.
I use [cockpit](cockpit-project.org/) and `who` commandline utility. None of these lists sessions opened via xrdp.

I guess something is wrong with initializing sessions.

I opened similar issue in cockpit repository: https://github.com/cockpit-project/cockpit/issues/18810

**Comment by matt335672** [comment] 2023-05-16 10:33
Can you tell us what your OS is?

I'm pretty sure this is a duplicate of #1302

**Comment by pktiuk** [comment] 2023-05-16 10:41
Ubuntu 22.04

**Comment by pktiuk** [comment] 2023-05-17 08:40
@matt335672  
so, it this issue a duplicate or not?    
Could I help you with solving this issue in any way? (I can provide additional logs and test it also on Ubuntu 20.04)

**Comment by matt335672** [comment] 2023-05-17 10:22
Yes it is.

For `who` to work, you need the something to update `/var/run/utmp`. This functionality doesn't seem to be available via a Linux PAM module at present. There's an interesting comment in the [Wikipedia entry for utmp](https://en.wikipedia.org/wiki/Utmp):-

> These files are not set by any given [PAM](https://en.wikipedia.org/wiki/Pluggable_authentication_module) module (such as pam_unix.so or pam_sss.so) but are set by the application performing the operation (e.g. min[getty](https://en.wikipedia.org/wiki/Getty_(Unix)), /bin/login, or sshd). As such it is the obligation of the program itself to record the utmp information.

I'm not sure how true this is in general - on FreeBSD I think PAM does do this.

The good news is that now we've re-architected sesman in devel, adding support for these should be quite easy. This isn't going to be back-ported to v0.9.x however.

**Comment by pktiuk** [comment] 2023-05-17 11:23
> The good news is that now we've re-architected sesman in devel, adding support for these should be quite easy. This isn't going to be back-ported to v0.9.x however

I'm fine with that. I just hope it fixed version will be available in Ubuntu 24.04 :)

**Comment by akarl10** [comment] 2023-05-22 14:24
@pktiuk if all you want to know is who is logged in (and not really more) maybe `loginctl list-sessions` is a `who` alternative for you.

Of course this will not solve the issue that cockpit does not show the last login

**Comment by matt335672** [comment] 2023-05-31 10:24
Closing as a duplicate of #1302

**Closed as completed by matt335672** 2023-05-31 10:24 UTC
