### ISSUE TITLE
Repeated Error Messages Following RH7 to RH8 Upgrade Despite Applicaiton Working Fine  

### ISSUE THREAD

**Issue by CossyCosmas** [neutrinolabs/xrdp#2505] opened 2023-01-17 13:08 UTC
We have recently upgraded our server from Red Hat 7 to Red Hat 8 and at the same time upgraded xrdp from: 0.9.13-2.el7.x86_64 to 0.9.20-1.el8.x86_64. 

The application is working fine but we are seeing lots of repeated errors in the logs: 
 
[root@f2f94009e19a2 crash]# tail  -30 /var/log/xrdp.log
[20230117-13:00:11] [ERROR] libxrdp_force_read: header read error
[20230117-13:00:11] [ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
[20230117-13:00:11] [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed
[20230117-13:00:11] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230117-13:00:11] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230117-13:00:11] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20230117-13:00:11] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

Is this anything to be concerned about? Should we do something to resolve the issue that appears to exist with this o/s / xrdp version combination? 

Any advice appreciated. 

Thank you. 

Ps. The errors occur every 10 seconds...

[root@-i06f5e2f1741fd12ca ~]# journalctl | grep -i "DisconnectProviderUltimatum failed"
Jan 18 12:50:50 -i06f5e2f1741fd12ca xrdp[15162]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:00 -i06f5e2f1741fd12ca xrdp[15163]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:10 -i06f5e2f1741fd12ca xrdp[15174]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:20 -i06f5e2f1741fd12ca xrdp[15176]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:30 -i06f5e2f1741fd12ca xrdp[15180]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:40 -i06f5e2f1741fd12ca xrdp[15182]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:51:50 -i06f5e2f1741fd12ca xrdp[15183]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:00 -i06f5e2f1741fd12ca xrdp[15184]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:10 -i06f5e2f1741fd12ca xrdp[15193]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:20 -i06f5e2f1741fd12ca xrdp[15353]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:30 -i06f5e2f1741fd12ca xrdp[15355]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:40 -i06f5e2f1741fd12ca xrdp[15361]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:52:50 -i06f5e2f1741fd12ca xrdp[15398]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 18 12:53:00 -i06f5e2f1741fd12ca xrdp[15401]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

**Comment by pavkamlc** [comment] 2023-01-17 17:21
I've the some problem on Rocky8.7. Errors in log occurs about 1-3x per second. It occurs if I'm logged in or not.
Every second is logged from another xrdp process with new PID.

Jan 17 18:24:00 terminal2 xrdp[4803]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Jan 17 18:24:00 terminal2 xrdp[4803]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jan 17 18:24:00 terminal2 xrdp[4803]: [INFO ] Security protocol: configured [RDP], requested [SSL|HYBRID|RDP], selected [RDP]
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] libxrdp_force_read: header read error
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] Processing [ITU-T T.125] Connect-Initial failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] [MCS Connection Sequence] receive connection request failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Jan 17 18:24:00 terminal2 xrdp[4803]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
Jan 17 18:24:00 terminal2 xrdp[1287]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:109.105.43.107 port 54039
Jan 17 18:24:00 terminal2 xrdp[4804]: [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
Jan 17 18:24:00 terminal2 xrdp[4804]: [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
Jan 17 18:24:00 terminal2 xrdp[4804]: [INFO ] Security protocol: configured [RDP], requested [SSL|HYBRID|RDP], selected [RDP]
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] libxrdp_force_read: header read error
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] Processing [ITU-T T.125] Connect-Initial failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] [MCS Connection Sequence] receive connection request failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Jan 17 18:24:00 terminal2 xrdp[4804]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

**Comment by matt335672** [comment] 2023-01-18 14:23
You'll get this sequence every time something connects to and disconnects from TCP port 3389:-

```
... connection received from ...
. . .
Sending [ITU T.125] DisconnectProviderUltimatum failed
```

We're already aware of this - see #2040.

Regular appearances of this message either indicate a lot of clients, or that you're being port-scanned. The IP addresses in the first message will let you determine who is trying to connect.

If you're exposing xrdp directly to the Internet on its default port this is inevitable. **Don't do this!** Use a VPN to provide an additional layer of security before getting to xrdp.

**Comment by CossyCosmas** [comment] 2023-01-18 14:46
Ours is a:
- Very tightly locked down PCI DSS environment with almost no Internet connectivity
- Scans only performed during specific intervals, so not all the time
- A single user applicaiton so not many clients. 

The ip address is what appears to be an ip v6 ip address relating to local host...

Jan 18 14:42:00 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 36844
Jan 18 14:42:10 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 56626
Jan 18 14:42:20 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 58246
Jan 18 14:42:30 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 38626
Jan 18 14:42:40 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 38520
Jan 18 14:42:50 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 59364
Jan 18 14:43:00 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 40936
Jan 18 14:43:10 5e2f1741fd12ca xrdp[12489]: [INFO ] Socket 12: AF_INET6 connection received from ::ffff:127.0.0.1 port 34052

**Comment by matt335672** [comment] 2023-01-18 14:58
The log is saying you've got a process local to the machine which is making connections to port 3389.

Have you got some sort of heartbeat monitoring script setup for xrdp?

**Comment by CossyCosmas** [comment] 2023-01-18 15:03
Correct!  :)

We use Terraform's Consul for service discovery & registration. 

[root@5e2f1741fd12ca consul]# cat service_xxxxx.json
{
  "service": {
    "checks": [
      {
        "interval": "10s",
        "tcp": "localhost:3389",
        "timeout": "2s"
      }
    ],
    "enable_tag_override": false,
    "id": "xxxxxx",
    "name": "xxxxxx",
    "port": 3389,
    "tags": [
      "envname-xxxxxx",
      "service-xxxxxx"
    ]
  }
}

Does this mean that we cannot monitor the service?   :(

**Comment by matt335672** [comment] 2023-01-18 15:32
That, then is the source of your log messages, and nothing to worry about.

@pavkamlc - let us know what you find related to your errors.

**Comment by CossyCosmas** [comment] 2023-01-18 15:37
Excellent, thanks for clarifying the situation, appreciate it. 
Would it be worth scaling down the message from an 'ERROR' to a 'WARNING'?
I guess that would be more appropriate as there is no 'error' in our scenario.

**Comment by matt335672** [comment] 2023-01-18 15:42
That's the point of #2040 as an 'Enhancement'.

Because of the complexity of the call stack in this area, sadly it's not a one-liner to fix it. We'll get to it at some stage. I'll update #2040 with a reference to what you're doing.

**Comment by matt335672** [comment] 2023-01-24 09:38
Closing as duplicate of #2040

**Closed as completed** 2023-01-24 09:38 UTC
