### ISSUE TITLE
Login failed while connecting window desktop through RDP to  Ubuntu desktop

### ISSUE THREAD

**Issue by indiaweblab** [neutrinolabs/xrdp#891] opened 2017-09-27 10:10 UTC
```
[20170927-15:34:27] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55210
[20170927-15:34:27] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:27] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:27] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:27] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:27] [DEBUG] Security layer: requested 11, selected 0
[20170927-15:34:27] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:27] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55212
[20170927-15:34:27] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:27] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:27] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:27] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:34:27] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:27] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:27] [DEBUG] Security layer: requested 0, selected 0
[20170927-15:34:28] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:28] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:28] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:34:31] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55214
[20170927-15:34:31] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:31] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:31] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:31] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:31] [DEBUG] Security layer: requested 11, selected 0
[20170927-15:34:31] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:31] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55215
[20170927-15:34:31] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:31] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:31] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:31] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:34:31] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:31] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:31] [DEBUG] Security layer: requested 0, selected 0
[20170927-15:34:31] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:31] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:31] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:34:41] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55216
[20170927-15:34:42] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:42] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:42] [DEBUG] Security layer: requested 11, selected 0
[20170927-15:34:42] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:42] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55217
[20170927-15:34:42] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:42] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:42] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:34:42] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:34:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:34:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:34:42] [DEBUG] Security layer: requested 0, selected 0
[20170927-15:34:42] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:34:42] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:34:42] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:35:04] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55220
[20170927-15:35:04] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:04] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:35:05] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:35:05] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:35:05] [DEBUG] Security layer: requested 11, selected 0
[20170927-15:35:05] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:35:05] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55221
[20170927-15:35:05] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:05] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:05] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:35:05] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:35:05] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:35:05] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:35:05] [DEBUG] Security layer: requested 0, selected 0
[20170927-15:35:05] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:35:05] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:05] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:35:08] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55223
[20170927-15:35:08] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:08] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:35:08] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:35:08] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:35:08] [DEBUG] Security layer: requested 11, selected 0
[20170927-15:35:08] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:35:08] [INFO ] A connection received from: ::ffff:192.168.0.6 port 55225
[20170927-15:35:08] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:08] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:08] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20170927-15:35:08] [ERROR] Listening socket is in wrong state, terminating listener
[20170927-15:35:08] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20170927-15:35:08] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20170927-15:35:08] [DEBUG] Security layer: requested 0, selected 0
[20170927-15:35:08] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions)
[20170927-15:35:08] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.0.5 port 3389)
[20170927-15:35:08] [ERROR] Listening socket is in wrong state, terminating listener
```

**Comment by metalefty** [comment] 2017-09-27 14:02
Here.

> [20170927-15:35:08] [CORE ] XRDP cannot read file: /etc/xrdp/rsakeys.ini (check permissions

**Comment by metalefty** [comment] 2017-10-11 01:41
The root cause is clear, no feedback from the reporter, closing.

**Closed by metalefty** 2017-10-11 01:41 UTC
Labels: waiting-feedback
