### ISSUE TITLE
xrdp memory growth is particularly fast when using VPN proxies

### ISSUE THREAD

**Issue by limenghui614** [neutrinolabs/xrdp#1608] opened 2020-06-17 01:55 UTC
Hi,
Memory has been growing rapidly with VPNS, especially for batch operations or video playback.

**Comment by metalefty** [comment] 2020-06-17 02:53
I don't think VPNs matter but can you confirm it reproduces also without VPN?

**Comment by limenghui614** [comment] 2020-06-17 02:56
I can confirm that the memory is stable without VPN

**Comment by matt335672** [comment] 2020-08-07 17:42
Possibly a duplicate of #1634

**Closed** 2020-11-17 09:31 UTC
Labels: duplicate, question or troubleshoot
