### ISSUE TITLE
Updating Kali linux to xrdp 0.9.17.1 breaks rdp

### ISSUE THREAD

**Issue by hiddengearz** [neutrinolabs/xrdp#2025] opened 2021-10-19 03:17 UTC
## Sumamry

If I update XRDP on my Kali linux VM I can no longer connect to the VM through the Hyper-v console in enhanced mode or via RDP (standard windows RDP client or Microsoft store RDP client).

## Specs
Windows 7 Pro Hyper V

```
cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.3"
VERSION_ID="2021.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/


uname -a
Linux Kryptonite 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux
```

## Description

If I update xrdp via `sudo apt-get install xrdp=0.9.17-1` or `sudo apt-get update && sudo apt-get upgrade -y `

The XRDP server is restarted and I'm brought to the xorg login page with the teal background. Once I enter my credentials the session just closes, this happens with the Hyper-V console in enchanced mode, the standard windows RDP client and the new Microsoft store RDP client. 

#### if I start in recovery mode this issue goes away!!!

Edit: It actually started working for a bit after i restarted the VM for like the 10th time but stopped working after i disconnected and reconnected to the VM a few times.

## Before updating
```
sudo apt-cache policy xrdp   

xrdp:
  Installed: 0.9.12-1.1
  Candidate: 0.9.17-1
  Version table:
     0.9.17-1 500
        500 http://http.kali.org/kali kali-rolling/main amd64 Packages
 *** 0.9.12-1.1 100
        100 /var/lib/dpkg/status


sudo apt list xrdp -a
Listing... Done
xrdp/kali-rolling 0.9.17-1 amd64 [upgradable from: 0.9.12-1.1]
xrdp/now 0.9.12-1.1 amd64 [installed,upgradable to: 0.9.17-1]

xrdp/kali-rolling 0.9.17-1 i386
```

## After updating

```
sudo apt-cache policy xrdp
xrdp:
  Installed: 0.9.17-1
  Candidate: 0.9.17-1
  Version table:
 *** 0.9.17-1 500
        500 http://http.kali.org/kali kali-rolling/main amd64 Packages
        100 /var/lib/dpkg/status

sudo apt list xrdp -a
Listing... Done
xrdp/kali-rolling,now 0.9.17-1 amd64 [installed]

xrdp/kali-rolling 0.9.17-1 i386
```
[.xorgxrdp.1.log](https://pastebin.com/nM2Ed45y)
[.xorgxrdp.2.log](https://pastebin.com/gtYKEACB)
[.xsession-errors](https://pastebin.com/0WFXXGXN)
[xrdp-sesman.log](https://pastebin.com/bz8TqnS9)
[xrdp.log](https://pastebin.com/zjZDw0eS)

A similar issue was described here in #1881

**Comment by matt335672** [comment] 2021-10-19 08:27
From your xrdp-sesman.log:-

```
[20211018-23:09:27] [WARN ] Window manager (pid 2755, display 2) exited with non-zero exit code 255 and signal 11. This could indicate a window manager config problem
[20211018-23:09:27] [WARN ] Window manager (pid 2755, display 2) exited quickly (1 secs). This could indicate a window manager config problem
```

Your .xsession-errors file above does not appear to be readable. Can you repost it? Also, straight after the error occurs, what is the output of `sudo journalctl -S -1m`

**Comment by hiddengearz** [comment] 2021-10-19 19:29
I uploaded [.xsession-errors.old](https://pastebin.com/NwuxRVHw) as the issue seems to fix itself when I restart the VM now so there are only errors present in the .old file. I now need to connect, disconnect, resize and etc a bunch before it stops working as described in OP.

Here is [sudo journalctl -S -1m](https://pastebin.com/nm7P0cwh), not sure how relevant it will be since it's only showing details from the last few minutes.

**Comment by matt335672** [comment] 2021-10-20 09:01
I'm getting a 404 on your uploaded file I'm afraid.

Also I need the journalctl output straight after the error occurs or, as you rightly say, it won't have anything useful in it.

**Comment by hiddengearz** [comment] 2021-10-20 21:46
[xsession-errors.old.txt](https://github.com/neutrinolabs/xrdp/files/7384522/xsession-errors.old.txt)

I'll try to reproduce the error and upload the ` sudo journalctl -S -1m`

**Comment by matt335672** [comment] 2021-10-21 09:25
I can read that file - thanks.

In general it's better to attach files to the issue so other users can find it in the future.

Looking at your file, I can see a potential issue around line 39:-

```
/usr/bin/x-session-manager: X server already running on display :0
xfce4-session-Message: 11:29:46.424: SSH authentication agent is already running
gpg-agent: a gpg-agent is already running - not starting a new one

(xfwm4:1360): Gtk-WARNING **: 11:29:46.583: cannot open display: :0
```

Can you edit `/etc/xrdp/sesman.ini` and check `X11DisplayOffset` is set to 10? That's the default value and it gives a useful space between any physical X servers and the virtual ones.

**Comment by hiddengearz** [comment] 2021-10-23 02:50
`Can you edit /etc/xrdp/sesman.ini and check X11DisplayOffset is set to 10? That's the default value and it gives a useful space between any physical X servers and the virtual ones.`

I did this and it instantly recreated the error from the OP. In this example it happened when I changed `X11DisplayOffset` to 11 but it also occurred with 10.

[xorgxrdp.11.log.txt](https://github.com/neutrinolabs/xrdp/files/7402158/xorgxrdp.11.log.txt)
[xrdp.log.txt](https://github.com/neutrinolabs/xrdp/files/7402159/xrdp.log.txt)
[xrdp-sesman.log.txt](https://github.com/neutrinolabs/xrdp/files/7402160/xrdp-sesman.log.txt)
[xsession-errors.old.txt](https://github.com/neutrinolabs/xrdp/files/7402161/xsession-errors.old.txt)
[xsession-errors.txt](https://github.com/neutrinolabs/xrdp/files/7402162/xsession-errors.txt)
[journalctl.txt](https://github.com/neutrinolabs/xrdp/files/7402163/journalctl.txt)
[xorgxrdp.11.log.old.txt](https://github.com/neutrinolabs/xrdp/files/7402164/xorgxrdp.11.log.old.txt)

**Comment by matt335672** [comment] 2021-10-25 08:49
Thanks.

Those files all look relatively OK. You've still got logins on display 0 and display 11 mixed in `.xsession-errors` which leads me to suspect you might be using the same user to log in to the X11 console and over XRDP. Is that the case?

There's a limitation with modern systems which use `systemd --user` (which Kali certainly does), in that a user can only be logged in to one graphical session at once. That's because the environment maintained by `systemd --user` can only store one DISPLAY variable.  It's a limitation which can't be worked around by us I'm afraid.

Are you logging in to the console and xrdp at the same time with the same user?

**Comment by matt335672** [comment] 2021-11-03 09:26
@hiddengearz - have you gotten any further with this?

Thanks,

**Comment by hiddengearz** [comment] 2021-11-03 19:11
@matt335672 I haven't had the issue since.

`Are you logging in to the console and xrdp at the same time with the same user?`

Yes but usually it will kill the previous session. For example I will often be on my desktop using the hyper-v console and then later RDP via my laptop. The hyperv console would be disconnected, this is what's happening now with no issue.

I think the issue may of appeared when I did it frequently between hyperv on desktop, rdp on desktop and rdp on my laptop.

**Comment by matt335672** [comment] 2021-11-04 10:16
I wouldn't depend on that behaviour - it's not defined by us. On my 20.04 machine I can't log the console in if rdp is active on the same user, but that's because the session ends very quickly. It also pollutes the `systemd --user` environment and breaks my rdp session!

The best-practice recommendation is to use separate users for rdp and console sessions on systemd-enabled distributions. There are a number of mechanisms you can use to enforce this.

One of them is to enable `[Security]/AlwaysGroupCheck` in `/etc/xrdp/sesman.ini` and add your RDP users to the group specified by `[Security]/TerminalServerUsers`. Only these users will be allowed to log in over RDP. That doesn't prevent the same users logging in on the console though.

**Comment by matt335672** [comment] 2021-11-15 12:05
I'm closing this now. Feel free to re-open it if you manage to reproduce it.

**Closed as completed by matt335672** 2021-11-15 12:05 UTC
