### ISSUE TITLE
win11h2 bug causes unusual behavior

### ISSUE THREAD

**Issue by MichaelMKKelly** [neutrinolabs/xrdp#2388] opened 2022-10-09 13:05 UTC
the current mstsc bug introduced with win11h2 (https://pureinfotech.com/windows-11-22h2-bug-remote-desktop/) caused the following behaviour for me.
ls of /home/user/ hung until ctrl+c
tab autocomplete in /home/user/ totally hung the shell.
some other misc behavior of apps trying to access the home directory

I tracked this back to something going wrong with the thinclient_drives mountpoint.
this behaviour did not occur when remoting in from a win10 box.

after disabling the udp stuff as recomended in the above link and rebooting both systems the issue does not reoccur..

I am not sure exactly what is going on but I was able to replicate the issue with win11h2 client and ubuntu 22.04lts server.

its likely microsoft will fix the issue on their end soon enough but given that this can cause this bizzare behavior on a server it might be a possible attack vector or at least an annoyance that a client can cause these issues.

perhaps worth investigating and handling the issue on server side?

**Comment by matt335672** [comment] 2022-10-12 08:45
@plez0r - we don't support UDP at all on the server side. I take your point however that the chansrv process could be trying to send a request to the client over TCP, and the response over UDP is never received.

Here's a link to the MS forum discussion:-

https://answers.microsoft.com/en-us/windows/forum/all/issues-with-remote-desktop-on-windows-11-after/2f0b90c8-9549-46bb-bede-41c2d3990380

We'll need to try to reproduce this to see if we can do anything server-side.

**Comment by MichaelMKKelly** [comment] 2022-10-12 11:32
@matt335672 - yeah that was my point, not supporting udp is fine but if a client tries to use it and it causes server side issues then that is obviously a bit of a problem.

notes for reproduction:
win11 22h2 with standard rdp client
ubuntu 22.04LTS running KDE

if you have any other questions about the setup if you cant reproduce and ill see what I can do to help.

**Comment by matt335672** [comment] 2022-10-13 14:17
Hi @piez0r 

I was having problems reproducing this, but I've just realised Windows Update is b0rked on my VM, so I'm stuck on 21H2. I'll have to re-install.

While I'm doing that, I could do with a log file from you. The use of UDP is initiated by the server during the optional 'multitransport bootstrapping' phase of the connection request - see [[MS-RDPBCGR] 1.3.1.1](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/023f1e69-cfe8-4ee6-9ee0-7e759fb4e4ee) point 8. If the server doesn't do this, the channels won't exist for the client to use.

So, at the moment it's a bit of a mystery. I could be misreading the spec., or something else may be going on.

Can you invoke a crash, and then post the log of the `xrdp-chansrv` process? It's stored in `~/.local/share/xrdp/xrdp-chansrv.<display>.log`, where `<display>` is the display number of the session. This process is at the very least mis-behaving, so it seems like a good place to start.

**Comment by matt335672** [comment] 2022-10-13 16:02
I can't actually install 22h2 on any hardware I have at the moment. The boot iso hangs.

That log file might be useful though.

**Comment by MichaelMKKelly** [comment] 2022-10-13 18:02
@matt335672
without any evidence to back it up I imagined that it worked in such a way:
client: talk to me on udp://xyz
instead of:
client: talk to me on tcp://xyz

and the server did its best to accommodate and somehow the mounting of thinclient_drives pooped the bed in the process

however onwards with the issue at hand: when I have tried to reproduce once again by changing my settings back to allow udp on the client I can no longer get it to produce the unusual behaviour.

I suspect this is due to cumulative update KB5018427 which had a number of bugfixes to various things which may have fixed the issue client side

I will try a few things to see if I can get it to fall over again but I suspect the reproduction method would now involve reinstalling with 22h2 initial version and not adding the cumulative update

that is unless this is a freak thing that only happened to me... which I suppose without further people adding information is entirely possible

as said: ill have a bit of a play around with it again time permitting and see if it falls over and report back if It does anything strange

**Comment by akarl10** [comment] 2022-10-14 06:17
@piez0r you say you use KDE Plasma: did plasmashell block also after login or was there no issue?
When I was hit by a thinclient_drive lockup issue that was because the clipboard tried to get a preview of a file in the clipboard that was not there (anymore) and chansrv (fuse) blocked for some reason. In plasma you can setup the clipboard that it does not keep its contents between logins. That is what I have done on the xrdp server.

**Comment by MichaelMKKelly** [comment] 2022-10-14 06:35
@akarl10  kde did indeed have some issues at the same time. I assumed it was because it was trying to look at my home directory and was hanging in the same way. also part of my testing was. rdpi'ing in with a win10 box and not getting the issue then straight away rdp'ing in with win11 box and the issue was there. hence the narrowing of the issue to the win11 box which had recently been updated to 22h2 then once turning off the udp stuff it worked without issue.

during the testing to the best of my knowledge i didnt change the clipboard. and even if i did that wouldnt account for it disappearing and then reappearing.

so whilst i dont think its clipboard contents directly causing the issue maybe whatever was happening might have caused the same issue somehow. perhaps it garbled what was supposed to be clipboard contents?

**Comment by akarl10** [comment] 2022-10-14 09:44
the reason why I mentioned the clipboard thing is because afaik chansrv is single threaded and if it blocks the whole filesystem is blocked. Anything that does interacts with thinclient_drive (even a stat that is done by ls $HOME) will be blocked too until chansrv recovers or gets killed.
For me something was able to block chansrv if the xrdp side clipboard contained a file reference to a previous rdp session that was not there any more. Don't know how that can happen, but it happened to me. The clipboard itself however is only a virtual directory in thinclient_drives. If something different is able to block "inside" thinclient_drive you will get the same result.
For me it was plasmashell (clipboard) accessing a "mstsc side" file in the clipboard. That blocked chansrv that in turn blocked the whole thing.

**Comment by matt335672** [comment] 2022-10-14 10:04
@akarl10 - you're right in that chansrv is single-threaded, and it is (or was) possible to get the clipboard and the file redirector wrapped around each other. See #1563.

I did some work on this for #2032 which was merged for xrdp v0.9.18. The version of xrdp packaged for 22.04 LTS is v0.9.17, so what you suggest is entirely possible. Or we may have hit another bug in this area.

As regards my somewhat embarrassing inability to run Windows 11; My VM server is powered by a 4th generation Intel Xeon, which is a bit long in the tooth now. After a bit of experimentation however, I think the problem I've got with Windows 11 is QEMU-related, so when I get a bit of time to upgrade QEMU/KVM I'm hopeful I can have another go at reproducing this.

On the meantime @piez0r, have a look at #1563 and see if it fits your problem. Given the way that UDP channels are negotiated, I think this is more likely than a UDP issue.

**Comment by matt335672** [comment] 2022-10-18 10:59
I've finally got 22H2 working on my rig, and again, I can't reproduce the problem as reported.

However, I'm able to reproduce #1563 as follows:-
1. Log in to 22H2
2. Open Windows Explorer and browse to a writeable directory. This is important and explained below.
3. Run mstsc.exe. On the 'local resources' tab make sure local printers aren't shared and drives are. Connect to Ubuntu 22.04 and log in.
4. Browse the `thinclient_drives` share. All should be OK.
5. Somewhere under `~/thinclient_drives/C:\` select a file and copy it.

On my system this breaks chansrv. Of the two threads within chansrv, one is stuck within the FUSE code:-

<pre>
$ ps -ef | grep chansrv
testuser    9352    9229  0 11:05 ?        00:00:00 /usr/local/sbin/xrdp-chansrv
$ ls /proc/9352/task
9352  9423
$ sudo cat /proc/9352/task/9352/stack
[<0>] do_select+0x56c/0x850
[<0>] core_sys_select+0x1dd/0x420
[<0>] do_pselect.constprop.0+0xca/0x170
[<0>] __x64_sys_pselect6+0x68/0x90
[<0>] do_syscall_64+0x5c/0xc0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xcb
<b>$ sudo cat /proc/9352/task/9423/stack
[<0>] request_wait_answer+0x104/0x210
[<0>] fuse_simple_request+0x1b5/0x360
[<0>] fuse_dentry_revalidate+0x17b/0x3c0
[<0>] lookup_fast+0xe0/0x160
[<0>] walk_component+0x43/0x1c0
[<0>] link_path_walk.part.0.constprop.0+0x23f/0x3a0
[<0>] path_lookupat+0x3e/0x1c0
[<0>] filename_lookup+0xcf/0x1d0
[<0>] user_path_at_empty+0x3f/0x60
[<0>] vfs_statx+0x7a/0x130
[<0>] __do_sys_newfstatat+0x36/0x70
[<0>] __x64_sys_newfstatat+0x1c/0x30
[<0>] do_syscall_64+0x5c/0xc0
[<0>] entry_SYSCALL_64_after_hwframe+0x61/0xcb</b>
</pre>

A program must be running on the windows side which is interested in file announcements on the clipboard. This is why I ran Windows Explorer. The sequence of operations is like this:-

1. File is copied on Ubuntu side.
2. chansrv picks up file announcement and sends a [Format List PDU](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/14e60d52-e0da-4e19-9455-e8643ff17673) to the RDP client containing the code `0xc0bc`.
3. RDP client announces that a file is available on the clipboard
4. Windows Explorer asks for file details
5. RDP client sends a [Format Data Request PDU](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeclip/b4c6e5c8-27dd-4d07-b15f-d7e40302a870) to chansrv containing the code `0xc0bc`.
6. chansrv deadlocks as described in 1563

Because this sequence is dependent on a Windows client, it won't happen all the time. I suspect this is why we don't see it more often.

Unless anyone has anything else to add, I'll close this in a while I think.

**Closed as completed** 2022-11-01 10:21 UTC
