### ISSUE TITLE
unimplemented DATA_PDU_TYPE_SUPPRESS_OUTPUT

### ISSUE THREAD

**Issue by sherwinkh** [neutrinolabs/xrdp#1312] opened 2019-03-23 10:20 UTC
I want to use the API update_send_suppress_output in NeutrinoRDP，but xrdp not implement this. Somebody can help?
xrdp_rdp_process_data(struct xrdp_rdp *self, struct stream *s)
{
    int data_type;

    in_uint8s(s, 6);
    in_uint8s(s, 2); /* len */
    in_uint8(s, data_type);
    in_uint8s(s, 1); /* ctype */
    in_uint8s(s, 2); /* clen */
    DEBUG(("xrdp_rdp_process_data code %d", data_type));

    switch (data_type)
    {
        case RDP_DATA_PDU_POINTER: /* 27(0x1b) */
            xrdp_rdp_process_data_pointer(self, s);
            break;
        case RDP_DATA_PDU_INPUT: /* 28(0x1c) */
            xrdp_rdp_process_data_input(self, s);
            break;
        case RDP_DATA_PDU_CONTROL: /* 20(0x14) */
            xrdp_rdp_process_data_control(self, s);
            break;
        case RDP_DATA_PDU_SYNCHRONISE: /* 31(0x1f) */
            xrdp_rdp_process_data_sync(self);
            break;
        case 33: /* 33(0x21) ?? Invalidate an area I think */
            xrdp_rdp_process_screen_update(self, s);
            break;
        case 35: /* 35(0x23) */
            /* 35 ?? this comes when minimizing a full screen mstsc.exe 2600 */
            /* I think this is saying the client no longer wants screen */
            /* updates and it will issue a 33 above to catch up */
            /* so minimized apps don't take bandwidth */
            break;
        case 36: /* 36(0x24) ?? disconnect query? */
            /* when this message comes, send a 37 back so the client */
            /* is sure the connection is alive and it can ask if user */
            /* really wants to disconnect */
            xrdp_rdp_send_disconnect_query_response(self); /* send a 37 back */
            break;
        case RDP_DATA_PDU_FONT2: /* 39(0x27) */
            xrdp_rdp_process_data_font(self, s);
            break;
        case 56: /* PDUTYPE2_FRAME_ACKNOWLEDGE 0x38 */
            xrdp_rdp_process_frame_ack(self, s);
            break;
        default:
            g_writeln("unknown in xrdp_rdp_process_data %d", data_type);
            break;
    }

    return 0;
}

**Comment by jsorg71** [comment] 2019-03-25 17:27
Yes, I think you're right, xrdp is ignoring the message.  I think we implemented invalidate(Client Refresh Rect PDU) but not suppress.
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/abebe6ac-ccdd-4547-89a8-d629831f5527

**Comment by sherwinkh** [comment] 2019-03-26 10:32
@ jsorg71 
Can you help to implement "suppress"?

**Comment by sherwinkh** [comment] 2019-03-29 08:56
@ jsorg71 thx for your help.Is there any progress?

**Comment by jsorg71** [comment] 2019-04-03 06:06
working on  this in branch d6cc487b3dcdc5a51ba9f9749fdc64a5aa5cd867

**Comment by jsorg71** [comment] 2019-04-03 21:23
I'm a bit confused on how this should work.  We can easily stop surface commands and orders, but should we stop channels like audio data?

**Comment by metalefty** [comment] 2019-04-04 02:56
I tested it on Win 10 to Win 10 RDPing. At least audio is not suppressed.

1. Playback some YouTube video with high graphics movements (network bandwidth consumption is around 10Mbps)
2. Minimize the mstsc
3. Network bandwidth consumption become less (around 200kbps, looks like only audio is transfered)

**Comment by jsorg71** [comment] 2019-04-04 03:25
Thanks @metalefty I think that makes sense.  They must only suppress orders, surface commands and GFX.  I wonder if cursor updates happen.  Docs don't really say.  Anyway, the client does not seem to panic if suppressed things are still sent so we can start with surface commands and orders.

**Comment by jsorg71** [comment] 2019-04-07 06:44
After thinking about this a lot, I think we should handle this in the back-end.  xrdp should pass the suppress info the the module so it can make the best use of it.  In proxy mode, it can pass it to the upstream RDP server.  When using Xorg, it can pass it to Xorg,  It can get complicated with orders.  This make that work nicely.  VNC has this sort of thing built in so libvnc can handle it for the RDP to VNC proxy or Xvnc.

**Comment by sherwinkh** [comment] 2019-04-08 04:48
@jsorg71 thx for your works.
I have tested your branch. NeutrinoRDP send a suppress data PDU to xrdp for suppressing, but NeutrinoRDP  still receive surface commands.
## log of xrdp:
xrdp_rdp_process_suppress: allowDisplayUpdates 0 bytes left 3
xrdp_rdp_process_suppress: suppress_output 1
xrdp:xrdp_mm [4212885514]: xrdp_mm_suppress_output: suppress 1 left 0 top 0 right 0 bottom 0
xrdp_rdp_process_suppress: allowDisplayUpdates 1 bytes left 11
xrdp_rdp_process_suppress: suppress_output 0 left 0 top 0 right 1920 bottom 1080
xrdp:xrdp_mm [4212895430]: xrdp_mm_suppress_output: suppress 0 left 0 top 0 right 1920 bottom 1080
## log of NeutrinoRDP:
[2019-04-08 12:10:02] <SuppressOutput@1850> update_send_suppress_output,allow=0
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:02] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:03] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:04] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <SuppressOutput@1850> update_send_suppress_output,allow=1
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!
[2019-04-08 12:10:05] <xf_gdi_surface_bits@666> get you!!!!

NeutrinoRDP/client/X11/xf_gdi.c
```
void xf_gdi_surface_bits(rdpContext* context, SURFACE_BITS_COMMAND* surface_bits_command)
{
	int i, tx, ty;
	XImage* image;
	RFX_MESSAGE* message;
	xfInfo* xfi = ((xfContext*) context)->xfi;
	RFX_CONTEXT* rfx_context = (RFX_CONTEXT*) xfi->rfx_context;
	NSC_CONTEXT* nsc_context = (NSC_CONTEXT*) xfi->nsc_context;
	LOG("get you!!!!");
	if (surface_bits_command->codecID == CODEC_ID_H264)
	{
.......
```

```
static void SuppressOutput(int allow)
{
	RECTANGLE_16 updateAreas;
	updateAreas.left = 0;
	updateAreas.top = 0;	 
	updateAreas.right = screen_w;
	updateAreas.bottom = screen_h;
	LOG("update_send_suppress_output,allow=%d",allow)
	if(g_update != NULL )
	{
		update_send_suppress_output(g_update->context, allow, &updateAreas);
	}

}
 ```

**Comment by jsorg71** [comment] 2019-04-08 05:02
You should get xrdp from(same as above)
https://github.com/jsorg71/xrdp/tree/suppress

and xorgxrdp from
https://github.com/jsorg71/xorgxrdp/tree/suppress

If that works, I'll make a PR.

**Comment by sherwinkh** [comment] 2019-04-08 08:47
@jsorg71 
your xrdp and xorgxrdp works well for DATA_PDU_TYPE_SUPPRESS_OUTPUT.
thx again.

**Comment by sherwinkh** [comment] 2019-04-18 01:39
@jsorg71 ,update_send_suppress_output(allow=0) can suppress surface cmd update ,
but update_send_suppress_output(allow=1) cannot resume surface cmd update randomly.
And at that moment,mouse can move, but  graphic output not update any more.

**Comment by sherwinkh** [comment] 2019-04-19 01:32
Another question:update_send_suppress_output(allow=1) called ,NeutrinoRDP receive a disconnect PDU from xrdp(randomly).
## log:
[1970-01-01 21:28:34] <SuppressOutput@1856> update_send_suppress_output,allow=1
[1970-01-01 21:28:34] <rdp_read_header@253> rdp->disconnect = true,reason = 128
[1970-01-01 21:28:34] <rdp_recv_tpkt_pdu@742> rdp_recv_tpkt_pdu: disconnect
transport_check_fds: transport->recv_callback failed
transport_check_fds: do_callback failed
Failed to check FreeRDP file descriptor
[1970-01-01 21:28:34] <freerdp_context_free@217> state = 10, errorInfo = 0

```
static tbool rdp_recv_tpkt_pdu(rdpRdp* rdp, STREAM* s)
{
	uint16 length;
	uint16 pduType;
	uint16 pduLength;
	uint16 pduSource;
	uint16 channelId;
	uint16 securityFlags;
	uint8* nextp;

	LLOGLN(10, ("rdp_recv_tpkt_pdu:"));
	if (!rdp_read_header(rdp, s, &length, &channelId))
	{
		LLOGLN(0, ("Incorrect RDP header."));
		return false;
	}
	LLOGLN(10, ("rdp_recv_tpkt_pdu: length %d", length));
	if (rdp->disconnect)
	{
		//LLOGLN(0, ("rdp_recv_tpkt_pdu: disconnect"));
		LOG("rdp_recv_tpkt_pdu: disconnect")
		return false;
	}

tbool rdp_read_header(rdpRdp* rdp, STREAM* s, uint16* length, uint16* channel_id)
{
	uint8 reason;
	uint16 initiator;
	enum DomainMCSPDU MCSPDU;

	MCSPDU = (rdp->settings->server_mode) ? DomainMCSPDU_SendDataRequest : DomainMCSPDU_SendDataIndication;
	if (!mcs_read_domain_mcspdu_header(s, &MCSPDU, length))
	{
		LLOGLN(0, ("rdp_read_header: mcs_read_domain_mcspdu_header failed"));
		return false;
	}
	if (*length - 8 > stream_get_left(s))
	{
		LLOGLN(0, ("rdp_read_header: parse error"));
		return false;
	}
	if (MCSPDU == DomainMCSPDU_DisconnectProviderUltimatum)
	{
		if (!per_read_enumerated(s, &reason, 0))
		{
			LLOGLN(0, ("rdp_read_header: per_read_enumerated failed"));
			return false;
		}
		rdp->disconnect = true;
		*channel_id = MCS_GLOBAL_CHANNEL_ID;
		LOG("rdp->disconnect = true,reason = %d",reason)
		return true;
	}
```

**Comment by jsorg71** [comment] 2019-04-19 04:24
@sherwinkh 
I've been testing, I can't reproduce.  Are you using NeutrinoRDP from my branch.  I ask because you said you were using NeutrinoRDP suppress output but it was not done.  I figured you had your own version.  Try my version and also make sure you make clean and make again to make sure you have everything built for all components xrdp, xorgxrdp, NeutrinoRDP.
Also can you test the ms client?  Does that disconnect too?

**Comment by sherwinkh** [comment] 2019-04-19 06:55
I have merged your commits into xrdp, xorgxrdp,NeutrinoRDP(branch devel).
NeutrinoRDP run on my arm board device,and jpeg codec is the only codec in xf_gdi_surface_bits,using hw jpeg codec.
build setting args in xrdp :configure --enable-fuse --enable-tjpeg --enable-jpeg .
Server :ubuntu 16.04.5

**Comment by sherwinkh** [comment] 2019-04-19 07:12
I ask because you said you were using NeutrinoRDP suppress output but it was not done
==>
in most case ,suppress PDU(allow=0) can suppress graphic output ,PDU(allow=1) can resume graphic output.
but sometimes,suppress PDU(allow=0) can suppress graphic output ,PDU(allow=1) cannot resume graphic output

**Comment by sherwinkh** [comment] 2019-04-20 02:30
> Another question:update_send_suppress_output(allow=1) called ,NeutrinoRDP receive a disconnect PDU from xrdp(randomly).
> 
> ## log:
> [1970-01-01 21:28:34] [SuppressOutput@1856](mailto:SuppressOutput@1856) update_send_suppress_output,allow=1
> [1970-01-01 21:28:34] [rdp_read_header@253](mailto:rdp_read_header@253) rdp->disconnect = true,reason = 128
> [1970-01-01 21:28:34] [rdp_recv_tpkt_pdu@742](mailto:rdp_recv_tpkt_pdu@742) rdp_recv_tpkt_pdu: disconnect
> transport_check_fds: transport->recv_callback failed
> transport_check_fds: do_callback failed
> Failed to check FreeRDP file descriptor
> [1970-01-01 21:28:34] [freerdp_context_free@217](mailto:freerdp_context_free@217) state = 10, errorInfo = 0
> 
> ```
> static tbool rdp_recv_tpkt_pdu(rdpRdp* rdp, STREAM* s)
> {
> 	uint16 length;
> 	uint16 pduType;
> 	uint16 pduLength;
> 	uint16 pduSource;
> 	uint16 channelId;
> 	uint16 securityFlags;
> 	uint8* nextp;
> 
> 	LLOGLN(10, ("rdp_recv_tpkt_pdu:"));
> 	if (!rdp_read_header(rdp, s, &length, &channelId))
> 	{
> 		LLOGLN(0, ("Incorrect RDP header."));
> 		return false;
> 	}
> 	LLOGLN(10, ("rdp_recv_tpkt_pdu: length %d", length));
> 	if (rdp->disconnect)
> 	{
> 		//LLOGLN(0, ("rdp_recv_tpkt_pdu: disconnect"));
> 		LOG("rdp_recv_tpkt_pdu: disconnect")
> 		return false;
> 	}
> 
> tbool rdp_read_header(rdpRdp* rdp, STREAM* s, uint16* length, uint16* channel_id)
> {
> 	uint8 reason;
> 	uint16 initiator;
> 	enum DomainMCSPDU MCSPDU;
> 
> 	MCSPDU = (rdp->settings->server_mode) ? DomainMCSPDU_SendDataRequest : DomainMCSPDU_SendDataIndication;
> 	if (!mcs_read_domain_mcspdu_header(s, &MCSPDU, length))
> 	{
> 		LLOGLN(0, ("rdp_read_header: mcs_read_domain_mcspdu_header failed"));
> 		return false;
> 	}
> 	if (*length - 8 > stream_get_left(s))
> 	{
> 		LLOGLN(0, ("rdp_read_header: parse error"));
> 		return false;
> 	}
> 	if (MCSPDU == DomainMCSPDU_DisconnectProviderUltimatum)
> 	{
> 		if (!per_read_enumerated(s, &reason, 0))
> 		{
> 			LLOGLN(0, ("rdp_read_header: per_read_enumerated failed"));
> 			return false;
> 		}
> 		rdp->disconnect = true;
> 		*channel_id = MCS_GLOBAL_CHANNEL_ID;
> 		LOG("rdp->disconnect = true,reason = %d",reason)
> 		return true;
> 	}
> ```

I  found some log in xorgxrdp.xx.log:
[ 15465.685] rdpClientConRecv: g_sck_recv failed(returned 0)
[ 15465.691] rdpClientConRecvMsg: error
[ 15465.692] rdpClientConCheck: rdpClientConGotData failed
[ 15465.692] rdpClientConDisconnect:
[ 15465.692] rdpRemoveClientConFromDev: removing clientCon 0x5632c3596ed0
I looks like connect closed, but I don't know why
```
static int
rdpClientConRecv(rdpPtr dev, rdpClientCon *clientCon, char *data, int len)
{
    int rcvd;

    if (!clientCon->connected)
    {
        return 1;
    }

    while (len > 0)
    {
        rcvd = g_sck_recv(clientCon->sck, data, len, 0);

        if (rcvd == -1)
        {
            if (g_sck_last_error_would_block(clientCon->sck))
            {
                g_sleep(1);
            }
            else
            {
                LLOGLN(0, ("rdpClientConRecv: g_sck_recv failed(returned -1)"));
                clientCon->connected = FALSE;
                return 1;
            }
        }
        else if (rcvd == 0)
        {
            LLOGLN(0, ("rdpClientConRecv: g_sck_recv failed(returned 0)"));
            clientCon->connected = FALSE;
            return 1;
        }
        else
        {
            data += rcvd;
            len -= rcvd;
        }
    }

    return 0;
}
```

**Comment by jsorg71** [comment] 2019-04-20 04:07
My guess is that you have some error in your suppress output PDU.
Grab the suppress branch from NeutrinoRDP and test that on x86 or x64 first.
I did a lot of minimize / restore and I don't see any problem.  I test too with MSTSC.

**Comment by sherwinkh** [comment] 2019-04-20 10:48
I grab the suppress branch from NeutrinoRDP,do the flowing tests:
8 arm board devices running NeutrinoRDP, sending SuppressOutput(0) or  SuppressOutput(1) to ubuntu server in every 3 mins.
After 4 hours , one arm board device can't restore output.
```
static void SuppressOutput(int allow)
{
	RECTANGLE_16 updateAreas;
	updateAreas.left = 0;
	updateAreas.top = 0;	 
	updateAreas.right = screen_w;
	updateAreas.bottom = screen_h;	
	if(g_update != NULL )
	{
		update_send_suppress_output(g_update->context, allow, &updateAreas);
		LOG("update_send_suppress_output,allow(%d)",allow)
	}
}
```

**Comment by jsorg71** [comment] 2019-04-21 03:48
can you send me what your
update_send_suppress_output() function looks like

**Comment by sherwinkh** [comment] 2019-04-22 01:22
after 24 hours , 5 arm devices can't restore output.and one is disconnected.Only one device is OK.
```
static void update_write_suppress_output(STREAM* s, uint8 allow, RECTANGLE_16* area)
{
	stream_write_uint8(s, allow); /* allowDisplayUpdates (1 byte) */
	stream_seek(s, 3); /* pad3Octets (3 bytes) */

	if (allow > 0)
		freerdp_write_rectangle_16(s, area);
}

void update_send_suppress_output(rdpContext* context, uint8 allow, RECTANGLE_16* area)
{
	STREAM* s;
	rdpRdp* rdp = context->rdp;

	s = rdp_data_pdu_init(rdp);
	update_write_suppress_output(s, allow, area);

	rdp_send_data_pdu(rdp, s, DATA_PDU_TYPE_SUPPRESS_OUTPUT, rdp->mcs->user_id);
}
```

**Comment by jsorg71** [comment] 2019-04-22 07:20
I ran one session(MSTSC) in recorder all night, no problem.
I'm doing RFX you are using a JPEG session I think.  I can try JPEG.  Shouldn't matter.
How are you generating the event to send the suppress message?
is it coming from a different thread?
Any chance you can try my branch, I still think something is wrong with your client.

The Xorg messages in your last post is normal when the client disconnects.
[ 15465.685] rdpClientConRecv: g_sck_recv failed(returned 0)
...

**Comment by sherwinkh** [comment] 2019-04-22 09:40
The Xorg messages in your last post is normal when the client disconnects.
[ 15465.685] rdpClientConRecv: g_sck_recv failed(returned 0)
==> But when I disconnect the client ,I don't see that log in xorgrdp.xx.log
I started a thread to watch a pipe,then another program will write "openSuppress" or "closeSuppress" to the pipe in every 3 minutes.
I will grab your branch,modify nothing ,using the software jpeg codec,then test "suppress".
My code like this:
```
static void* control(void * none)
{
	char  buff[256];
	char *argv[16];
	int   argc;	
	int nRead;
	LOG("\t[%-16s] starting, the tid=%d",__func__,gettid());
	while(1)
	{			
		//nRead = read(fd_pipe_control, &flag, sizeof(int));
		nRead = read(fd_pipe_control, buff, 256);
		if(nRead > 0){	
			argc = splitString(argv, buff, nRead);
			if(argc == 0) continue;
			if(strcmp(argv[0], "openSuppress") == 0)
			{	
				SuppressOutput(0);

			}
			else if(strcmp(argv[0], "closeSuppress") == 0)
			{
				SuppressOutput(1);
			}	
		}		
	}
	
	LOG("control thread exit !..... " )	
	pthread_exit(NULL);

}
static int control_init(char *pipeName)
{
	if( access(PIPENAME, R_OK) == -1 ){	
		PT_FUNC_PT_STR("", " pipe file not exist ")
	 	return -1;
	}                                 
	
	int ret;
	fd_pipe_control = open(pipeName, O_RDWR/*O_RDONLY | O_NONBLOCK*/);
	if(-1 == fd_pipe_control)
	{
		PT_FUNC_PT_STR("", " open pipe error")
		return -1;
	}
	
	

	ret = pthread_create(&thread_broadcast_control, NULL, control, NULL);
	if(ret)
	{
		close(fd_pipe_control);
		return -1;
	}
	
	return 0;
}
int main(int argc, char* argv[])
{
	pthread_t thread;
	freerdp* instance;
	struct thread_data* data;
	freerdp_handle_signals();

	setlocale(LC_ALL, "");

	freerdp_channels_global_init();

	g_sem = freerdp_sem_new(1);

	instance = freerdp_new();

	jpegDecoder_init();
	hky_show_init();
	control_init(PIPENAME);

	instance->PreConnect = xf_pre_connect;
	instance->PostConnect = xf_post_connect;
	instance->Authenticate = xf_authenticate;
	instance->VerifyCertificate = xf_verify_certificate;
	instance->ReceiveChannelData = xf_receive_channel_data;

	instance->context_size = sizeof(xfContext);
	instance->ContextNew = (pContextNew) xf_context_new;
	instance->ContextFree = (pContextFree) xf_context_free;
	freerdp_context_new(instance);

	instance->context->argc = argc;
	instance->context->argv = argv;
	instance->settings->sw_gdi = false;

	data = (struct thread_data*) xzalloc(sizeof(struct thread_data));
	data->instance = instance;

	g_thread_count++;
	pthread_create(&thread, 0, thread_func, data);
```

**Comment by jsorg71** [comment] 2019-04-22 17:28
It's the thread sending the suppress that making your session unstable.  Only one thread can call into libfreerdp per session.  You can have 2 sessions and then 2 threads, one for each but only one thread session.  Get rid of the thread and move the pipe to the main loop and add it to the select in xfreerdp_run.

**Comment by sherwinkh** [comment] 2019-04-23 03:20
Get rid of the thread and move the pipe to the main loop and add it to the select in xfreerdp_run
==》how to do this?
I can't create my thread in rdp session?

**Comment by jsorg71** [comment] 2019-04-23 06:33
I edited your code a bit but I didn't compile.  You'll have to debug.

**Comment by sherwinkh** [comment] 2019-04-23 07:16
Thanks a lot ,testing is running.

**Comment by sherwinkh** [comment] 2019-04-24 06:24
After about 24 hours,8 devices are running normally.I think It works.
Thanks again~

**Comment by jsorg71** [comment] 2019-04-25 22:15
Ok, great, I'll close this and we can open a new one if we find issues

**Closed** 2019-04-25 22:15 UTC
