### ISSUE TITLE
snaps not running in xrdp

### ISSUE THREAD

**Issue by graylion** [neutrinolabs/xrdp#2920] opened 2024-01-23 17:01 UTC
### xrdp version

0.9.17-2ubuntu2

### Detailed xrdp version, build options

~~~
xrdp 0.9.17
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-asBei3/xrdp-0.9.17=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -Wno-error=deprecated-declarations
      PKG_CONFIG_PATH=/build/xrdp-asBei3/xrdp-0.9.17/pkgconfig

  Compiled with OpenSSL 3.0.2 15 Mar 2022

~~~

### Operating system & version

Mint 21.3

### Installation method

git clone & make install

### What desktop environment do you use?

Cinnamon

### Environment xrdp running on

physical with AMD Fury 64

### What's your client?

Microsoft RDP

### Area(s) with issue?

Other

### Steps to reproduce

I have installed NVIDIA GeForce NOW on the server. It works fine when using the machine directly, but launching it from XRDP gets me the following error

### ✔️ Expected Behavior

for geforce now to launch

### ❌ Actual Behavior

/user.slice/user-1001.slice/session-c3.scope is not a snap cgroup

### Anything else?

This appears to be a common issue with snap applications in xrdp, see also https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1968908

**Comment by matt335672** [comment] 2024-01-24 08:56
Most likely cause on your version of Ubuntu is #1684 

A possible workaround is described in [this post](1684#issuecomment-717904769). The issue is fixed in the development branch, but we haven't released that yet.

**Comment by graylion** [comment] 2024-01-24 13:27
Thanks for that. I tried compiling the workaround, but get an error. I logged an issue with it.

**Comment by matt335672** [comment] 2024-02-20 11:13
@graylion - do you need any more input on this?

**Closed as completed** 2024-03-22 17:50 UTC
Labels: bug

**Comment by matt335672** [comment] 2024-04-30 10:52
For anyone still reading this, see also #3053. This affects the `xdg-desktop-portal.service` which I believe is also used by snap applications.

**Comment by alvinliju** [comment] 2025-04-19 20:19
install firefox-esr

**Comment by alvinliju** [comment] 2025-04-19 20:20
sudo apt remove firefox
sudo apt-add-repository ppa:mozillateam/ppa
sudo apt update
sudo apt install firefox-esr. 

firefox-esr it'll launch

**Comment by metalefty** [comment] 2025-04-21 02:51
It just switches Firefox from snap to apt. It is not related to snap packages not launching.
