### ISSUE TITLE
Can't mount USB drives after updating xrdp Ubuntu

### ISSUE THREAD

**Issue by bananas123f** [neutrinolabs/xrdp#2934] opened 2024-02-03 05:33 UTC
### xrdp version

0.9.17-2ubuntu2

### Detailed xrdp version, build options

ii  xorgxrdp                                   1:0.2.17-1build1                         amd64        Remote Desktop Protocol (RDP) modules for X.org
ii  xrdp                                       0.9.17-2ubuntu2                          amd64        Remote Desktop Protocol (RDP) server

### Operating system & version

Ubuntu 22.04.3

### Installation method

other

### Which backend do you use?

xorg

### Environment xrdp running on

Physical machine

### What's your client?

Windows 10 Official Microsoft RDP client

### Steps to reproduce

1. Reboot system.
2. Open files application
3. Try to mount drive
4. it fails "Unable to access "drive_name" An operation is already pending

### ✔️ Expected Behavior

Drives to mount, worked great previously, then Ubuntu ESM updated xrdp. I uninstalled and reinstalled and the same thing is occuring.

### ❌ Actual Behavior

Can't mount any USB drives after updating xrdp

**Comment by matt335672** [comment] 2024-02-03 17:34
For this version of xrdp:-
1) make sure you are not sharing printers from the client (even if you have none).
2) The USB drives have to be plugged in when you start the RDP client, and you need to mark them to be used in your remote session. I don't think hot plugging works on this version.

However:-
- I'm unable to reproduce your problem on this version of xrdp. I do not get the error you describe.
- There have also been no changes to the drive redirector code with your update. The package update log is [here](http://changelogs.ubuntu.com/changelogs/pool/universe/x/xrdp/xrdp_0.9.17-2ubuntu2/changelog). So the update is unlikely to be causing this.

Check the USB stick functions normally under Windows. You should be able to access it from both sides at the same time.

**Comment by bananas123f** [comment] 2024-02-03 18:02
Thanks, to clarify, this is not an issue redirecting drives from local machine to the remote Ubuntu host machine.


This is an issue mounting USB drives on the remote Ubuntu machine that are physically plugged into that machine. I can no longer mount any drives on the remote machine that are physically plugged into it when I am using xrdp. When I walk up to the Ubuntu machine and log in physically everything works as intended.

**Comment by matt335672** [comment] 2024-02-05 10:30
Ah OK  - I see what you mean. That's a different situation entirely.

A couple of observations about this:-
1) In general, using hot-plug devices from remote sessions (whether xrdp or not) isn't likely to be supported out-of-the-box. This isn't to say it isn't doable, but it wouldn't surprise me if something was done earlier to the installation to support this, and this has been undone by the ESM patching.
2) If another user is logged in to the machine locally using the GUI, they may well get a prompt relating to the hot-plug device. This would be compatible with your error message. So check that no-one is logged in on the console of the machine.
3) Does your xrdp user have administrative privileges? If not, temporarily grant them and see what happens.

Going back to 1) above, the system component that would prevent this is polkit. Have a look at the [FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ#why-cant-i-perform-some-privileged-gui-actions) on this.

I suspect you'll need to configure one of more polkit actions to allow you to do what you want to do. In particular, as you are trying to take ownership of a USB stick which is assigned to what's called 'seat 0', you'll need to set the `ResultAny` flag for `org.freedesktop.udisks2.filesystem-mount-other-seat` appropriately, depending on whether your xrdp user has administrative permissions or not.

**Comment by bananas123f** [comment] 2024-02-06 01:06
Thanks, yes it worked fine before, but required lots of authentication/passwords. Locally the GUI doesn't prompt related to hot-plug devices, which is odd. Nobody else is logged onto the console.

my xrdp user has admin privileges. I will try modifying polkit flags further. Thanks.

Edit, tried editing the file and rebooting as you suggested, and it still doesn't work.

**Comment by matt335672** [comment] 2024-02-20 11:43
On my GNOME system (which works) I've enabled local polkit logging with:-

```
sudo bash -c 'G_MESSAGES_DEBUG=all /usr/libexec/polkitd -r' 2>&1 | tee /tmp/polkit.log
```

Be aware this replaces the existing polkitd. You'll get a rash of startup messages.

When the startup message have stopped, hot-plugging a USB stick gives me:-

```
** (polkitd:235736): DEBUG: 11:37:27.084: system-bus-name::1.10 is inquiring whether system-bus-name::1.109 is authorized for org.freedesktop.udisks2.filesystem-mount-other-seat
** (polkitd:235736): DEBUG: 11:37:27.084:  user of caller is unix-user:root
** (polkitd:235736): DEBUG: 11:37:27.085:  user of subject is unix-user:testuser
** (polkitd:235736): DEBUG: 11:37:27.085: checking whether system-bus-name::1.109 is authorized for org.freedesktop.udisks2.filesystem-mount-other-seat
** (polkitd:235736): DEBUG: 11:37:27.086:   0x7fd38c003560
** (polkitd:235736): DEBUG: 11:37:27.086: Checking whether session 20 is active.
** (polkitd:235736): DEBUG: 11:37:27.086: Session 20 has UID 1001.
** (polkitd:235736): DEBUG: 11:37:27.086: UID 1001 has state active.
** (polkitd:235736): DEBUG: 11:37:27.086:  subject is in session 20 (local=0 active=1)
** (polkitd:235736): DEBUG: 11:37:27.087:  is authorized (has implicit authorization local=0 active=1)
** (polkitd:235736): DEBUG: 11:37:27.087:  
```

Restart the real polkitd afterwards by hitting CTRL-C and typing:-

```
sudo systemctl restart polkit
```

Try that and post what you get as a result.

**Comment by bananas123f** [comment] 2024-02-23 06:44
> On my GNOME system (which works) I've enabled local polkit logging with:-
> 
> ```
> sudo bash -c 'G_MESSAGES_DEBUG=all /usr/libexec/polkitd -r' 2>&1 | tee /tmp/polkit.log
> ```
> 
> Be aware this replaces the existing polkitd. You'll get a rash of startup messages.
> 
> When the startup message have stopped, hot-plugging a USB stick gives me:-
> 
> ```
> ** (polkitd:235736): DEBUG: 11:37:27.084: system-bus-name::1.10 is inquiring whether system-bus-name::1.109 is authorized for org.freedesktop.udisks2.filesystem-mount-other-seat
> ** (polkitd:235736): DEBUG: 11:37:27.084:  user of caller is unix-user:root
> ** (polkitd:235736): DEBUG: 11:37:27.085:  user of subject is unix-user:testuser
> ** (polkitd:235736): DEBUG: 11:37:27.085: checking whether system-bus-name::1.109 is authorized for org.freedesktop.udisks2.filesystem-mount-other-seat
> ** (polkitd:235736): DEBUG: 11:37:27.086:   0x7fd38c003560
> ** (polkitd:235736): DEBUG: 11:37:27.086: Checking whether session 20 is active.
> ** (polkitd:235736): DEBUG: 11:37:27.086: Session 20 has UID 1001.
> ** (polkitd:235736): DEBUG: 11:37:27.086: UID 1001 has state active.
> ** (polkitd:235736): DEBUG: 11:37:27.086:  subject is in session 20 (local=0 active=1)
> ** (polkitd:235736): DEBUG: 11:37:27.087:  is authorized (has implicit authorization local=0 active=1)
> ** (polkitd:235736): DEBUG: 11:37:27.087:  
> ```
> 
> Restart the real polkitd afterwards by hitting CTRL-C and typing:-
> 
> ```
> sudo systemctl restart polkit
> ```
> 
> Try that and post what you get as a result.


Thanks. I ended up giving up and installing Linux mint and configuring it the same way as my previous Ubuntu install. Everything works as intended even after installing updates. Totally stumped, but that was my only solution

**Comment by matt335672** [comment] 2024-02-23 15:52
Sorry I dropped the ball on that by not getting back to you sooner.

**Closed as completed by matt335672** 2024-02-23 15:52 UTC
Labels: bug
