### ISSUE TITLE
Resize problem when reconnecting at a different resolution

### ISSUE THREAD

**Issue by diego-santacruz** [neutrinolabs/xrdp#914] opened 2017-10-16 22:39 UTC
I have just set up xrdp to use with xorgxrdp on CentoS 7.4.

Connections work well, but when I reconnect with a different client with a different resolution the screen is not completely resized.

To test I connected from my laptop first (1600x900) in "full screen" and then I connect from my iPhone using the MS RD client which uses 1364x768. It reconnects to the same session (good!) but there is clearly stuff left outside the visible screen and there is no panning, the right and bottom are missing. Interestingly, the windows are automatically repositioned so that they are within the visible screen, but the desktop background, task bar in the bottom and menu bar at the top are not resized. So I am missing part of the taskbar and the buttons at the right of the menu bar.

Querying with xrandr shows that the output is set the the new resolution, but the some of the DE elements were not resized. I discovered that if I attempt set a size via xrandr which is larger than the xrdp screen then everything adjusts to match the xrdp screen size (I have first to define the corresponding mode and add it to the output, via xrandr cli).

The converse occurs when I connect back with my laptop in "full screen", which has a larger screen. Now I see "empty" areas on the right and bottom. Again, setting a size larger than the xrdp screen adjusts everything to match the xrdp screen size.

So it appears that xorgxrdp is doing resizing but not completely, or missing some notifications, and attempting to resize with xrandr to a size larger than the xrdp screen forces it to resync everything to the xrdp screen size.

Note that I run on CentOS 7.4 with the gnome session.

Versions:
xrdp-0.9.3-2.el7.x86_64
xorgxrdp-0.2.4-3.el7.x86_64
Windows 10 remote desktop client 10.0.15063
Microsoft RD client for iOS 8.1.35 (on iOS 11.0.2)

**Comment by metalefty** [comment] 2017-10-17 01:11
Can you show us screenshots? Your issue seems the same issue I saw.  The solution I chose is quit using GNOME. I thought the issue is DE issue and cannot be fixed at xrdp/xorgxrdp side so I quit using GNOME but I have no evidence.  I didn't any further investigations.

If the issue is xorgxrdp issue, as you say resizing is not complete, the issue should be addressed.

**Comment by metalefty** [comment] 2017-10-17 08:48
Thanks for sharing screenshots. The issue looks identical to the issue I encountered before.
Maybe the issue can be solved xorgxrdp side.

**Comment by jsorg71** [comment] 2017-10-17 16:27
DEs are supposed to listen for randr event to detect monitor changes.
I was wondering, why do you set 2560x1440?

**Comment by diego-santacruz** [comment] 2017-10-17 17:23
Nothing special about that resolution, the only thing was that it is larger than the screen size in both directions. I just happened to have a modeline for that resolution handy and cut & paste sufficed.

And as far as I can tell the Gnome DE is listening to xrandr changes, when I change the resolution via xrandr when running under plain Xvnc it does adjust without problem.

Diego Santa Cruz

Le 17 oct. 2017 à 19:08, jsorg71 <notifications@github.com<mailto:notifications@github.com>> a écrit :


DEs are supposed to listen for randr event to detect monitor changes.
I was wondering, why do you set 2560x1440?

**Comment by metalefty** [comment] 2017-10-18 00:32
Hmm, I certainly encountered the issue before but I cannot reproduce the issue today. Using GNOME on CentOS 7.4.1708.

```
$ rpm -qa |grep xrdp
xrdp-0.9.3-2.el7.x86_64
xorgxrdp-0.2.4-3.el7.x86_64
```

**Comment by gnshkl1** [comment] 2018-03-24 06:56
@metalefty try ubuntu-gnome-16.04  to reproduce this issue i am also facing same problem

**Comment by gnshkl1** [comment] 2018-03-24 06:57
@metalefty  also what factors can create such issue for xrdp

**Comment by Nexarian** [comment] 2019-11-01 14:09
I do not have a consistent reproduction of the issue, but I have the following:

1. It seems to work less well when expanding the screen size. Shrinking nearly always seems to work.
2. The log below shows that XRDP seems to have known what the correct resolution to change is, but on the call to XRANDR it fails or times out.

And yes, sometimes when this fails a crash occurs. The stack trace of that is below as well.

```
[615718.283] rdpRRGetInfo:
[618437.261] rdpClientConGotConnection:
[618437.261] rdpClientConGotConnection: g_sck_accept ok new_sck 43
[618437.261] rdpClientConGotConnection: marking only clientCon 0x55616b671e40 for disconnect
[618437.261] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[618437.261] rdpAddClientConToDev: adding clientCon 0x55616c159f90
[618437.261] rdpClientConDisconnect:
[618437.261] rdpRemoveClientConFromDev: removing clientCon 0x55616b671e40
[618437.265] rdpClientConProcessMsgVersion: version 0 0 0 1
[618437.265] rdpClientConProcessScreenSizeMsg: set width 3440 height 1390 bpp 32
[618437.266] rdpClientConProcessScreenSizeMsg: shmemid 94109727 shmemptr 0x7f2043363000
[618437.266] rdpRRScreenSetSize: width 3440 height 1390 mmWidth 910 mmHeight 368
[618437.270] rdpRRGetInfo:
[618437.270]   screen resized to 3440x1390
[618437.273] rdpClientConProcessScreenSizeMsg: RRScreenSizeSet ok=[1]
[618437.273] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 3440 cy 1390
[618437.275] rdpRROutputGetProperty:
[618437.275] rdpRRScreenSetSize: width 1920 height 1178 mmWidth 508 mmHeight 312
[618437.278] rdpRRGetInfo:
[618437.278]   screen resized to 1920x1178
[618437.309] rdpRROutputGetProperty:
[618437.379] rdpClientConProcessMsgClientInfo:
[618437.379]   got client info bytes 5752
[618437.379]   jpeg support 0
[618437.379]   offscreen support 1
[618437.379]   offscreen size 7864320
[618437.379]   offscreen entries 2000
[618437.379] rdpClientConProcessMsgClientInfo: got RFX capture
[618437.379]   cap_width 3456 cap_height 1408
[618437.380] rdpClientConProcessMsgClientInfo: shmemid 94142495 shmemptr 0x7f2043311000 bytes 19464192
[618437.380]   client supports glyph cache but server disabled
[618437.380]   client can do offscreen to offscreen blits
[618437.380]   client can do new(color) cursor
[618437.380]   client can not do multimon
[618437.380] rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
[618437.380] rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1920 height 1178
[618437.380] rdpRRUpdateOutput:
[618437.380] rdpLoadLayout: keylayout 0x00000409 variant  display 11
[618437.380] rdpkeybChangeKeyboardControl:
[618437.380] rdpkeybChangeKeyboardControl: autoRepeat on
[618437.381] rdpkeybChangeKeyboardControl:
[618437.381] rdpkeybChangeKeyboardControl: autoRepeat on
[618437.386] rdpRROutputGetProperty:
[618437.455] (EE) 
[618437.455] (EE) Backtrace:
[618437.456] (EE) 0: /usr/lib/xorg/Xorg (OsLookupColor+0x139) [0x55616a916889]
[618437.457] (EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x50) [0x7f20bbfe7f8f]
[618437.457] (EE) 2: /lib/x86_64-linux-gnu/libc.so.6 (gsignal+0xc7) [0x7f20bbe2aed7]
[618437.457] (EE) 3: /lib/x86_64-linux-gnu/libc.so.6 (abort+0x121) [0x7f20bbe0c535]
[618437.457] (EE) 4: /lib/x86_64-linux-gnu/libc.so.6 (__fsetlocking+0x496) [0x7f20bbe738e6]
[618437.458] (EE) 5: /lib/x86_64-linux-gnu/libc.so.6 (_IO_str_seekoff+0x5ea) [0x7f20bbe7ab6a]
[618437.458] (EE) 6: /lib/x86_64-linux-gnu/libc.so.6 (_IO_str_seekoff+0x28ef) [0x7f20bbe7e9af]
[618437.458] (EE) 7: /usr/lib/xorg/modules/libxorgxrdp.so (rdpCapRect+0x2b8) [0x7f20b99b8228]
[618437.459] (EE) 8: /usr/lib/xorg/modules/libxorgxrdp.so (rdpDeferredUpdateCallback+0x26e) [0x7f20b99b9a1e]
[618437.459] (EE) 9: /usr/lib/xorg/Xorg (TimerSet+0x180) [0x55616a9100b0]
[618437.459] (EE) 10: /usr/lib/xorg/Xorg (TimerSet+0x1f8) [0x55616a910178]
[618437.459] (EE) 11: /usr/lib/xorg/Xorg (WaitForSomething+0x267) [0x55616a910247]
[618437.459] (EE) 12: /usr/lib/xorg/Xorg (SendErrorToClient+0x10c) [0x55616a7b77ac]
[618437.459] (EE) 13: /usr/lib/xorg/Xorg (InitFonts+0x3b6) [0x55616a7bb9c6]
[618437.459] (EE) 14: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xeb) [0x7f20bbe0db6b]
[618437.459] (EE) 15: /usr/lib/xorg/Xorg (_start+0x2a) [0x55616a7a567a]
```

**Comment by Nexarian** [comment] 2019-11-01 22:20
Also, here's a script to restart XRDP if this type of crash happens to you. It happens to me frequently, so I needed a quick way to restart:

```
#!/bin/bash

function kill_all() {
        process=$1
        for i in $(ps aux | grep $process | tr -s ' ' | cut -d" " -f 2)
        do
                sudo kill -9 $i
        done
}

sudo -v

kill_all "/usr/local/sbin/xrdp"
kill_all "/usr/lib/xorg/Xorg"

sudo /etc/xrdp/xrdp.sh restart
```

**Comment by Nexarian** [comment] 2019-11-05 21:48
Here's another call stack from when it doesn't crash. Again, we see that the size is set in one instance, but not in another. In this case, the screen is bigger than the FreeRDP window I'm using, so lots of stuff is "off screen."

```
[261928.934] rdpClientConProcessMsgVersion: version 0 0 0 1
[261928.934] rdpClientConProcessScreenSizeMsg: set width 2560 height 1390 bpp 32
[261928.934] rdpClientConProcessScreenSizeMsg: shmemid 14155800 shmemptr 0x7fdd58439000
[261928.934] rdpRRScreenSetSize: width 2560 height 1390 mmWidth 677 mmHeight 368
[261928.937] rdpRRGetInfo:
[261928.937]   screen resized to 2560x1390
[261928.938] rdpClientConProcessScreenSizeMsg: RRScreenSizeSet ok=[1]
[261928.938] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 2560 cy 1390
[261928.944] rdpRROutputGetProperty:
[261928.945] rdpRRScreenSetSize: width 3440 height 1390 mmWidth 910 mmHeight 368
[261928.948] rdpRRGetInfo:
[261928.948]   screen resized to 3440x1390
[261928.976] rdpRROutputGetProperty:
[261929.048] rdpClientConProcessMsgClientInfo:
[261929.048]   got client info bytes 5752
[261929.048]   jpeg support 0
[261929.048]   offscreen support 1
[261929.048]   offscreen size 7864320
[261929.048]   offscreen entries 2000
[261929.048] rdpClientConProcessMsgClientInfo: got RFX capture
[261929.049]   cap_width 2560 cap_height 1408
[261929.049] rdpClientConProcessMsgClientInfo: shmemid 14188568 shmemptr 0x7fdd5840c000 bytes 14417920
[261929.049]   client supports glyph cache but server disabled
[261929.049]   client can do offscreen to offscreen blits
[261929.049]   client can do new(color) cursor
[261929.049]   client can not do multimon
[261929.049] rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
[261929.049] rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 3440 height 1390
[261929.049] rdpRRUpdateOutput:
[261929.049] rdpLoadLayout: keylayout 0x00000409 variant  display 10
[261929.049] rdpkeybChangeKeyboardControl:
[261929.049] rdpkeybChangeKeyboardControl: autoRepeat on
[261929.051] rdpkeybChangeKeyboardControl:
[261929.051] rdpkeybChangeKeyboardControl: autoRepeat on
[261929.111] rdpRROutputGetProperty:
[261929.152] rdpInDeferredRepeatCallback:
[261929.152] rdpkeybChangeKeyboardControl:
[261929.152] rdpkeybChangeKeyboardControl: autoRepeat off
[261929.199] rdpInDeferredRepeatCallback:
[261929.199] rdpkeybChangeKeyboardControl:
[261929.199] rdpkeybChangeKeyboardControl: autoRepeat off
```

**Comment by jsorg71** [comment] 2019-11-20 06:33
I create https://github.com/neutrinolabs/xorgxrdp/pull/153 for possible fix

**Comment by metalefty** [comment] 2019-12-11 03:02
Closing. I'll reopen this it the issue still continues. Leave a comment then.

**Closed by metalefty** 2019-12-11 03:02 UTC

**Comment by niiiksh** [comment] 2020-06-30 11:18
Debian 8, Gnome 3.14 
Resize problem still exists.
