### ISSUE TITLE
scrolling on MacOS with Touch Bar

### ISSUE THREAD

**Issue by gahabana** [neutrinolabs/xrdp#837] opened 2017-07-27 05:29 UTC
hi, I've been running xrdp server (latest GitHub builds updated monthly) on Ubuntu 16.04.2 for months and everything is working great except scrolling which in remote browser or file manager seems to be very very fast and erratic (tiny scroll down is not smooth and causes much larger scroll to be performed).

Is there some 'settings' or compile time options that needs to be specified ?

Thanks tin advanca !!!

**Comment by matt335672** [comment] 2023-07-03 12:06
Duplicate of neutrinolabs/xorgxrdp#150

**Closed by matt335672** 2023-07-03 12:06 UTC
