### ISSUE TITLE
dual display AKA multimon AKA dualmon support

### ISSUE THREAD

**Issue by nestoru** [neutrinolabs/xrdp#289] opened 2015-10-14 20:17 UTC
Hello!,

Great job guys! I have a question, is dual display supported?

Grepping the code I can see support for it (multimon):
```
./xorg/X11R7.6/rdp/rdpup.c:static int g_do_multimon = 0; /* multimon - turn on or off */
./xorg/X11R7.6/rdp/rdpup.c:            LLOGLN(0, ("  client can do multimon"));
./xorg/X11R7.6/rdp/rdpup.c:            g_do_multimon = 1;
./xorg/X11R7.6/rdp/rdpup.c:            LLOGLN(0, ("  client can not do multimon"));
./xorg/X11R7.6/rdp/rdpup.c:            g_do_multimon = 0;
grep: ./xorgxrdp: Is a directory
grep: ./xrdp: Is a directory
./xrdp/xrdp.ini:allow_multimon=true
./xrdp/xrdp_login_wnd.c:        else if (g_strncmp(n, "allow_multimon", 64) == 0)
./xrdp/xrdp_login_wnd.c:            globals->allow_multimon = g_text2bool(v);
./xrdp/xrdp_login_wnd.c:    g_writeln("allow_multimon:          %d", globals->allow_multimon);
./xrdp/xrdp_login_wnd.c:    g_writeln("allow_multimon:          %d", globals->allow_multimon);
./xrdp/xrdp_types.h:    int  allow_multimon;
```
However I do not see any traces in /var/log/xrdp-sesman.log nor /var/log/xrdp.log suggesting that the client I am using to connect with (windows RDP client with multimon flag set) "can do multimon". Is there anything I should do get information about the multimon negotiation?

Thanks,
- Nestor

**Comment by speidy** [comment] 2015-10-14 23:37
Hello,

Multimon should work with Xorg driver for now.

X11rdp / xvnc not supporting dual mon for now.
בתאריך יום ד׳, 14 באוק׳ 2015 ב-23:17 מאת Nestor Urquiza <
notifications@github.com>:

**Comment by jsorg71** [comment] 2015-10-14 23:50
Yes, as Speidy says, we only got it working in the Xorg driver.
It's really nice, you can connect from MSTSC in full screen and when you maximize apps in the session, they only maximize on the monitor, not the whole desktop.
It used RandR in X11.  The monitors show up as rdp0, rdp1, ...
This can be merged to X11rdp.
It was done first in Xorg driver because I thought we would need some of the monitor helper functions in the XFree86 libs but we didn't.

**Comment by nestoru** [comment] 2015-10-27 13:16
X11rdp is unfortunately the only option I have seen that works for ubuntu 14.04 (http://scarygliders.net/x11rdp-o-matic-information/). Any plans to do the merge into X11rdp? Thanks!

**Comment by coredump4** [comment] 2016-04-08 18:27
I am glad to see multi-monitor is in progress!
I am trying to test with Xorg but not having success.  I've got MSTSC configured for multiple monitors as well as in xrdp.ini.  What's a valid xorg.conf look like for dual monitors however?

Thanks!

**Comment by metalefty** [comment] 2016-04-10 16:02
Leaving it default will work.

**Comment by coredump4** [comment] 2016-04-10 17:15
Hmmm.  I always see "client can not do multimon" in the Xorg log.  If MSTSC has the checkbox selected to use all monitors & xrdp.ini has multimon enabled, where should I look first for the problem?

**Comment by speidy** [comment] 2016-04-10 18:50
Hi,

Can you paste your xrdp output ?
בתאריך יום א׳, 10 באפר׳ 2016 ב-20:15 מאת coredump4 <notifications@github.com

**Comment by coredump4** [comment] 2016-04-18 13:37
If I leave xrdp in the foreground, attached is what I get on the console when a multimon client connects.  The client connects through an SSH tunnel.

[xrdp-no-daemon-console-output.txt](https://github.com/neutrinolabs/xrdp/files/223836/xrdp-no-daemon-console-output.txt)

**Comment by metalefty** [comment] 2016-04-19 08:46
Rebuild xrdp with `./configure --enable-xrdpdebug` and get the output of xrdp running in foreground.
It gives us more verbose log.

Like this.
```
processing monitors data, allow_multimon is 1
monitorCount= 2
got a monitor: left= 0, top= 0, right= 1919, bottom= 1199, is_primary?= 1
got a monitor: left= 1920, top= 0, right= 3519, bottom= 899, is_primary?= 0
```

**Comment by coredump4** [comment] 2016-04-19 20:19
Thanks for this tip.  I now see more detail logged to the console, but nothing having to do with the client's monitor configuration.  All I can see is "item allow_multimon value yes" as it parses the xrdp.ini.

I have LogLevel=DEBUG right now; is another value required to see the extra debugging output?

**Comment by jsorg71** [comment] 2016-04-19 21:52
The multimon bits are in the Xorg driver but not X11rdp.  Some are there but not all.
Everything else is done(xrdp, libxrdp).
I'll merge them.

**Comment by jsorg71** [comment] 2016-04-19 22:37
ok, in devel branch now with 473f3dc

**Comment by coredump4** [comment] 2016-04-20 15:31
I'd prefer to stick with Xorg if possible...

**Comment by jsorg71** [comment] 2016-04-21 06:02
Ok, I think X11rdp is multimon ready now with 5e398e0
Of course, you need to use a desktop manager that is multimon aware.
I tested with xfce4 and ubuntu 14.04 amd64.

**Comment by coredump4** [comment] 2016-04-21 13:00
@metalefty what else could I try in order to get the extra debugging information?  I'd really like to see what Xrdp reports for monitorCount so I can make sure it and mstsc are agreeing on the configuration.

**Comment by metalefty** [comment] 2016-04-22 00:58
You've been built xrdp with `--enable-xrdpdebug`, right?

For example, 
```
./configure --enable-xrdpdebug --enable-other-else-your-configuration
make && make install 
```
and run xrdp and sesman with `-ns` flag.  You should be able to see very verbose logs.

With information you gave us so far, your xrdp setup looks already support multimon.
However, mstsc is not telling xrdp that have client can do multimon for some reasons.
Seeing verbose log with `--enable-xrdpdebug` will clarify that.

**Comment by coredump4** [comment] 2016-04-22 14:16
Yes, this is confirmed.  In the debug output, I can see in the "client mcs data received" dump, there's no CS_MONITOR PDU.  I'm investigating the client end of things now.

**Comment by coredump4** [comment] 2016-04-22 20:59
OK, I tracked down the cause.
In xrdp_iso.c, xrdp_iso_negotiate_security() sets rdpNegData=0 if the security protocol is rdp.  This causes xrdp_iso_send_cc() not to send a Connection Confirm PDU with the EXTENDED_CLIENT_DATA_SUPPORTED flag.  This was why my clients were not sending the CS_MONITOR PDU to the server.
For testing, I just forced rdpNegData=1 and it worked, but the real solution is probably a different test in xrdp_iso_send_cc() in order to de-couple setting ECDS from the security protocol.

**Comment by speidy** [comment] 2016-04-22 21:23
Which rdp client do you use ? (What version?)

It seems like it doesn't do security layer negotiation
בתאריך יום ו׳, 22 באפר׳ 2016 ב-23:59 מאת coredump4 <notifications@github.com

**Comment by speidy** [comment] 2016-04-22 21:26
There is a rdp file parameter called "security layer negotiation"
Look in "my documents\Default.rdp" if it's turned off
בתאריך שבת, 23 באפר׳ 2016 ב-0:23 מאת Idan Freiberg <speidy@gmail.com>:

**Comment by speidy** [comment] 2016-04-22 21:26
https://technet.microsoft.com/en-us/library/ff393719(v=ws.10).aspx
בתאריך שבת, 23 באפר׳ 2016 ב-0:25 מאת Idan Freiberg <speidy@gmail.com>:

**Comment by coredump4** [comment] 2016-04-22 21:38
I'm using regular mstsc.exe, patched up to RDP 8.1.  I actually do have "negotiate security layer:i:1" in my config file.

**Comment by speidy** [comment] 2016-04-22 22:49
Do non-xrdp RDP servers works with multimon for you ?
בתאריך שבת, 23 באפר׳ 2016 ב-0:38 מאת coredump4 <notifications@github.com>:

**Comment by speidy** [comment] 2016-04-22 23:14
Is it possible that you build the master branch? It seems broken in that
case.

Did you test devel branch ?
בתאריך שבת, 23 באפר׳ 2016 ב-1:49 מאת Idan Freiberg <speidy@gmail.com>:

**Comment by coredump4** [comment] 2016-04-22 23:26
Yes, multimon sessions are fine when connecting to Windows systems.  And sorry, I should've mentioned I was working with Master.

**Comment by coredump4** [comment] 2016-04-22 23:26
I can test Devel but I need stability...

**Comment by speidy** [comment] 2016-04-22 23:50
That was a bug iv'e fixed a long time ago in devel branch.
Unfortunately we didn't merge it to master yet.

Anyway, I think you can cherry pick this change from devel.

**Comment by coredump4** [comment] 2016-05-03 19:13
I've been testing Devel branch using multimon with Xorg, and so far, so good.
I've encountered one issue that's more nuisance than problem; I'll open a new issue for that.

**Comment by metalefty** [comment] 2016-06-29 08:32
Seems to be solved.

**Closed by metalefty** 2016-06-29 08:32 UTC
