### ISSUE TITLE
[VNC] Cannot connect with same user after closing session

### ISSUE THREAD

**Issue by magist3r** [neutrinolabs/xrdp#284] opened 2015-09-25 01:19 UTC
I connect to my server using xrdp vnc. After successful login and logout I can't connect with same user to the server.

After logout I have this in logs:
(3217)(139883610253056)[INFO ] An established connection closed to endpoint: 192.168.1.134:54066 - socket: 8
(3217)(139883610253056)[DEBUG] xrdp_mm_module_cleanup
(3217)(139883610253056)[DEBUG] VNC mod_exit
(3217)(139883610253056)[INFO ] An established connection closed to endpoint: 127.0.0.1:5921 - socket: 12
**(3217)(139883610253056)[ERROR] Listening socket is in wrong state we terminate listener**
systemd[3163]: pam_unix(systemd-user:session): session closed for user tc1

And on reconnect:
(3149)(139883610253056)[INFO ] A connection received from: 192.168.1.134 port 54067
(3149)(139883610253056)[INFO ] An established connection closed to endpoint: 192.168.1.134:54067 - socket: 8
(3242)(139883610253056)[INFO ] An established connection closed to endpoint: NULL:NULL - socket: 7
(3242)(139883610253056)[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
(3242)(139883610253056)[CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
(3242)(139883610253056)[DEBUG] xrdp_00000caa_wm_login_mode_event_00000001
(3242)(139883610253056)[WARN ] local keymap file for 0x0409 found and dosen't match built in keymap, using local keymap file
(3145)(139782075074304)[INFO ] A connection received from: 127.0.0.1 port 46956
(3242)(139883610253056)[DEBUG] returnvalue from xrdp_mm_connect 0
(3145)(139782075074304)[INFO ] scp thread on sck 8 started successfully
(3145)(139782047024896)[INFO ] ++ reconnected session: username tc1, display :21.0, session_pid 3152, ip 192.168.1.134:54067 - socket: 8
(3145)(139782047024896)[INFO ] An established connection closed to endpoint: 127.0.0.1:46956 - socket: 8
**(3242)(139883610253056)[DEBUG] VNC Error after security negotiation
(3242)(139883610253056)[DEBUG] VNC error before sending share flag
(3242)(139883610253056)[DEBUG] VNC error before receiving server init
(3242)(139883610253056)[DEBUG] VNC error before receiving pixel format
(3242)(139883610253056)[DEBUG] VNC error before receiving name length
(3242)(139883610253056)[DEBUG] VNC error before receiving name
(3242)(139883610253056)[DEBUG] xrdp_mm_module_cleanup
(3242)(139883610253056)[DEBUG] VNC mod_exit**
(3242)(139883610253056)[INFO ] An established connection closed to endpoint: NULL:NULL - socket: 12
(3242)(139883610253056)[INFO ] An established connection closed to endpoint: 127.0.0.1:3350 - socket: 11

I can connect successfully with another user, but only for one session.
Restarting xrdp-sesman solves the problem, but this is only a workaround.

**Comment by magist3r** [comment] 2015-09-25 01:23
Looks like xrdp tries to reconnect to nonexistent session.

**Comment by paulvt** [comment] 2015-10-06 10:46
I'm pretty sure that this is related to: https://sourceforge.net/p/xrdp/bugs/54/.

**Comment by tastle73** [comment] 2015-11-02 18:54
@paulvt I see you have some code to fix this problem.  Did you check that in somewhere?  I'm not seeing it the code on here.  This would solve a long standing issue for me.

**Comment by paulvt** [comment] 2015-11-02 21:11
@tastle73 I haven't because it is really not a good solution.  The patch just indicates what the problem is.
But you can apply the patch at https://sourceforge.net/p/xrdp/bugs/54/#108d for a workaround.

**Comment by execlogic** [comment] 2016-09-29 10:11
I use Centos7 KDE + xrdp and have same bug.
I think xrdp incorrect close session when logout from session.
For resolve this bug i make folder ~/.kde/shutdown and create shutdown script

>#/bin/bash
> killall -9 -u $USER

And this work for me.

**Comment by metalefty** [comment] 2016-10-02 00:55
Can you show me the process status after logout?
Remove ~/.kde/shutdown and let's see `pstree -cl`.


BTW, `killall -9 -u $USER` does overkill.

**Comment by execlogic** [comment] 2016-10-03 10:35
[pstree.txt](https://github.com/neutrinolabs/xrdp/files/505919/pstree.txt)
I can replay this bug when I use xrdp + vnc. Patch from  https://sourceforge.net/p/xrdp/bugs/54/#108d doesnt help. xrdp was build from git.
In this video you can see this bug. https://youtu.be/fIyK3DeU6BA
I attach logs also
[xrdp.log.zip](https://github.com/neutrinolabs/xrdp/files/505969/xrdp.log.zip)

**Comment by metalefty** [comment] 2018-03-29 00:55
No feedback from the reporter for years, closing.

**Closed by metalefty** 2018-03-29 00:55 UTC

**Comment by j-preston** [comment] 2018-09-07 13:52
Can we reopen this issue.  I am still having this issue with the xrdp build in the CentOS epel repository and I haven't found a solution.  Once I log out as the user, I'm locked out.  Even restarting doesn't clear the error.  The error only appears to be with users and not with root.

**Comment by fraber** [comment] 2019-02-15 17:54
Same f... bug after 4 years on CentOS 7 (1810). That's pretty embarrassing... Or at least it should be...

I believe there is an issue with:

/usr/lib/systemd/system/vncserver@.service

I believe you'd need to manually start VNC or something like this.

Let's see...
