### ISSUE TITLE
Previous warnings in chansrv_fuse.c are now errors due to -Werror

### ISSUE THREAD

**Issue by gdsotirov** [neutrinolabs/xrdp#1678] opened 2020-09-04 16:20 UTC
There's a difference in latest [version 0.9.14](https://github.com/neutrinolabs/xrdp/releases/tag/v0.9.14) compared to [0.9.13.1](https://github.com/neutrinolabs/xrdp/releases/tag/v0.9.13.1) coming from commit 7e58209 by @aquesnel, which now turns all warnings into errors on Linux (i.e. with `-Werror` compiler option). However, thus previous warnings in chansrv_fuse.c are now turned into errors and thus are blocking the build of the software.

The relevant part of my build log is:

```
Making all in chansrv
make[3]: Entering directory '/usr/src/tmp/xrdp-0.9.14/sesman/chansrv'
i586-slackware-linux-gcc -DHAVE_CONFIG_H -I. -I../..  -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_SOCKET_PATH=\"/tmp/.xrdp\" -I../../common  -DXRDP_FUSE -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse  -DXRDP_OPUS -DXRDP_MP3LAME    -O3 -march=i586 -mtune=i686 -Wall -Wwrite-strings -Werror -O2 -c -o chansrv_fuse.o chansrv_fuse.c
chansrv_fuse.c: In function 'xfuse_cb_readdir':
chansrv_fuse.c:1610:20: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     else if ((dh = (struct xfs_dir_handle *) fi->fh) == NULL)
                    ^
chansrv_fuse.c: In function 'xfuse_cb_read':
chansrv_fuse.c:2098:15: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     if ((fh = (XFUSE_HANDLE *)fi->fh) == NULL)
               ^
chansrv_fuse.c: In function 'xfuse_cb_write':
chansrv_fuse.c:2171:15: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     if ((fh = (XFUSE_HANDLE *)fi->fh) == NULL)
               ^
chansrv_fuse.c: In function 'xfuse_cb_releasedir':
chansrv_fuse.c:2439:33: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     struct xfs_dir_handle *dh = (struct xfs_dir_handle *) fi->fh;
                                 ^
cc1: all warnings being treated as errors
Makefile:535: recipe for target 'chansrv_fuse.o' failed
make[3]: *** [chansrv_fuse.o] Error 1
make[3]: Leaving directory '/usr/src/tmp/xrdp-0.9.14/sesman/chansrv'
Makefile:706: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/tmp/xrdp-0.9.14/sesman'
Makefile:481: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/tmp/xrdp-0.9.14'
Makefile:413: recipe for target 'all' failed
make: *** [all] Error 2
```

I'd like to make it clear that I'm trying to build for Slackware 14.2 with GCC 5.5.0, which is quite old. However, building on Slackware-current with GCC 9.3.0 rends even more warnings now turned into errors. It doesn't seem to me that all warnings were fixed, so `-Werror` could be enabled by default on Linux. Should this option remain by default or is there are plan to fix all the warnings?

**Comment by aquesnel** [comment] 2020-09-04 18:52
I plan to fix the warnings to make sure that it does build.

I don't have time to look at the details of your build at the moment. Do you know what the difference is between your build and the [builds that succeeded](https://travis-ci.org/github/neutrinolabs/xrdp/builds/711832581) when the commit was published?

**Comment by aquesnel** [comment] 2020-09-05 05:00
Hi @gdsotirov,

I have not been able to reproduce the error that you found on my machine.

I tried to reproduce the error with the following commands:
```
git checkout v0.9.14
./configure --enable-fuse --enable-mp3lame --enable-opus
make clean
make V=1
```

Make used the following command to successfully compile chansrv_fuse.c
```
gcc -DHAVE_CONFIG_H -I. -I../..  -DXRDP_CFG_PATH=\"/etc/xrdp\" -DXRDP_SBIN_PATH=\"/usr/local/sbin\" -DXRDP_SHARE_PATH=\"/usr/local/share/xrdp\" -DXRDP_PID_PATH=\"/var/run\" -DXRDP_SOCKET_PATH=\"/tmp/.xrdp\" -I../../common  -DXRDP_FUSE -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse  -DXRDP_OPUS -DXRDP_MP3LAME    -g -O2 -Wall -Wwrite-strings -Werror -MT chansrv_fuse.o -MD -MP -MF .deps/chansrv_fuse.Tpo -c -o chansrv_fuse.o chansrv_fuse.c
```

Can you please verify if you can reproduce the error using the same commands that I did? And if so, can you try to reproduce the error on a travis-ci build by following the instructions [here](https://github.com/neutrinolabs/xrdp/blob/v0.9.14/faq-compile.txt#L36)

**Comment by gdsotirov** [comment] 2020-09-05 06:12
@aquesnel The difference between the builds is only the xrdp version. I'll provide more details  and do the requested later as I'm currently not on PC.

**Comment by gdsotirov** [comment] 2020-09-05 17:24
So @aquesnel, I configure like this:

```
CFLAGS="-O3 -march=i586 -mtune=i686" \
CXXFLAGS="-O3 -march=i586 -mtune=i686" \
./configure --build=i586-slackware-linux \
            --host=i586-slackware-linux \
            --prefix=/usr \
            --libdir=/usr/lib \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --docdir=/usr/doc \
            --mandir=/usr/man \
            --disable-silent-rules \
            --disable-dependency-tracking" \
            --enable-shared=yes \
            --enable-static=no \
            --enable-ipv6 \
            --enable-jpeg \
            --enable-fuse \
            --enable-opus \
            --enable-mp3lame \
            --enable-pixman \
            --enable-painter \
            --enable-rfxcodec
```

The actual build script could be seen here - [xrdp.SLackBuild](https://github.com/gdsotirov/xrdp.SlackBuild/blob/master/xrdp.SlackBuild). I enable the same (i.e. fuse, mp3lame and opus), but I also enable other features (e.g. IPv6, JPEG, pixman, painter and rfxcodec) and set paths, which is necessary for the build of a general purpose system-wide package. The exact differences with your compiler command are the following:

```diff
--- aquesnel
+++ gdsotirov
@@ -1,14 +1,14 @@
-gcc \
+i586-slackware-linux-gcc \
 -DHAVE_CONFIG_H -I. -I../.. \
 -DXRDP_CFG_PATH=\"/etc/xrdp\" \
--DXRDP_SBIN_PATH=\"/usr/local/sbin\" \
--DXRDP_SHARE_PATH=\"/usr/local/share/xrdp\" \
+-DXRDP_SBIN_PATH=\"/usr/sbin\" \
+-DXRDP_SHARE_PATH=\"/usr/share/xrdp\" \
 -DXRDP_PID_PATH=\"/var/run\" \
 -DXRDP_SOCKET_PATH=\"/tmp/.xrdp\" \
 -I../../common \
 -DXRDP_FUSE -D_FILE_OFFSET_BITS=64 \
 -I/usr/include/fuse \
 -DXRDP_OPUS -DXRDP_MP3LAME \
--g -O2 \
--Wall -Wwrite-strings -Werror -MT chansrv_fuse.o -MD -MP -MF .deps/chansrv_fuse.Tpo \
+-O3 -march=i586 -mtune=i686 \
+-Wall -Wwrite-strings -Werror -MT chansrv_fuse.o -MD -MP -MF .deps/chansrv_fuse.Tpo -O2 \
 -c -o chansrv_fuse.o chansrv_fuse.c
```

_Note_: Command `i586-slackware-linux-gcc` on Slackware is just a symbolic link to GCC.

But I do not think these differences are important. And of course I was able to reproduce the same warnings (i.e. errors) with the same compiler command as you. So what's your compiler version? And the next things that come to mind are: What version of FUSE you're using? What OS and version? I'm trying to build package for Slackware 14.2 (released 2016-07-01), so I'm building with old GCC 5.5.0 and old FUSE version - 2.9.5.

However, I tried the same build on Slackware-current with newer GCC 9.3.0 and newer FUSE 2.9.9, but with removed `-Werror` option I have the same warnings plus one more:

```
log.c:558:30: warning: ‘%.2d’ directive output may be truncated writing between 2 and 11 bytes into a region of size between 9 and 16 [-Wformat-truncation=]
chansrv_fuse.c:1610:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
chansrv_fuse.c:2098:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
chansrv_fuse.c:2171:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
chansrv_fuse.c:2439:33: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
```

I'm totally for fixing all compilation warnings, which is necessary, before enforcing `-Werror`. However, this is what I get in my environments and searching for the reason I found [your revision](https://github.com/neutrinolabs/xrdp/commit/7e58209b195052205831d53a9f4cd0b4604a293d). I had the same warnings for 0.9.13, but they were just warnings back then. Let me know if you need other information from me. Let's first try to understand why I have warnings and you do not.

**Comment by matt335672** [comment] 2020-09-07 08:21
Hi @gdsotirov 

Apologies for butting in to this conversation but I think I can see what's happening here.

The `fi->fh` value referred to in the error is defined in `/usr/include/fuse/fuse_common.h` as being a `uint64_t` (on my system at least). The errors suggest to me you're building on a 32-bit operating system. Is this right?

The other warning you're getting on `log.c:558` is fixed in devel by commit 8b54de320c257ab696371f8fd81e1e9554fb8711 

Exactly what we do about this isn't clear to me at the moment but I though this would help a bit.

**Comment by aquesnel** [comment] 2020-09-08 13:39
@gdsotirov thanks for the build info, I'll try to reproduce the issue.
I'm using the CI builds to verify if the build succeeds. Right now for the 32-bit build it's using Ubuntu 16.04 with gcc 5.4.0 (see the [build output for more details](https://travis-ci.org/github/neutrinolabs/xrdp/builds/711832581))

@matt335672 Thanks for helping to debug the issue.

#### notes

It looks like this warning was not caught in the CI builds because fuse is disabled for 32-bit builds.
https://github.com/neutrinolabs/xrdp/blob/devel/.travis.yml#L87

#### next actions

* reproduce the failure with the same flags
* try enabling fuse on 32-bit builds since there have been a bunch of changes to fuse lately

**Comment by aquesnel** [comment] 2020-09-08 17:31
#### notes

* I've been able to reproduce the error in CI build
  * https://travis-ci.com/github/aquesnel/xrdp/builds/183411044
  * https://github.com/aquesnel/xrdp/commit/ec53a0398d22d27fdb21b23fc1f3d1f8c37d3db6
* I don't understand why only the gcc build fails, and not the g++ or clang builds

#### next actions

* investigate the fuse types and make a plan to fix the warning

**Comment by aquesnel** [comment] 2020-09-08 20:47
I've looked at the code and there are two problems:

1. a pointer is stored in the `fuse_file_info.fh` field which is of type `uint64_t` and this field is used as context argument for callbacks. A pointer is stored into the field. For 64 bit-systems this is fine, but for 32-bit systems this causes a widening from the pointer to the `fh` field, and then a narrowing from the 64-bit field to the 32-bit pointer when retrieving the callback context. This should be safe since only 32-bit pointers can be stored in the field, and the callback context is local to the current process. These warning can be solved by adding `(tintptr)` to the missing locations, since it is a known safe operation.

2. `fuse_file_info.fh` field is used to store a pointer two different types: an `xfuse_handle` and a `xfs_dir_handle`. There is no type identifier in the handle, so without further investigation it is not clear if there type error in the code.
The solutions that I can think of is to:
* do nothing and leave the analysis for the next change to the module
* use a single type in `fuse_file_info.fh`. eg. add the `xfs_dir_handle` struct (or a pointer) as a field of `xfuse_handle` and then only set the `xfuse_handle` pointer as the `fuse_file_info.fh` field.

@matt335672 since you have been modifying this fuse code recently, let me know if you have a recommended fix, otherwise I'll just only fix the warnings, and leave the second problem alone.

**Comment by matt335672** [comment] 2020-09-09 08:39
Thanks for the analysis.

I think your solution to problem 1. is fine. In an ideal world we'd be moving to the standard `intptr_t`, but we are where we are.

Nice spot on problem 2. From a pragmatic point of view what we've got works OK, but I can understand it's not ideal from a strongly typed perspective.

Another option which occurred to me would be to introduce another type for `fuse_file_info.fh` which would be type identifier plus a union of pointers. That would allow us to check the pointer type at runtime was correct, a bit like a C++ `dynamic_cast`. However, I think your proposal is better, as introducing another type is I think needlessly complicating this module. It also introduces quite a lot of runtime error checking.

Considering your proposal, if I understand you right, in the two places where the result of `xfs_opendir()` is assigned to `fuse_file_info.fh`, we'd simply interpose another allocated `xfuse_handle` structure. Have I got that right?

We could then wrap the conversion to and from the void pointer in a couple of static functions (which the compiler will inline) and make the whole thing a bit more amenable to static type analysis.

**Comment by matt335672** [comment] 2020-09-09 08:55
Automatic closure!
I've re-opened this so we can keep the conversation going about the typing issue.

**Comment by gdsotirov** [comment] 2020-09-09 16:00
I'm sorry for my late replay - I was busy these days.

@matt335672 Yes, 32 bit OS. I do not have these warnings on 64 bit Slackware.

@aquesnel @matt335672 Thank you both for investigating time and efforts into finding and fixing the problem. I'll test the fix with the next release.

**Comment by aquesnel** [comment] 2020-09-12 22:58
@matt335672 I've implemented my idea for unifying the types for the fuse file handle in #1686 . Let me know what you think.

**Comment by matt335672** [comment] 2020-09-14 06:56
Great - since you're opened #1686, I'll close this now.

**Closed by matt335672** 2020-09-14 06:56 UTC
