### ISSUE TITLE
Session reconnect gives black screen until screen changes

### ISSUE THREAD

**Issue by saddy001** [neutrinolabs/xrdp#1964] opened 2021-08-06 09:24 UTC
This is xrdp v0.9.16, xorgxrdp v*.16, Linux, Guacamole, Firefox client, with initial-program (single application, not desktop) set.

When reconnecting to a session by reloading the browser tab, while not moving the mouse the screen remains black. Only when the mouse is moved AND some GUI element is hovered that triggers a "screen change", for example an input element that changes its appearance on hover, or the mouse cursor changing to the text input cursor, the screen goes from black to showing the actual program. If no such alement exists, e.g. when some modal dialog is blocking the rest of the UI, the black screen cannot be cured. 

Can you reproduce this with a more simple setup? If not, where else would you report this?

**Comment by matt335672** [comment] 2021-08-06 10:55
I've had a play with this, and I 'think' I can see what's happening here.

When you hit refresh, guacamole starts a new connection to xrdp. However, the previous connection isn't killed, as it doesn't look like tomcat is closing it promptly.

I've run a simple xterm from guacamole. While it's running, I've got the following connection to port 3389 on my xrdp host (IP addresses removed):-

```
$ ss 'sport = 3389'
Netid    State    Recv-Q     Send-Q                  Local Address:Port                            Peer Address:Port     Process    
tcp      ESTAB    0          0              [<host-address>]:ms-wbt-server         [<guac-address>]:38502               
```

When I hit refresh on firefox, I get a second xrdp connection, but I get a black screen. The first connection is still active :-

```
$ ss 'sport = 3389'
Netid    State    Recv-Q     Send-Q                  Local Address:Port                            Peer Address:Port     Process    
tcp      ESTAB    0          0              [<host-address>]:ms-wbt-server         [<guac-address>]:38506               
tcp      ESTAB    0          0              [<host-address>]:ms-wbt-server         [<guac-address>]:38502               
```

After around 10 seconds, tomcat closes the connection and the new connection sequence is able to complete. The delay is down to xrdp being unable to connect to xrdp-chansrv, as it's already occupied.

So it looks to me like the problem is tomcat connection pooling. You should be able to reproduce what I've done above to confirm this.

A workaround on our side could be to run a session without xrdp-chansrv, but we don't currently support that. You'd lose a bit of functionality that way.

**Comment by saddy001** [comment] 2021-08-06 15:25
Ok thanks. Could you also see the "only mouse triggers session takeover"?

**Comment by saddy001** [comment] 2021-08-06 15:30
Here's my connections:
```
Initial Connection:
# ss 'sport = 3389'
Netid                     State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                       
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58700                      

Shortly after F5 refresh
# ss 'sport = 3389'
Netid                     State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                       
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58700                      
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58720                      

About 3 seconds after refresh
# ss 'sport = 3389'
Netid                     State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                       
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58720                      
```
The new session immediately takes over, however the screen remains black until mouse move + screen change.
This also works when closing the browser tab, opening a new one, then connecting again, however the old con is properly closed:

```
# ss 'sport = 3389'
Netid                     State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                       
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58744                      

# ss 'sport = 3389'
Netid                      State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                      

# ss 'sport = 3389'
Netid                     State                       Recv-Q                       Send-Q                                              Local Address:Port                                             Peer Address:Port                       
tcp                       ESTAB                       0                            0                                                       [<host-address>]:3389                                                [<host-address>]:58762                      
```

**Comment by saddy001** [comment] 2021-08-06 15:38
So to me, the problem looks like there is some refresh screen trigger missing after reconnection. At the moment, it's only triggered on "screen content changed".

**Comment by matt335672** [comment] 2021-08-09 11:36
Nice work. If you're seeing the problem on a browser close and reconnect, there's something else going on here.

Can you post a bit more detail about your VNC server and Linux installation?

I think the next step is to run your application in a 'normal' VNC session (i.e. not started by sesman) so we can connect to it from both xrdp/guacamole and a vnc viewer and see what happens. I'm out of time today, but I can give you a hand with setting that up if you need it.

**Comment by saddy001** [comment] 2021-08-10 08:48
Setup of server1:
ubuntu 18.04 <- x.org <- xorgxrdp <- xrdp <- guacamole

Client:
guacamole's html5-client

There is no VNC anywhere. I tried to login to RDP from server1 to server1 with remmina, but that didn't work.

/var/log/xrdp.log with "Xorg" selected in the ugly GUI at login:
```
[20210810-10:40:40] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20210810-10:40:40] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210810-10:40:40] [INFO ] sesman connect ok
[20210810-10:40:40] [INFO ] sending login info to session manager, please wait...
[20210810-10:40:42] [INFO ] xrdp_wm_log_msg: login failed for display 0
[20210810-10:40:42] [INFO ] login failed for display 0
```
with "Xvnc" (does that even make sense?):
```
[20210810-10:43:31] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20210810-10:43:31] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210810-10:43:31] [INFO ] sesman connect ok
[20210810-10:43:31] [INFO ] sending login info to session manager, please wait...
[20210810-10:43:33] [INFO ] xrdp_wm_log_msg: login failed for display 0
[20210810-10:43:33] [INFO ] login failed for display 0
```
with "neutrinordp-any":
```
[20210810-10:44:33] [ERROR] xrdp_wm_log_msg: error loading libxrdpneutrinordp.so specified in xrdp.ini, please add a valid entry like lib=libxrdp-vnc.so or similar
[20210810-10:44:33] [INFO ] error loading libxrdpneutrinordp.so specified in xrdp.ini, p
[20210810-10:44:33] [INFO ] lease add a valid entry like lib=libxrdp-vnc.so or similar
[20210810-10:44:33] [ERROR] Failure setting up module
```
You said without sesman, but looking at the logs, it seems involved. The last log suggests adding a lib= entry, however I wonder why guacamole doesn't need that.

**Comment by matt335672** [comment] 2021-08-10 13:28
Sorry about the confusion. I've made an assumption which isn't true in your case.

xrdp supports two back-end X servers with these two modules:-
- `Xorg` supports a standard `Xorg` X server with an additional plug-in which is used to provide RDP compatibility.
- `Xvnc` uses a VNC server (by default TigerVNC on 16.04) with xrdp providing a conversion between the VNC and RDP protocols.

Both modules support most use-cases. The `Xorg` module can generally provide better performance, but sometimes this requires more work to achieve.

I'd assumed you'd be using the `Xvnc` module. It's easier to debug in situations like this, as you can use a VNC client to work out where the issue lies. You can also use the `Xvnc` module to start a new session (using sesman), or to connect to a VNC session which has been started in another manner.

if you don't need the session management in `sesman`, you don't even need to use `xrdp`. Guacamole is capable of connecting directly to a VNC server.

I suppose the first question to ask is do you need session management for your use-case?

Assuming you do need session management, It seems strange that you're not able to log in using remmina. The error you're getting is saying that the username and password aren't working. However, exactly the same process is being used for authentication in both cases. I think using remmina is a good idea, as we can then discount Guacamole as causing your problem.

One possibility is keyboard mapping. The characters in your password may not be working for you. You can use the username box to see whether this is the case or not.

Also, is the application you're starting a proprietary one, or is it generally available? One thing I've seen in the past with proprietary apps is that they don't cope with expose events well, and if this is the case might benefit from backing-store being enabled on the X server.

**Comment by saddy001** [comment] 2021-08-10 15:51
Thanks for the insights.

> One possibility is keyboard mapping
Yep this was it, I could login. 

```
[20210810-17:16:21] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20210810-17:16:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210810-17:16:21] [INFO ] sesman connect ok
[20210810-17:16:21] [INFO ] sending login info to session manager, please wait...
[20210810-17:16:21] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20210810-17:16:21] [INFO ] login successful for display 10
[20210810-17:16:21] [INFO ] loaded module 'libxup.so' ok, interface size 10288, version 4
[20210810-17:16:21] [INFO ] started connecting
[20210810-17:16:21] [INFO ] lib_mod_connect: connecting via UNIX socket
[20210810-17:16:21] [INFO ] lib_mod_log_peer: xrdp_pid=13055 connected to X11rdp_pid=10696 X11rdp_uid=1023 X11rdp_gid=1024 client_ip=127.0.0.1 client_port=52240
[20210810-17:16:21] [INFO ] connected ok
```
However, the screen remained blue-green after that.

The backing store is already enabled:
`[ 28479.353] (==) XRDPDEV(0): Backing store enabled`

Regarding using VNC instead of RDP and omiting sesman: I would prefer not changing the running system since it is working pretty well except for this small issue. I'd rather implement some workaround in my GUI testing app, like some blinking light that is enabled when a stale session is detected to trigger a screen redraw on reconnect ;-)

**Comment by matt335672** [comment] 2021-08-10 19:58
So we've got a problem starting a full session. We could try to solve that, but there's not much point.

In Remmina, on the Advanced tab, you should be able to set the startup program.

![tmp](https://user-images.githubusercontent.com/30179339/128926602-89c2632c-5120-4220-8cb9-50eaec9b5eef.png)

If you set that to whatever Guacamole is using, you should be able to reproduce logging in with Guacamole. That's worth a go.

**Comment by saddy001** [comment] 2021-08-11 08:22
Same blue-green screen when I choose "Xorg" from the dropdown list having set startup program und startup path.

xrdp.log
```
[20210811-09:47:14] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210811-09:47:14] [INFO ] sesman connect ok
[20210811-09:47:14] [INFO ] sending login info to session manager, please wait...
[20210811-09:47:14] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20210811-09:47:14] [INFO ] login successful for display 10
[20210811-09:47:14] [INFO ] loaded module 'libxup.so' ok, interface size 10288, version 4
[20210811-09:47:14] [INFO ] started connecting
[20210811-09:47:14] [INFO ] lib_mod_connect: connecting via UNIX socket
[20210811-09:47:14] [INFO ] lib_mod_log_peer: xrdp_pid=27409 connected to X11rdp_pid=13615 X11rdp_uid=1023 X11rdp_gid=1024 client_ip=127.0.0.1 client_port=54306
[20210811-09:47:14] [INFO ] connected ok
```

.xorgxrdp.10.log
```
[ 88005.901] rdpClientConGotConnection:
[ 88005.901] rdpClientConGotConnection: g_sck_accept ok new_sck 7
[ 88005.901] rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
[ 88005.901] rdpAddClientConToDev: adding first clientCon 0x5584187b4350
[ 88005.909] rdpClientConProcessMsgVersion: version 0 0 0 1
[ 88005.909] rdpClientConProcessScreenSizeMsg: set width 1280 height 1024 bpp 24
[ 88005.910] rdpClientConProcessScreenSizeMsg: shmemid 6127629 shmemptr 0x7faa2bb00000
[ 88005.910] rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1280 cy 1024
[ 88005.918] KbdSync: toggling num lock
[ 88005.918] rdpClientConProcessMsgClientInfo:
[ 88005.918]   got client info bytes 7064
[ 88005.918]   jpeg support 0
[ 88005.918]   offscreen support 0
[ 88005.918]   offscreen size 0
[ 88005.918]   offscreen entries 0
[ 88005.918]   client can not do offscreen to offscreen blits
[ 88005.918]   client can do new(color) cursor
[ 88005.918]   client can not do multimon
[ 88005.918] rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
[ 88005.918] rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1280 height 1024
[ 88005.918] rdpRRUpdateOutput:
[ 88005.918] rdpLoadLayout: keylayout 0x00000407 variant  display 10
[ 88005.918] rdpkeybChangeKeyboardControl:
[ 88005.918] rdpkeybChangeKeyboardControl: autoRepeat on
[ 88005.919] rdpkeybChangeKeyboardControl:
[ 88005.919] rdpkeybChangeKeyboardControl: autoRepeat on
[ 88005.919] rdpkeybChangeKeyboardControl:
[ 88005.919] rdpkeybChangeKeyboardControl: autoRepeat on
[ 88005.919] rdpkeybChangeKeyboardControl:
[ 88005.919] rdpkeybChangeKeyboardControl: autoRepeat on
[ 88006.018] rdpInDeferredRepeatCallback:
[ 88006.018] rdpkeybChangeKeyboardControl:
[ 88006.018] rdpkeybChangeKeyboardControl: autoRepeat off
[ 88006.019] rdpInDeferredRepeatCallback:
[ 88006.019] rdpkeybChangeKeyboardControl:
[ 88006.019] rdpkeybChangeKeyboardControl: autoRepeat off
[ 88006.019] rdpInDeferredRepeatCallback:
[ 88006.019] rdpkeybChangeKeyboardControl:
[ 88006.019] rdpkeybChangeKeyboardControl: autoRepeat off
[ 88006.019] rdpInDeferredRepeatCallback:
[ 88006.019] rdpkeybChangeKeyboardControl:
[ 88006.019] rdpkeybChangeKeyboardControl: autoRepeat off
```

Is choosing "Xorg" correct for my setup? Shouldn't I choose "neutrinordp-any"? And if so, would I need to set a lib= as suggested in the error message from https://github.com/neutrinolabs/xrdp/issues/1964#issuecomment-895849032 ?

**Comment by matt335672** [comment] 2021-08-11 09:23
Hi @saddy001 

Something occurred to me last night. I was about to post another idea for you (below), but your post came in first. I'll address yours first.

The purpose of `neutrinordp-any` is to allow xrdp to function as a proxy for other RDP servers (normally Windows machines). To use it, you need to build the `libxrdpneutrinordp.so` module which isn't provided by default. Since it's not available, you'll get the error messages in https://github.com/neutrinolabs/xrdp/issues/1964#issuecomment-895849032 if you try to use it.

I suspect the blue screen is resulting as xrdp on your system has gotten a bit confused, probably as a result of the things I've been asking you to try. The number in square brackets on each line in `.xorgxdp.10.log` is the number of seconds since the X server was started. That X server has been running for a day now. I suggest you stop the `xrdp` service, kill any outstanding `Xorg` processes, and restart the `xrdp` service.

The thing that occurred to me last night was I remembered #1906. I'm wondering if your problem is another manifestation of this fault. It sounds like it might be.

We can rule #1906 out by setting the session depth to 24 bit in Guacamole:-

![tmp](https://user-images.githubusercontent.com/30179339/129003494-859e06bd-14b8-4abd-9ee2-5329b56bc597.png)

Sorry this is coming across in a bit of a confusing order. It entirely up to you of course, but I'd suggest ruling out the colour depth first.

**Comment by saddy001** [comment] 2021-08-11 09:56
Nope, didn't change anything ;-)
I also tried changing the resize method (pretty new?) but it's the same either.
Thanks for you investigation. Since I believe to have a workaround and it's a minor bug, you can low-prioritize the issue or even close and try to fix it during a later feature implementation.

**Comment by matt335672** [comment] 2021-08-11 10:04
Well it bothers me that we're not actually able to work out where the fault actually lies. At the moment it could be Guacamole, xrdp, xorgxrdp, or even your application expose event processing. 

I'd like to get that far at least, if you're able and willing to do so.

Can you post the xrdp.log after a successful connection from Guacamole, and also your xrdp.ini? I think it might be worth switching over to the Xvnc backend to see what happens. If you provide that info, I'll give you all the steps you need to try that.

**Comment by saddy001** [comment] 2021-08-11 10:50
Successful login from guac with screen appearing instantly:
```
[20210811-12:41:40] [INFO ] Socket 12: AF_INET connection received from 127.0.0.1 port 54822
[20210811-12:41:40] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20210811-12:41:40] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20210811-12:41:40] [INFO ] Connected client computer name: Guacamole RDP
[20210811-12:41:40] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20210811-12:41:40] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20210811-12:41:40] [INFO ] xrdp_load_keyboard_layout: keyboard_type [4] keyboard_subtype [0]
[20210811-12:41:40] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [de] options []
[20210811-12:41:40] [INFO ] TLS connection established from 127.0.0.1 port 54822: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
[20210811-12:41:40] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20210811-12:41:40] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 7864320 MB cache entries 2000
[20210811-12:41:40] [WARN ] Client Capability: not enough orders supported by client, client wants off screen bitmap but offscreen bitmaps disabled
[20210811-12:41:40] [INFO ] Loading keymap file /etc/xrdp/km-00000407.ini
[20210811-12:41:40] [WARN ] local keymap file for 0x00000407 found and doesn't match built in keymap, using local keymap file
[20210811-12:41:40] [INFO ] connecting to sesman ip 127.0.0.1 port 3350
[20210811-12:41:40] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20210811-12:41:40] [INFO ] sesman connect ok
[20210811-12:41:40] [INFO ] sending login info to session manager, please wait...
[20210811-12:41:40] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20210811-12:41:40] [INFO ] login successful for display 10
[20210811-12:41:41] [INFO ] loaded module 'libxup.so' ok, interface size 10288, version 4
[20210811-12:41:41] [INFO ] started connecting
[20210811-12:41:41] [INFO ] lib_mod_connect: connecting via UNIX socket
[20210811-12:41:41] [INFO ] lib_mod_log_peer: xrdp_pid=29200 connected to X11rdp_pid=29230 X11rdp_uid=1023 X11rdp_gid=1024 client_ip=127.0.0.1 client_port=54822
[20210811-12:41:41] [INFO ] connected ok
```

/etc/xrdp/xrdp.ini (it's the default that comes with xrdp)
```
[Globals]
; xrdp.ini file version number
ini_version=1

; fork a new process for each incoming connection
fork=true

; ports to listen on, number alone means listen on all interfaces
; 0.0.0.0 or :: if ipv6 is configured
; space between multiple occurrences
; ALL specified interfaces must be UP when xrdp starts, otherwise xrdp will fail to start
;
; Examples:
;   port=3389
;   port=unix://./tmp/xrdp.socket
;   port=tcp://.:3389                           127.0.0.1:3389
;   port=tcp://:3389                            *:3389
;   port=tcp://<any ipv4 format addr>:3389      192.168.1.1:3389
;   port=tcp6://.:3389                          ::1:3389
;   port=tcp6://:3389                           *:3389
;   port=tcp6://{<any ipv6 format addr>}:3389   {FC00:0:0:0:0:0:0:1}:3389
;   port=vsock://<cid>:<port>
port=3389

; 'port' above should be connected to with vsock instead of tcp
; use this only with number alone in port above
; prefer use vsock://<cid>:<port> above
use_vsock=false

; regulate if the listening socket use socket option tcp_nodelay
; no buffering will be performed in the TCP stack
tcp_nodelay=true

; regulate if the listening socket use socket option keepalive
; if the network connection disappear without close messages the connection will be closed
tcp_keepalive=true

; set tcp send/recv buffer (for experts)
#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768

; security layer can be 'tls', 'rdp' or 'negotiate'
; for client compatible layer
security_layer=negotiate

; minimum security level allowed for client for classic RDP encryption
; use tls_ciphers to configure TLS encryption
; can be 'none', 'low', 'medium', 'high', 'fips'
crypt_level=high

; X.509 certificate and private key
; openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
certificate=
key_file=

; set SSL protocols
; can be comma separated list of 'SSLv3', 'TLSv1', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'
ssl_protocols=TLSv1.2, TLSv1.3
; set TLS cipher suites
#tls_ciphers=HIGH

; concats the domain name to the user if set for authentication with the separator
; for example when the server is multi homed with SSSd
#domain_user_separator=@

; Section name to use for automatic login if the client sends username
; and password. If empty, the domain name sent by the client is used.
; If empty and no domain name is given, the first suitable section in
; this file will be used.
autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
#hidelogwindow=true
max_bpp=32
new_cursors=true
; fastpath - can be 'input', 'output', 'both', 'none'
use_fastpath=both
; when true, userid/password *must* be passed on cmd line
#require_credentials=true
; when true, the userid will be used to try to authenticate
#enable_token_login=true
; You can set the PAM error text in a gateway setup (MAX 256 chars)
#pamerrortxt=change your password according to policy at http://url

;
; colors used by windows in RGB format
;
blue=009cb5
grey=dedede
#black=000000
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72

;
; configure login screen
;

; Login Screen Window Title
#ls_title=My Login Title

; top level window background color in RGB format
ls_top_window_bg_color=009cb5

; width and height of login screen
ls_width=350
ls_height=430

; login screen background color in RGB format
ls_bg_color=dedede

; optional background image filename (bmp format).
#ls_background_image=

; logo
; full path to bmp-file or file in shared folder
ls_logo_filename=
ls_logo_x_pos=55
ls_logo_y_pos=50

; for positioning labels such as username, password etc
ls_label_x_pos=30
ls_label_width=65

; for positioning text and combo boxes next to above labels
ls_input_x_pos=110
ls_input_width=210

; y pos for first label and combo box
ls_input_y_pos=220

; OK button
ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=370
ls_btn_ok_width=85
ls_btn_ok_height=30

; Cancel button
ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=370
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
; Note: Log levels can be any of: core, error, warning, info, debug, or trace
LogFile=xrdp.log
LogLevel=INFO
EnableSyslog=true
#SyslogLevel=INFO
#EnableConsole=false
#ConsoleLevel=INFO
#EnableProcessId=false

[LoggingPerLogger]
; Note: per logger configuration is only used in XRDP_DEBUG builds of XRDP.
#xrdp.c=INFO
#main()=INFO

[Channels]
; Channel names not listed here will be blocked by XRDP.
; You can block any channel by setting its value to false.
; IMPORTANT! All channels are not supported in all use
; cases even if you set all values to true.
; You can override these settings on each session type
; These settings are only used if allow_channels=true
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

; for debugging xrdp, in section xrdp1, change port=-1 to this:
#port=/tmp/.xrdp/xrdp_display_10


;
; Session types
;

; Some session types such as Xorg, X11rdp and Xvnc start a display server.
; Startup command-line parameters for the display server are configured
; in sesman.ini. See and configure also sesman.ini.
[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20

[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=-1
#xserverbpp=24
#delay_ms=2000
; Disable requested encodings to support buggy VNC servers
; (1 = ExtendedDesktopSize)
#disabled_encodings_mask=0
; Use this to connect to a chansrv instance created outside of sesman
; (e.g. as part of an x11vnc console session). Replace '0' with the
; display number of the session
#chansrvport=DISPLAY(0)

[vnc-any]
name=vnc-any
lib=libvnc.so
ip=ask
port=ask5900
username=na
password=ask
#pamusername=asksame
#pampassword=asksame
#pamsessionmng=127.0.0.1
#delay_ms=2000

[neutrinordp-any]
name=neutrinordp-any
lib=libxrdpneutrinordp.so
ip=ask
port=ask3389
username=ask
password=ask
; Currently NeutrinoRDP doesn't support dynamic resizing. Uncomment
; this line if you're using a client which does.
#enable_dynamic_resizing=false

; You can override the common channel settings for each session type
#channel.rdpdr=true
#channel.rdpsnd=true
#channel.drdynvc=true
#channel.cliprdr=true
#channel.rail=true
#channel.xrdpvr=true
```
As I said I wouldn't like to make breaking changes (Xvnc) to the system as it runs fine.

**Comment by matt335672** [comment] 2021-08-11 13:20
Thanks,

Looking at the log file, you're using the `Xorg` backend :-

```
[20210811-12:41:41] [INFO ] loaded module 'libxup.so' ok, interface size 10288, version 4
```

So we can try the VNC backend if you're willing. I understand that this must be possible to back out. I suggest you read the whole of this message and then make a decision as to whether you want to go further with this.

I note that you're using Ubuntu 16.04. This is out of standard support but in extended support. I don't know what the status of the mirrors are for it.

First thing is to see if you've got a VNC server installed. This can be done with this command:-

```
Xvnc --help
```

If you get some sort of output a VNC server is installed. If you get `command not found`, one isn't.

If no VNC server is installed, you can install one with `sudo apt install tigervnc-standalone-server`. This may or may not work, depending on whether your mirrors are still carrying 16.04. If they are, `tigervnc-standalone-server` will be installed, plus any dependent packages. Make a note of all the packages that are installed.

Once the VNC server is installed, swap over to using it as follows:-
- Copy `/etc/xrdp/xrdp.ini` to `/etc/xrdp/xrdp.ini.sav`
- Edit `/etc/xrdp/xrdp.ini` and use `#` characters to comment out these lines:-
   ```
   #[Xorg]
   #name=Xorg
   #lib=libxup.so
   #username=ask
   #password=ask
   #ip=127.0.0.1
   #port=-1
   #code=20
   ```
   The next stanza should be `[Xvnc]`, and Guacamole will default to using this
- Restart the `xrdp` service

Try to connect from Guacamole and see what happens.

To revert:-
- Copy `/etc/xrdp/xrdp.ini.sav` to `/etc/xrdp/xrdp.ini`
- Restart the `xrdp` service
- Use `sudo apt remove tigervnc-standalone-server` to remove the VNC server (if you installed it)
- Use `sudo apt remove ...` to remove any additional packages that were installed along with the VNC server.

**Comment by saddy001** [comment] 2021-08-11 15:52
> I note that you're using Ubuntu 16.04

It's Ubuntu 18.04.

```
# lsb_release -a
Description:	Ubuntu 18.04.5 LTS
Codename:	bionic
```
I did the changes you mentioned.
Result: The Xvnc backend doesn't have the same problem, the screen is immediately shown on reconnection. Colors are slightly off. Mouse cursor is just 4 dots when reconnecting, but not on initial connect. Performance is markedly worse.

Okay, the problem is specific to the Xorg backend. What's next? ;-)

**Comment by matt335672** [comment] 2021-08-11 16:19
Identifying the faulty component is definitely progress. Thanks for making the changes.

I'm sure we can get the VNC colours sorted out, but if the performance is worse there's little point. Let's discount that option.

Having a look through the xorgxrdp issues and PRs, I've come across neutrinolabs/xorgxrdp#186. This could well be DAMAGE related.

Looking at your previous posts, you're more than capable of compiling xorgxrdp. Would you like to try J's PR? Let me know if you need a hand.

**Comment by saddy001** [comment] 2021-08-12 08:05
I used the branch https://github.com/jsorg71/xorgxrdp/tree/damage which fixes this issue. Idle and busy network load is the same for xorgxrdp v*.16 and the branch.

**Comment by matt335672** [comment] 2021-08-12 09:08
That's great news - thanks for sticking with my blundering about, and I'm glad we found a solution to your problem. Also, thanks for the interesting discussion.

I see you've added a comment to the PR which should close this issue automatically when it gets merged.

**Comment by FlintRiverSystems** [comment] 2021-09-16 21:28
I ran into this issue and I've found a different way to reproduce it.  

I set up a fresh ubuntu 20.04 vm, cloned the latest xrdp and xorgxrdp from github, built and installed them, and got it all working as expected using the Xorg backend.

I connected using xfreerdp running on the same vm and established a session.  It's important that the session be completely static with nothing changing, not even a blinking cursor.  In my case, I'm using 

`xfreerdp ... /shell:"/usr/bin/google-chrome about.google"` (i know, using chrome is a bit overkill, but...)

So far so good.  Everything working as expected.

Now, without closing the first session, in another terminal I run the same xfreerdp command to steal the session from the first xfreerdp instance.  Sometimes it works but usually I get a black screen instead of chrome and it does not show the chrome window until I move the mouse cursor over it.

Doing a bit of a manual bisect, I traced the problem to this commit: https://github.com/neutrinolabs/xorgxrdp/commit/aff6ef80c917e764acc65d741a29ebf9740adafd

In particular it's the 

`if (clientCon->shmemstatus == SHM_UNINITIALIZED || clientCon->shmemstatus == SHM_RESIZING) {
  ...
  return 0;
}`

at line 2465+ in rdpClientCon.c.  It seems that, when stealing a session, most of the time `shmemstatus` is `SHM_RESIZING` on the very first call to `rdpDeferredUpdateCallback` and so it skips it.

I don't understand xorgxrdp well enough to know how to fix this correctly so I'll leave that to the experts.

**Comment by Nexarian** [comment] 2021-09-16 23:31
I wrote that line, though I wouldn't necessarily call myself an expert. I'm closer to a devoted fan who has debugged XRDP with lots of blood, sweat, and tears.

The reason for that fix is due to the need for the memory buffer status to be consistent with what's in it. Without this, resize-on-the-fly is unstable with xorgxrdp.

If you remove that line, does this issue go away? I'd be surprised if it does, because SHM_RESIZING means that nothing has initialized the shared memory buffer yet. So instead of a black screen, you should get a segfault.

I'm happy to work through this with you, however.

**Comment by saddy001** [comment] 2021-09-17 07:20
Also interesting: What does the damage branch do differently to shmemstatus

**Comment by FlintRiverSystems** [comment] 2021-09-17 16:13
It does not crash if I comment out that line and the problem does go away.  But I agree with you that that line is necessary.

I did a little more digging and I think I see what's going on.  According to the xorg log, things are happening in this order:
- `rdpClientConProcessScreenSizeMsg` is setting `shmemstatus` to `SHM_RESIZING` and allocating some shared memory
- `rdpDeferredUpdateCallback` is called but exits early because of `shmemstatus`
- `rdpClientConProcessMsgClientInfo` is then called, which reallocates the shared memory only if RFX or H264 are active, and then sets `shmemstatus` appropriately
- since the screen is static, no further updates are sent to the client until client input is received

Because I'm not using RFX or H264, the shared memory allocated in `rdpClientConProcessScreenSizeMsg` is sufficient and the check in `rdpDeferredUpdateCallback` is not necessary.  But I don't think that will be the case if either of RFX or H264 are active.

So, I propose that we leave your commit intact and just invalidate the entire screen at the end of `rdpClientConProcessMsgClientInfo`:

	rdpClientConAddDirtyScreen(dev, clientCon, 0, 0, clientCon->rdp_width, clientCon->rdp_height);

That seems to take care of the black screen problem for me but I don't know if it will have unintended side effects.

@saddy001, the damage branch does not include the commit in question so it does not even have the `shmemstatus` variable.

**Comment by Nexarian** [comment] 2021-09-20 07:05
I think that fix is reasonable. Invalidate is a pretty benign operation, and is called frequently throughout xorgxrdp. I struggle to think of any reason this might be bad. In addition, rdpClientConProcessMsgClientInfo is not a common operation. If it was invoked frequently we could have an issue, but it's not. Submit a PR and you'll get my approval, and excellent work!

The damage branch is interesting. It shouldn't be necessary since, in theory, all xorg drawing calls are supposed to be intercepted by xorgxrdp and then processed. The fact that damage is necessary is a bug because it means something is not intercepted that should be, unless damage IS the necessary way to intercept certain calls, which would be unfortunate.

I worry about damage causing performance issues, and I need to test that. I hope to get to that soon.

Also: If you're interested in how resize-on-the-fly works with the in progress hardware accelerated egfx branch, check these out:

https://github.com/jsorg71/xrdp/commit/3b45cddca0342aa8068962efd0b42463c398db7b
https://github.com/jsorg71/xrdp/pull/6

**Closed as completed** 2021-09-21 14:41 UTC
