### ISSUE TITLE
xRDP 0.9.10 and OSX 10.14.5 and MSRD client 10.2.13 No text in login debug window

### ISSUE THREAD

**Issue by tastle73** [neutrinolabs/xrdp#1356] opened 2019-06-03 14:29 UTC
I just upgraded to the 0.9.10 version from EPEL running on CentOS 7, fully patched.

For some reason, there seems to have been a regression where the login screen fonts are working, however the text in the login "debug" progress screen is missing.

I will send any other info you need to debug.

Thanks

**Comment by metalefty** [comment] 2019-06-13 00:56
Could you show us the screenshot?

**Comment by tastle73** [comment] 2019-06-13 19:35
One shot is the login dialog, fonts work there. 

The other is the login debug screen with nothing in it.

**Comment by tastle73** [comment] 2019-06-13 19:36
<img width="1623" alt="Screen Shot 2019-06-13 at 3 32 39 PM" src="https://user-images.githubusercontent.com/2339489/59462141-090d1d80-8df1-11e9-9c50-01754d2a8561.png">
<img width="1625" alt="Screen Shot 2019-06-13 at 3 32 23 PM" src="https://user-images.githubusercontent.com/2339489/59462144-0c080e00-8df1-11e9-83a7-9341cadad3ab.png">

**Comment by esutton** [comment] 2020-04-13 18:20
+1

- Ubuntu 18.04 all updates and upgrades applied
- xrdp Version 0.9.5
- Microsoft Remote Desktop 10.3.9 on macOS 10.15.3

![Screen Shot 2020-04-13 at 1 18 04 PM](https://user-images.githubusercontent.com/6115047/79147234-3b790580-7d89-11ea-90ce-79d25cd457ca.png)

Anyone suggest any alternatives that work?  

Go back to using VNC?

**Comment by metalefty** [comment] 2020-04-14 01:03
@tastle73 @esutton I looked into the issue, your issue looks identical but have different root cause.

Regarding @esutton 's issue, it is already fixed 2 years ago at #643, v0.9.9. However, you're using v0.9.5. Please always don't forget to confirm the issue with the latest release. That's all.

Regarding @tastle73 's issue, you didn't provide any client information. What client are you use?

**Comment by metalefty** [comment] 2020-04-14 01:12
At least it doesn't reproduce on my CentOS setup with
* Remote Decktop Client for Mac Version 10.3.8 (1747)
* FreeRDP 2.0.0-rc4

```
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
```

```
xrdp 0.9.13
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic
      LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by esutton** [comment] 2020-04-14 14:19
@metalefty My mistake.  I assumed Ubuntu 18.04 would pull latest rdp updates and that v0.9.5 was the latest update.  I guess Ubuntu 18.04 package manager is still delivering two year old packages.  I should have checked your github site.

Does anyone have tips on installing v0.9.9 on two-year old Ubuntu 18.04 LTS ?

Unfortunately I am stuck on Ubuntu 18.04 LTS for Linux embedded cross-compiling work.

**Comment by metalefty** [comment] 2020-04-15 00:25
> Regarding @tastle73 's issue, you didn't provide any client information. What client are you using?

My mistake, you provided client info in issue title. Sorry.

**Comment by esutton** [comment] 2020-04-15 14:05
xRDP – [Custom Installation Script for Ubuntu 18.xx – version 2.3](http://c-nergy.be/blog/?p=13432) installed xrdp v0.9.13 on Ubuntu 18.04

Now I can see the login screens and text, but as soon as I login, a black windows starts to expand, and then close before seeing the remote desktop?

Here's is what I tried:
````
./Install-xrdp-2.3.sh

# Restore keyboard and mouse input functionality broken by the script
sudo apt-get install --reinstall xserver-xorg-input-all
sudo reboot
````

**Comment by metalefty** [comment] 2020-04-22 04:51
I am not responsible for the contents written in that site so I don't breakdown the issue not installed official way. BTW, Ubuntu 20.04 (perhaps LTS) has come. What about trying 20.04?

**Comment by metalefty** [comment] 2021-04-26 16:13
Duplicate of #643.

**Closed by metalefty** 2021-04-26 16:13 UTC
Labels: duplicate
