### ISSUE TITLE
Pasting from client to host doesn't work when using with X11vnc backend

### ISSUE THREAD

**Issue by GoldenMouse** [neutrinolabs/xrdp#969] opened 2017-12-07 23:25 UTC
For our setup, we want to remote into the desktop (console). I setup so that X11vnc starts a session on 5900 on bootup. XRDP is able to connect this session (using Xvnc library). Everything works great except pasting from HOST into RDP client. Oddly, copying from RDP client works fine.  I've tried running vncconfig to no result.  This is using the compiled latest stable build from Github.

**Comment by matt335672** [comment] 2021-09-09 14:23
@GoldenMouse 

I believe this is a duplicate of #1616, and should be fixed in xrdp v0.9.17 which was released recently.

**Closed by matt335672** 2021-09-09 14:23 UTC
Labels: clipboard, vnc
