### ISSUE TITLE
Windows 11 RDC - Protocol error 0xd06 when server max_bpp<32

### ISSUE THREAD

**Issue by its-vincent** [neutrinolabs/xrdp#3128] opened 2024-06-19 10:53 UTC
### xrdp version

0.10.0

### Detailed xrdp version, build options

~~~
# xrdp -V
xrdp 0.10.0
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --build=x86_64-redhat-linux-gnu
      --host=x86_64-redhat-linux-gnu
      --program-prefix=
      --disable-dependency-tracking
      --prefix=/usr
      --exec-prefix=/usr
      --bindir=/usr/bin
      --sbindir=/usr/sbin
      --sysconfdir=/etc
      --datadir=/usr/share
      --includedir=/usr/include
      --libdir=/usr/lib64
      --libexecdir=/usr/libexec
      --localstatedir=/var
      --sharedstatedir=/var/lib
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-fuse
      --enable-pixman
      --enable-painter
      --enable-vsock
      --enable-ipv6
      --with-socketdir=/run/xrdp
      --with-imlib2
      build_alias=x86_64-redhat-linux-gnu
      host_alias=x86_64-redhat-linux-gnu
      CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
      CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

  Compiled with OpenSSL 1.1.1k  FIPS 25 Mar 2021

~~~

### Operating system & version

Rocky Linux 8.10

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

Xfce

### Environment xrdp running on

Microsoft Hyper-V VM

### What's your client?

Windows 11 Remote Desktop Connection

### Area(s) with issue?

Compatiblity aginst clients, Network

### Steps to reproduce

In the xrdp.ini file, set 

max_bpp=16 or 
max_bpp=24 

to reduce latency/overhead and restart the xrdp server.

Try to establish a connection from a default settings Windows 11 RDC client 
![Screenshot 2024-06-19 111015](https://github.com/neutrinolabs/xrdp/assets/73174230/20875ab5-d902-47b0-bec9-458007d07476)

The default settings have colour depth set to "Highest Quality (32 bit)" 

### ✔️ Expected Behavior

It is expected that the client and server will negotiate to agree to use the lower colour quality level configured on the server side. 

### ❌ Actual Behavior

With the default setting of max_bpp=32 in the xrdp.ini file, the Windows 11 RDC client with default colour settings ("Highest Quality (32 bit)" will successfully connect to the server. 

However, if the server max_bpp is reduced to 16/24 to reduce latency/overhead then the Windows 11 client will fail to connect. The window will open, display an error message: 

"Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again." 

The dropdown details show 

Error code: 0xd06
Extended error code: 0x0 

As soon as OK is pressed, the window closes. 

![Screenshot 2024-06-19 111111](https://github.com/neutrinolabs/xrdp/assets/73174230/26b1a829-3129-4437-b585-b6d9f831e789)

### Anything else?

Changing the windows client to any lower colour quality 
"True Colour (24 bit)" 
"High Colour (16 bit)"
"High Colour (15 bit)" 

will allow it to connect as expected - even if that colour quality is still higher than the setting configured on the server. 

The only combination that seems to be a problem is "Highest Quality (32 bit)" on the RDC client side with anything lower than max_bpp=32 configured on the server side.

**Comment by matt335672** [comment] 2024-06-19 14:19
Duplicate of #3118.

**Closed as completed by matt335672** 2024-06-19 14:19 UTC
Labels: bug
