### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by Whaiy** [neutrinolabs/xrdp#2558] opened 2023-02-19 04:06 UTC
xrdp on archlinux-aarch64  gnome

xrdp.log
```
20230217-22:37:56] [ERROR] SSL_read: I/O error
[20230217-22:37:56] [ERROR] libxrdp_force_read: header read error
[20230217-22:37:56] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20230217-22:37:56] [ERROR] [MCS Connection Sequence] receive connection request failed
[20230217-22:37:56] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20230217-22:37:56] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230217-22:37:56] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230217-22:37:56] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20230217-22:37:56] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20230217-22:37:56] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:192.168.31.208 port 51093[20230217-22:37:56] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230217-22:37:56] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230217-22:37:56] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20230217-22:37:56] [INFO ] Connected client computer name: LOADER
[20230217-22:37:56] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230217-22:37:56] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230217-22:37:56] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x07], keyboard_subtype:[0x00], keylayout:[0x00000804]
[20230217-22:37:56] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []        
[20230217-22:37:56] [INFO ] TLS connection established from ::ffff:192.168.31.208 port 51093: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20230217-22:37:57] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230217-22:37:57] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 5242880 MB cache 
entries 100
[20230217-22:37:57] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230217-22:37:57] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230217-22:37:57] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230217-22:37:57] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230217-22:37:57] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230217-22:37:57] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230217-22:37:57] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20230217-22:38:02] [INFO ] connecting to sesman on 127.0.0.1:3350
[20230217-22:38:02] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230217-22:38:02] [INFO ] sesman connect ok
[20230217-22:38:02] [INFO ] sending login info to session manager. Please wait...
[20230217-22:38:02] [INFO ] xrdp_wm_log_msg: login successful for user testu on display 10
[20230217-22:38:02] [INFO ] login successful for user testu on display 10
[20230217-22:38:02] [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
[20230217-22:38:02] [INFO ] started connecting
[20230217-22:38:02] [INFO ] lib_mod_connect: connecting via UNIX socket

```

xrdp-sesman.log
```

[20230217-22:36:59] [INFO ] starting xrdp-sesman with pid 1550
[20230217-22:38:02] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 39968
[20230217-22:38:02] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20230217-22:38:02] [INFO ] ++ created session (access granted): username testu, ip ::ffff:192.168.31.208:51093 - socket: 12
[20230217-22:38:02] [INFO ] starting Xorg session...
[20230217-22:38:02] [INFO ] Starting session: session_pid 1568, display :10.0, width 1440, height 900, bpp 24, client ip ::ffff:192.168.31.208:51093 - socket: 12, user name testu
[20230217-22:38:02] [INFO ] [session start] (display 10): calling auth_start_session from pid 1568       
[20230217-22:38:02] [ERROR] sesman_data_in: scp_process_msg failed
[20230217-22:38:02] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230217-22:38:12] [WARN ] Timed out waiting for X server on display 10 to startup
[20230217-22:38:12] [WARN ] Timed out waiting for X server on display 10 to startup
[20230217-22:38:12] [INFO ] Session started successfully for user testu on display 10
[20230217-22:38:12] [INFO ] Session in progress on display 10, waiting until the window manager (pid 1569) exits to end the session
[20230217-22:38:12] [INFO ] Starting the xrdp channel server for display 10
[20230217-22:38:12] [ERROR] There is no X server active on display 10
[20230217-22:38:12] [ERROR] A fatal error has occurred attempting to start the window manager on display 
10, aborting connection
[20230217-22:38:12] [WARN ] Window manager (pid 1569, display 10) exited quickly (0 secs). This could indicate a window manager config problem
[20230217-22:38:12] [INFO ] Calling auth_stop_session and auth_end from pid 1568
[20230217-22:38:12] [INFO ] Terminating X server (pid 1570) on display 10
[20230217-22:38:12] [INFO ] Terminating the xrdp channel server (pid 1577) on display 10
[20230217-22:38:22] [INFO ] Starting X server on display 10: Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20230217-22:38:22] [INFO ] X server on display 10 (pid 1570) returned exit code 1 and signal number 0   
[20230217-22:38:22] [INFO ] xrdp channel server for display 10 (pid 1577) exit code 1 and signal number 0[20230217-22:38:22] [INFO ] cleanup_sockets:
[20230217-22:38:22] [INFO ] Process 1568 has exited
[20230217-22:38:22] [INFO ] ++ terminated session:  username testu, display :10.0, session_pid 1568, ip ::ffff:192.168.31.208:51093 - socket: 12
```

client bluescreen
```
connecting sesman ok
login use on display 10 ok
connection problem,giving up
error connectin to user session
```

**Comment by matt335672** [comment] 2023-02-20 14:01
Looks like a duplicate of ~~#2553~~ #2253

**Comment by metalefty** [comment] 2023-02-21 00:25
@matt335672 wrong issue number?

**Comment by matt335672** [comment] 2023-02-21 11:42
Quite right - thanks. Comment above updated.

**Comment by Whaiy** [comment] 2023-02-27 14:25
really thanks, complete solve that problem

**Closed as completed** 2023-02-27 14:25 UTC
Labels: duplicate
