### ISSUE TITLE
Windows Remote Desktop will close session after I enter username and password 

### ISSUE THREAD

**Issue by MehdiSalari** [neutrinolabs/xrdp#1881] opened 2021-05-09 23:38 UTC
after enter ip windows remote desktop, xrdp login page is open and after enter my username and password remote desktop session will close.

**Comment by matt335672** [comment] 2021-05-10 09:29
Hi @Mahdi-Slr79

First think to say is I've removed your video link as it appears to contain information about a publically open network port which I don't believe should be shared on the public internet. Please PM me on Gitter if you want more info on this.

**Comment by matt335672** [comment] 2021-05-10 09:34
As to your actual problem (which can be discussed publicly):-
- xrdp won't allow root logins at all. This explains the first bit of your video.
- There are quite a few reasons why you may be experiencing the behaviour you're seeing when you try to log in as `mehdi`. We'll need more information to help you though:-

1. What OS are you running on the target?
2. Have you installed xrdp from a package or from source?
3. (if installed from a package) Have you also installed xordxrdp?

Thanks

**Comment by matt335672** [comment] 2021-05-18 17:25
@Mahdi-Slr79 - do you need more help with this?

**Comment by spitzd** [comment] 2021-10-07 06:54
Hi Matt,

I'm hoping you can help with the below. 

I'm encountering the same issue (enter non-root credentials, accept certificate warning, nothing happens) as above after running an update on my virtual machine. I am connecting to my VM using Microsoft Remote Desktop on MacOS. The below is the output of the log from the connection attempt. 

[20211007-10:44:52] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:192.168.1.104 port 64126
[20211007-10:44:52] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.158 port 3389)
[20211007-10:44:52] [DEBUG] Closed socket 11 (AF_INET6 :: port 3389)
[20211007-10:44:52] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20211007-10:44:52] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20211007-10:44:52] [DEBUG] TLSv1.3 enabled
[20211007-10:44:52] [DEBUG] TLSv1.2 enabled
[20211007-10:44:52] [DEBUG] Security layer: requested 11, selected 1
[20211007-10:44:58] [INFO ] connected client computer name: OBFUSCATED
[20211007-10:44:58] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0x80800000
[20211007-10:44:58] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
[20211007-10:44:58] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
[20211007-10:44:58] [INFO ] adding channel item name drdynvc chan_id 1007 flags 0xc0800000
[20211007-10:44:58] [INFO ] TLS connection established from ::ffff:192.168.1.104 port 64126: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20211007-10:44:58] [DEBUG] xrdp_00000970_wm_login_mode_event_00000001
[20211007-10:44:58] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20211007-10:44:58] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
[20211007-10:44:58] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20211007-10:44:58] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20211007-10:44:58] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20211007-10:44:58] [DEBUG] return value from xrdp_mm_connect 0
[20211007-10:44:58] [INFO ] xrdp_wm_log_msg: login successful for display 15
[20211007-10:44:58] [DEBUG] xrdp_wm_log_msg: started connecting
[20211007-10:44:59] [INFO ] lib_mod_log_peer: xrdp_pid=2416 connected to X11rdp_pid=2441 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=::ffff:192.168.1.104 client_port=64126
[20211007-10:44:59] [DEBUG] xrdp_wm_log_msg: connected ok
[20211007-10:44:59] [DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
[20211007-10:44:59] [DEBUG] Closed socket 18 (AF_INET6 ::1 port 35192)
[20211007-10:44:59] [DEBUG] Closed socket 12 (AF_INET6 ::ffff:192.168.1.158 port 3389)
[20211007-10:44:59] [DEBUG] xrdp_mm_module_cleanup
[20211007-10:44:59] [DEBUG] Closed socket 19 (AF_UNIX)
[20211007-10:44:59] [DEBUG] Closed socket 20 (AF_UNIX)

Been researching this and looks similar to this maybe, https://github.com/neutrinolabs/xrdp/issues/1490? I could not try the suggestion "Glyph Cache" cause I don't see it on the Microsoft Remote Desktop client. 

Any help would be greatly appreciated. 

Many Thanks,
Denver

**Comment by matt335672** [comment] 2021-10-07 09:32
Your log looks clean to me.

A few questions:-
- What do you mean by 'nothing happens'. Are you at a blue screen?
- What OS are you running?
- What does `~/.xorgxrdp.15.log` contain?

Thanks.

**Comment by spitzd** [comment] 2021-10-07 09:56
- Nothing happens in the sense that the authentication prompt disappears and no RDP session is opened. Just returns back to the Microsoft Remote Desktop app
- MacOS Catalina v10.15.7
- Please see attached

[xorgxrdp.13.log](https://github.com/neutrinolabs/xrdp/files/7301486/xorgxrdp.13.log)
[xsession-errors.log](https://github.com/neutrinolabs/xrdp/files/7301488/xsession-errors.log)

Please let me know if you need anything else and thank you for the quick response!!

**Comment by matt335672** [comment] 2021-10-07 10:29
Sorry - I meant what OS are you running on your VM.

Your problem seems to be here:-

```
[  8687.838] expected xrdp client_info version 20210723, got 32
[  8687.838] (EE) 
Fatal server error:
[  8687.838] (EE) Incompatible xrdp version detected  - please recompile(EE) 
[  8687.838] (EE) 
```

It looks like your version of xorgxrdp was built against v0.9.17 of xrdp. However the version of xrdp you are running seems to be older than v0.9.16. Does that make sense at all?

**Comment by spitzd** [comment] 2021-10-07 10:50
That makes sense and I've now updated it. 

OLD
dspitz@kali-server:~# sudo apt list xrdp -a
Listing... Done
xrdp/kali-rolling 0.9.17-1 amd64 [upgradable from: 0.9.12-1.1]
xrdp/now 0.9.12-1.1 amd64 [installed,upgradable to: 0.9.17-1]

NEW
dspitz@kali-server:~# sudo apt list xrdp -a
Listing... Done
xrdp/kali-rolling,now 0.9.17-1 amd64 [installed]

It's now working as expected! Thank you very much Matt, appreciate your quick response on this.

**Comment by matt335672** [comment] 2021-10-07 10:54
Thanks for the swift response - it really helps with the house-keeping.

I'm closing this issue now, as the OP hasn't responded since the initial issue was raised.

**Closed as completed by matt335672** 2021-10-07 10:54 UTC
Labels: question or troubleshoot

**Comment by Explorare** [comment] 2025-01-11 01:45
Got the exact same issue today after a rolling update on Arch, the issue is that the [xorgxrdp-glamor](https://aur.archlinux.org/packages/xorgxrdp-glamor) is unmaintained and outdated. 
```
5 aur/xorgxrdp-devel-git 0.10.0.r14.gaf43a8b-1 (+2 0.00)
    Xorg drivers for xrdp
4 aur/xorgxrdp-nvidia 0.2.18.r49.g3d30c7a-1 (+5 0.00)
    Xorg drivers for xrdp, with NVIDIA GPU support.
3 aur/xorgxrdp-glamor 0.10.1-1 (+6 0.66) (Out-of-date: 2024-12-26)
    Xorg drivers for xrdp, with glamor enabled. Only works on Intel and AMD GPUs.
2 aur/xorgxrdp-git 0.10.1.r24.g4c25520-1 (+13 0.00)
    Xorg drivers for xrdp. Git version, devel branch.
1 aur/xorgxrdp 0.10.3-1 (+17 0.80)
    Xorg drivers for xrdp
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```
Replace it with [xorgxrdp](https://aur.archlinux.org/packages/xorgxrdp) solved the problem.
