### ISSUE TITLE
one user one session , is it possible?

### ISSUE THREAD

**Issue by tenhow** [neutrinolabs/xrdp#1300] opened 2019-02-28 17:11 UTC
I'd like to use xrdp with Xvnc backend from multiple machine with the same account.

0. I have a user `abc`
1. I want to use sesman to create a vnc screen  
2. I login into `abc` from mac
3. then I login into `abc` from pc
4. now, there are two sessions.
5. one user one session, possible?

Is there any configs could  help me to achieve this goal?

**Comment by metalefty** [comment] 2019-03-08 01:52
Change session policy in sesman.ini.

**Comment by tenhow** [comment] 2019-03-14 18:09
Is there any sample settings, sesman.ini seems simple but I cannot find a valid path to my need.

**Comment by tangjn** [comment] 2019-05-29 09:46
I think you can change below section, the path is /etc/ssh/sesman.ini

`;; Policy - session allocation policy
; Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]
; Default: Xrdp:<User,BitPerPixel> and Xvnc:<User,BitPerPixel,DisplaySize>
; "UBD" session per <User,BitPerPixel,DisplaySize>
; "UBI" session per <User,BitPerPixel,IPAddr>
; "UBC" session per <User,BitPerPixel,Connection>
; "UBDI" session per <User,BitPerPixel,DisplaySize,IPAddr>
; "UBDC" session per <User,BitPerPixel,DisplaySize,Connection>
Policy=Default
`

**Comment by abma** [comment] 2019-07-30 09:15
I don't see a policy which covers
`Xrdp:<User> and Xvnc:<User>`

i guess thats a feature request then?!

**Comment by metalefty** [comment] 2019-07-30 23:57
Currently, Xvnc session doesn't support session resizing. Thus `DisplaySize` cannot be removed.

**Comment by abma** [comment] 2019-07-31 06:56
idk if xrdp supports to run Real VNC server, but with it it seems possible:
https://stackoverflow.com/questions/15816/changing-the-resolution-of-a-vnc-session-in-linux

vnc4server seems to support it, too.

can the policy changed, so it can be configured by the type of session?

**Comment by abma** [comment] 2019-07-31 06:59
maybe this needs to be rephrased a bit:

the problem is, that sometimes users connecting with the same username and password get a new session. they should always get the same session, regardingless of the BitPerPixel / DisplaySize.

Most clients can handle when the rdp/vnc resolution is different to the screen resolution, i.e. by stretching the view.

**Comment by metalefty** [comment] 2019-07-31 09:23
I don't mean VNC doesn't support resizing but **xrdp's Xvnc session** doesn't use that VNC's resizing functionality. xrdp doesn't have a feature to tell VNC to resize that session right now.

Do you understand that? Some VNC supports resizing, yes, that's true. However, xrdp doesn't support resizing VNC session.

**Comment by metalefty** [comment] 2019-07-31 09:26
> the problem is, that sometimes users connecting with the same username and password get a new session.

To avoid getting a new session, use xorgxrdp instead of VNC. That's the easiest solution.

**Comment by jsorg71** [comment] 2019-07-31 18:05
We don't work much on the vnc client(libvnc) built into xrdp.  It was used heavily in the beginning before the X11rdp and not the Xorg xrdp back end were done.
But I'm not opposed to taking libvnc patches.  It's pretty amazing how many are still using it.
Possible fixes would be to
 1 resize the vnc server if it possible(not sure if any can).
 2 resize the rdp client to match the server.
But either way would take some coding.

**Comment by mtoupsUNO** [comment] 2020-01-03 20:31
I think one reason why many folks still use the libvnc client is that it performs better (lower latency). This is a very noticeable difference for our users. So we'd like to be able to use the same session policy as xorg `<User,BitPerPixel>` with libvnc.

I'd be interested in patching libvnc to support resizing. Would this code be in `vnc.c`? Thanks for any tips.

**Comment by matt335672** [comment] 2020-01-05 13:45
Hi @mtoupsUNO 

Support for resizeable VNC sessions (together with multiple screens) is a work in progress. See #259, #287 and #1343.

From what you're saying above, I think the functionality proposed in #1343 includes what you're after.

I'd suggest you look at the code for #1343 to decide whether or not it will work for you. If not, it will at least give you a good idea of the files you'll need to edit.

The code can be found either in the extended-vnc branch in the main repo, or from the branch of the same name in [https://github.com/matt335672/xrdp.git](https://github.com/matt335672/xrdp.git). It's currently based on v0.9.10 rather than 0.9.12. I'll pull the latest devel changes in to my own branch sometime this week, which may help.

You'll need to be using an Xvnc server which supports the `ExtendedDesktopSize` extension. Tiger VNC certainly does.

I hope that's useful. Let me know if you have any questions.

**Comment by metalefty** [comment] 2020-03-12 02:58
No feedback from the reporter, closing.

**Closed by metalefty** 2020-03-12 02:58 UTC
Labels: question, waiting-feedback

**Comment by mailinglists35** [comment] 2022-06-19 12:11
> Change session policy in sesman.ini.

to what?

(using xorgxrdp here)

If I disconnect then change mstsc.exe resolution I am logged again twice. I want to be able to disconnect at any resolution and reconnect at any other resolution without creating two sessions.

**Comment by mailinglists35** [comment] 2022-06-19 12:12
also, what does Connection mean in "; "UBC" session per <User,BitPerPixel,Connection>" ? what effect does it have?

**Comment by matt335672** [comment] 2022-06-20 07:39
@mailinglists35,

The 'Connection' is badly named in xrdp v0.9.x. See #2239. It doesn't do anything obvious.

For xorgxrdp, just set the Policy to Default and you should get single sessions per user. For Xvnc bckends this only works for xrdp v0.9.14 and later.
