### ISSUE TITLE
Using XRDP, VMD program text display is not normal;

### ISSUE THREAD

**Issue by liu-shaobo** [neutrinolabs/xrdp#2307] opened 2022-07-07 10:18 UTC
Hi, use CentOS-7.x or CentOS-8.x
VMD is a molecular visualization program for displaying, animating, and analyzing large biomolecular systems using 3-D graphics and built-in scripting. VMD supports computers running MacOS X, Unix, or Windows, is distributed free of charge, and includes source code.

When the RDP client is connected to the XRDP service, the VMD program will have unclear text display;
<img width="934" alt="image" src="https://user-images.githubusercontent.com/6166167/177749919-6836f074-b31d-4b83-bf41-e9c8d1c9ef6b.png">

vncview connects to vncerver, and the VMD program is displayed normally. <tigervnc>
<img width="700" alt="image" src="https://user-images.githubusercontent.com/6166167/177750398-50b34024-3195-4393-9008-1130417ed52a.png">

**Comment by matt335672** [comment] 2022-07-07 10:33
Possible duplicate of #1906.

Try setting your colour depth to 24 on the RDP client.

**Comment by liu-shaobo** [comment] 2022-07-12 10:27
Thanks ，I'm use remote desktop in mac, no suport depth to 24 , Windows use depth to 24 is normal.

**Comment by matt335672** [comment] 2022-07-15 11:06
See also TigerVNC/tigervnc#1308 which has a very similar issue. This doesn't appear to be an xrdp issue as such.

**Closed as completed** 2022-09-08 08:55 UTC
