### ISSUE TITLE
xrdp 0.10 + x11vnc on Raspberry Pi OS Bookworm 64-bit + Jump Desktop for macOS: screen redraw and scaling problems

### ISSUE THREAD

**Issue by usa-** [neutrinolabs/xrdp#3211] opened 2024-08-17 10:11 UTC
### xrdp version

v0.10.1

### Detailed xrdp version, build options

~~~
xrdp 0.10.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2024 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      

  Compiled with OpenSSL 3.0.13 30 Jan 2024
~~~

### Operating system & version

Debian GNU/Linux 12 (bookworm)

### Installation method

git clone & make install

### Which backend do you use?

Xvnc (x11vnc: 0.9.16 lastmod: 2019-01-05)

### What desktop environment do you use?

LXDE

### Environment xrdp running on

Paspberry Pi 4b

### What's your client?

Jump Desktop 8.10.7 for macOS

### Area(s) with issue?

Graphic glitches

### Steps to reproduce

sudo apt install x11vnc
x11vnc -storepasswd
Enter and save the password.

wget https://github.com/neutrinolabs/xrdp/releases/download/v0.10.1/xrdp-0.10.1.tar.gz
tar xvzf xrdp-0.10.1.tar.gz
cd xrdp-0.10.1
./bootstrap
./configure
make
sudo make install
cd ..

wget https://github.com/neutrinolabs/xorgxrdp/releases/download/v0.10.2/xorgxrdp-0.10.2.tar.gz
tar xvzf xorgxrdp-0.10.2.tar.gz
cd xorgxrdp-0.10.2
./bootstrap
./configure
make
sudo make install

Edit /etc/xrdp/xrdp.ini.
Remove all connection (backend) definitions.
Add a connection (backend) definition.

```
[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=5900
```

sudo systemctl daemon-reload
sudo service xrdp restart
x11vnc -display :0 -forever -repeat -noxdamage -usepw
Connect with Jump Desktop.

### ✔️ Expected Behavior

Screen is being redrawn properly on every connection

### ❌ Actual Behavior

On most connections, the screen is not being redrawn properly. For example, if I drag-and-drop an icon on the desktop with my mouse, it may partially appear in the new destination on the wallpaper may slightly change there. The screen is fully redrawn on the subsequent connection.

On some connections, the mouse cursor is displayed as a dot instead of an arrow, with the symptom described above still taking place.

On some connections, everything works just fine.

### Anything else?

The problem is specific to Jump Desktop for macOS.
Microsoft Remote Desktop for macOS does not have such problems.
Also, if I install xrdp v0.9.26 and xorgxrdp v0.9.20, I don't experience such problems even with Jump Desktop, too.

One more related problem. If I don't use the VNC password: remove the `--usepw` switch from x11vnc command line and change the xrdp conneciton definition to:

```
[Xvnc]
name=Xvnc
lib=libvnc.so
password=
ip=127.0.0.1
port=5900
```

and don't use autologon in Jump DEsktop, connect and just press the [OK] button in the logon window (which has no text fields), the remote desktop is not scaled down (the remote screen is larger than the local screen) and as a result, I see no taskbar. It is "under" my local screen.

But if I use any username and password in autologon and connect, then the logon window does not appear, and the screen is properly scaled.

**Comment by usa-** [comment] 2024-08-17 14:56
Remote Desktop Client for Windows 10: authentication screen shows in full screen, after logon desktop shown in the middle of the screen with a black border around.

RD Client for Android (Microsoft Remote Desktop in Play Store, com.microsoft.rdc.androidx) shows distorted screen on connection. However, mouse movements are transferred to the server.

RD Client for Android (old, was Microsoft Remote Desktop in Play Store, com.microsoft.rdc.android) usually shows black screen on connection. However, mouse movements are transferred to the server. On some connections works perfectly.

**Comment by matt335672** [comment] 2024-08-19 08:44
Try setting `max_bpp = 24` in your xrdp.ini. That should give you v0.9.x behaviour on v0.10.x

If you're using `x11vnc`, we can't control scaling. We have to accept the size that the physical screen is set to.

**Comment by usa-** [comment] 2024-08-19 11:54
> Try setting `max_bpp = 24` in your xrdp.ini. That should give you v0.9.x behaviour on v0.10.x

Thanks, it fixed redraw issues with most clients. Is it supposed to be a solution for all the future versions? If yes, then this is strange.

Unfortunately, it did not fix the problem with com.microsoft.rdc.androidx, the **modern** Android RD client. I've just checked this client with xrdp v0.9.x, it also shows garbish.

> If you're using `x11vnc`, we can't control scaling. We have to accept the size that the physical screen is set to.

Do you mean, that among all the Remote Desktop clients by Microsoft, only the one for Windows can not scale the remote desktop picture to the local desktop size at the client, without resizing the remote desktop itself at the server?

If yes, then:
1) Why can't xrdp get a smaller picture from VNC, scale it up and pass the scaled picture to the RD client?
2) What VNC server do you recommend, which does not have such a problem?

Remote Desktop clients by Microsoft for macOS and Android perform the scaling perfectly well.

**Comment by matt335672** [comment] 2024-08-19 13:16
I think you need to consider the architecture you're using here.

1) You're using `x11vnc` at the server. This simply provides a way to view an X11 desktop over the RFB protocol. To the best of my knowledge it does not provide a way to change the desktop size directly, although it can try to respond to desktop resizes produced in other ways (see `-xrandr` on [x11vnc(1)](https://linux.die.net/man/1/x11vnc)). It can also scale a desktop using `-scale`, but I think you'll need to enter this parameter when you start `x11vnc`.

2) In the mode you are running `xrdp`, it simply acts as a protocol converter between RFB protocol received from the X server and the RDP protocol passed to the client. xrdp does not interpret this stream, and does not implement any kind of scaling.

To your questions:-
1) Setting `max_bpp = 24` for VNC only connections will maximise portability by disabling some more complex RDP features. You seem to want to use a lot of different clients, so I'd recommend you set this regardless.
2) If you're getting garbage with v0.9.x, try playing with your client settings. v0.9.x is a pretty mature version now, so although it could be a problem with the server end, this is unlikely.
3) I don't believe mstsc.exe does any scaling, other than that provided by the Windows desktop as a whole. Try `mstsc.exe /?` from the command line to see what options are available.
4) We don't do scaling in xrdp. 
5) I'm not aware of any generic X11 <-> RFB interface other than `x11vnc`.


What you are trying to do can be made to work with xrdp, but it's not what we see most of our users doing. xrdp is intended as a remote desktop server, running a virtual desktop completely controlled by xrdp.

To put this another way, the only value that xrdp is offering if you run it like this is:-
1) A relatively secure way to connect to your VNC server
2) the possibility of using the chansrv functionality.

You might want to consider if this is the best product for your own use case(s). In particular, if you don't want or need the chansrv functionality, consider VNC tunnelled over SSH. There are a lot of products that support this setup, and you'll end up with a simpler configuration that way.

**Comment by usa-** [comment] 2024-08-20 10:19
> If you're getting garbage with v0.9.x, try playing with your client settings. v0.9.x is a pretty mature version now, so although it could be a problem with the server end, this is unlikely.

The latest xrdp version (0.10) also does not work properly (displays garbish) with **the only** official Microsoft Remote Desktop for Android. I only tried version 0.9 to check that it never worked properly in the past.

Don't you  think that's a problem?

I have different screen resolutions on my Raspberry, my Mac and my Windows machine. Let's assume that I only use official Microsoft Remote Desktop clients, and use them in full screen, to connect to my Raspberry running xrdp and x11vnc.
- When I connect from Mac, the remote screen fills the local screen (it is being scaled up).
- When I connect from Windows, the xrdp login screen shows first and **fills the local screen**. For an unknown reason, I can't bypass it with autologin. After I enter my credentials, the actual remote desktop appears and it does not fill the whole local screen, it has black borders around it.

Isn't the resolution of the xrdp login screen the problem? Shouldn't it be equal to the remote, not the local desktop resolution?

**Comment by usa-** [comment] 2024-08-20 11:04
I have found workarounds for the second problem, scaling small remote desktops to large local screens in full screen mode:

1. Copy `C:\Windows\System32\mstsc.exe` to `C:\Temp\X\ folder`, and `C:\Windows\System32\en-US\mstsc.exe.mui` to `C:\Temp\X\en-US\` folder, where `C:\Temp\X` is any folder, `en-US` is the current Windows language code. The **Compatibility** tab becomes available in the properties of the new exe file. On this tab, click **Change high DPI settings**, check **Operride high DPI scaling behavior** and set **Scaling performed by** to **System**. Problems: all other connections will be performed in low DPI mode, too.
2. Instead of the built-in **Remote Desktop Connection** program (`C:\Windows\System32\mstsc.exe`), use the [Microsoft Remote Desktop app from the Microsoft store](https://apps.microsoft.com/detail/9wzdncrfj3ps) and autologin. **Problems**: without autologin (presumably, when xrdp login screen is about to appear), it crashes.

**Comment by matt335672** [comment] 2024-08-20 17:16
To answer your blunt question - no. I don't think it's a problem, at least not one I can see here.

I've just taken these screenshots from version 10.0.19.1290 of `com.microsoft.rdc.androidx` talking to a v0.10.x build of xrdp. I didn't set anything special in the settings. Phone is running LineageOS 19 (Android 12) with a Snapdragon 625 chipset. I'm logging in to an XFCE desktop.

[Screenshot_20240820-174412_Microsoft Remote Desktop](https://github.com/user-attachments/assets/eec91dca-ca0b-4267-9ff7-a73d7f5bde2b)
[Screenshot_20240820-174829_Microsoft Remote Desktop](https://github.com/user-attachments/assets/f4cd2cfd-f773-4415-9b16-1671a1988b29)
[Screenshot_20240820-174910_Microsoft Remote Desktop](https://github.com/user-attachments/assets/931f772e-dbe5-49f7-90fd-b4b00728e7de)

I note the Microsoft Android client has mixed reviews. For what it's worth, I don't believe it's developed by the same Microsoft group which develop `mstsc.exe`. You might want to check another Android app (or device) maybe. Maybe aFreeRDP from the fdroid repo? It's build from the FreeRDP sources, and we use those a lot for testing.

For the login screen, we use the pixel resolution sent from the client, whatever that is. It may not match the screen resolution if the client isn't running full-screen. At login time we have nothing else to work with. The user may be connecting to any one of several user sessions, or starting a new session. We can't get a resolution from anywhere apart from the client. If the client's scaling output, we can't actually see that.

Thanks for your other observations. They may be useful to other users working with a similar setup.

**Comment by usa-** [comment] 2024-08-20 18:08
I am also a software developer (for over 30 years), and I never tell my users "it works for me".

Average user does not even know about F-Droid repository. They use the first Play Store hit, especially as it is from the same developer who created the RDP protocol and "who makes Windows".

But as I can't convince you to do something against your will, I have tried aFreeRDP with the latest xrdp release v.0.10.1:

aFreeRDP from F-Droid screenshot
![aFreeRDP from F-Droid screenshot
](https://usachov.eu/misc/ixLRjChDzaWqcDh-afreerdp.jpg)

Current official Android client screenshot
![Current official Android client screenshot](https://usachov.eu/misc/ixLRjChDzaWqcDh-androidx.jpg)

Deprecated official Android client screenshot
![Deprecated official Android client screenshot](https://usachov.eu/misc/ixLRjChDzaWqcDh-android.jpg)

What am I doing wrong with my xrdp installation?

About the resolution of the xrdp login screen you are right, I was wrong.

**Comment by matt335672** [comment] 2024-08-21 09:32
I'm sorry if I got a bit heated @usa-. I agree that telling users "it works for me" is never productive.

Let's reset this conversation, so we're both clear about the reason we're having it.

xrdp is a productivity tool. Our users (primarily enterprise users) are generally doing a job which requires them to interact with a UNIX desktop using RDP. My job in this is to focus on users' productivity. In the course of that we find bugs, and get an idea of the features we need to add to continuously improve the product. We also suggest workarounds, where an immediate fix isn't possible.

We get a lot of users posting here. That's absolutely fine, and it's an important part of product development. However, we don't know the background of anyone, or what their motives are.

Without wishing to be rude, you're not presenting as a typical user of this product. It's still not obvious to me what your actual use-cases are, and what you're trying to achieve with xrdp. As I've already said there are other ways to connect to a PI remotely which are less complex and don't involve xrdp. The reasons why you haven't explored this are not clear to me.

Before we go any further, can you tell me what you're hoping to achieve with xrdp?  When I've got a clear idea of what your actual goals are, I'll be happy to help with technical issues.

**Comment by usa-** [comment] 2024-08-21 09:45
I want to be able to access each of my devices (except my Android smartphone, which I always carry with me) from each of them using the latest version of the same client on each device, preferably the official one from Microsoft.

At the moment I'm having problems accessing my Paspberry Pi, which has xrdp installed, from Android using the latest client from Microsoft and using the aFreeRDP you suggested. I'm assuming there is some sort of problem with xrdp. I assume it would be better if it was fixed.

I also assume that it would be better if xrdp works properly on more systems [immediately after installation].

I would be happy to help you with this and provide more information about my system.

**Comment by matt335672** [comment] 2024-08-21 10:19
Thank you - I'm very happy to work with you on this. There's clearly something happening with the Android client on your setup which could do with looking into.

A couple of things:-
1) I'm assuming you require console access only.
2) Since you've build xrdp, let's use the development version so we can make changes.
3) As I've previously mentioned, there are two Microsoft clients for Windows. `mstsc.exe` is available on pretty much any Windows version. Some time ago, Microsoft announced a Windows Store version. That has some features that `mstsc.exe` doesn't. It appears to be a completely separate codebase - it's a UWP app. However, development of that version now appears to be stalled. This may have something to do with UWP being deprecated. Speaking purely personally, I've always found `mstsc.exe` to be rock-solid.

Let's look at your architecture:-

```
+----------------------+         +--------+        +------+        +-----------+
| X11 server (desktop) |  <----- | x11vnc | <----- | xrdp | <----- | client(s) |
+----------------------+   (X11) +--------+  (RFB) +------+  (RDP) +-----------+
```

Working along this chain seems like a good idea to me.
1) What arguments are you providing to `x11vnc`?
2) Do you have a VNC client which supports SSH on anything? If so, connect to TCP port 5900 on the PI and check the desktop looks reasonable to start with.

**Comment by usa-** [comment] 2024-08-21 11:15
> I'm assuming you require console access only.

Yes

> Since you've build xrdp, let's use the development version so we can make changes.

Now I installed it with `git clone https://github.com/neutrinolabs/xorgxrdp`. I is v0.10.80 now.

> As I've previously mentioned, there are two Microsoft clients for Windows (...)

It was me who mentioned it, but yes, I agree.

> Let's look at your architecture (...)

Yes. Since now we struggle with Android only, the `client(-s)` are `com.microsoft.rdc.androidx` and `com.freerdp.afreedrp`.

I checked both with xrdp v0.10.80, and both still show corrupted desktop, as shown in previous comments.

> What arguments are you providing to x11vnc?

x11vnc -display :0 -forever -repeat -noxdamage -usepw

> Do you have a VNC client which supports SSH on anything? If so, connect to TCP port 5900 on the PI and check the desktop looks reasonable to start with.

On my Android phone, I have `com.realvnc.viewer.android` and `com.cobolrforge.dontmind.multivnc`. I don't know it they support SSH. I checked both with xrdp v0.10.80, and both show the desktop properly.

If you want me to try some specific VNC client on one of my devices, please, name it.

**Comment by matt335672** [comment] 2024-08-21 14:45
No - that's good for now.

The corruption you show is interesting:-
1) The aFreeRDP is either undrawn lines, or extra blanks. I can't think what would cause that at the moment.
2) The MS client looks like a size mismatch. There are groups of 4 lines that are together, but the 4 lines that should be under them are offset by something like 220 pixels. That's just looking at the pole of the boatman.

Focussing on 2):-
1. what is the native resolution of your Android device?
2. what is the resolution of your PI desktop?
3. Is any scaling set in the client?
4. What's the exact version of your MS Android app you're using?

I'm out of time today, but I can try to reproduce this tomorrow on an Ubuntu VM.

**Comment by usa-** [comment] 2024-08-21 17:45
How aFreeRDP works in motion:
https://usachov.eu/misc/gzlumw5wNloTAjz-1.mp4

The native resolution of my Samsung S21 Ultra is **1440×3200**.

The resolution of my Pi desktop is **1920×1080**.

In MS client, in **Customuse display redolution**, this option is selected: **Default: 600×1292**. I have noticed, that if I change it to **Match this device** or _some_ other predefined resolutions, a normal picture appears for a short moment after the connection has been established.

https://usachov.eu/misc/gzlumw5wNloTAjz-2.mp4

The version of MS client is [10.0.19.1290](https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx).

**Comment by matt335672** [comment] 2024-08-22 17:30
Thanks - I can reproduce this now.

There are definitely some issues around v0.10.x and dynamic resizing. We added support for v0.10.x for client-side resizing which allows the client to resize the session in real-time when connected. This isn't supported by mstsc.exe, but is by other clients.

At the moment this facility isn't interacting well with `x11vnc` which can't support resizing. There's a way to disable it, but this isn't working for me on initial connect. After the weekend I'll sort this out, which should at least make v0.10.x and v0.9.x behave the same way.

After that I'll look at the MS Android client. I'm not getting a great feeling about this. It looks to me like the new version simply can't support an aspect ratio which is different from the target system. I'm probably missing something, but I'll have a look after I've got the first problem sorted out.

**Comment by usa-** [comment] 2024-08-31 09:00
Thank you!

**Comment by matt335672** [comment] 2024-09-23 15:24
Following #3243, I've got back to this.

It's not good news I'm afraid.  The MS client can't cope with a resize request generated on the server end. With the configuration we're trying to use here (MS client connecting to a fixed size session), this simply doesn't work.

Essentially the client sends over its initial size as part of the [Client Core Data](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/00f1da4a-ee9c-421a-852f-c19f92343d73). Since the session can't support this, we initiate a [Deactivation-Reactivation Sequence](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dfc234ce-481a-4674-9a5d-2a7bafb14432) when we try to reconnect with a session.

The MS client allows for custom resolutions, but they're essentially just scaled versions of the resolution supported by the hardware. On my Android device, I've got a native resolution of 600x1216. I'm offered these resolutions by the client, and no others:-
- 1560x768
- 1644x808
- 2192x1080
- 2740x1348
- 3288x1620
- 3836x1888

Since I'm using a fixed-size VM for testing, I was able to get the client working my resizing my VM console to 2192x1080, and then connecting from the app at that resolution. That all works fine.

I've also tried the "Wiindows App" in beta on Android:-

https://play.google.com/store/apps/details?id=com.microsoft.rdc.androidx.beta

Exactly the same result. The app looks pretty identical.

I've reported this to MS:-

https://techcommunity.microsoft.com/t5/zaure-virtual-desktop-feedback/support-server-side-resizes/idi-p/4252948

**Comment by MalgathThelamin** [comment] 2024-09-24 16:06
Thank you!

> Since the session can't support this, we initiate a [Deactivation-Reactivation Sequence](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dfc234ce-481a-4674-9a5d-2a7bafb14432) when we try to reconnect with a session.

Isn't this the point, before which `MS-client` briefly displays the remote desktop correctly (see my video [above](https://github.com/neutrinolabs/xrdp/issues/3211#issuecomment-2302635462))?

Have you been able to resolve the issue with the skipping horizontal lines in `aFreeRDP`?

P. S. For now, I will continue to use an older client (https://play.google.com/store/apps/details?id=com.microsoft.rdc.android) that works.

**Comment by usa-** [comment] 2024-09-24 16:07
Thank you!

> Since the session can't support this, we initiate a [Deactivation-Reactivation Sequence](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dfc234ce-481a-4674-9a5d-2a7bafb14432) when we try to reconnect with a session.

Isn't this the point, before which `MS-client` briefly displays the remote desktop correctly (see my video [above](https://github.com/neutrinolabs/xrdp/issues/3211#issuecomment-2302635462))?

Have you been able to resolve the issue with the skipping horizontal lines in `aFreeRDP`?

P. S. For now, I will continue to use an older client (https://play.google.com/store/apps/details?id=com.microsoft.rdc.android) that works.

**Comment by matt335672** [comment] 2024-09-25 09:00
It might well be, but since we can't cope with the size being sent by the client it's a moot point.

I managed to get aFreeRDP working with the latest changes to xrdp. I needed to set bpp to 32 in the client, and resolution to automatic. I couldn't get the keyboard up on the login screen however, so it's not something I'd recommend, despite having suggested it in the first place.

If the older client works for you, that's great. The only other thing I can suggest is to set up a separate user on the PI and create a normal (resizeable) xrdp session which will work fine. Based on my previous interactions with MS, I'm not at all confident of even a reply to my post.

**Comment by matt335672** [comment] 2024-11-14 11:50
I'm closing this now - there's not a lot more we can do from here. At the time of writing, MS have not responded to the issue we raised above on Sep 23.

**Closed as completed by matt335672** 2024-11-14 11:50 UTC
Labels: bug

**Comment by matt335672** [comment] 2025-01-03 12:01
As a follow-up, the post I made to the Microsoft forum has finally received a non-reply.

Looking at the linked new forum, and selecting 'official Microsoft responses', it seems we probably can't expect this to be fixed in the Android client for the foreseeable future.
