### ISSUE TITLE
[ERROR] libxrdp_force_read: header read error

### ISSUE THREAD

**Issue by yurivict** [neutrinolabs/xrdp#2714] opened 2023-06-06 01:12 UTC
When the MS RDP client on MacOS connects to the xrdp server running on FreeBSD 13.2 these messages are printed in log:

```
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] libxrdp_force_read: header read error
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Jun  5 18:07:01 xx xrdp[52316]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
```

xrdp-0.9.22

**Comment by matt335672** [comment] 2023-06-06 09:00
This is a duplicate of #2040. 

Didn't we cover this in #2710? Am I missing something?

**Comment by yurivict** [comment] 2023-06-06 09:05
The error is different - ```SSL_accept: I/O error``` is only in https://github.com/neutrinolabs/xrdp/issues/2710
"[ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed" is only here.

It's not immediately obvious that this is the same error.

**Comment by matt335672** [comment] 2023-06-06 09:30
OK - thanks for pointing it out.

It's possible your MacOS client is using RDP encryption rather than SSL. Do you have more of the log there?

**Comment by pnowack** [comment] 2023-06-06 11:45
> It's possible your MacOS client is using RDP encryption rather than SSL.

@matt335672 The [X.224 Connection Request PDU](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/18a27ef9-6f9a-4501-b000-94b1fe3c2c10) is the very first PDU sent by the client. At that point no kind of security handling (ancient RDP security, TLS-, NLA-, or AAD-Security) took place yet.

So, if the connection already fails at this point, then there normally are only two ways: Either something in the parsing handling on the server side is wrong, or the client did send a malformed X.224 request.

**Comment by matt335672** [comment] 2023-06-07 09:01
Thanks @pnowack - you're quite right and I should have made a more thorough analysis.

This looks very much like #2505, which is also linked to from #2040. I just duplicated it by:-
1) Building v0.9.22
2) Running `xrdp -n`
3) From another machine, running `nmap -p 3389 <host>` to simply open the TCP port and close it again.
4) Stopping xrdp.

The complete xrdp log (with line numbers) looks like this:-

```
1:[20230607-09:51:15] [INFO ] [main(xrdp.c:691)] starting xrdp with pid 17571
2:[20230607-09:51:16] [INFO ] [xrdp_listen_process_startup_params(xrdp_listen.c:678)] address [0.0.0.0] port [3389] mode 1
3:[20230607-09:51:16] [INFO ] [xrdp_listen_process_startup_params(xrdp_listen.c:687)] listening to port 3389 on 0.0.0.0
4:[20230607-09:51:16] [INFO ] [xrdp_listen_process_startup_params(xrdp_listen.c:674)] xrdp_listen_pp done
5:[20230607-09:51:41] [INFO ] [g_sck_accept(os_calls.c:1384)] Socket 12: AF_INET6 connection received from <redacted> port 40740
6:[20230607-09:51:42] [INFO ] [xrdp_rdp_read_config(xrdp_rdp.c:225)] Using default X.509 certificate: /etc/xrdp/cert.pem
7:[20230607-09:51:42] [INFO ] [xrdp_rdp_read_config(xrdp_rdp.c:257)] Using default X.509 key file: /etc/xrdp/key.pem
8:[20230607-09:51:42] [ERROR] [libxrdp_force_read(libxrdp.c:135)] libxrdp_force_read: header read error
9:[20230607-09:51:42] [ERROR] [xrdp_iso_incoming(xrdp_iso.c:489)] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
10:[20230607-09:51:42] [ERROR] [xrdp_sec_incoming(xrdp_sec.c:2820)] xrdp_sec_incoming: xrdp_iso_incoming failed
11:[20230607-09:51:42] [ERROR] [xrdp_rdp_incoming(xrdp_rdp.c:921)] xrdp_rdp_incoming: xrdp_sec_incoming failed
12:[20230607-09:51:42] [ERROR] [xrdp_process_main_loop(xrdp_process.c:302)] xrdp_process_main_loop: libxrdp_process_incoming failed
13:[20230607-09:51:42] [ERROR] [xrdp_iso_send(xrdp_iso.c:639)] xrdp_iso_send: trans_write_copy_s failed
14:[20230607-09:51:42] [ERROR] [xrdp_mcs_disconnect(xrdp_mcs.c:1538)] Sending [ITU T.125] DisconnectProviderUltimatum failed
15:[20230607-09:51:44] [INFO ] [xrdp_listen_main_loop(xrdp_listen.c:915)] Received termination signal, stopping the server accept new conne
```

Lines 8-14 look identical to the messages logged above, making allowances for the development build. Consequently I'm quite happy to close this one and fold it into #2040.

**Closed as completed by matt335672** 2023-06-07 09:01 UTC

**Comment by seanajohnston** [comment] 2024-02-27 18:07
> This is a duplicate of #2040.
> 
> Didn't we cover this in #2710? Am I missing something?

Why did you reference #2040 if #2040 does not contain a legitimate solution? Currently having the same issue. And why was this issue closed when it doesn't contain a fix?

**Comment by matt335672** [comment] 2024-02-28 09:12
@seanajohnston - this is an observation about messages in the log. The explanation for these messages is in #2040. The messages are normal, but confusing and we need to clean them up.

Does that make more sense to you?

**Comment by craftzneko** [comment] 2024-03-06 23:28
I am having same issue as described here, on a Mac using windows Remote Desktop to connect to Multipass ubuntu with xrdp setup as described here https://multipass.run/docs/set-up-a-graphical-interface#heading--using-rdp

immediate failure only thing I notice is this in the log

Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] libxrdp_force_read: header read error
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] xrdp_iso_send: trans_write_copy_s failed
Mar 06 23:24:04 proven-troll xrdp[32031]: [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed

**Comment by matt335672** [comment] 2024-03-07 09:51
@craftzneko - these messages are explained in the rest of this thread.

If you're having a problem please enter a separate and detailed report so we can look at it. I can't do anything with the information you've posted above for reasons I hope are clear.

**Comment by craftzneko** [comment] 2024-03-07 23:05
was not sure if the issue was related to xrdp so also logged issue on Multipass repo and it appears it can be reproduced with it being looked into https://github.com/canonical/multipass/issues/3422#issuecomment-1983607154

**Comment by ApolloDS** [comment] 2025-02-05 13:08
Please see my comment here: https://github.com/canonical/multipass/issues/3422#issuecomment-2636589216

**Comment by ColeNorthway** [comment] 2025-10-01 17:08
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/use-remote-desktop?tabs=azure-cli

link is good link isn't bad
