### ISSUE TITLE
XRDP Centos 7.5 No sound PulseAudio

### ISSUE THREAD

**Issue by doctorjnupe** [neutrinolabs/xrdp#1689] opened 2020-09-17 04:27 UTC
>pulseaudio  -vvvv
> I: [pulseaudio] main.c: setrlimit(RLIMIT_NICE, (31, 31)) failed: Operation not permitted
> I: [pulseaudio] main.c: setrlimit(RLIMIT_RTPRIO, (9, 9)) failed: Operation not permitted
> D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
> I: [pulseaudio] core-util.c: Failed to acquire high-priority scheduling: Input/output error
> I: [pulseaudio] main.c: This is PulseAudio 10.0
> D: [pulseaudio] main.c: Compilation host: x86_64-redhat-linux-gnu
> D: [pulseaudio] main.c: Compilation CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -W -Wextra -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -ffast-math -fno-common -fdiagnostics-show-option -fdiagnostics-color=auto
> D: [pulseaudio] main.c: Running on host: Linux x86_64 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
> D: [pulseaudio] main.c: Found 32 CPUs.
> I: [pulseaudio] main.c: Page size is 4096 bytes
> D: [pulseaudio] main.c: Compiled with Valgrind support: no
> D: [pulseaudio] main.c: Running in valgrind mode: no
> D: [pulseaudio] main.c: Running in VM: yes
> D: [pulseaudio] main.c: Optimized build: yes
> D: [pulseaudio] main.c: FASTPATH defined, only fast path asserts disabled.
> I: [pulseaudio] main.c: Machine ID is 6371ed740f398ca50cfadbab61ae99a0.
> I: [pulseaudio] main.c: Using runtime directory /home/jhiggs/.config/pulse/6371ed740f398ca50cfadbab61ae99a0-runtime.
> I: [pulseaudio] main.c: Using state directory /home/jhiggs/.config/pulse.
> I: [pulseaudio] main.c: Using modules directory /usr/lib64/pulse-10.0/modules.
> I: [pulseaudio] main.c: Running in system mode: no
> I: [pulseaudio] main.c: System supports high resolution timers
> D: [pulseaudio] memblock.c: Using shared memfd memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65472
> I: [pulseaudio] cpu-x86.c: CPU flags: CMOV MMX SSE SSE2 SSE3 SSSE3 SSE4_1 SSE4_2 
> I: [pulseaudio] svolume_mmx.c: Initialising MMX optimized volume functions.
> I: [pulseaudio] remap_mmx.c: Initialising MMX optimized remappers.
> I: [pulseaudio] svolume_sse.c: Initialising SSE2 optimized volume functions.
> I: [pulseaudio] remap_sse.c: Initialising SSE2 optimized remappers.
> I: [pulseaudio] sconv_sse.c: Initialising SSE2 optimized conversions.
> I: [pulseaudio] svolume_orc.c: Initialising ORC optimized volume functions.
> I: [pulseaudio] module.c: Loaded "module-augment-properties" (index: #0; argument: "").
> D: [pulseaudio] module-always-sink.c: Autoloading null-sink as no other sinks detected.
> I: [pulseaudio] sink.c: Created sink 0 "auto_null" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
> I: [pulseaudio] sink.c:     device.description = "Dummy Output"
> I: [pulseaudio] sink.c:     device.class = "abstract"
> I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
> I: [pulseaudio] source.c: Created source 0 "auto_null.monitor" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
> I: [pulseaudio] source.c:     device.description = "Monitor of Dummy Output"
> I: [pulseaudio] source.c:     device.class = "monitor"
> I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
> D: [null-sink] module-null-sink.c: Thread starting up
> I: [pulseaudio] core.c: default_source: (unset) -> auto_null.monitor
> I: [pulseaudio] core.c: default_sink: (unset) -> auto_null
> I: [pulseaudio] module.c: Loaded "module-null-sink" (index: #2; argument: "sink_name=auto_null sink_properties='device.description="Dummy Output"'").
> I: [pulseaudio] module.c: Loaded "module-always-sink" (index: #1; argument: "").
> D: [pulseaudio] module.c: Checking for existence of '/usr/lib64/pulse-10.0/modules/module-xrdp-sink.so': success
> **E: Invalid sample format specification or channel map**
> **E: [pulseaudio] module.c: Failed to load module "module-xrdp-sink.so" (argument: ""): initialization failed.**
> **E: [pulseaudio] main.c: Module load failed.**
> **E: [pulseaudio] main.c: Failed to initialize daemon.**
> I: [pulseaudio] module.c: Unloading "module-null-sink" (index: #2).
> D: [pulseaudio] module-always-sink.c: Autoloaded null-sink removed
> I: [pulseaudio] core.c: default_sink: auto_null -> (unset)
> I: [pulseaudio] core.c: default_source: auto_null.monitor -> (unset)
> D: [null-sink] module-null-sink.c: Thread shutting down
> I: [pulseaudio] sink.c: Freeing sink 0 "auto_null"
> I: [pulseaudio] source.c: Freeing source 0 "auto_null.monitor"
> I: [pulseaudio] module.c: Unloaded "module-null-sink" (index: #2).
> I: [pulseaudio] module.c: Unloading "module-always-sink" (index: #1).
> I: [pulseaudio] module.c: Unloaded "module-always-sink" (index: #1).
> I: [pulseaudio] module.c: Unloading "module-augment-properties" (index: #0).
> I: [pulseaudio] module.c: Unloaded "module-augment-properties" (index: #0).
> **I: [pulseaudio] main.c: Daemon terminated.**
> 

I am trying to get sound to work for multi-user.  I have followed this: [https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README](https://github.com/neutrinolabs/pulseaudio-module-xrdp/wiki/README)

I have added the user to the pulse, audio and pulse-audio Groups.   I am not sure why loading of the sink "module-xrdp-sink.so" (argument: ""): is failing.  Does anyone have any idea?  What am I missing?  I feel that I am so very close.

**Comment by Nexarian** [comment] 2020-09-17 12:48
I have also struggled to get sound working with XRDP on Ubuntu 20.04 with FreeRDP. Not sure if it's just me though.

**Comment by doctorjnupe** [comment] 2020-09-17 13:42
> I have also struggled to get sound working with XRDP on Ubuntu 20.04 with FreeRDP. Not sure if it's just me though.

I've tried everything.  I'm not able to figure out why I'm having an issue.  So many people have gotten sound working, but all by doing something slightly different.  I'm going to try some more stuff today.  If I get it working, I will come back here and share my results.

**Comment by matt335672** [comment] 2020-09-18 10:57
I'm not that familiar with this module I'm afraid.

The error message `Invalid sample format specification or channel map` is being generated by the module initialisation code I think (at least it's in there). I've had a look in the module sources and compared them with other pulseaudio modules. The source code looks pretty boiler-plate, so I think the problem probably isn't with the module itself which seems to be being loaded and called properly

I've just run a build on 7.8 and all seems OK so I think you must be pretty close as you say. However, despite playing around with settings, I can't reproduce your problem.

A couple of things to try, but these are long-shots:-
- Are you in a position where you could try removing any existing PA settings  in `/home/jhiggs/.config/pulse/` and `/home/jhiggs/.config/pavucontrol.ini`?
- Since you're on RHEL/CentOS, check the SELinux log for possible problems with `sudo ausearch -m avc -ts recent` after trying to start the daemon.

Sorry I can't be more helpful.

**Comment by matt335672** [comment] 2020-09-18 11:10
One other thing - are you running xrdp from EPEL or have you built it yourself? The working config I have is running xrdp-0.9.13.1-1.el7.x86_64 from EPEL.

**Comment by doctorjnupe** [comment] 2020-09-21 20:21
> One other thing - are you running xrdp from EPEL or have you built it yourself? The working config I have is running xrdp-0.9.13.1-1.el7.x86_64 from EPEL.

@matt335672  I wanted to provide additional context.  I was able to get the daemon started by using  the `pulseaudio -D` command.  My issue now, is that the xrdp sink is still not being used.  

I do not have any PA details in `/home/jhiggs/.config/pulse/` 

I only have the following details in the `.config/pulse/` directory:

`
6371ed740f398ca50cfadbab61ae99a0-card-database.tdb  
6371ed740f398ca50cfadbab61ae99a0-default-source      
6371ed740f398ca50cfadbab61ae99a0-runtime             
cookie
6371ed740f398ca50cfadbab61ae99a0-default-sink       
6371ed740f398ca50cfadbab61ae99a0-device-volumes.tdb  
6371ed740f398ca50cfadbab61ae99a0-stream-volumes.tdb
`

The issues seems to be that PA is not picking up the `xrdp sink` and `xrdp source`.

**Comment by doctorjnupe** [comment] 2020-09-22 14:33
> One other thing - are you running xrdp from EPEL or have you built it yourself? The working config I have is running xrdp-0.9.13.1-1.el7.x86_64 from EPEL.

@matt335672 I think the problem is in my settings.  Either my  of the following:

- `default.pa `
- `client.conf`
- `xrdp.ini` 

Are you able to share the relevant details for comparison?
-

**Comment by matt335672** [comment] 2020-09-25 14:38
Hi @doctorjnupe 

Sorry about the radio silence - just had a few non-IT related days.

I've had a poke around into how all this stuff hangs together, and it's possible the problem you have is down to the lack of environment settings.

When the session is started by `xrdp-sesman`, it should set the following environment variables which are needed for pulseaudio to successfully load the module:-

| Variable | Purpose  | Defined by?  |
|---------|---------|-------------|
| PULSE_SCRIPT  | Tells pulse how to start  | Setting in `/etc/xrdp/sesman.ini`  |
| XRDP_PULSE_SINK_SOCKET | Tells the PA module audio sink code how to talk to chansrv | Code | 
| XRDP_PULSE_SOURCE_SOCKET | Tells the PA module audio source code how to talk to chansrv | Code |
| XRDP_SOCKET_PATH | Tells the PA module where the chansrv sockets are located in the filesystem | Defined at compile time |

On my system, if I log in to DISPLAY :10, I get the following settings

| Variable | Value |
|---------|-------|
| PULSE_SCRIPT  | /etc/xrdp/pulse/default.pa |
| XRDP_PULSE_SINK_SOCKET | xrdp_chansrv_audio_out_socket_10 |
| XRDP_PULSE_SOURCE_SOCKET | xrdp_chansrv_audio_in_socket_10 |
| XRDP_SOCKET_PATH | /run/xrdp |

Pulseaudio also uses `XRDP_SESSION_ID` and `DBUS_SESSION_BUS_ADDRESS` if they are set.

I suspect from your questions that `PULSE_SCRIPT` isn't defined. You should have this section in `/etc/xrdp/sesman.ini`:-

```
[SessionVariables]
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
```

As fat as `client.conf` goes, my `/etc/pulse/client.conf` is empty except for comments and I don't have any configs at all in `~/.config/pulse`:-

<pre>
$ <b>ls ~/.config/pulse/</b>
total 36
-rw-r--r--. 1 mjb mjb   696 Sep 25 14:51 03aa670d94e8408abbc1b50ce89a9ba0-card-database.tdb
-rw-r--r--. 1 mjb mjb     1 Sep 25 15:06 03aa670d94e8408abbc1b50ce89a9ba0-default-sink
-rw-r--r--. 1 mjb mjb     1 Sep 25 15:06 03aa670d94e8408abbc1b50ce89a9ba0-default-source
-rw-r--r--. 1 mjb mjb  8192 Sep 25 14:51 03aa670d94e8408abbc1b50ce89a9ba0-device-volumes.tdb
-rw-r--r--. 1 mjb mjb 12288 Sep 25 14:51 03aa670d94e8408abbc1b50ce89a9ba0-stream-volumes.tdb
-rw-------. 1 mjb mjb   256 Sep 18 11:42 cookie
</pre>

You'll also need `xrdp-chansrv` to be running in your session. It's started automatically at the start of a session, but if it crashes for any reason, it will be unable to convey any audio through to your xrdp client.

Is that useful?

**Comment by Nexarian** [comment] 2020-09-25 15:17
After a lot of extensive testing, I've determined my issue was a problem with FreeRDP and not xrdp. XRDP is properly reporting sound, it's FreeRDP that can't initialize on a mac for some reason.

**Comment by lee-staples** [comment] 2021-01-21 18:15
On installation on Fedora 33 socket for sinks created in /run/xrdp 

xorgxrdp-0.2.15-1.fc33.x86_64
xrdp-selinux-0.9.15-3.fc33.x86_64
xrdp-0.9.15-3.fc33.x86_64
pulseaudio-module-xrdp  (tested on both master and devel branch)

As workaround created a symbolic link
 ln -s /run/xrdp /tmp/.xrdp

**Comment by lee-staples** [comment] 2021-01-22 10:13
> On installation of Fedora 33 socket for sinks and source created in /run/xrdp
> 
> xorgxrdp-0.2.15-1.fc33.x86_64
> xrdp-selinux-0.9.15-3.fc33.x86_64
> xrdp-0.9.15-3.fc33.x86_64
> pulseaudio-module-xrdp (tested on both master and devel branch)
> 
> As workaround created a symbolic link
> ln -s /run/xrdp /tmp/.xrdp

Looks like the rpm file for the package is built with the defaults and chansrv defaults to using /tmp/.xrdp in Fedora 33 so not seeing the sockets created in /run/xrdp by pulseaudio module

AC_ARG_WITH([socketdir],
  [AS_HELP_STRING([--with-socketdir=DIR],
                  [Use directory for UNIX sockets (default: /tmp/.xrdp)])],
                  [], [with_socketdir="/tmp/.xrdp"])
AC_SUBST([socketdir], [$with_socketdir])

**Comment by lee-staples** [comment] 2021-01-22 12:20
> On installation of Fedora 33 socket for sinks and source created in /run/xrdp
> 
> xorgxrdp-0.2.15-1.fc33.x86_64
> xrdp-selinux-0.9.15-3.fc33.x86_64
> xrdp-0.9.15-3.fc33.x86_64
> pulseaudio-module-xrdp (tested on both master and devel branch)
> 
> As workaround created a symbolic link
> ln -s /run/xrdp /tmp/.xrdp

Rebuilt in docker with Fedora 33 and is using /run/xrdp correctly - unable to reproduce

https://hub.docker.com/r/leestaples/chrome-mstsc

**Comment by matt335672** [comment] 2021-11-19 10:44
I'm closing this issue now. Version 0.6 of the pulseaudio module [has been released](/neutrinolabs/pulseaudio-module-xrdp/releases/tag/v0.6) with significant changes, and the [wiki README](/neutrinolabs/pulseaudio-module-xrdp/wiki/README) has been updated with better build instructions.

**Closed by matt335672** 2021-11-19 10:44 UTC
