### ISSUE TITLE
xrdp-chansrv segmentation fault on client disconnect when FUSE is not available

### ISSUE THREAD

**Issue by ad-65** [neutrinolabs/xrdp#2330] opened 2022-08-03 04:44 UTC
When the RDP client disconnects it can cause a segmentation fault in xrdp-chansrv if FUSE is not enabled. Running xrdp 0.9.12 in Ubuntu 20.04 inside a Linux container with no FUSE everything works fine on the initial connection until the client disconnects then xrdp-chansrv segfaults and on re-connection copy and paste (as well as other xrdp-chansrv functions) will not work.

There are two workarounds, log out and back in to restart xrdp-chansrv or enable FUSE in the LXC (probably applies to Docker too).

I am creating this issue because the cause was hard to track down as everything works initially (before client disconnect), there wasn't anything obvious in the logs, and xrdp-chansrv should not really be segfaulting.

Debugging info:
```
user@host:~$ sudo gdb attach 3140
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 3140
[New LWP 3149]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f403bf21fcb in __GI___select (nfds=nfds@entry=9, readfds=readfds@entry=0x7ffff33af7c0, writefds=writefds@entry=0x7ffff33af840,
    exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
41      ../sysdeps/unix/sysv/linux/select.c: No such file or directory.
(gdb) cont
Continuing.

Thread 2 "xrdp-chansrv" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f403b6a5700 (LWP 3149)]
0x0000561ef6bd822d in xfs_delete_xfs_fs (xfs=0x0) at chansrv_xfs.c:390
390     chansrv_xfs.c: No such file or directory.
(gdb) where
#0  0x0000561ef6bd822d in xfs_delete_xfs_fs (xfs=0x0) at chansrv_xfs.c:390
#1  0x0000561ef6bd6ed7 in xfuse_deinit_xrdp_fs () at chansrv_fuse.c:867
#2  xfuse_deinit () at chansrv_fuse.c:557
#3  0x0000561ef6bda5e9 in clipboard_deinit () at clipboard.c:525
#4  0x0000561ef6bd47b0 in channel_thread_loop (in_val=<optimized out>) at chansrv.c:1435
#5  0x00007f403c007609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f403bf2c133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
```

Error when running xrdp-chansrv manually:
```
[20220802-20:27:22] [CORE ] main: app started pid 8639(0x000021bf)
[20220802-20:27:22] [INFO ] main: DISPLAY env var set to :10.0
[20220802-20:27:22] [INFO ] main: using DISPLAY 10
[20220802-20:27:22] [INFO ] channel_thread_loop: thread start
[20220802-20:27:51] [INFO ] Socket 12: AF_UNIX connection received
process_message_channel_setup: chan name 'rdpdr' id 0 flags 00000000
process_message_channel_setup: chan name 'rdpsnd' id 1 flags 00000000
process_message_channel_setup: chan name 'cliprdr' id 2 flags 00000000
process_message_channel_setup: chan name 'drdynvc' id 3 flags 00000000
fuse: device not found, try 'modprobe fuse' first
[1636295737]: FUSE       xfuse_init_lib: 790 : ERROR: fuse_mount() failed
No protocol specified
[20220802-20:27:51] [ERROR] xcommon_init: error, XOpenDisplay failed
xrdp-chansrv [1636295748]: segfault_signal_handler: entered.......
Segmentation fault
```

I know the xrdp version is a bit older but I didn't see an issue indicating that was addressed yet.

Thanks.

**Comment by matt335672** [comment] 2022-08-04 09:31
Duplicate of #1487 which was fixed on v0.9.13.

**Closed as completed by matt335672** 2022-08-04 09:31 UTC
