### ISSUE TITLE
XRDP stopped working on Debian 11. Only turquoise screen.

### ISSUE THREAD

**Issue by ky8585** [neutrinolabs/xrdp#2800] opened 2023-09-24 16:54 UTC
### Discussed in https://github.com/neutrinolabs/xrdp/discussions/2799

<div type='discussions-op-text'>

<sup>Originally posted by **ky8585** September 24, 2023</sup>
Hello,

I'm not a developer - just a newbie user of xrdp. I came across the problem under Debian 11.
After some upgrade xrdp stopped working and I only observe turquoise blank screen after credentials.
My config is as follows:
user@debian:~$ dpkg -l| grep xrdp
ii  xorgxrdp                              1:0.2.15-1                       amd64        Remote Desktop Protocol (RDP) modules for X.org
ii  xrdp                                  0.9.21.1-1~deb11u1               amd64        Remote Desktop Protocol (RDP) server

And the log file looks like this:
[20230923-23:13:15] [INFO ] starting xrdp-sesman with pid 628
[20230923-23:13:51] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 36310
[20230923-23:13:51] [INFO ] ++ created session (access granted): username user, ip ::ffff:192.168.29.168:56306 - socket: 12
[20230923-23:13:51] [INFO ] starting Xorg session...
[20230923-23:13:51] [INFO ] Starting session: session_pid 828, display :10.0, width 1920, height 1200, bpp 24, client ip ::ffff:192.168.29.168:56306 - socket: 12, user name user
[20230923-23:13:51] [ERROR] sesman_data_in: scp_process_msg failed
[20230923-23:13:51] [INFO ] [session start] (display 10): calling auth_start_session from pid 828
[20230923-23:13:51] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230923-23:13:51] [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20230923-23:13:52] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230923-23:13:52] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230923-23:13:52] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230923-23:13:52] [INFO ] Starting the xrdp channel server for display 10
[20230923-23:13:52] [INFO ] Session started successfully for user user on display 10
[20230923-23:13:52] [INFO ] Starting the default window manager on display 10: /etc/xrdp/startwm.sh
[20230923-23:13:52] [INFO ] Session in progress on display 10, waiting until the window manager (pid 829) exits to end the session

I need to restore functionality of xrdp ASAP. Please, help/
</div>

**Comment by ky8585** [comment] 2023-09-24 17:01
After reboot:

[20230924-09:43:08] [INFO ] starting xrdp-sesman with pid 607
[20230924-09:43:54] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 35450
[20230924-09:43:54] [INFO ] ++ created session (access granted): username user, ip ::ffff:192.168.29.168:59652 - socket: 12
[20230924-09:43:54] [INFO ] starting Xorg session...
[20230924-09:43:54] [INFO ] Starting session: session_pid 901, display :10.0, width 1920, height 1200, bpp 24, client ip ::ffff:192.168.29.168:59652 - socket: 12, user name user
[20230924-09:43:54] [ERROR] sesman_data_in: scp_process_msg failed
[20230924-09:43:54] [INFO ] [session start] (display 10): calling auth_start_session from pid 901
[20230924-09:43:54] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230924-09:43:54] [INFO ] Starting X server on display 10: /usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20230924-09:43:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230924-09:43:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230924-09:43:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20230924-09:43:54] [INFO ] Session started successfully for user user on display 10
[20230924-09:43:54] [INFO ] Starting the xrdp channel server for display 10
[20230924-09:43:54] [INFO ] Starting the default window manager on display 10: /etc/xrdp/startwm.sh
[20230924-09:43:54] [INFO ] Session in progress on display 10, waiting until the window manager (pid 902) exits to end the session

**Comment by metalefty** [comment] 2023-09-24 17:04
Duplicate of #2799.

**Closed as completed by metalefty** 2023-09-24 17:04 UTC

**Comment by metalefty** [comment] 2023-09-24 17:06
If you want to raise an issue, please do use the issue template to collect detailed information.

https://github.com/neutrinolabs/xrdp/discussions/2799#discussioncomment-7094681
