### ISSUE TITLE
Mouse mistakenly affected by scaling on Ubuntu 22.04

### ISSUE THREAD

**Issue by AndreasNasman** [neutrinolabs/xrdp#2209] opened 2022-04-03 13:14 UTC
Increasing the scaling in Ubuntu settings makes the mouse become incorrectly smaller:
![100%](https://user-images.githubusercontent.com/17124245/161427519-2283e3f6-9a61-40af-b1ee-02f213ef4f1c.jpg)
The mouse pointer at 100 % scaling, looks correct.
![300%](https://user-images.githubusercontent.com/17124245/161427516-2eaa129f-ca3a-4493-8727-a6d2a0229175.jpg)
The mouse pointer at 300 % scaling, looks incorrect, being cropped from the bottom.

xrdp version: 0.9.17-2ubuntu2
Ubuntu version: 22.04

Windows specs:
Edition: Windows 10 Pro
Version: 21H2
OS build: 19044.1620
Experience: Windows Feature Experience Pack 120.2212.4170.0

PC specs:
Model: ThinkPad P14s Gen 2a
BIOS version: R1MET45W 1.15 

I tried connecting to the virtual machine using *Remote Desktop Connection* and Hyper-V in Enhanced mode (followed [this guide](https://www.nakivo.com/blog/install-ubuntu-20-04-on-hyper-v-with-enhanced-session/)), and the issue is present in both connections. The virtual machine is created in Hyper-V, where I also start it before connecting to it.

I'm quite new to virtual machines and xrdp so not sure what else to include in the issue ticket. 🙂

**Comment by matt335672** [comment] 2022-04-04 08:31
Duplicate of #2092

**Closed as completed by matt335672** 2022-04-04 08:31 UTC
