### ISSUE TITLE
Unable to use xrdp on KDE with Alpine Linux V3.15.4

### ISSUE THREAD

**Issue by xdoomer01** [neutrinolabs/xrdp#2232] opened 2022-04-19 19:56 UTC
Hello,
I have a fresh install of Linux Alpine 3.15.4 with KDE.

I installed light KDE like this :
apk add plasma elogind polkit-elogind dbus
apk add kde-applications-base kde-applications-network

I installed xrdp like this :

apk add xrdp xorgxrdp
rc-update add xrdp
rc-update add xrdp-sesman
reboot

Here is the log when I connect in rdp:

cat /var/log/xrdp.log 
[20220419-21:45:42] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220419-21:45:42] [INFO ] listening to port 3389 on 0.0.0.0
[20220419-21:45:42] [INFO ] xrdp_listen_pp done
[20220419-21:45:44] [INFO ] starting xrdp with pid 2301
[20220419-21:45:44] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220419-21:45:44] [INFO ] listening to port 3389 on 0.0.0.0
[20220419-21:45:44] [INFO ] xrdp_listen_pp done
[20220419-21:46:41] [INFO ] Socket 12: AF_INET connection received from 192.168.50.200 port 54276
[20220419-21:46:41] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220419-21:46:41] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220419-21:46:41] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220419-21:46:41] [ERROR] SSL_read: I/O error
[20220419-21:46:41] [ERROR] libxrdp_force_read: header read error
[20220419-21:46:41] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20220419-21:46:41] [ERROR] [MCS Connection Sequence] receive connection request failed
[20220419-21:46:41] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20220419-21:46:41] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20220419-21:46:41] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20220419-21:46:41] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20220419-21:46:41] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20220419-21:46:43] [INFO ] Socket 12: AF_INET connection received from 192.168.50.200 port 54277
[20220419-21:46:43] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220419-21:46:43] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220419-21:46:43] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220419-21:46:43] [INFO ] Connected client computer name: DESKTOP-IPUMR3I
[20220419-21:46:43] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20220419-21:46:43] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20220419-21:46:43] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x0000040C]
[20220419-21:46:43] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [fr] options []
[20220419-21:46:43] [INFO ] TLS connection established from 192.168.50.200 port 54277: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20220419-21:46:43] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20220419-21:46:43] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20220419-21:46:43] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20220419-21:46:43] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20220419-21:46:43] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20220419-21:46:43] [INFO ] Loading keymap file /etc/xrdp/km-0000040c.ini
[20220419-21:46:43] [WARN ] local keymap file for 0x0000040c found and doesn't match built in keymap, using local keymap file
[20220419-21:46:50] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220419-21:46:50] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220419-21:46:50] [INFO ] sesman connect ok
[20220419-21:46:50] [INFO ] sending login info to session manager. Please wait...
[20220419-21:46:50] [INFO ] xrdp_wm_log_msg: login successful for user david on display 10
[20220419-21:46:50] [INFO ] login successful for user david on display 10
[20220419-21:46:50] [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
[20220419-21:46:50] [INFO ] started connecting
[20220419-21:46:50] [INFO ] lib_mod_connect: connecting via UNIX socket

cat /var/log/xrdp-sesman.log 
[20220419-21:45:42] [INFO ] starting xrdp-sesman with pid 2330
[20220419-21:46:50] [INFO ] Socket 8: AF_INET connection received from 127.0.0.1 port 47314
[20220419-21:46:50] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20220419-21:46:50] [INFO ] ++ created session (access granted): username david, ip 192.168.50.200:54277 - socket: 12
[20220419-21:46:50] [INFO ] starting Xorg session...
[20220419-21:46:50] [INFO ] Starting session: session_pid 2390, display :10.0, width 1600, height 900, bpp 24, client ip 192.168.50.200:54277 - socket: 12, user name david
[20220419-21:46:50] [ERROR] sesman_data_in: scp_process_msg failed
[20220419-21:46:50] [INFO ] [session start] (display 10): calling auth_start_session from pid 2390
[20220419-21:46:50] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220419-21:46:50] [INFO ] Starting X server on display 10: Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20220419-21:47:00] [WARN ] Timed out waiting for X server on display 10 to startup
[20220419-21:47:00] [INFO ] Session started successfully for user david on display 10
[20220419-21:47:00] [INFO ] Session in progress on display 10, waiting until the window manager (pid 2391) exits to end the session
[20220419-21:47:00] [INFO ] Starting the xrdp channel server for display 10
[20220419-21:47:00] [WARN ] Timed out waiting for X server on display 10 to startup
[20220419-21:47:00] [ERROR] There is no X server active on display 10
[20220419-21:47:00] [ERROR] A fatal error has occured attempting to start the window manager on display 10, aborting connection
[20220419-21:47:00] [WARN ] Window manager (pid 2391, display 10) exited quickly (0 secs). This could indicate a window manager config problem
[20220419-21:47:00] [INFO ] Calling auth_stop_session and auth_end from pid 2390
[20220419-21:47:00] [INFO ] Terminating X server (pid 2392) on display 10
[20220419-21:47:00] [INFO ] Terminating the xrdp channel server (pid 2396) on display 10
[20220419-21:47:00] [INFO ] X server on display 10 (pid 2392) returned exit code 1 and signal number 0
[20220419-21:47:00] [INFO ] xrdp channel server for display 10 (pid 2396) exit code 0 and signal number 0
[20220419-21:47:00] [INFO ] cleanup_sockets:
[20220419-21:47:00] [INFO ] ++ terminated session:  username david, display :10.0, session_pid 2390, ip 192.168.50.200:54277 - socket: 12

Do you have an idea of ​​the problem ?

**Comment by matt335672** [comment] 2022-04-20 09:05
Likely duplicate of #2224. Try that first and please let us know how you get on.

**Comment by xdoomer01** [comment] 2022-04-20 15:57
I already tried, but still the problem.
I tried everything I found on the internet and on the github, but nothing worked.
I also tried #2177

Below is the log with the modification :
cat /var/log/xrdp.ini
[20220420-17:42:25] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220420-17:42:25] [INFO ] listening to port 3389 on 0.0.0.0
[20220420-17:42:25] [INFO ] xrdp_listen_pp done
[20220420-17:42:27] [INFO ] starting xrdp with pid 2305
[20220420-17:42:27] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220420-17:42:27] [INFO ] listening to port 3389 on 0.0.0.0
[20220420-17:42:27] [INFO ] xrdp_listen_pp done
[20220420-17:44:44] [INFO ] Socket 12: AF_INET connection received from 192.168.50.200 port 54783
[20220420-17:44:44] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220420-17:44:44] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220420-17:44:44] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220420-17:44:44] [ERROR] SSL_read: I/O error
[20220420-17:44:44] [ERROR] libxrdp_force_read: header read error
[20220420-17:44:44] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20220420-17:44:44] [ERROR] [MCS Connection Sequence] receive connection request failed
[20220420-17:44:44] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20220420-17:44:44] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20220420-17:44:44] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20220420-17:44:44] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20220420-17:44:44] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20220420-17:44:46] [INFO ] Socket 12: AF_INET connection received from 192.168.50.200 port 54784
[20220420-17:44:46] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220420-17:44:46] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220420-17:44:46] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220420-17:44:46] [INFO ] Connected client computer name: DESKTOP-IPUMR3I
[20220420-17:44:46] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20220420-17:44:46] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20220420-17:44:46] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x0000040C]
[20220420-17:44:46] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [fr] options []
[20220420-17:44:46] [INFO ] TLS connection established from 192.168.50.200 port 54784: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20220420-17:44:46] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20220420-17:44:46] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20220420-17:44:46] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20220420-17:44:46] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20220420-17:44:46] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20220420-17:44:46] [INFO ] Loading keymap file /etc/xrdp/km-0000040c.ini
[20220420-17:44:46] [WARN ] local keymap file for 0x0000040c found and doesn't match built in keymap, using local keymap file
[20220420-17:44:53] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220420-17:44:53] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220420-17:44:53] [INFO ] sesman connect ok
[20220420-17:44:53] [INFO ] sending login info to session manager. Please wait...
[20220420-17:44:53] [INFO ] xrdp_wm_log_msg: login successful for user david on display 10
[20220420-17:44:53] [INFO ] login successful for user david on display 10
[20220420-17:44:54] [INFO ] loaded module 'libxup.so' ok, interface size 10296, version 4
[20220420-17:44:54] [INFO ] started connecting
[20220420-17:44:54] [INFO ] lib_mod_connect: connecting via UNIX socket
[20220420-17:44:54] [INFO ] lib_mod_log_peer: xrdp_pid=2401 connected to X11rdp_pid=2404 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=192.168.50.200 client_port=54784
[20220420-17:44:54] [INFO ] connected ok


cat /var/log/xrdp-sesman.log 
[20220420-17:42:25] [INFO ] starting xrdp-sesman with pid 2334
[20220420-17:44:53] [INFO ] Socket 8: AF_INET connection received from 127.0.0.1 port 34442
[20220420-17:44:53] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20220420-17:44:53] [INFO ] ++ created session (access granted): username david, ip 192.168.50.200:54784 - socket: 12
[20220420-17:44:53] [INFO ] starting Xorg session...
[20220420-17:44:53] [INFO ] Starting session: session_pid 2402, display :10.0, width 1600, height 900, bpp 24, client ip 192.168.50.200:54784 - socket: 12, user name david
[20220420-17:44:53] [ERROR] sesman_data_in: scp_process_msg failed
[20220420-17:44:53] [INFO ] [session start] (display 10): calling auth_start_session from pid 2402
[20220420-17:44:53] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220420-17:44:54] [INFO ] Starting X server on display 10: /usr/libexec/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log  
[20220420-17:44:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20220420-17:44:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20220420-17:44:54] [INFO ] Session started successfully for user david on display 10
[20220420-17:44:54] [INFO ] Session in progress on display 10, waiting until the window manager (pid 2403) exits to end the session
[20220420-17:44:54] [INFO ] Starting the xrdp channel server for display 10
[20220420-17:44:54] [INFO ] Found X server running at /tmp/.X11-unix/X10
[20220420-17:44:54] [INFO ] Starting the default window manager on display 10: /etc/xrdp/startwm.sh
[20220420-17:44:54] [WARN ] Window manager (pid 2403, display 10) exited quickly (0 secs). This could indicate a window manager config problem
[20220420-17:44:54] [INFO ] Calling auth_stop_session and auth_end from pid 2402
[20220420-17:44:54] [INFO ] Terminating X server (pid 2404) on display 10
[20220420-17:44:54] [INFO ] Terminating the xrdp channel server (pid 2409) on display 10
[20220420-17:44:54] [INFO ] X server on display 10 (pid 2404) returned exit code 0 and signal number 0
[20220420-17:44:54] [INFO ] xrdp channel server for display 10 (pid 2409) exit code 0 and signal number 0
[20220420-17:44:54] [INFO ] cleanup_sockets:
[20220420-17:44:54] [INFO ] ++ terminated session:  username david, display :10.0, session_pid 2402, ip 192.168.50.200:54784 - socket: 12

**Comment by matt335672** [comment] 2022-04-21 09:24
The `/usr/libexec/Xorg` looks right, and is definitely needed.

Looking at the Alpine script `/etc/X11/xinit/xinitrc` (under source control [here](https://git.alpinelinux.org/aports/tree/community/xinit/xinitrc?h=3.15-stable)), it doesn't look like KDE is directly supported. Looking [here](https://wiki.alpinelinux.org/wiki/KDE#From_the_console) it looks like you need to invoke the command `startplasma-x11` to do that.

You'll need to install `plasma-workspace` if it isn't already installed. Then try this as user `david`:-

```
ln -s /usr/bin/startplasma-x11 ~/.xinitrc
```

**Comment by xdoomer01** [comment] 2022-04-23 08:02
Hello,

It actually works perfectly!

Thanks very much !

**Comment by matt335672** [comment] 2022-04-24 08:37
Thanks for the feedback

**Closed as completed by matt335672** 2022-04-24 08:37 UTC
