### ISSUE TITLE
[systemd] no error if port already in use

### ISSUE THREAD

**Issue by cocoon** [neutrinolabs/xrdp#644] opened 2017-01-25 07:06 UTC
When I try to start a second instance with the same port configured in xrdp.ini for example with:
`systemctl start xrdp2.service`

It shows no error message but will not be running.
You can see the error in:
 ` journalctl -xe`

`[ERROR] xrdp_listen_main_loop: listen error, possible port already in use`

(Ubuntu 16.04)

**Comment by metalefty** [comment] 2017-05-15 06:58
I confiemd this issue.

**Comment by metalefty** [comment] 2017-05-15 08:59
This issue is caused xrdp process exits normally even if `xrdp_listen_main_loop` returns with failure.
I'm working on this issue.

**Comment by cocoon** [comment] 2017-05-15 09:43
Thanks for the great work you are all doing to get this stable on modern systems!

**Comment by metalefty** [comment] 2017-05-16 05:20
Also, xrdp-sesman service should raise error if 3350 port is already in use.

**Comment by metalefty** [comment] 2017-05-17 09:02
@cocoon I've submitted a fix. Can you test?

**Comment by cocoon** [comment] 2017-05-17 10:13
Great, looks good.
The only thing I would add to xrdp is the same hint where to check for the exact error like for xrdp-sesman:

**Currently:**
```
# systemctl start xrdp-sesman
Job for xrdp-sesman.service failed because the control process exited with error code. See "systemctl status xrdp-sesman.service" and "journalctl -xe" for details.

# systemctl start xrdp
Job for xrdp.service canceled.
```

**Improved:**
```
# systemctl start xrdp
Job for xrdp.service canceled. See "systemctl status xrdp.service" and "journalctl -xe" for details.
```

**Comment by metalefty** [comment] 2017-05-18 00:47
The message is shown by systemd, not by xrdp. It cannot be controlled by xrdp code. Probably, the difference of these messages might be caused by service dependency. Both 3350/tcp and 3389/tcp is in use, the message is not "Job for xrdp.service canceled.".

```
$ nc -l 3350 & nc -l 3389 &
$ sudo systemctl start xrdp
(see what is shown)
```


I'm not sure about systemd services and what I can do to implement what you want.

**Comment by cocoon** [comment] 2017-05-18 06:59
Oh yes sorry you're right.
I was so sure it must be possible to control that but I found that request for systemd:
https://github.com/systemd/systemd/issues/3448

**Comment by metalefty** [comment] 2017-06-20 05:29
Fixed by #753.

**Closed by metalefty** 2017-06-20 05:29 UTC
Labels: confirmed
