### ISSUE TITLE
xrdp memory leak

### ISSUE THREAD

**Issue by yuyiliang1993** [neutrinolabs/xrdp#1634] opened 2020-07-14 04:33 UTC
Playing video in an xrdp session will cause memory growth for a long time, and the memory leak in the vpn environment is more serious. How to solve it?

**Comment by matt335672** [comment] 2020-07-14 12:27
Hi @yuyiliang1993 

Can you please give us a bit more information?

The following would be useful:-
- Server operating system
- Version of XRDP
- Does this happen with Xorg backend or Xvnc backend or both?
- If Xorg backend, what is the version of xorgxrdp?
- If Xvnc backend, what is the colour depth you are using?
- Which processes are using more memory

Thanks,

**Comment by yuyiliang1993** [comment] 2020-07-14 12:35
Hello there
I connected the Windows target machine through the neutrinordp module, and then watched the video, and found that the memory of the xrdp process increased relatively fast, and the CPU occupancy rate was 100%, especially in the vpn environment. The version I use is xrdp-0.9.11.
Thank you

**Comment by yuyiliang1993** [comment] 2020-07-14 12:36
> Hi @yuyiliang1993
> 
> Can you please give us a bit more information?
> 
> The following would be useful:-
> 
> * Server operating system
> * Version of XRDP
> * Does this happen with Xorg backend or Xvnc backend or both?
> * If Xorg backend, what is the version of xorgxrdp?
> * If Xvnc backend, what is the colour depth you are using?
> * Which processes are using more memory
> 
> Thanks,

**Comment by yuyiliang1993** [comment] 2020-07-14 12:37
Hello there
I connected the Windows target machine through the neutrinordp module, and then watched the video, and found that the memory of the xrdp process increased relatively fast, and the CPU occupancy rate was 100%, especially in the vpn environment. The version I use is xrdp-0.9.11.
Thank you

**Comment by matt335672** [comment] 2020-07-14 13:00
What operating system are you running xrdp on?

Thanks.

**Comment by yuyiliang1993** [comment] 2020-07-14 15:50
Debian7.5 and Centos7

**Comment by yuyiliang1993** [comment] 2020-07-15 04:50
On 7/14/2020 21:00，matt335672<notifications@github.com> wrote：

What operating system are you running xrdp on?

Thanks.

**Comment by matt335672** [comment] 2020-07-20 11:17
I've spent a bit of time looking at this, and while I'm seeing memory usage by XRDP increasing to what seems a lot, it all seems to be caching of various sorts. Eventually XRDP reaches a certain level of memory usage and stays there. I can't find any actual leaks as such.

So it's possible I'm not seeing exactly what you're seeing.

Can you try the following for me?
- See if the same thing occurs with the `xfreerdp` binary which is built as part of the NeutrinoRDP distro. It's probably in `/usr/local/bin/xfreerdp` if you're just taken the defaults.
- Install valgrind and run xrdp with the command:-
   ```bash
   sudo valgrind --leak-check=full  /usr/local/sbin/xrdp -n 2>&1 | tee ~/valgrind.log
   ```

If the same thing occurs with valgrind (it may not), please post the contents of `valgrind.log`.

Also, I'm guessing you're connecting to the proxying machine over some kind of WAN link. Is that right? If so, posting the bandwidth and latency of this link could be useful.

**Comment by yuyiliang1993** [comment] 2020-07-20 11:55
Hello there
Thank you for helping me deal with this problem, I have found the problem so far. I sent an email to the mailbox of the development team, I hope you can check,
Thank you

**Comment by matt335672** [comment] 2020-07-21 09:22
Thanks for letting me know.

I can't see that mailbox at the moment and the lead developer is not available for a couple of weeks. If you're happy to leave it that's fine (we will get to it), otherwise feel free to post more info here.

**Comment by yuyiliang1993** [comment] 2020-07-21 09:41
Hi
In the trans_write_copy_s function in trans.c, when the data is not sent, the linked list wait_s is used for temporary caching, but the actual problem encountered is that this linked list will cause unlimited memory growth, especially when browsing the web or watching videos remotely In the case of. If you use VPN to access the target machine in the intranet, when the client traffic tends to 0, it will cause serious memory usage. At last,the structure "tran" is destroyed, there is no processing for wait_s to free memory. 
thanks

**Comment by matt335672** [comment] 2020-07-21 09:50
Thanks - that's a clear description. I'll take a look.

**Comment by matt335672** [comment] 2020-07-28 09:29
Hi @yuyiliang1993 

Why have you closed this?

I'm still looking at it - there may be a significant issue here which should be addressed.

Thanks for any info

**Comment by jsorg71** [comment] 2020-07-28 18:43
The way this was intended to work.  xrdp has a output buffer limit(if setup in trans).  If acceded, it should temporarily stop listening on the source.  It does this to allow the source to feel the back pressure.  The source here being chansrv and Xorg.  If this mechanism is not working and xrdp keeps growing that would be a bug.

**Comment by matt335672** [comment] 2020-07-31 07:55
Thanks Jay - I though there would be something like that in there.

I'm setting up a test network here with an emulated WAN so I can (hopefully) reproduce the reported fault and see whether we need to make any changes.

**Comment by yuyiliang1993** [comment] 2020-08-01 08:49
Hello 
This problem has not been resolved. I mainly use VPN to access the remote desktop of the intranet, and then watch the video on the remote desktop, I will find that xrdp occupies more and more memory. Due to the relatively low bandwidth of my VPN, mstsc cannot read the server's data immediately, so the server uses a cache. When the amount of data is large, the system memory will be exhausted and cause a crash.
I'm currently trying to solve this problem by adopting flow control that restricts xrdp reading and sending, but there is no good algorithm at present, I hope everyone will work together.
Thanks

**Comment by matt335672** [comment] 2020-08-07 11:03
Hi @yuyiliang1993 

I believe I've got a fix for your reported problem which adapts the existing flow control mechanism for the neutrinordp module.

I've created a branch in my git repository for XRDP which has a test fix. It seems OK on my simulated WAN link (5Mb/s).

Would you be happy to try the test fix for me?

My git repository is at [https://github.com/matt335672/xrdp](https://github.com/matt335672/xrdp)

You'll need to clone it, check out the ` neutrinordp-flow-control` branch and rebuild XRDP.

Thanks for any feedback

**Comment by yuyiliang1993** [comment] 2020-08-07 16:13
Ok, I will test this fix as soon as possible.

**Comment by matt335672** [comment] 2020-08-26 10:48
Hi @yuyiliang1993 

Will you get a chance to test this shortly do you think?

Thanks

**Comment by yuyiliang1993** [comment] 2020-09-15 02:22
The current test results do not seem to have any problems, and online problems need further testing.

**Closed** 2020-11-17 09:31 UTC
