### ISSUE TITLE
address 127.0.0.1 listens on ip6 only

### ISSUE THREAD

**Issue by stan3** [neutrinolabs/xrdp#770] opened 2017-06-08 16:27 UTC
If I specify address=127.0.0.1 in xrdp.ini then I'm finding xrdp is only listening on the ip6 localhost address.  From netstat:

`tcp6       0      0 ::1:3389                :::*                    LISTEN      3912/xrdp       
`
so connections to 127.0.0.1 fail.

**Comment by metalefty** [comment] 2017-06-09 01:25
Can't reproduce with current devel head bb9756f.

`address=127.0.0.1` 

```
$ netstat -an | grep 3389
tcp        0      0 127.0.0.1:3389          0.0.0.0:*               LISTEN
```

**Comment by stan3** [comment] 2017-06-12 07:59
Thanks for trying, I'm using 0.9.1, will try a later version.

**Comment by metalefty** [comment] 2017-07-04 10:44
No response from submitter. Closing.

**Comment by stan3** [comment] 2017-07-04 10:56
I tried this with the current latest (0.9.2) and still getting the same on my system.  Perhaps due to a change since 0.9.2.

**Comment by metalefty** [comment] 2017-07-04 11:02
Can you try the latest head?

**Comment by stan3** [comment] 2017-07-04 14:20
Will try.  Changes from https://github.com/neutrinolabs/xrdp/issues/714 look like they touched this area which may have improved things.

**Comment by metalefty** [comment] 2017-07-05 00:00
Yes, maybe your issue has been fixed by that.

**Closed** 2017-07-26 02:26 UTC
