### ISSUE TITLE
large screen refreshes cause session to crash

### ISSUE THREAD

**Issue by johnarnold** [neutrinolabs/xrdp#888] opened 2017-09-22 16:55 UTC
xrdp 0.9.3 / Ubuntu 16.04 / xorgxrdp

Using a 4k monitor, if you have a large (full screen or most of the screen) terminal window open and refresh a lot of data (e.g. cat /var/log/syslog) , it can cause your session to crash (and can't reconnect).  You have to login via ssh and pkill -u <user> to get back on.

I don't have a cleaner repro than that, but it happens fairly often.

**Comment by metalefty** [comment] 2017-09-28 01:58
The issue should be addressed but needs more investigation.

BTW, it looks you've finally built xorgxrdp successfully and no problem with smaller screen (ex 2K), right?

**Comment by johnarnold** [comment] 2017-10-01 15:44
@metalefty builds are working fine using hacky bash script.  Would still love a straightforward way to build .deb packages, since Ubuntu never updates.

Is there a fix commit for this issue?  I want to rule it in or out.  Thanks!

**Comment by johnarnold** [comment] 2017-10-26 22:18
I've encountered this issue multiple times today, so it's still ongoing.

**Comment by metalefty** [comment] 2017-10-27 00:57
Could you explain what your "crash" mean?

**Comment by johnarnold** [comment] 2017-11-09 17:10
Session disconnect, can’t reconnect “internal error”.

Interestingly, after the session error, if I change the screen size to something smaller (1080p etc)  I can reconnect fine. Then if I disconnect and set back to 4k I can reconnect fine too.

**Comment by metalefty** [comment] 2017-11-10 01:59
That's interesting. I tried to reproduce but can't reproduce with FreeRDP.
I cannot test with mstsc because AFAIK mstsc's maximum screen size is limited to the actual display size.  I don't have 4K monitor.

Can you let me know what's happening when you can't reconnect after unintended disconnection?

1. run xrdp and xrdp-sesman in foreground
2. reproduce the crash
3. try to reconnect and show me the output

**Comment by metalefty** [comment] 2018-03-09 06:55
I've got 4K monitor. I can test it now.

**Comment by metalefty** [comment] 2018-04-11 05:58
xrdp v0.9.5 with 3840x2160 screen working fine for me.

**Comment by akireyev** [comment] 2018-06-27 08:37
If this is the same issue that I'm experiencing, it might be possible to reconnect to the same session by changing the connection type in the Remote Desktop client to WAN.

**Comment by matt335672** [comment] 2024-08-06 11:22
Closing this one - in the last 6 years we've fixed a lot of bugs in this area (e.g. #3083).

**Closed by matt335672** 2024-08-06 11:22 UTC
