### ISSUE TITLE
XRDP, X11RDP black screen when logging in as a LDAP user

### ISSUE THREAD

**Issue by Michel-5** [neutrinolabs/xrdp#597] opened 2016-12-29 08:04 UTC
Hello all,

First of all i need to say that the code you guys give here is awesome!

I also want to say in advance that my english is terrible, so sorry for that.

For a project i've build multiple Linux Terminal Server Projects with users who authenticate trough LDAP because some users work on different locations. I want to build it in a way that users can login through RDP. So for an example, if you have 2 locations and a persons account is on location 1 and he or she wants to work from location 2, he or she needs a RDP connection.

When i build XRDP and Xorg from neutrinolabs i get the local users to work with dual screen. But when i want to login with a LDAP User, i only get a black screen.

When i use the X11rdp-o-Matic script, i only get it working with one monitor because that script build's it like a xvnc server.

I hope someone knows the answer for this problem.

Thanks in advance for the use of your time

Greetings Michel

**Comment by proski** [comment] 2016-12-29 17:19
I suspect that the issue is with Xorg being setuid root. That would explain why xorgxrdp is affected and why remote users are affected. Please try xrdp 0.9.1 or the current devel branch of xrdp. What is the kernel version you are using (assuming xrdp runs on Linux)?

Can you try copying Xorg to another executable, setting its permission to 755 (no setuid) and using it instead of Xorg in sesman.ini?

What do you see in logs (xrdp.log and xrdp-sesman.log) around the time when the black screen is shown?

**Comment by metalefty** [comment] 2017-12-13 17:18
No feedback from the reporter for long, closing.

**Closed by metalefty** 2017-12-13 17:18 UTC
Labels: waiting-feedback
