### ISSUE TITLE
Test suite failure on sparc64, loong64

### ISSUE THREAD

**Issue by alexmyczko** [neutrinolabs/xrdp#2899] opened 2024-01-04 08:12 UTC
### xrdp version

0.9.24

### Detailed xrdp version, build options

```
See tests/common/test-suite.log
Please report to xrdp-devel@googlegroups.com
============================================================================
make[5]: *** [Makefile:801: test-suite.log] Error 1
make[5]: Leaving directory '/<<PKGBUILDDIR>>/tests/common'
make[4]: *** [Makefile:909: check-TESTS] Error 2
make[4]: Leaving directory '/<<PKGBUILDDIR>>/tests/common'
make[3]: *** [Makefile:982: check-am] Error 2
make[3]: Leaving directory '/<<PKGBUILDDIR>>/tests/common'
make[2]: *** [Makefile:397: check-recursive] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/tests'
make[1]: *** [Makefile:483: check-recursive] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_test: error: make -j4 check "TESTSUITEFLAGS=-j4 --verbose" VERBOSE=1 returned exit code 2
make: *** [debian/rules:61: binary-arch] Error 25
```

### Operating system & version

Debian GNU/Linux sid

### Installation method

git clone & make install

### What desktop environment do you use?

amiwm

### Environment xrdp running on

physical machine

### What's your client?

Microsoft Remote Desktop on macOS and rdesktop and xfreerdp

### Area(s) with issue?

Compile error

### Steps to reproduce

Please see https://buildd.debian.org/status/package.php?p=xrdp&suite=experimental

not yet available .dsc link, but basically dget -x url.to.the.dsc
available now from: 

```
dget -x http://sid.ethz.ch/debian/xrdp/2023/xrdp_0.9.24-1.dsc
cd xrdp*/
debuild
```

### ✔️ Expected Behavior

it builds

### ❌ Actual Behavior

FTBFS

**Comment by matt335672** [comment] 2024-01-04 13:23
I've downloaded the sparc64 build log

[xrdp_0.9.24-1_sparc64.log](https://github.com/neutrinolabs/xrdp/files/13830179/xrdp_0.9.24-1_sparc64.log)

This is a duplicate of #2214 by the looks of it.

The loong64 tests have no logs - I don't think this is anything we can have done.

@alexmyczko - are these machines more heavily loaded than previously? This test hasn't changed.

**Comment by alexmyczko** [comment] 2024-01-04 13:26
ahhh i'm sorry for the disruption, you certainly are right

**Comment by matt335672** [comment] 2024-01-04 14:14
No that's fine - we really need to address this.

I'll close this one now, but continue the conversation in #2214 - I've done some more analysis.

**Comment by matt335672** [comment] 2024-01-04 14:39
Sorry - meant #2213, which is the actual fault report.

**Closed as completed by matt335672** 2024-01-04 14:39 UTC
Labels: bug
