### ISSUE TITLE
reconnect after connection drop hangs

### ISSUE THREAD

**Issue by vixie** [neutrinolabs/xrdp#2021] opened 2021-10-17 21:43 UTC
connecting to suse leap 15.3 inside hyper-v under windows 10 (21H2) using windows rdp client. any network failure including suspend/resume results in an unkillable and nonreconnectable session. searched the web, found this old bug report:

https://sourceforge.net/p/xrdp/bugs/54/

that fix, modified for changes made since then to the surrounding source code, is still necessary, and still sufficient.

```
--- xrdp-0.9.13.1/sesman/session.c.orig 2021-10-17 21:26:45.386189301 +0000
+++ xrdp-0.9.13.1/sesman/session.c      2021-10-17 21:26:26.638741197 +0000
@@ -833,6 +833,7 @@
     }
     else
     {
+        g_signal_child_stop(sig_sesman_session_end); /* SIGCHLD */
         temp->item->pid = pid;
         temp->item->display = display;
         temp->item->width = s->width;
```

**Comment by matt335672** [comment] 2021-10-18 11:42
Thanks for that, @vixie

I've had a look at the existing code, and as Paul van Tilburg says on the original thread this shouldn't be necessary on the face of it, although I'm quite prepared to believe it as the signal handling needs some updating.

In the existing code, the SIGCHLD handler is set once, whereas the patch causes the SIGCHLD handler to be reset after every session is created. That may be significant.

I don't suppose you've got any sesman logs from the hangs have you? It would be good to get some more understanding of exactly what codepath is being taken to cause the SIGCHLD handler to be lost.

**Comment by matt335672** [comment] 2021-10-19 08:35
I'd like to try to reproduce this here if possible, but I'm a little confused from your description and the link to https://sourceforge.net/p/xrdp/bugs/54/.

When you say 'network failure', this wouldn't normally cause a session to exit, and so SIGCHLD wouldn't come into this. Are you setting `KillDisconnected` and `DisconnectedTimeLimit` in `/etc/xrdp/sesman.ini`?

Thanks.

**Comment by vixie** [comment] 2021-10-19 20:24
at the moment i've broken _everything_ and i need to set up a clean 
environment, so that i can do A/B testing, with the diags you've asked 
for. sorry for any delay.

**Comment by matt335672** [comment] 2021-10-20 09:22
I sympathise with you on 'breaking everything' - it's something I seem to have a talent for myself.

I'd really like to get to the bottom if this. This whole area will be restructured as part of #1961, so I'd like to understand what is going on here. I suspect somewhere along the lines the signal handler for SIGCHLD is getting set to SIG_DFL, and that's breaking the whole session failure detection logic. Your patch is compensating for this, but it bothers me that we don't have the complete story yet.

In the longer term, we need to rip the `signal` stuff out and use `sigaction`.

**Comment by matt335672** [comment] 2021-10-21 15:59
This might be muddying the waters somewhat, but there is a situation I've come across today where the chansrv process hangs hard, and doesn't respond to a SIGTERM. I'm still investigating.

In that situation, the session can exit, but because the session leader is waiting indefinitely for chansrv to finish, the session is not marked as exited and the signal handler doesn't fire.

That's got some similarities with your issue, but I can't see how the patch would fix it. If you do manage to reproduce your issue however, it would be interesting to see an output of `ps -ef | grep xrdp` so we can see exactly what's running.

**Comment by matt335672** [comment] 2021-11-19 11:01
@vixie - have you managed to find any time to look into this further?

Thanks.

**Comment by matt335672** [comment] 2022-01-13 16:19
@vixie - please feel free to comment further if you get anywhere with this, and I'll re-open it.

At the moment I haven't got enough info to go on, I'm afraid.

**Closed as completed by matt335672** 2022-01-13 16:19 UTC

**Comment by vixie** [comment] 2022-01-17 04:14
kk. got busy with day job; now unemployed. will remove all traces of the opensuse build version of xrdp and install yours fresh and see what i can see.

**Comment by matt335672** [comment] 2022-03-04 11:56
@vixie - if you're still interested in this area, I've re-worked the signal processing in PR #2168 to use a varaint of Stevens' "self-pipe trick". I think it makes a bit more sense now, but if you've got any comments please feel free to add them
