### ISSUE TITLE
Tests failing on hppa

### ISSUE THREAD

**Issue by alexmyczko** [neutrinolabs/xrdp#2924] opened 2024-01-25 16:35 UTC
Please report to xrdp-devel@googlegroups.com

from https://buildd.debian.org/status/package.php?p=xrdp&suite=sid

**Comment by matt335672** [comment] 2024-01-25 17:28
Duplicate of #2899 (not immediately obvious)

Should be fixed by #2903

**Closed as completed by matt335672** 2024-01-25 17:28 UTC
