### ISSUE TITLE
Kickout from RDP session

### ISSUE THREAD

**Issue by Suncatcher** [neutrinolabs/xrdp#754] opened 2017-05-17 14:23 UTC
From time to time I get this warning and now my session is interrupted. Multiple trials give no result and I have to restart the machine.

![untitled4](https://cloud.githubusercontent.com/assets/6388034/26158810/8a65f328-3b25-11e7-8cdc-fa9369020166.png)

What is it?

**Comment by Suncatcher** [comment] 2017-05-17 14:40
I noticed that it happens frequently after establishing openvpn connection. Does these things correlated?

**Comment by Suncatcher** [comment] 2017-05-17 15:43
Here is the `xrdp.log`

    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:20] [CORE ] shutting down log subsystem...
    [20170517-18:37:20] [INFO ] Socket 12: AF_INET connection received from 192.168.0.1 port 4190
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3383)
    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [INFO ] connected client computer name: DELLANO
    [20170517-18:37:20] [INFO ] TLS connection established from 192.168.0.1 port 4190: TLSv1.2 with cipher AES256-GCM-SHA384
    [20170517-18:37:21] [DEBUG] xrdp_000006cd_wm_login_mode_event_00000001
    [20170517-18:37:21] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
    [20170517-18:37:21] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
    [20170517-18:37:21] [DEBUG] return value from xrdp_mm_connect 0
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: login successful for display 10
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: started connecting
    [20170517-18:37:21] [INFO ] lib_mod_log_peer: xrdp_pid=1741 connected to X11rdp_pid=1013 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=192.168.0.1 client_port=4190
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connected ok
    [20170517-18:37:21] [DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
    [20170517-18:37:21] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:35898)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpdr (0)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpsnd (1)
    [20170517-18:37:21] [INFO ] The following channel is allowed: cliprdr (2)
    [20170517-18:37:21] [INFO ] The following channel is allowed: drdynvc (3)
    [20170517-18:37:21] [DEBUG] The allow channel list now initialized for this session
    [20170517-18:37:21] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:22] [DEBUG] xrdp_mm_module_cleanup
    [20170517-18:37:22] [DEBUG] Closed socket 19 (AF_UNIX)
    [20170517-18:37:22] [DEBUG] Closed socket 20 (AF_UNIX)
    [20170517-18:37:22] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:22] [CORE ] shutting down log subsystem...

And here is the xrdp-sesman.log

    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:20] [CORE ] shutting down log subsystem...
    [20170517-18:37:20] [INFO ] Socket 12: AF_INET connection received from 192.168.0.1 port 4190
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3383)
    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [INFO ] connected client computer name: DELLANO
    [20170517-18:37:20] [INFO ] TLS connection established from 192.168.0.1 port 4190: TLSv1.2 with cipher AES256-GCM-SHA384
    [20170517-18:37:21] [DEBUG] xrdp_000006cd_wm_login_mode_event_00000001
    [20170517-18:37:21] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
    [20170517-18:37:21] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
    [20170517-18:37:21] [DEBUG] return value from xrdp_mm_connect 0
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: login successful for display 10
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: started connecting
    [20170517-18:37:21] [INFO ] lib_mod_log_peer: xrdp_pid=1741 connected to X11rdp_pid=1013 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=192.168.0.1 client_port=4190
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connected ok
    [20170517-18:37:21] [DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
    [20170517-18:37:21] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:35898)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpdr (0)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpsnd (1)
    [20170517-18:37:21] [INFO ] The following channel is allowed: cliprdr (2)
    [20170517-18:37:21] [INFO ] The following channel is allowed: drdynvc (3)
    [20170517-18:37:21] [DEBUG] The allow channel list now initialized for this session
    [20170517-18:37:21] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:22] [DEBUG] xrdp_mm_module_cleanup
    [20170517-18:37:22] [DEBUG] Closed socket 19 (AF_UNIX)
    [20170517-17:23:38] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:23:42] [INFO ] A connection received from 127.0.0.1 port 50402
    [20170517-17:23:43] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:2893 - socket: 12
    [20170517-17:23:43] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:29:25] [INFO ] A connection received from 127.0.0.1 port 50404
    [20170517-17:29:25] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:3131 - socket: 12
    [20170517-17:29:25] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:29:29] [INFO ] A connection received from 127.0.0.1 port 50406
    [20170517-17:29:30] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:3133 - socket: 12
    [20170517-17:29:30] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:35:21] [DEBUG] libscp initialized
    [20170517-17:35:21] [INFO ] starting xrdp-sesman with pid 759
    [20170517-17:35:21] [INFO ] listening to port 3350 on 127.0.0.1
    [20170517-17:37:39] [INFO ] A connection received from 127.0.0.1 port 35254
    [20170517-17:37:40] [INFO ] ++ created session (access granted): username suncatcher, ip 192.168.0.1:3257 - socket: 12
    [20170517-17:37:40] [INFO ] starting Xorg session...
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6010)
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6210)
    [20170517-17:37:40] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp
    [20170517-17:37:40] [CORE ] waiting for window manager (pid 1012) to exit
    [20170517-17:38:16] [INFO ] A connection received from 127.0.0.1 port 35376
    [20170517-17:38:16] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:3260 - socket: 12
    [20170517-17:38:16] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:08:58] [INFO ] A connection received from 127.0.0.1 port 35780
    [20170517-18:08:58] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:3719 - socket: 12
    [20170517-18:08:58] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:35:27] [INFO ] A connection received from 127.0.0.1 port 35886
    [20170517-18:35:27] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4154 - socket: 12
    [20170517-18:35:28] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:35:44] [INFO ] A connection received from 127.0.0.1 port 35890
    [20170517-18:35:45] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4158 - socket: 12
    [20170517-18:35:45] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:37:21] [INFO ] A connection received from 127.0.0.1 port 35898
    [20170517-18:37:21] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4190 - socket: 12
    [20170517-18:37:21] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)

**Comment by Suncatcher** [comment] 2017-05-17 15:43
Here is the `xrdp.log`

    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:20] [CORE ] shutting down log subsystem...
    [20170517-18:37:20] [INFO ] Socket 12: AF_INET connection received from 192.168.0.1 port 4190
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3383)
    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [INFO ] connected client computer name: DELLANO
    [20170517-18:37:20] [INFO ] TLS connection established from 192.168.0.1 port 4190: TLSv1.2 with cipher AES256-GCM-SHA384
    [20170517-18:37:21] [DEBUG] xrdp_000006cd_wm_login_mode_event_00000001
    [20170517-18:37:21] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
    [20170517-18:37:21] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
    [20170517-18:37:21] [DEBUG] return value from xrdp_mm_connect 0
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: login successful for display 10
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: started connecting
    [20170517-18:37:21] [INFO ] lib_mod_log_peer: xrdp_pid=1741 connected to X11rdp_pid=1013 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=192.168.0.1 client_port=4190
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connected ok
    [20170517-18:37:21] [DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
    [20170517-18:37:21] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:35898)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpdr (0)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpsnd (1)
    [20170517-18:37:21] [INFO ] The following channel is allowed: cliprdr (2)
    [20170517-18:37:21] [INFO ] The following channel is allowed: drdynvc (3)
    [20170517-18:37:21] [DEBUG] The allow channel list now initialized for this session
    [20170517-18:37:21] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:22] [DEBUG] xrdp_mm_module_cleanup
    [20170517-18:37:22] [DEBUG] Closed socket 19 (AF_UNIX)
    [20170517-18:37:22] [DEBUG] Closed socket 20 (AF_UNIX)
    [20170517-18:37:22] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:22] [CORE ] shutting down log subsystem...

And here is the xrdp-sesman.log

    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [ERROR] Listening socket is in wrong state, terminating listener
    [20170517-18:37:20] [CORE ] shutting down log subsystem...
    [20170517-18:37:20] [INFO ] Socket 12: AF_INET connection received from 192.168.0.1 port 4190
    [20170517-18:37:20] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:20] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3383)
    [20170517-18:37:20] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
    [20170517-18:37:20] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
    [20170517-18:37:20] [DEBUG] TLSv1.2 enabled
    [20170517-18:37:20] [DEBUG] TLSv1.1 enabled
    [20170517-18:37:20] [DEBUG] TLSv1 enabled
    [20170517-18:37:20] [DEBUG] Security layer: requested 11, selected 1
    [20170517-18:37:20] [INFO ] connected client computer name: DELLANO
    [20170517-18:37:20] [INFO ] TLS connection established from 192.168.0.1 port 4190: TLSv1.2 with cipher AES256-GCM-SHA384
    [20170517-18:37:21] [DEBUG] xrdp_000006cd_wm_login_mode_event_00000001
    [20170517-18:37:21] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
    [20170517-18:37:21] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: sesman connect ok
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
    [20170517-18:37:21] [DEBUG] return value from xrdp_mm_connect 0
    [20170517-18:37:21] [INFO ] xrdp_wm_log_msg: login successful for display 10
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: started connecting
    [20170517-18:37:21] [INFO ] lib_mod_log_peer: xrdp_pid=1741 connected to X11rdp_pid=1013 X11rdp_uid=1000 X11rdp_gid=1000 client_ip=192.168.0.1 client_port=4190
    [20170517-18:37:21] [DEBUG] xrdp_wm_log_msg: connected ok
    [20170517-18:37:21] [DEBUG] xrdp_mm_connect_chansrv: chansrv connect successful
    [20170517-18:37:21] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:35898)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpdr (0)
    [20170517-18:37:21] [INFO ] The following channel is allowed: rdpsnd (1)
    [20170517-18:37:21] [INFO ] The following channel is allowed: cliprdr (2)
    [20170517-18:37:21] [INFO ] The following channel is allowed: drdynvc (3)
    [20170517-18:37:21] [DEBUG] The allow channel list now initialized for this session
    [20170517-18:37:21] [DEBUG] Closed socket 12 (AF_INET 192.168.0.100:3383)
    [20170517-18:37:22] [DEBUG] xrdp_mm_module_cleanup
    [20170517-18:37:22] [DEBUG] Closed socket 19 (AF_UNIX)
    [20170517-17:23:38] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:23:42] [INFO ] A connection received from 127.0.0.1 port 50402
    [20170517-17:23:43] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:2893 - socket: 12
    [20170517-17:23:43] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:29:25] [INFO ] A connection received from 127.0.0.1 port 50404
    [20170517-17:29:25] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:3131 - socket: 12
    [20170517-17:29:25] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:29:29] [INFO ] A connection received from 127.0.0.1 port 50406
    [20170517-17:29:30] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1024, ip 192.168.0.1:3133 - socket: 12
    [20170517-17:29:30] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:35:21] [DEBUG] libscp initialized
    [20170517-17:35:21] [INFO ] starting xrdp-sesman with pid 759
    [20170517-17:35:21] [INFO ] listening to port 3350 on 127.0.0.1
    [20170517-17:37:39] [INFO ] A connection received from 127.0.0.1 port 35254
    [20170517-17:37:40] [INFO ] ++ created session (access granted): username suncatcher, ip 192.168.0.1:3257 - socket: 12
    [20170517-17:37:40] [INFO ] starting Xorg session...
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6010)
    [20170517-17:37:40] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6210)
    [20170517-17:37:40] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-17:37:40] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp
    [20170517-17:37:40] [CORE ] waiting for window manager (pid 1012) to exit
    [20170517-17:38:16] [INFO ] A connection received from 127.0.0.1 port 35376
    [20170517-17:38:16] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:3260 - socket: 12
    [20170517-17:38:16] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:08:58] [INFO ] A connection received from 127.0.0.1 port 35780
    [20170517-18:08:58] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:3719 - socket: 12
    [20170517-18:08:58] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:35:27] [INFO ] A connection received from 127.0.0.1 port 35886
    [20170517-18:35:27] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4154 - socket: 12
    [20170517-18:35:28] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:35:44] [INFO ] A connection received from 127.0.0.1 port 35890
    [20170517-18:35:45] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4158 - socket: 12
    [20170517-18:35:45] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
    [20170517-18:37:21] [INFO ] A connection received from 127.0.0.1 port 35898
    [20170517-18:37:21] [INFO ] ++ reconnected session: username suncatcher, display :10.0, session_pid 1011, ip 192.168.0.1:4190 - socket: 12
    [20170517-18:37:21] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)

**Comment by metalefty** [comment] 2017-05-18 00:27
Duplicate of #737.

**Closed** 2017-05-18 00:28 UTC
Labels: duplicate
