### ISSUE TITLE
Error connecting to sesman: 127.0.0.1 port: 6100

### ISSUE THREAD

**Issue by rahuljain257** [neutrinolabs/xrdp#1342] opened 2019-04-30 15:41 UTC
I'm using SUSE Linux 12 SP4  (GNOME desktop,Version 3.28.2)
xRDP is installed through Zypper (Version 0.9.0).
But I found I can't connect my remote computer.I checked the logs and they says I am failing to connect sesman.

I followed the step from this link --[Click here]( https://answers.sap.com/questions/680097/enabling-xrdp-on-suse-linux-enterprise-server-12-s.html)

**Below is the output of XRDP.LOG**

```
ip-172-31-31-24:/var/log # vim xrdp.log
[20190430-13:24:20] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-13:24:20] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-13:24:20] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-13:24:22] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-13:24:22] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-13:25:58] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-13:31:20] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-13:31:20] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-13:31:20] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-13:31:21] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-13:31:21] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-14:40:11] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-14:40:11] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-14:40:11] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-14:40:12] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-14:40:12] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-14:46:32] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-14:46:32] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-14:55:02] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-14:55:02] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-14:55:02] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-14:55:03] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-14:55:03] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:03:19] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:03:19] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:03:19] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-15:03:19] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:03:19] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:05:22] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-15:05:23] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:05:23] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:05:23] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-15:05:24] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:05:24] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:19:27] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:19:27] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
[20190430-15:19:27] [ERROR] Listening socket is in wrong state we terminate listener
[20190430-15:19:28] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20190430-15:19:28] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
```

**Below is the output of  xrdp-sesman.log:**

```
ip-172-31-31-24:/var/log # vim xrdp-sesman.log
[20190430-14:54:57] [CORE ] starting sesman with pid 10569
[20190430-14:55:08] [ERROR] env_set_user: error creating .vnc dir
[20190430-14:56:57] [ERROR] env_set_user: error creating .vnc dir
[20190430-15:03:24] [ERROR] env_set_user: error creating .vnc dir
[20190430-15:19:37] [ERROR] env_set_user: error creating .vnc dir
[20190430-15:22:38] [CORE ] starting sesman with pid 17492
[20190430-15:22:38] [ERROR] bind error on port '3350': 98 (Address already in use)
[20190430-15:32:40] [CORE ] starting sesman with pid 17933
[20190430-15:32:40] [ERROR] bind error on port '3350': 98 (Address already in use)
[20190430-15:32:45] [CORE ] starting sesman with pid 17955
[20190430-15:32:45] [ERROR] bind error on port '3350': 98 (Address already in use)
[20190430-15:33:03] [CORE ] starting sesman with pid 17998
```

### XRDP.INI

```
ip-172-31-31-24:/etc/xrdp # vim xrdp.ini
bitmap_cache=yes
bitmap_compression=yes
port=3389
allow_channels=true
max_bpp=32
fork=yes
# minimum security level allowed for client
# can be 'none', 'low', 'medium', 'high', 'fips'
crypt_level=high
# security layer can be 'tls', 'rdp' or 'negotiate'
# for client compatible layer
security_layer=rdp
# X.509 certificate and private key
# openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
certificate=
key_file=

# regulate if the listening socket use socket option tcp_nodelay
# no buffering will be performed in the TCP stack
tcp_nodelay=yes

# regulate if the listening socket use socket option keepalive
# if the network connection disappear without close messages the connection will be closed
tcp_keepalive=yes

#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768

#
# colors used by windows in RGB format
#

blue=009cb5
grey=dedede
#black=000000
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72
#autorun=xrdp1
#hidelogwindow=yes

# when true, userid/password *must* be passed on cmd line
# require_credentials=yes

# set a default entry for autorun if the client send login and pass directly
autorun=xrdp1

"xrdp.ini" 179L, 3894C
```    

**SESMAN-XRDP.INI**

```
ip-172-31-31-24:/etc/xrdp # vim sesman.ini
[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=1
UserWindowManager=startwm.sh
DefaultWindowManager=startwm.sh

[Security]
AllowRootLogin=1
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
# When AlwaysGroupCheck = false access will be permitted
# if the group TerminalServerUsers is not defined.
AlwaysGroupCheck = false

[Sessions]
## X11DisplayOffset - x11 display number offset
# Type: integer
# Default: 200
X11DisplayOffset=200

## MaxSessions - maximum number of connections to an xrdp server
# Type: integer
# Default: 0
MaxSessions=50

## KillDisconnected - kill disconnected sessions
# Type: integer
# Default: 0
# if 1, true, or yes, kill session after 60 seconds
KillDisconnected=0

## IdleTimeLimit - when to disconnect idle sessions
# Type: integer
# Default: 0
# if not zero, the seconds without mouse or keyboard input before disconnect
# not complete yet
IdleTimeLimit=0

## DisconnectedTimeLimit - when to kill idle sessions
# Type: integer
# Default: 0
# if not zero, the seconds before a disconnected session is killed
# min 60 seconds
DisconnectedTimeLimit=0

## Policy - session allocation policy
# Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]
# Default: Xrdp:<User,BitPerPixel> and Xvnc:<User,BitPerPixel>
# "UBD" session per <User,BitPerPixel,DisplaySize>
"sesman.ini" 88L, 2059C  
```                                     

**Login Screen of XRDP**

![image](https://user-images.githubusercontent.com/948834/56973397-65daae80-6b8a-11e9-9d34-ab800b7445bf.png)

**After logging I am getting the below error >>**

![image](https://user-images.githubusercontent.com/948834/56973315-37f56a00-6b8a-11e9-9eb3-2fd5e5ddfc59.png)

**Comment by metalefty** [comment] 2019-09-12 02:08
This is not the real issue.

> Error connecting to sesman: 127.0.0.1 port: 6100 

This seems to be a root cause of your issue.

> [20190430-15:19:37] [ERROR] env_set_user: error creating .vnc dir

**Comment by metalefty** [comment] 2019-10-29 02:40
No feedback from the reporter, closing. When you're back leave comment on this. Will reopen.

**Closed by metalefty** 2019-10-29 02:40 UTC
