### ISSUE TITLE
Please help with documentation

### ISSUE THREAD

**Issue by clarsen-007** [neutrinolabs/xrdp#2197] opened 2022-03-28 07:52 UTC
I think I might be reading documentation wrong.
In sesman.ini - If MaxLoginRetry is set to 1 - then another login attempt should not be allowed.

So I only want one login attempt, and then session should disconnect.
Do not want users to be able to have multiple Login attempt.

Is this the correct config?

Currently it shows Login screen - if you enter incorrect details then is shows the "... login failed for display 0", and if you click on "OK" button it goes back to Login screen and prompt.
Should it not disconnect if MaxLoginRetry is set?

Ubuntu 20.04

**Comment by metalefty** [comment] 2022-03-28 08:10
I don't get you.

`MaxLoginRetry` do not control disconnection. Why do you think it SHOULD disconnect?

**Comment by metalefty** [comment] 2022-03-28 08:25
For the record, MaxLoginRetry finally checked here. It is SCPv1 stuff.

https://github.com/neutrinolabs/xrdp/blob/v0.9.19/sesman/scp_v1.c#L59-L94

And this is the documented behaviour. Login attempts more than `MaxLoginRetry` is not allowed. 

```
       MaxLoginRetry=number
              The number of login attempts that are allowed on terminal
              server. If set to 0, unlimited attempts are allowed. If not
              specified, defaults to 3.
```

BTW, we are reworking authentication now. So `MaxLoginRetry` takes no effect with the current HEAD (will be reintroduced in near future).

**Comment by matt335672** [comment] 2022-03-28 17:55
Duplicate of #1739

I'll close this for now - we are aware of it @clarsen-007 but thanks for engaging with us.

**Closed as completed by matt335672** 2022-03-28 17:55 UTC
Labels: docs
