### ISSUE TITLE
Any way to connect over rdp when session started at local pc ?

### ISSUE THREAD

**Issue by rootbdfy** [neutrinolabs/xrdp#980] opened 2017-12-21 15:27 UTC
Situation: I work on pc locally, and not end session when going home. From home I want to connect to pc over rdp, and I can't do it. 
I use xrdp + xorgxrdp.

**Comment by metalefty** [comment] 2017-12-22 00:18
Duplicate of #960.

You should connect to localhost via rdp from the beginning. Local session should be used only to run rdp client.

**Closed** 2017-12-22 08:44 UTC
