### ISSUE TITLE
MacOS : Can't connect to session

### ISSUE THREAD

**Issue by davemagro** [neutrinolabs/xrdp#2246] opened 2022-05-02 08:43 UTC
I used the instructions in this [page](https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX-%28not-official%29) to setup xRDP on my macOS (mojave) and I am able to connect to the xRDP server and see the xRDP login screen just fine. 

But when I try to input my macOS username and password, I get this error (after a few minutes of waiting): 
![image](https://user-images.githubusercontent.com/91385443/166207199-b6fc3a75-05d0-4d53-a134-b8e20872bcb9.png)

This is the only modification I made to `/etc/xrdp/xrdp.ini`
```
[Xorg]
name=Xorg
lib=libxup.dylib            # <== MODIFIED, original: libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20
``` 

This is the only modification I made to `/etc/xrdp/sesman.ini`
```
[Sessions]
;; X11DisplayOffset - x11 display number offset
; Type: integer
; Default: 10
X11DisplayOffset=10

;; MaxSessions - maximum number of connections to an xrdp server
; Type: integer
; Default: 0
MaxSessions=50

;; KillDisconnected - kill disconnected sessions
; Type: boolean
; Default: false
; if 1, true, or yes, every session will be killed within DisconnectedTimeLimit
; seconds after the user disconnects
KillDisconnected=true                                  # <== MODIFIED, original: false

...

[Logging]
; Note: Log levels can be any of: core, error, warning, info, debug, or trace
LogFile=xrdp-sesman.log
LogLevel=debug                                           # <== MODIFIED, original: info
EnableSyslog=true
```

This is the `/var/log/xrdp.log`
```
[20220502-00:25:17] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220502-00:25:17] [INFO ] listening to port 3389 on 0.0.0.0
[20220502-00:25:17] [INFO ] xrdp_listen_pp done
[20220502-00:25:19] [INFO ] starting xrdp with pid 6963
[20220502-00:25:19] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220502-00:25:19] [INFO ] listening to port 3389 on 0.0.0.0
[20220502-00:25:19] [INFO ] xrdp_listen_pp done
[20220502-00:26:53] [INFO ] Socket 11: AF_INET connection received from 103.73.58.180 port 61126
[20220502-00:26:53] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220502-00:26:53] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220502-00:26:53] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220502-00:26:54] [ERROR] SSL_read: I/O error
[20220502-00:26:54] [ERROR] libxrdp_force_read: header read error
[20220502-00:26:54] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20220502-00:26:54] [ERROR] [MCS Connection Sequence] receive connection request failed
[20220502-00:26:54] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20220502-00:26:54] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20220502-00:26:54] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20220502-00:26:54] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20220502-00:26:54] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20220502-00:26:56] [INFO ] Socket 11: AF_INET connection received from 103.73.58.180 port 61034
[20220502-00:26:56] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220502-00:26:56] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220502-00:26:56] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220502-00:26:57] [INFO ] Connected client computer name: DESKTOP-6TF07H0
[20220502-00:26:57] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20220502-00:26:57] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20220502-00:26:58] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000409]
[20220502-00:26:58] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20220502-00:26:58] [INFO ] TLS connection established from 103.73.58.180 port 61034: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20220502-00:27:00] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20220502-00:27:00] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20220502-00:27:00] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20220502-00:27:00] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20220502-00:27:00] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20220502-00:27:00] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20220502-00:27:00] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
[20220502-00:27:10] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:27:25] [ERROR] xrdp_wm_log_msg: Error connecting to sesman on 127.0.0.1:3350
[20220502-00:27:25] [INFO ] Error connecting to sesman on 127.0.0.1:3350
[20220502-00:31:32] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:31:32] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:31:32] [INFO ] sesman connect ok
[20220502-00:31:32] [INFO ] sending login info to session manager. Please wait...
[20220502-00:31:34] [INFO ] xrdp_wm_log_msg: login failed for user signed
[20220502-00:31:34] [INFO ] login failed for user signed
[20220502-00:31:44] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:31:44] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:31:44] [INFO ] sesman connect ok
[20220502-00:31:44] [INFO ] sending login info to session manager. Please wait...
[20220502-00:31:46] [INFO ] xrdp_wm_log_msg: login failed for user signed
[20220502-00:31:46] [INFO ] login failed for user signed
[20220502-00:31:56] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:31:57] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:31:57] [INFO ] sesman connect ok
[20220502-00:31:57] [INFO ] sending login info to session manager. Please wait...
[20220502-00:31:57] [INFO ] xrdp_wm_log_msg: login successful for user signed on display 10
[20220502-00:31:57] [INFO ] login successful for user signed on display 10
[20220502-00:31:57] [ERROR] xrdp_wm_log_msg: error loading libxup.so specified in xrdp.ini, please add a valid entry like lib=libxrdp-vnc.so or similar
[20220502-00:31:57] [INFO ] error loading libxup.so specified in xrdp.ini, please add a 
[20220502-00:31:57] [INFO ] valid entry like lib=libxrdp-vnc.so or similar
[20220502-00:31:57] [ERROR] Failure setting up module
[20220502-00:33:54] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:33:54] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:33:54] [INFO ] sesman connect ok
[20220502-00:33:54] [INFO ] sending login info to session manager. Please wait...
[20220502-00:33:54] [INFO ] xrdp_wm_log_msg: login successful for user signed on display 10
[20220502-00:33:54] [INFO ] login successful for user signed on display 10
[20220502-00:33:54] [ERROR] xrdp_wm_log_msg: error loading libxup.so specified in xrdp.ini, please add a valid entry like lib=libxrdp-vnc.so or similar
[20220502-00:33:54] [INFO ] error loading libxup.so specified in xrdp.ini, please add a 
[20220502-00:33:54] [INFO ] valid entry like lib=libxrdp-vnc.so or similar
[20220502-00:33:54] [ERROR] Failure setting up module
[20220502-00:34:18] [INFO ] Received termination signal, stopping the server accept new connections thread
[20220502-00:34:44] [ERROR] xrdp_sec_recv: xrdp_mcs_recv failed
[20220502-00:34:44] [ERROR] xrdp_rdp_recv: xrdp_sec_recv failed
[20220502-00:34:44] [ERROR] libxrdp_process_data: xrdp_rdp_recv failed
[20220502-00:34:44] [ERROR] xrdp_process_data_in: xrdp_process_loop failed
[20220502-00:34:44] [ERROR] SSL_write: I/O error
[20220502-00:34:44] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20220502-00:34:44] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20220502-00:35:27] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220502-00:35:27] [INFO ] listening to port 3389 on 0.0.0.0
[20220502-00:35:27] [INFO ] xrdp_listen_pp done
[20220502-00:35:29] [INFO ] starting xrdp with pid 7030
[20220502-00:35:29] [INFO ] address [0.0.0.0] port [3389] mode 1
[20220502-00:35:29] [INFO ] listening to port 3389 on 0.0.0.0
[20220502-00:35:29] [INFO ] xrdp_listen_pp done
[20220502-00:35:41] [INFO ] Socket 11: AF_INET connection received from 103.73.58.188 port 61225
[20220502-00:35:41] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220502-00:35:41] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220502-00:35:41] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220502-00:35:42] [ERROR] SSL_read: I/O error
[20220502-00:35:42] [ERROR] libxrdp_force_read: header read error
[20220502-00:35:42] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20220502-00:35:42] [ERROR] [MCS Connection Sequence] receive connection request failed
[20220502-00:35:42] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20220502-00:35:42] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20220502-00:35:42] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20220502-00:35:42] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20220502-00:35:42] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20220502-00:35:44] [INFO ] Socket 11: AF_INET connection received from 103.73.58.191 port 61166
[20220502-00:35:44] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20220502-00:35:44] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20220502-00:35:44] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20220502-00:35:45] [INFO ] Connected client computer name: DESKTOP-6TF07H0
[20220502-00:35:45] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20220502-00:35:45] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20220502-00:35:48] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000409]
[20220502-00:35:48] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20220502-00:35:48] [INFO ] TLS connection established from 103.73.58.191 port 61166: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20220502-00:35:49] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20220502-00:35:49] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20220502-00:35:49] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20220502-00:35:49] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20220502-00:35:49] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20220502-00:35:49] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20220502-00:35:49] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
[20220502-00:35:59] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:35:59] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:35:59] [INFO ] sesman connect ok
[20220502-00:35:59] [INFO ] sending login info to session manager. Please wait...
[20220502-00:36:01] [INFO ] xrdp_wm_log_msg: login failed for user signed
[20220502-00:36:01] [INFO ] login failed for user signed
[20220502-00:36:13] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:36:13] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:36:13] [INFO ] sesman connect ok
[20220502-00:36:13] [INFO ] sending login info to session manager. Please wait...
[20220502-00:36:13] [INFO ] xrdp_wm_log_msg: login successful for user signed on display 10
[20220502-00:36:13] [INFO ] login successful for user signed on display 10
[20220502-00:36:13] [INFO ] loaded module 'libxup.dylib' ok, interface size 10296, version 4
[20220502-00:36:13] [INFO ] started connecting
[20220502-00:36:13] [INFO ] lib_mod_connect: connecting via UNIX socket
[20220502-00:39:44] [INFO ] connection problem, giving up
[20220502-00:39:44] [INFO ] some problem
[20220502-00:39:44] [ERROR] xrdp_wm_log_msg: Error connecting to user session
[20220502-00:39:44] [INFO ] Error connecting to user session
[20220502-00:55:13] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:55:28] [ERROR] xrdp_wm_log_msg: Error connecting to sesman on 127.0.0.1:3350
[20220502-00:55:28] [INFO ] Error connecting to sesman on 127.0.0.1:3350
[20220502-00:58:29] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:58:44] [ERROR] xrdp_wm_log_msg: Error connecting to sesman on 127.0.0.1:3350
[20220502-00:58:44] [INFO ] Error connecting to sesman on 127.0.0.1:3350
[20220502-00:59:02] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-00:59:02] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-00:59:02] [INFO ] sesman connect ok
[20220502-00:59:02] [INFO ] sending login info to session manager. Please wait...
[20220502-00:59:02] [INFO ] xrdp_wm_log_msg: login successful for user signed on display 10
[20220502-00:59:02] [INFO ] login successful for user signed on display 10
[20220502-00:59:02] [INFO ] loaded module 'libxup.dylib' ok, interface size 10296, version 4
[20220502-00:59:02] [INFO ] started connecting
[20220502-00:59:02] [INFO ] lib_mod_connect: connecting via UNIX socket
[20220502-01:02:34] [INFO ] connection problem, giving up
[20220502-01:02:34] [INFO ] some problem
[20220502-01:02:34] [ERROR] xrdp_wm_log_msg: Error connecting to user session
[20220502-01:02:34] [INFO ] Error connecting to user session
[20220502-01:28:44] [INFO ] connecting to sesman on 127.0.0.1:3350
[20220502-01:28:44] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20220502-01:28:44] [INFO ] sesman connect ok
[20220502-01:28:44] [INFO ] sending login info to session manager. Please wait...
[20220502-01:28:44] [INFO ] xrdp_wm_log_msg: login successful for user signed on display 10
[20220502-01:28:44] [INFO ] login successful for user signed on display 10
[20220502-01:28:44] [INFO ] loaded module 'libxup.dylib' ok, interface size 10296, version 4
[20220502-01:28:44] [INFO ] started connecting
[20220502-01:28:44] [INFO ] lib_mod_connect: connecting via UNIX socket
[20220502-01:32:16] [INFO ] connection problem, giving up
[20220502-01:32:16] [INFO ] some problem
[20220502-01:32:16] [ERROR] xrdp_wm_log_msg: Error connecting to user session
[20220502-01:32:16] [INFO ] Error connecting to user session
```

This the `/var/log/xrdp-sesman.log`
```
[20220502-00:31:27] [INFO ] starting xrdp-sesman with pid 7014
[20220502-00:31:32] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51360
[20220502-00:31:34] [ERROR] pam_authenticate failed: authentication error
[20220502-00:31:34] [INFO ] AUTHFAIL: user=signed ip=103.73.58.180 time=1651476694
[20220502-00:31:34] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:31:34] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:31:44] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51361
[20220502-00:31:46] [ERROR] pam_authenticate failed: authentication error
[20220502-00:31:46] [INFO ] AUTHFAIL: user=signed ip=103.73.58.180 time=1651476706
[20220502-00:31:46] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:31:46] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:31:56] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51362
[20220502-00:31:57] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20220502-00:31:57] [INFO ] ++ created session (access granted): username signed, ip 103.73.58.180:61034 - socket: 11
[20220502-00:31:57] [INFO ] starting Xorg session...
[20220502-00:31:57] [INFO ] Starting session: session_pid 7015, display :10.0, width 1364, height 768, bpp 24, client ip 103.73.58.180:61034 - socket: 11, user name signed
[20220502-00:31:57] [INFO ] [session start] (display 10): calling auth_start_session from pid 7015
[20220502-00:31:57] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:31:57] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:33:54] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51365
[20220502-00:33:54] [INFO ] ++ reconnected session: username signed, display :10.0, session_pid 7015, ip 103.73.58.180:61034 - socket: 11
[20220502-00:33:54] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:33:54] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:33:54] [INFO ] Starting session reconnection script on display 10: /etc/xrdp/reconnectwm.sh
[20220502-00:33:54] [INFO ] Process 7022 has exited
[20220502-00:35:59] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51366
[20220502-00:36:01] [ERROR] pam_authenticate failed: authentication error
[20220502-00:36:01] [INFO ] AUTHFAIL: user=signed ip=103.73.58.191 time=1651476961
[20220502-00:36:01] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:36:01] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:36:13] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51367
[20220502-00:36:13] [INFO ] ++ reconnected session: username signed, display :10.0, session_pid 7015, ip 103.73.58.191:61166 - socket: 11
[20220502-00:36:13] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:36:13] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:36:13] [INFO ] Starting session reconnection script on display 10: /etc/xrdp/reconnectwm.sh
[20220502-00:36:13] [INFO ] Process 7033 has exited
[20220502-00:44:36] [INFO ] sesman_main_loop: sesman asked to terminate
[20220502-00:58:51] [DEBUG] libscp initialized
[20220502-00:58:51] [DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
[20220502-00:58:51] [DEBUG] Closed socket 4 (AF_INET 127.0.0.1:3350)
[20220502-00:58:51] [INFO ] starting xrdp-sesman with pid 7062
[20220502-00:58:51] [DEBUG] sesman_create_listening_transport: address 127.0.0.1 port 3350
[20220502-00:59:02] [INFO ] Socket 11: AF_INET connection received from 127.0.0.1 port 51382
[20220502-00:59:02] [DEBUG] session_get_bydata: search policy 0 U signed W 1364 H 768 bpp 24 T 3 IP 103.73.58.191:61166 - socket: 11
[20220502-00:59:02] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20220502-00:59:02] [INFO ] ++ created session (access granted): username signed, ip 103.73.58.191:61166 - socket: 11
[20220502-00:59:02] [INFO ] starting Xorg session...
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.X11-unix/X10
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.X10-lock
[20220502-00:59:02] [DEBUG] Closed socket 12 (AF_INET 0.0.0.0:5910)
[20220502-00:59:02] [DEBUG] Did not find a running X server at 5910
[20220502-00:59:02] [DEBUG] Closed socket 12 (AF_INET 0.0.0.0:6010)
[20220502-00:59:02] [DEBUG] Did not find a running X server at 6010
[20220502-00:59:02] [DEBUG] Closed socket 12 (AF_INET 0.0.0.0:6210)
[20220502-00:59:02] [DEBUG] Did not find a running X server at 6210
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.xrdp/xrdp_chansrv_socket_10
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.xrdp/xrdp_chansrv_audio_out_socket_10
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.xrdp/xrdp_chansrv_audio_in_socket_10
[20220502-00:59:02] [DEBUG] Did not find a running X server at /tmp/.xrdp/xrdpapi_10
[20220502-00:59:02] [INFO ] Starting session: session_pid 7063, display :10.0, width 1364, height 768, bpp 24, client ip 103.73.58.191:61166 - socket: 11, user name signed
[20220502-00:59:02] [INFO ] [session start] (display 10): calling auth_start_session from pid 7063
[20220502-00:59:02] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:59:02] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20220502-00:59:02] [DEBUG] Closed socket 11 (AF_INET 127.0.0.1:3350)
```

I have been trying to search for any resource regarding: (in the sesman log)
```
[20220502-00:59:02] [ERROR] sesman_data_in: scp_process_msg failed
[20220502-00:59:02] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
```
but I haven't been able to found anything useful. 

I also noticed the error regarding SSL in xrdp.log, could it be related to that? Thanks.

**Comment by matt335672** [comment] 2022-05-02 10:36
Duplicate of #2184.

The wiki page you link to above contains this line:-

> The remaining work is to be able to start X with the xrdpxorg module. This is the actual stopper.

You are trying to run with this module.

See also #2194 which contains important information relating to MacOS. In particular, the link to the [platform support tier page](/neutrinolabs/xrdp/wiki/Platform-Support-Tier)

You should be able to get something working with the Xvnc backend. I'm sure someone has managed this, but I can't find a reference I'm afraid.

I'm closing this now - I can't think of anything else to add.

**Closed as completed by matt335672** 2022-05-02 10:36 UTC
