### ISSUE TITLE
Web Browser corrupt on Raspberry Pi

### ISSUE THREAD

**Issue by jridder** [neutrinolabs/xrdp#2869] opened 2023-12-08 21:21 UTC
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=aarch64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/aarch64-linux-gnu
      --libexecdir=${prefix}/lib/aarch64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=aarch64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-xCPoG3/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security 
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 
      PKG_CONFIG_PATH=/build/xrdp-xCPoG3/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.11 19 Sep 2023
~~~

### Operating system & version

Debian GNU/Linux 12 (bookworm)

### Installation method

dnf / apt / zypper / pkg / etc

### What desktop environment do you use?

LXDE

### Environment xrdp running on

Raspberry Pi 5

### What's your client?

Microsoft Mac Client, latest release

### Area(s) with issue?

Graphic glitches

### Steps to reproduce

Logged in and open Chromium or Firefox. They both do the same thing. 
![Screenshot 2023-12-08 at 2 11 41 PM](https://github.com/neutrinolabs/xrdp/assets/11082465/6ce282ea-89e8-4c1b-95fd-d1cab9eaf648)

### ✔️ Expected Behavior

To see the web browser as it normally does

### ❌ Actual Behavior

Corrupt display within web browser window

**Comment by jridder** [comment] 2023-12-08 21:24
Just FYI, I added --disable-gpu to the command line when launching Chromium and Chromium displays correctly.

**Comment by matt335672** [comment] 2023-12-11 09:37
Duplicate of #2851

**Closed as completed by matt335672** 2023-12-11 09:37 UTC
Labels: bug

**Comment by timgrahame** [comment] 2024-03-10 07:47
> Just FYI, I added --disable-gpu to the command line when launching Chromium and Chromium displays correctly.

This fixed it for me.  Thank you!
