### ISSUE TITLE
XRDP does not handle PAM_PROMPT_ECHO_ON PAM message

### ISSUE THREAD

**Issue by ed-boykin** [neutrinolabs/xrdp#3303] opened 2024-11-08 14:30 UTC
### xrdp version

0.9.24-4

### Detailed xrdp version, build options

~~~
xrdp 0.9.24
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/xrdp-Fn5kxo/xrdp-0.9.24=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/xrdp-Fn5kxo/xrdp-0.9.24=/usr/src/xrdp-0.9.24-4 
      LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=3 
      PKG_CONFIG_PATH=/build/xrdp-Fn5kxo/xrdp-0.9.24/pkgconfig

  Compiled with OpenSSL 3.0.13 30 Jan 2024
~~~

### Operating system & version

Ubuntu 22.04

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp  1:0.9.19-1

### What desktop environment do you use?

GNOME

### Environment xrdp running on

Azure VM

### What's your client?

Windows RDP client and Azure Bastion 

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

The issue is specifically occurring while using Ubuntu with Authd and the EntraID broker.
When logging into the VM via Azure Bastion the login fails. The issue occurs because sessman does not handle the PAM_PROMPT_ECHO_ON message.

Relevant logs:
```
Nov 07 18:38:53 authd xrdp[5067]: [ERROR] xrdp_rdp_recv: xrdp_channel_process failed
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] connecting to sesman on 127.0.0.1:3350
Nov 07 18:38:57 authd xrdp-sesman[1194]: [INFO ] Socket 13: AF_INET6 connection received from ::1 port 34608
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] xrdp_wm_log_msg: sesman connect ok
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] sesman connect ok
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] sending login info to session manager. Please wait...
Nov 07 18:38:57 authd authd-pam[5165]: adapter.userSelected{username:"###REDACTED###"}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.userSelected{username:"###REDACTED###"}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.supportedUILayoutsReceived{layouts:[]*authd.UILayout{(*authd.UILayout)(0xc0001a79d0), (*authd.UILayout)(0xc0001a7a40), (*a>
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.supportedUILayoutsReceived{layouts:[]*authd.UILayout{(*authd.UILayout)(0xc0001a79d0), (*authd.UILayou>
Nov 07 18:38:57 authd authd-pam[5165]: adapter.UsernameOrBrokerListReceived{}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.GetAuthenticationModesRequested{}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.brokersListReceived{brokers:[]*authd.ABResponse_BrokerInfo{(*authd.ABResponse_BrokerInfo)(0xc0000c0140), (*authd.ABRespons>
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.brokersListReceived{brokers:[]*authd.ABResponse_BrokerInfo{(*authd.ABResponse_BrokerInfo)(0xc0000c014>
Nov 07 18:38:57 authd authd-pam[5165]: adapter.UsernameOrBrokerListReceived{}
Nov 07 18:38:57 authd authd[1146]: 2024/11/07 18:38:57 WARN rpc error: code = NotFound desc =
Nov 07 18:38:57 authd authd[1146]: DEBUG User "###REDACTED###" is unknown
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.brokerSelectionRequired{}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: tea.sequenceMsg{(tea.Cmd)(0x56fd77ae2d80), (tea.Cmd)(0x56fd77aef160)}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.ChangeStage{Stage:1}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.nativeAsyncOperationCompleted{}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: tea.sequenceMsg{(tea.Cmd)(0x56fd77aec7a0), (tea.Cmd)(nil), (tea.Cmd)(nil)}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.nativeStageChangeRequest{Stage:1}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.nativeChangeStage{Stage:1}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: tea.sequenceMsg{(tea.Cmd)(0x56fd77aef3e0), (tea.Cmd)(0x56fd77aef360)}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.ChangeStage{Stage:1}
Nov 07 18:38:57 authd xrdp-sesman[1194]: [ERROR] Unhandled message in verify_pam_conv { style = PAM_PROMPT_ECHO_ON, msg = "== Broker selection ==
                                         1 - local
                                         2 - Microsoft Entra ID
                                         Select broker: " }
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.nativeBrokerSelection{}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: tea.sequenceMsg{(tea.Cmd)(nil), (tea.Cmd)(nil)}
Nov 07 18:38:57 authd xrdp-sesman[1194]: pam_authd_exec(xrdp-sesman:auth): conversation failed
Nov 07 18:38:57 authd authd-pam[5165]: failed to call com.ubuntu.authd.pam.Prompt: Conversation error
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: tea.sequenceMsg{(tea.Cmd)(0x56fd77ae2d80), (tea.Cmd)(0x56fd77af07c0)}
Nov 07 18:38:57 authd authd-pam[5165]: Native model update: adapter.nativeAsyncOperationCompleted{}
Nov 07 18:38:57 authd authd-pam[5165]: adapter.pamError{status:4, msg:"broker selection error: <nil>: Conversation error"}
Nov 07 18:38:57 authd xrdp-sesman[1194]: [ERROR] PAM: broker selection error: <nil>: Conversation error
Nov 07 18:38:57 authd authd-pam[5165]: AUTH: exiting with error System error: broker selection error: <nil>: Conversation error
Nov 07 18:38:57 authd xrdp-sesman[1194]: [ERROR] pam_authenticate failed: System error
Nov 07 18:38:57 authd xrdp-sesman[1194]: [INFO ] AUTHFAIL: user=###REDACTED### ip=::ffff:10.47.1.132 time=1731004737
Nov 07 18:38:57 authd xrdp-sesman[1194]: [ERROR] sesman_data_in: scp_process_msg failed
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] xrdp_wm_log_msg: login failed for user ###REDACTED###
Nov 07 18:38:57 authd xrdp-sesman[1194]: [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
Nov 07 18:38:57 authd xrdp[5067]: [INFO ] login failed for user ###REDACTED###
Nov 07 18:39:02 authd sudo[5176]: edboykin : TTY=pts/2 ; PWD=/home/######; USER=root ; 
```

### ✔️ Expected Behavior

Broker selection per the PAM_PROMPT_ECHO_ON  message, followed by a successful login.

### ❌ Actual Behavior

PAM_PROMPT_ECHO_ON  not handled, login fails

### Anything else?

Link to the original Authd bug report:  https://github.com/ubuntu/authd/issues/592

**Comment by matt335672** [comment] 2024-11-08 14:47
@ed-boykin - thanks for raising this.

Duplicate of #736 - at the moment xrdp does not handle interactive PAM sessions.

We've changed the architecture to allow this, but that work isn't planned in at present.

**Closed as completed by matt335672** 2024-11-08 14:47 UTC
Labels: bug

**Comment by ed-boykin** [comment] 2024-11-08 15:03
Gotcha, thanks.
