### ISSUE TITLE
gnome-shell[1717]: segfault at 28

### ISSUE THREAD

**Issue by Herbert-Hotz** [neutrinolabs/xrdp#949] opened 2017-11-14 17:58 UTC
Hi all,
i'm not sure if this is the right place to post. if not, plz forgive and give me a pointer. Thanks!

To make it short, here is what I got from
# dmesg
[   28.252916] gnome-shell[1717]: segfault at 28 ip 00007fa08013bb74 sp 00007ffe5f11c4e0 error 4 in libmutter-0.so.0.0.0[7fa0800ec000+13a000]
[   31.512996] gnome-shell[1895]: segfault at 28 ip 00007fac6b384b74 sp 00007ffd8d62c7a0 error 4 in libmutter-0.so.0.0.0[7fac6b335000+13a000]
[   34.227978] gnome-shell[2010]: segfault at 28 ip 00007f4963e2eb74 sp 00007ffe54f97c00 error 4 in libmutter-0.so.0.0.0[7f4963ddf000+13a000]
[   36.959938] gnome-shell[2123]: segfault at 28 ip 00007fbce54afb74 sp 00007ffc691b46f0 error 4 in libmutter-0.so.0.0.0[7fbce5460000+13a000]
[   41.497656] gnome-shell[2367]: segfault at 28 ip 00007f7db8b53b74 sp 00007fff2deb7780 error 4 in libmutter-0.so.0.0.0[7f7db8b04000+13a000]
[   42.454135] gnome-shell[2381]: segfault at 28 ip 00007fc647d86b74 sp 00007fffac3c6050 error 4 in libmutter-0.so.0.0.0[7fc647d37000+13a000]

and

# coredumpctl info 1348
           PID: 1348 (gnome-shell)
           UID: 42 (gdm)
           GID: 42 (gdm)
        Signal: 11 (SEGV)
     Timestamp: Tue 2017-11-14 14:08:04 CET (4h 49min ago)
  Command Line: /usr/bin/gnome-shell
    Executable: /usr/bin/gnome-shell
 Control Group: /user.slice/user-42.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-42.slice
       Session: c1
     Owner UID: 42 (gdm)
       Boot ID: 5d41fa6eefd94ff284075a55dc1f3b99
    Machine ID: e7b78b4b388a4e4aa3cb458ec919077a
      Hostname: udoo.symmetrix.ch
       Storage: /var/lib/systemd/coredump/core.gnome-shell.42.5d41fa6eefd94ff284075a55dc1f3b99.1348.1510664884000000.lz4
       Message: Process 1348 (gnome-shell) of user 42 dumped core.

                Stack trace of thread 1348:
                #0  0x00007fe0ec560b74 center_pointer (libmutter-0.so.0)
                #1  0x00007fe0ec5eab8f meta_backend_native_post_init (libmutter-0.so.0)
                #2  0x00007fe0ec59fcc6 meta_init (libmutter-0.so.0)
                #3  0x00005647a5b111aa main (gnome-shell)
                #4  0x00007fe0e5f9c88a __libc_start_main (libc.so.6)
                #5  0x00005647a5b115ba _start (gnome-shell)

                Stack trace of thread 1414:
                #0  0x00007fe0e6080d2d poll (libc.so.6)
                #1  0x00007fe0e7b66569 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                #2  0x00007fe0e7b6667c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe0e7b666c1 glib_worker_main (libglib-2.0.so.0)
                #4  0x00007fe0e7b8d536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe0e635836d start_thread (libpthread.so.0)
                #6  0x00007fe0e608ce1f __clone (libc.so.6)

                Stack trace of thread 1424:
                #0  0x00007fe0e6080d2d poll (libc.so.6)
                #1  0x00007fe0e7b66569 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                #2  0x00007fe0e7b66902 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fe0e968ccb6 gdbus_shared_thread_func (libgio-2.0.so.0)
                #4  0x00007fe0e7b8d536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe0e635836d start_thread (libpthread.so.0)
                #6  0x00007fe0e608ce1f __clone (libc.so.6)

                Stack trace of thread 1488:
                #0  0x00007fe0e60877b9 syscall (libc.so.6)
                #1  0x00007fe0e7bab6fa g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007fe0e7b3ab31 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                #3  0x00007fe0e7b8ded4 g_thread_pool_thread_proxy (libglib-2.0.so.0)
                #4  0x00007fe0e7b8d536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe0e635836d start_thread (libpthread.so.0)
                #6  0x00007fe0e608ce1f __clone (libc.so.6)

                Stack trace of thread 1518:
                #0  0x00007fe0e6080d2d poll (libc.so.6)
                #1  0x00007fe0e7b66569 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                #2  0x00007fe0e7b6667c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe0c8e3ef3d dconf_gdbus_worker_thread (libdconfsettings.so)
                #4  0x00007fe0e7b8d536 g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe0e635836d start_thread (libpthread.so.0)
                #6  0x00007fe0e608ce1f __clone (libc.so.6)

**Comment by metalefty** [comment] 2017-11-22 01:23
I believe xrdp doesn't affect other application's segfault.

**Comment by moobyfr** [comment] 2017-11-22 06:57
can you add your .xorgxrdp.XX.log ? there can be X11 erors too, I encoureded such an issue within one of my VM.

**Comment by Herbert-Hotz** [comment] 2017-11-27 02:32
I think it's important to note that this error happens when I invoke a reboot from remote SSH, like:
`sync; reboot`

As there is no display nor a keyboard connected to the physical computer, it could be that gnome-shell crashes because of this fact.

IMHO gnome should eventually come into play only when connecting from remote using the xrdp service.

**Comment by metalefty** [comment] 2018-01-15 07:39
Fixed by neutrinolabs/xorgxrdp#111. 
@Herbert-Hotz @moobyfr Can you test?

**Comment by Herbert-Hotz** [comment] 2018-01-15 15:40
Have to wait until this fix appears in the official F26 repository. I frequently perform 'dnf update'.
As soon as this is the case, I'll inform you again.

**Comment by metalefty** [comment] 2018-01-15 23:55
Okay, I've requested the package maintainer to apply the patch. I hope you'll get the update soon.

**Comment by moobyfr** [comment] 2018-01-18 05:00
I confirm that the issue is fixed on my side, in centos 7.4. no more crash from gnome-settings after querying xrandr, and no more X11 errors in xorg log file.

**Comment by metalefty** [comment] 2018-01-18 08:24
Closing since @moobyfr has confirmed but please inform me when you also confirm.

**Comment by Herbert-Hotz** [comment] 2018-01-24 13:00
Hi metalefty,
Today I've updated the system having this problem with `dnf update` and installed/updated (beside others) the following:
`xorgxrdp 0.2.5-3.fc26`
`kernel 4.14.8-200.fc26`

After reboot the error is still there:
`Jan 24 09:30:37.453976 udoo.symmetrix.ch abrt-notification[2438]: Process 1369 (gnome-shell) crashed in center_pointer()
...
Jan 24 09:30:38.766474 udoo.symmetrix.ch kernel: gnome-shell[2495]: segfault at 28 ip 00007faa0d547b74 sp 00007ffe5a46e570 error 4 in libmutter-0.so.0.0.0[7faa0d4f8000+13a000]
...
Jan 24 09:30:39.304155 udoo.symmetrix.ch systemd-coredump[2523]: Process 2495 (gnome-shell) of user 42 dumped core.

                                                                 Stack trace of thread 2495:
                                                                 #0  0x00007faa0d547b74 center_pointer (libmutter-0.so.0)
                                                                 #1  0x00007faa0d55c129 meta_backend_x11_post_init (libmutter-0.so.0)
                                                                 #2  0x00007faa0d55d169 meta_backend_x11_cm_post_init (libmutter-0.so.0)
                                                                 #3  0x00007faa0d586cc6 meta_init (libmutter-0.so.0)
                                                                 #4  0x000055e8887031aa main (gnome-shell)
                                                                 #5  0x00007faa06f8188a __libc_start_main (libc.so.6)
                                                                 #6  0x000055e8887035ba _start (gnome-shell)

                                                                 Stack trace of thread 2518:
                                                                 #0  0x00007faa07065a5d poll (libc.so.6)
                                                                 #1  0x00007faa08b4d579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007faa08b4d912 g_main_loop_run (libglib-2.0.so.0)
                                                                 #3  0x00007faa0a673db6 gdbus_shared_thread_func (libgio-2.0.so.0)
                                                                 #4  0x00007faa08b74516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007faa0733d36d start_thread (libpthread.so.0)
                                                                 #6  0x00007faa07071b4f __clone (libc.so.6)

                                                                 Stack trace of thread 2520:
                                                                 #0  0x00007faa0706c4e9 syscall (libc.so.6)
                                                                 #1  0x00007faa08b926da g_cond_wait_until (libglib-2.0.so.0)
                                                                 #2  0x00007faa08b21b31 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                                                                 #3  0x00007faa08b74eb4 g_thread_pool_thread_proxy (libglib-2.0.so.0)
                                                                 #4  0x00007faa08b74516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007faa0733d36d start_thread (libpthread.so.0)
                                                                 #6  0x00007faa07071b4f __clone (libc.so.6)

                                                                 Stack trace of thread 2521:
                                                                 #0  0x00007faa07065a5d poll (libc.so.6)
                                                                 #1  0x00007faa08b4d579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007faa08b4d68c g_main_context_iteration (libglib-2.0.so.0)
                                                                 #3  0x00007fa9e920bf3d dconf_gdbus_worker_thread (libdconfsettings.so)
                                                                 #4  0x00007faa08b74516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007faa0733d36d start_thread (libpthread.so.0)
                                                                 #6  0x00007faa07071b4f __clone (libc.so.6)

                                                                 Stack trace of thread 2502:
                                                                 #0  0x00007faa07065a5d poll (libc.so.6)
                                                                 #1  0x00007faa08b4d579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007faa08b4d68c g_main_context_iteration (libglib-2.0.so.0)
                                                                 #3  0x00007faa08b4d6d1 glib_worker_main (libglib-2.0.so.0)
                                                                 #4  0x00007faa08b74516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007faa0733d36d start_thread (libpthread.so.0)
                                                                 #6  0x00007faa07071b4f __clone (libc.so.6)
...
Jan 24 09:30:39.913942 udoo.symmetrix.ch kernel: gnome-shell[2524]: segfault at 28 ip 00007fdefd604b74 sp 00007ffd191907a0 error 4 in libmutter-0.so.0.0.0[7fdefd5b5000+13a000]
...
Jan 24 09:30:39.920223 udoo.symmetrix.ch abrt-server[2228]: Deleting problem directory ccpp-2018-01-24-09:30:31.982837-2121 (dup of ccpp-2017-07-24-21:28:38.502733-906)
Jan 24 09:30:39.925839 udoo.symmetrix.ch systemd[1]: Started Process Core Dump (PID 2543/UID 0).
Jan 24 09:30:39.925000 udoo.symmetrix.ch audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@6-2543-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 24 09:30:40.214408 udoo.symmetrix.ch gnome-session[2434]: gnome-session-binary[2434]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Jan 24 09:30:40.214408 udoo.symmetrix.ch gnome-session[2434]: gnome-session-binary[2434]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly
Jan 24 09:30:40.212529 udoo.symmetrix.ch gnome-session-binary[2434]: Unrecoverable failure in required component org.gnome.Shell.desktop
Jan 24 09:30:40.212132 udoo.symmetrix.ch gnome-session-binary[2434]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Jan 24 09:30:40.212176 udoo.symmetrix.ch gnome-session-binary[2434]: WARNING: App 'org.gnome.Shell.desktop' respawning too quickly
Jan 24 09:30:40.324828 udoo.symmetrix.ch gnome-session[2434]: Unable to init server: Could not connect: Connection refused
Jan 24 09:30:40.326037 udoo.symmetrix.ch gnome-session-f[2549]: Cannot open display:
Jan 24 09:30:40.405814 udoo.symmetrix.ch spice-vdagent[2554]: Cannot access vdagent virtio channel /dev/virtio-ports/com.redhat.spice.0
Jan 24 09:30:40.417582 udoo.symmetrix.ch systemd-coredump[2544]: Process 2524 (gnome-shell) of user 42 dumped core.

                                                                 Stack trace of thread 2524:
                                                                 #0  0x00007fdefd604b74 center_pointer (libmutter-0.so.0)
                                                                 #1  0x00007fdefd619129 meta_backend_x11_post_init (libmutter-0.so.0)
                                                                 #2  0x00007fdefd61a169 meta_backend_x11_cm_post_init (libmutter-0.so.0)
                                                                 #3  0x00007fdefd643cc6 meta_init (libmutter-0.so.0)
                                                                 #4  0x000055dcd454c1aa main (gnome-shell)
                                                                 #5  0x00007fdef703e88a __libc_start_main (libc.so.6)
                                                                 #6  0x000055dcd454c5ba _start (gnome-shell)

                                                                 Stack trace of thread 2533:
                                                                 #0  0x00007fdef7122a5d poll (libc.so.6)
                                                                 #1  0x00007fdef8c0a579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007fdef8c0a912 g_main_loop_run (libglib-2.0.so.0)
                                                                 #3  0x00007fdefa730db6 gdbus_shared_thread_func (libgio-2.0.so.0)
                                                                 #4  0x00007fdef8c31516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007fdef73fa36d start_thread (libpthread.so.0)
                                                                 #6  0x00007fdef712eb4f __clone (libc.so.6)

                                                                 Stack trace of thread 2534:
                                                                 #0  0x00007fdef71294e9 syscall (libc.so.6)
                                                                 #1  0x00007fdef8c4f6da g_cond_wait_until (libglib-2.0.so.0)
                                                                 #2  0x00007fdef8bdeb31 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0)
                                                                 #3  0x00007fdef8c31eb4 g_thread_pool_thread_proxy (libglib-2.0.so.0)
                                                                 #4  0x00007fdef8c31516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007fdef73fa36d start_thread (libpthread.so.0)
                                                                 #6  0x00007fdef712eb4f __clone (libc.so.6)

                                                                 Stack trace of thread 2535:
                                                                 #0  0x00007fdef7122a5d poll (libc.so.6)
                                                                 #1  0x00007fdef8c0a579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007fdef8c0a68c g_main_context_iteration (libglib-2.0.so.0)
                                                                 #3  0x00007fded920bf3d dconf_gdbus_worker_thread (libdconfsettings.so)
                                                                 #4  0x00007fdef8c31516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007fdef73fa36d start_thread (libpthread.so.0)
                                                                 #6  0x00007fdef712eb4f __clone (libc.so.6)

                                                                 Stack trace of thread 2530:
                                                                 #0  0x00007fdef7122a5d poll (libc.so.6)
                                                                 #1  0x00007fdef8c0a579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
                                                                 #2  0x00007fdef8c0a68c g_main_context_iteration (libglib-2.0.so.0)
                                                                 #3  0x00007fdef8c0a6d1 glib_worker_main (libglib-2.0.so.0)
                                                                 #4  0x00007fdef8c31516 g_thread_proxy (libglib-2.0.so.0)
                                                                 #5  0x00007fdef73fa36d start_thread (libpthread.so.0)
                                                                 #6  0x00007fdef712eb4f __clone (libc.so.6)
Jan 24 09:30:40.461000 udoo.symmetrix.ch audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@6-2543-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 24 09:30:40.537112 udoo.symmetrix.ch abrt-notification[2561]: Process 1369 (gnome-shell) crashed in center_pointer()
Jan 24 09:30:41.265081 udoo.symmetrix.ch gnome-session[2434]: gnome-session-binary[2434]: WARNING: App 'spice-vdagent.desktop' exited with code 1
Jan 24 09:30:41.267660 udoo.symmetrix.ch gnome-session-binary[2434]: WARNING: App 'spice-vdagent.desktop' exited with code 1
`

However, I'm not sure if the fix you mentioned is already included in the official F26 repository.

Sorry, that I cannot confirm that 'my' issue is fixed.

**Comment by metalefty** [comment] 2018-01-25 01:15
I think 0.2.5-3 should include that fix.
https://src.fedoraproject.org/rpms/xorgxrdp/c/2e19a707a4aeb72583b34aefff78a3411a7ae095?branch=master

Possibly your issue is different from the issue fixed by the patch.  I'm not familiar with GNOME.
@moobyfr Any ideas?

**Comment by Herbert-Hotz** [comment] 2018-01-25 08:57
Thanks!
How can I assist you more? It's `gnome-shell` which is causing the error(s), is this the right place to ask for a fix?

I want to remark again, that this error happens eventually because **no display nor a keyboard is connected at re-boot**. Perhaps this has some impact.

**Comment by Herbert-Hotz** [comment] 2018-02-13 02:46
Hi everybody,

After upgrading kernel the issue disappeared. I herewith confirm the issue as fixed. 

`# uname -a`
`Linux 4.14.18-200.fc26.x86_64 #1 SMP Thu Feb 8 01:35:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Thanks & congrats!

**Closed** 2018-02-13 04:17 UTC
Labels: waiting-feedback
