### ISSUE TITLE
xrdp-sesman and no image when using 24bit ot 32bit color depth

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [neutrinolabs/xrdp#430] opened 2016-10-04 09:35 UTC
Using latest xrdp with the xorg driver and remotefx, if I connect to the host with 24bit or 32bit I can see the login screen but after login no image is shown. Just the blue background. And the proper mouse cursor.
If I reconnect to the session with 16bit, I can see my session running as expected.
If I reconnect back with 24bit or 32bit, blue screens with mouse shows again.

Client:
- Windows 10 mstsc
Server:
- Ubuntu 16.0.4.1
- xrdp -> tested branches: devel; noorders; v0.8, master

**Comment by metalefty** [comment] 2016-10-04 15:25
Duplicate of #358.

**Comment by metalefty** [comment] 2016-10-05 00:13
Keep your eyes on 358, closing.

**Closed by metalefty** 2016-10-05 00:13 UTC
Labels: duplicate
