### ISSUE TITLE
sesadmin list IP address error of reconnected 

### ISSUE THREAD

**Issue by tsz8899** [neutrinolabs/xrdp#3134] opened 2024-06-21 10:17 UTC
### xrdp version

0.10

### Detailed xrdp version, build options

~~~
Paste the result between `~~~`.  Please DO NOT remove `~~~`!
~~~

### Operating system & version

debian 12

### Installation method

git clone & make install

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

xfce

### Environment xrdp running on

vm

### What's your client?

freerdp

### Area(s) with issue?

Session manager (sesman)

### Steps to reproduce

After the user session is disconnected, reconnecting can use original Xorg again.

but, if the client IP address changes, sesadmin list still shows the IP address used during the initial connection.

How can accurately obtain client IP address for the current session?

Thank

### ✔️ Expected Behavior

sesadmin can show reconnected client ip

**Comment by matt335672** [comment] 2024-06-24 08:37
@tsz8899 - we're aware of this one. It's effectively a duplicate of #2627 / #2415.

The IP address is logged on a reconnection, but currently there's no way to reliably get the address into the session.

**Closed as completed by matt335672** 2024-06-24 08:37 UTC
Labels: bug
