### ISSUE TITLE
Issue : missing libvnc.so on the release 0.9.22-3

### ISSUE THREAD

**Issue by gjk20000157** [neutrinolabs/xrdp#2683] opened 2023-05-17 12:03 UTC
OS          : Rockylinux 8
Package : xrdp release 0.9.21-1 to 0.9.22-3.x86_64

After the update, we are facing an connection issue with this error : 
Error loading libvnc.so specified in xrdp.ini, please add valid entry like lib=libxrdp-vnc.so or similar.

The libvnc.so librarie was provided by the package xrdp release 0.9.21-1 and disapear from the last one.
Let me know why this package stop to provide this library and which package have to do it.
The issue is present on centos7, RL8 & RL9
Thanks.

**Comment by strawhatAravind** [comment] 2023-05-17 12:13
I am also getting that error in RHEL 9. @gjk20000157 do you know how to get the last working version?
Thanks

**Comment by gjk20000157** [comment] 2023-05-17 12:34
The xrdp released 0.9.21-1 ( same release between RL8 & RL9 ) was working fine.

I just copy the file /usr/lib64/xrdp/libvnc.so from this release to the last one, and it solved the issue.
So my question is why the librarie disapeared, if it's normal/logical and if there another package to install it.

**Comment by strawhatAravind** [comment] 2023-05-17 12:54
@gjk20000157 Thanks I copied libvnc.so file to /usr/lib64/xrdp and it worked. But I don't know the reason for the missing file.

**Comment by matt335672** [comment] 2023-05-17 13:30
Duplicate of #2678 and #2680 

This is an EPEL issue and not related to our team.

Please add further comments to #2678.

**Closed as completed by matt335672** 2023-05-17 13:30 UTC
Labels: duplicate
