### ISSUE TITLE
Parallels Client is not able to RDP to xRDP

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [neutrinolabs/xrdp#439] opened 2016-10-12 09:40 UTC
Parallels Client, a RDP client for Android, iPhone and Windows Phone, is unable to RDP to xRDP.
Already tried noorders branch without success.

**Comment by Natureshadow** [comment] 2016-10-12 11:48
Any chance they share codebases with Microsoft's client?

What is the exact thing that happens when you try to connect?

**Comment by ricardoteixeiraduarte** [comment] 2016-10-12 12:38
The Windows Client does share code, and works fine. All the other clients use their own implementation. 
I can connect to all my RDP servers (NLA, TLS, RDP) without a problem.

xrdp-sesman is never called.

Also setup TLS within xrdp, but the problem remains.

The log:
`
[20161012-13:35:17] [INFO ] A connection received from: 0.0.0.0 port 52338
[20161012-13:35:17] [INFO ] An established connection closed to endpoint: 0.0.0.0:52338 - socket: 11
[20161012-13:35:17] [INFO ] An established connection closed to endpoint: NULL:NULL - socket: 10
[20161012-13:35:17] [CORE ] WARNING: Invalid x.509 certificate path defined, default path will be used: /etc/xrdp/cert.pem
[20161012-13:35:17] [WARN ] Invalid X.509 certificate path defined, default path will be used: /etc/xrdp/key.pem
pub_mod bytes 256
pri_exp 256
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x000f (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x0225 (0x0002 want32)
got client client connection type 0x00000006
xrdp_sec_process_mcs_data_CS_SECURITY:
  client supports 40 bit encryption
  client supports 128 bit encryption
  client supports 56 bit encryption
  client supports fips encryption
  client and server support high crypt, using high crypt
xrdp_sec_out_mcs_data: using 2048 bit RSA key
xrdp_load_keyboard_layout:
xrdp_load_keyboard_layout: model [] variant [] layout [us]
xrdp_sec_establish_keys:
xrdp_caps_process_order: bitmap cache v3 supported
xrdp_caps_process_pointer: client supports new(color) cursor
xrdp_caps_process_codecs: nscodec codec id 1 prop len 3
unknown in xrdp_caps_process_confirm_active 27
unknown in xrdp_caps_process_confirm_active 28
xrdp_caps_process_frame_ack:
  max_unacknowledged_frame_count 0
yeah, up_and_running
[20161012-13:35:17] [DEBUG] xrdp_00002a57_wm_login_mode_event_00000001
xrdp:xrdp_mm [3101935351]: xrdp_mm_create: bpp 16 mcs_connection_type 6 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 0 h264_codec_id 0
[20161012-13:35:17] [WARN ] local keymap file for 0x0409 found and doesn't match built in keymap, using local keymap file
xrdp_wm_login_mode_changed: login_mode is 0
in xrdp_wm_init:
out xrdp_wm_init:
[20161012-13:35:17] [INFO ] An established connection closed to endpoint: 0.0.0.0:52338 - socket: 11
xrdp_mcs_disconnect - socket closed
[20161012-13:35:17] [DEBUG] xrdp_mm_module_cleanup
xrdp:xrdp_encoder [3101935377]: xrdp_encoder_delete:
[20161012-13:35:17] [ERROR] Listening socket is in wrong state we terminate listener
`

**Comment by ricardoteixeiraduarte** [comment] 2016-10-12 13:29
Got a bit further. 
If I disable fastpath, the client connects but the display is somehow garbled. 
I can see some gui, but it is mostly a black screen.

rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 1 rect_id_ack 0
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpRRGetPanning: 0x56324d7044c0
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRRGetPanning: 0x56324d7044c0
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpInDeferredUpdateCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1
rdpDeferredUpdateCallback: reschedual rect_id 2 rect_id_ack 1

**Comment by Natureshadow** [comment] 2016-10-12 13:34
I guess Parallels uses the new Microsoft RDP code and this is another duplicate of #246.

**Comment by ricardoteixeiraduarte** [comment] 2016-10-12 14:18
Shouldn't the noorders branch fix it?
I still get the same garbled display with it.

**Comment by Natureshadow** [comment] 2016-10-12 14:48
It seems to be supposed to fix it. So if your issue is the same as #246, this indicates the fix is incomplete - or that the issue is not the same ;).

**Comment by ricardoteixeiraduarte** [comment] 2016-10-12 14:59
Just tried XRDP-rh-matic with the noorders and it does work.
Still requires fastpath=none and 16bpp tho.

**Comment by Natureshadow** [comment] 2016-10-12 15:06
So this is a duplicate. Please report your findings in #246 :)!

**Comment by ricardoteixeiraduarte** [comment] 2016-10-12 16:10
Keyboard also does not work.

**Comment by metalefty** [comment] 2016-10-13 06:43
Recently, fix on fastpath has been made (409878666fcab91092dd72b554dad7eafb564966).
Cherry-pick it to noorders branch, does keyboard work?

**Comment by ricardoteixeiraduarte** [comment] 2016-10-13 08:30
Already had tried it yesterday.
Unfortunatelly it still does not work with that patch.

**Comment by ricardoteixeiraduarte** [comment] 2016-10-13 09:57
Some updates:

- fastpath=input allows the client to connect. fastpath=output or fastpath=both does not
- With fastpath=input the "enter" key works. alphanumeric do not work
- Running "xev" I can see that no events for those non-working keys are received

**Comment by jsorg71** [comment] 2016-10-13 17:00
I think this is because the client is using unicode input only.  xrdp(and X11) implements keysyms / keycodes so we have to simulate or use some IME method.
We should create a new issue for this since it's connecting and drawing now.

**Comment by jsorg71** [comment] 2016-10-13 17:14
This is the Unicode input event(not implemented).
https://msdn.microsoft.com/en-us/library/cc240585.aspx
This is the Keyboard input event(implemented).
https://msdn.microsoft.com/en-us/library/cc240584.aspx

If you look in xrdp/xrdp_wm.c function callback() about line 1700.
The switch statement needs to handle 5(INPUT_EVENT_UNICODE).

**Comment by ricardoteixeiraduarte** [comment] 2016-10-13 18:58
As far as I can see, it never reaches the callback function.

xrdp_process_data_in
in xrdp_rdp_recv
 in xrdp_sec_recv
  in xrdp_mcs_recv
  out xrdp_mcs_recv
 in xrdp_sec_recv flags $8
 out xrdp_sec_recv
out (4) xrdp_rdp_recv
libxrdp_process_data code 7
xrdp_rdp_process_data code 28
in xrdp_rdp_process_data_input 1 events
xrdp_process_data_in
xrdp_process_data_in
xrdp_process_data_in
in xrdp_rdp_recv
 in xrdp_sec_recv
  in xrdp_mcs_recv
  out xrdp_mcs_recv
 in xrdp_sec_recv flags $8
 out xrdp_sec_recv
out (4) xrdp_rdp_recv
libxrdp_process_data code 7
xrdp_rdp_process_data code 28
in xrdp_rdp_process_data_input 1 events
xrdp_process_data_in
xrdp_process_data_in
xrdp_process_data_in
in xrdp_rdp_recv
 in xrdp_sec_recv
  in xrdp_mcs_recv
  out xrdp_mcs_recv
 in xrdp_sec_recv flags $8
 out xrdp_sec_recv
out (4) xrdp_rdp_recv
libxrdp_process_data code 7
xrdp_rdp_process_data code 28
in xrdp_rdp_process_data_input 1 events
xrdp_process_data_in
xrdp_process_data_in

**Comment by ricardoteixeiraduarte** [comment] 2016-10-13 21:34
@jsorg71 you are correct.
I should have a working patch by tomorrow.

**Comment by speidy** [comment] 2016-10-15 08:51
Even its not implemented, I don't see why its a totally an xrdp issue.
we didn't advertise RDP_INPUT_UNICODE flag to client in caps so client should not do unicode.

**Comment by Natureshadow** [comment] 2016-10-15 08:54
Am 15. Oktober 2016 10:51:10 MESZ, schrieb Idan Freiberg <notifications@github.com>:
>Even its not implemented, I don't see why its a totally an xrdp issue.
>we didn't advertise RDP_INPUT_UNICODE flag to client in caps so client
>should not do unicode.

Now these are true words :D.

Unfortunately, the average user won't care whether their proprietary client adheres to protocols :(.

**Comment by macdanger** [comment] 2016-12-24 16:07
hi guys,

first of all: marry christmas :)
and thanks for your incredible work !
I m using the devel branch on ubuntu 16.10 and also am unable to connect using the parallels client (iOS in this case).
I tried the workarounds using fastpath=none and 16bpp : I can connect but the dispay is completely garbled and unusable. I could provide a screenshot if that help. Using more than 16bpp results in a black screen.
And using Jump Desktop I cant connect at all but for this I will open a new bug.

I have problem with a windows rdp client (w7 and w10) and its fast (remotefx)

I compiled using these parameters:
./configure --enable-fuse --enable-opus --enable-xrdpdebug --enable-rfxcodec --enable-mp3lame --enable-pixman --enable-painter --disable-ipv6 --enable-tjpeg

cheers and nice holidays
markus

**Comment by ricardoteixeiraduarte** [comment] 2016-12-24 16:41
@macdanger you should use the noorders branch

**Comment by proski** [comment] 2016-12-24 17:09
Really? Is is still relevant? All the code from the noorders branch was merged into devel and master branches, and it's part of the 0.9.1 release. I actually checked at one point if all patches were merged. One was missing, it affected Parallels Client for Mac OS, so I submitted it (#557), and it's part of the release as well. `--enable-painter` should enable that functionality.

I can only use Parallels Client on Mac OS if bitmap compression and audio redirection are both disabled. Parallels Client for Android doesn't work for me at all. Generally, Parallels Client is very configurable, but also very picky. I think we should have separate issues for every platform, as the issues and the workarounds are not the same.

**Comment by macdanger** [comment] 2016-12-28 01:05
Ok, I tried with the noorders branch, just to be sure... but I cant get it working. At least with the noorders branch I can connect (needs ages) when using max_bpp=16 and use_fastpath=input.
But it is not usable at all. I can see some parts of the screen and the rest is blank.
With max_bpp=24 or 32 the connection just hangs. With max_bpp=16 I get messages like this:
error in xrdp_cache_add_bitmap, too big(8192) bpp 16

Maybe that helps.

**Comment by proski** [comment] 2016-12-28 19:41
The fix for fastpath synchronization is in the devel branch but not in the noorders branch. The noorders branch is dead, it existed for a specific task that has been completed. It should be removed now.

**Comment by macdanger** [comment] 2017-01-02 17:18
ok, I played a bit with the parallels iOS client (new one, not legacy). It will work when I select "Standard" under the acceleration config and then select 8bpp (256 colors).
Also I have to disable audio playback.

**Comment by macdanger** [comment] 2017-01-08 22:28
just tested with #615 on top of todays devel branch. I don't know if its because of #615 or any other commits from the last week but now I can connect even with 32bit color and fast path and it seems using remotefx. No audio though.

**Comment by metalefty** [comment] 2017-07-05 09:30
Except for audio problem, Parallels Client can connect to xrdp now.

**Closed by metalefty** 2017-07-05 09:30 UTC
Labels: client
