### ISSUE TITLE
Windows 10 2004 update broke the ability to connect to XRDP-based hosts

### ISSUE THREAD

**Issue by lamune6809** [neutrinolabs/xrdp#1618] opened 2020-06-25 04:17 UTC
While this isn't an XRDP issue I did want to raise awareness. Something changed in the RDP client with the 2004 update to Windows 10 and I can no longer connect to XRDP clients on any machine that has taken this update. The behavior observed is the session starts normally, but when it connects and the debug display shows the steps, it will get to the "connecting to 127.0.0.1 5910", hang, and then say 'error - problem connecting'. Using a machine that hasn't yet taken this update results in a normal connection.

I've looked at some log files I've found, but I'm unclear as to why this behavior is observed. If I understand the workflow correctly at this step the VNC session should be started on that port- however monitoring the system I see no VNC session being launched.

If someone could tell me what to look for I can share whatever I find to try and understand why an apparent change in the mstsc behavior is causing this particular problem.

The xrdp clients are running on Centos6.10.

**Comment by metalefty** [comment] 2020-06-25 04:58
It looks like a server issue rather than the client issue. Because you see "connecting to 127.0.0.1 5910" screen. It is CONNECTED.  Updating to Windows 2004 doesn't matter.

![スクリーンショット 2020-06-25 13 54 14](https://user-images.githubusercontent.com/941609/85656171-6c5faa00-b6eb-11ea-95dd-f5263f564881.png)


If  it is the client side issue, you should see error messages at the client side like this:

![39675643-166e3bca-5199-11e8-91ef-44ae274480f8](https://user-images.githubusercontent.com/941609/85656596-e728c500-b6eb-11ea-89a2-8428095f87e9.jpg)

![スクリーンショット 2020-06-25 13 56 28](https://user-images.githubusercontent.com/941609/85656470-be083480-b6eb-11ea-8e0b-1c9978b24b7b.png)

**Comment by metalefty** [comment] 2020-06-25 05:00
You should confirm the issue with 2004 update and older revision of Windows 10.

If the issue occurs only on the 2004 update, I assume the issue is definitely occurred by 2004 update.

**Comment by lamune6809** [comment] 2020-06-25 05:25
I should have posted this in earlier of what the 2004 clients do when attempting to connect.

![Capture](https://user-images.githubusercontent.com/67404336/85659358-501b2900-b669-11ea-8b92-e044f6d57630.PNG)

The problem started immediately after the 2004 update. No clients running 2004 can connect, all clients pre-2004 update connect normally (same network, same targets) so the problem is a change made in this update. I just don't seem to be able to find any log on the server side that might explain why.

**Comment by matt335672** [comment] 2020-06-25 10:29
Hi @lamune6809 

I've got the Windows 2004 update installed, and I'm not seeing the behaviour you describe. That's with a modern version of XRDP.

I've had a look online for changes to mstsc.exe version  "10.0.19041.1" and I can't find anything significant.

I don't have a VM running CentOS 6.x to hand I'm afraid. What version of XRDP are you running?

I'll take a guess you're running the EPEL one (0.6.1-5) which is fairly ancient. Please correct me if I'm wrong. If so, you could try one of the following:-
- Build a more modern version of XRDP yourself from source. This may not be straightforward, as CentOS 6.x is fairly ancient now.
- Copy `c:\Windows\system32\mstsc.exe` from a working copy of Windows 10 to a 2004 installation (use a different directory), and try that.

If you really want to get a log, one way to do it on CentOS 6.x would be:-
- Stop `xrdp-sesman`
- Run it in a terminal (as root) with `sudo xrdp-sesman -n`
- Try to connect again. You should at least see sesman trying to start the X server.

I hope that's of some use - let us know how you get on.

**Comment by lamune6809** [comment] 2020-06-25 22:54
Thanks. That is useful- here's what xrdp-sesman says when I attempt the connection from a 2004 client

# xrdp-sesman -n
starting sesman in foregroud...
sesman config:
        ListenAddress:            127.0.0.1
        ListenPort:               3350
        EnableUserWindowManager:  1
        UserWindowManager:        startwm.sh
        DefaultWindowManager:     startwm.sh
        AuthFilePath:             disabled
Xvnc parameters:
        Parameter 00                   -bs
        Parameter 01                   -nolisten
        Parameter 02                   tcp
        Parameter 03                   -localhost
        Parameter 04                   -dpi
        Parameter 05                   96
X11rdp parameters:
        Parameter 00                   -bs
        Parameter 01                   -nolisten
        Parameter 02                   tcp
logging configuration:
        LogFile:       /var/log/xrdp-sesman.log
        LogLevel:      4
        EnableSyslog:  0
        SyslogLevel:   4
security configuration:
        AllowRootLogin:       1
        MaxLoginRetry:        4
        No TSUsersGroup defined
        No TSAdminsGroup defined
session configuration:
        MaxSessions:                 10
        X11DisplayOffset:            10
        KillDisconnected:            0
        IdleTimeLimit:               0
        DisconnectedTimeLimit:       0
[20200625-15:23:20] [WARN ] [init:45] libscp initialized
[20200625-15:23:20] [CORE ] starting sesman with pid 3401
[20200625-15:23:20] [INFO ] listening...
[20200625-15:23:25] [INFO ] scp thread on sck 7 started successfully
[20200625-15:23:25] [INFO ] ++ created session (access granted): username root, ip 192.168.69.111:56465 - socket: 7
[20200625-15:23:25] [INFO ] starting Xvnc session...

Xvnc TigerVNC 1.1.0 - built Mar 22 2017 18:06:28
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11704000, The X.Org Foundation

(EE)
Fatal server error:
(EE) Couldn't add screen 0(EE)
[20200625-15:23:34] [ERROR] X server for display 11 startup timeout
[20200625-15:23:34] [INFO ] starting xrdp-sessvc - xpid=3407 - wmpid=3406
xrdp-sessvc: waiting for X (pid 3407) and WM (pid 3406)
xrdp-chansrv [3985915482]: main: app started pid 3414(0x00000d56)
xrdp-chansrv [3985915482]: main: DISPLAY env var set to :11.0
xrdp-chansrv [3985915482]: main: using DISPLAY 11
xrdp-chansrv [3985915482]: channel_thread_loop: thread start
[20200625-15:23:35] [ERROR] X server for display 11 startup timeout
[20200625-15:23:35] [ERROR] another Xserver is already active on display 11
[20200625-15:23:35] [DEBUG] aborting connection...
xrdp-sessvc: WM is dead (waitpid said 3406, errno is 0) exiting...
xrdp-sessvc: stopping channel server
xrdp-chansrv [3985915722]: term_signal_handler: got signal 15
xrdp-chansrv [3985915722]: channel_thread_loop: g_term_event set
xrdp-chansrv [3985915722]: channel_thread_loop: thread stop
xrdp-chansrv [3985915722]: main: app exiting pid 3414(0x00000d56)
xrdp-sessvc: stopping X server
xrdp-sessvc: clean exit
[20200625-15:23:35] [INFO ] ++ terminated session:  username root, display :11.0, session_pid 3405, ip 192.168.69.111:56465 - socket: 7
^C[20200625-15:25:00] [INFO ] shutting down sesman 1
[20200625-15:25:00] [CORE ] shutting down log subsystem...


And then, with a machine not running 2004:


# xrdp-sesman -n
starting sesman in foregroud...
sesman config:
        ListenAddress:            127.0.0.1
        ListenPort:               3350
        EnableUserWindowManager:  1
        UserWindowManager:        startwm.sh
        DefaultWindowManager:     startwm.sh
        AuthFilePath:             disabled
Xvnc parameters:
        Parameter 00                   -bs
        Parameter 01                   -nolisten
        Parameter 02                   tcp
        Parameter 03                   -localhost
        Parameter 04                   -dpi
        Parameter 05                   96
X11rdp parameters:
        Parameter 00                   -bs
        Parameter 01                   -nolisten
        Parameter 02                   tcp
logging configuration:
        LogFile:       /var/log/xrdp-sesman.log
        LogLevel:      4
        EnableSyslog:  0
        SyslogLevel:   4
security configuration:
        AllowRootLogin:       1
        MaxLoginRetry:        4
        No TSUsersGroup defined
        No TSAdminsGroup defined
session configuration:
        MaxSessions:                 10
        X11DisplayOffset:            10
        KillDisconnected:            0
        IdleTimeLimit:               0
        DisconnectedTimeLimit:       0
[20200625-15:44:41] [WARN ] [init:45] libscp initialized
[20200625-15:44:41] [CORE ] starting sesman with pid 4996
[20200625-15:44:41] [INFO ] listening...
[20200625-15:45:05] [INFO ] scp thread on sck 7 started successfully
[20200625-15:45:05] [INFO ] ++ created session (access granted): username root, ip 192.168.69.69:63292 - socket: 7
[20200625-15:45:05] [INFO ] starting Xvnc session...

Xvnc TigerVNC 1.1.0 - built Mar 22 2017 18:06:28
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11704000, The X.Org Foundation


Thu Jun 25 15:45:05 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5911
 vncext:      created VNC server for screen 0
[20200625-15:45:05] [INFO ] starting xrdp-sessvc - xpid=5142 - wmpid=5141
xrdp-sessvc: waiting for X (pid 5142) and WM (pid 5141)
xrdp-chansrv [3987206233]: main: app started pid 5161(0x00001429)
xrdp-chansrv [3987206233]: main: DISPLAY env var set to :11.0
xrdp-chansrv [3987206233]: main: using DISPLAY 11
xrdp-chansrv [3987206233]: channel_thread_loop: thread start
 Connections: accepted: 127.0.0.1::53648
gnome-session[5233]: WARNING: Could not parse desktop file /root/.config/autostart/xfconf-migration-4.6.desktop: Key file does not have key 'Name'
gnome-session[5233]: WARNING: could not read /root/.config/autostart/xfconf-migration-4.6.desktop
GNOME_KEYRING_SOCKET=/tmp/keyring-hCstbk/socket
SSH_AUTH_SOCK=/tmp/keyring-hCstbk/socket.ssh
GNOME_KEYRING_PID=5249
 SConnection: Client needs protocol version 3.3

Thu Jun 25 15:45:06 2020
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
Cleaned 50 files 9 still live

(polkit-gnome-authentication-agent-1:5282): GLib-GObject-WARNING **: cannot register existing type `_PolkitError'

(polkit-gnome-authentication-agent-1:5282): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
W: main.c: This program is not intended to be run as root (unless --system is specified).

(process:5314): GLib-WARNING **: goption.c:2132: ignoring no-arg, optional-arg or filename flags (8) on option of type 0

(process:5314): GLib-WARNING **: goption.c:2132: ignoring no-arg, optional-arg or filename flags (8) on option of type 0

(process:5314): GLib-WARNING **: goption.c:2132: ignoring no-arg, optional-arg or filename flags (8) on option of type 0

MCS->Xfconf settings migration complete

** Message: applet now removed from the notification area

** (nm-applet:5287): WARNING **: get_all_cb: couldn't retrieve system settings properties: (2) The name org.freedesktop.NetworkManagerSystemSettings was not provided by any .service files.

** (gnome-user-share:5313): WARNING **: gnome-user-share cannot be started as root for security reasons.

** (nm-applet:5287): WARNING **: fetch_connections_done: error fetching system connections: (2) The name org.freedesktop.NetworkManagerSystemSettings was not provided by any .service files.
Initializing nautilus-gdu extension
Initializing nautilus-open-terminal extension
** Message: applet now embedded in the notification area
** Message: applet now removed from the notification area
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888
xrdp-chansrv [3987207685]: send_init_response_message:
xrdp-chansrv [3987207808]: clipboard_init: g_xfixes_event_base 86
xrdp-chansrv [3987207808]: clipboard_init st 1, maj 5 min 0

(nautilus:5278): Gdk-WARNING **: gdkproperty-x11.c:325 invalid X atom: 1610629264

(nautilus:5278): Gdk-WARNING **: gdkproperty-x11.c:325 invalid X atom: 1610648432

So the error as shown is that it thinks a session on display 11 is already running. I can confirm there are no X sessions running on the machine (no VNC, console is in text mode) - this strikes me as strange since it doesn't appear like anything on the client side is broken. I also double checked for stale lockfiles in tmp and nothing appears there either.

I did try copying the mstsc binaries over from another machine, and get the same result from that. So I don't believe based on that result that there's a change in mstsc that's causing this change of behavior.

I did also get the source code for xrdp 0.9.13 since the version on the servers is 0.6.1-5, but I can't even bootstrap it since autoconf is too old.

**Comment by matt335672** [comment] 2020-06-26 09:12
It's a shame about the autoconf, but I can't help feeling you may come across more problems with 0.9.13 on RHEL 6 if you persist with it. Depending on how long you're planning on hanging on to RHEL 6 it may be worth it.

I've had a quick poke around in git. All the 0.9.x versions of XRDP require 2.65 of autoconf. The last version I can see that would build on RHEL 6 (autoconf 2.63) without some hackery would be 0.8.0 which is also pretty old.

Not being able to start the screen suggests to me that you might have a problem with colour depth. Can you check the colour depth settings on the clients for the working and non-working systems?

Failing that, we need to find what parameters are being passed to Xvnc by sesman (again, later versions of XRDP log this).

One way to do this is to create a shim file to do the logging for us, and then call Xvnc from the shim. I don't have a copy of CentOS 6 to hand to check this, but you can try the following:
- Create a file `/usr/local/bin/XvncLogger` with the following contents:-
```
#!/bin/bash

echo "Xvnc parameters : $@" >&2

exec Xvnc "$@"
```
- Change `/etc/xrdp/sesman.ini` to call `/usr/local/bin/XvncLogger`  instead of `Xvnc` when starting the session.

**Comment by lamune6809** [comment] 2020-06-26 17:48
@matt335672 that was very good intuition on the color depth setting. Indeed the clients were all set to use 15 bit color. Changing that to 16 or 24 bit color restored the ability to connect. I'd consider that a fix, 

15 bit connections stopped working from all machines, not just ones that took the 2004 update. It may not be related. Looking at the yum logs I see that XRDP was updated on Jun 15 but that was after I first noticed the problem when the client updated to 2004 on Jun 10. 

In any case, I think switching over to 16 bit is fine for now until these machines get retired. Thanks again all.

**Comment by matt335672** [comment] 2020-06-29 13:06
Glad we found it.

Do you need more help, or can we close this one now?

**Comment by lamune6809** [comment] 2020-06-29 17:21
I think we can close it. But there are two things that stand out (and I do realize they may already have been fixed in newer versions)

- Something changed since these connection profiles have been in use for years. It's unclear what changed.

- If the VNC server was unable to start due to not supporting 15 bit color for some reason, it should log something somewhere. I think the logging and error reporting should be improved. "Problem connecting" is true, but not very helpful, especially when combined with little logging to look against. Nowhere did I see anything that said "15 bit color not supported" or similar which would have been far more useful than silently dying during startup.

**Comment by matt335672** [comment] 2020-06-30 08:10
I agree with both those points.

I can't add anything much on the first. The EPEL 6 version of XRDP (xrdp-0.6.1-5.el6.x86_64.rpm) has a date of 29th October 2016 on my closest mirror which corresponds to the last [Koji build](https://koji.fedoraproject.org/koji/buildinfo?buildID=813515). The obvious change in your overall system is your RDP client but using the previous RDP client shows the same behaviour.

On the second point the Xvnc server is logging the less-than-helpful:-

```
(EE)
Fatal server error:
(EE) Couldn't add screen 0(EE)
```

Later versions of XRDP actually log the command which is used to start the X server. That would have been useful in diagnosing this particular problem. We can maybe make changes our end to harmonise the logging between the two backends which might help in situations like this.

I'll close this in a couple of days unless you feel like adding any other info for anyone else reading the thread.

**Closed** 2020-07-08 07:50 UTC
Labels: question or troubleshoot
