### ISSUE TITLE
[DEBUG] Closed socket 19 (AF_UNIX) - XORGXRDP on  RHEL 7

### ISSUE THREAD

**Issue by sureshkatukuri** [neutrinolabs/xrdp#911] opened 2017-10-13 12:09 UTC
Hello 

I have installed xorgxrdp on rhel 7 
When I put my credentials for Xorg session and click Ok I get blue screen and nothing happens and after some time i am got below on the screen

Connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login successful for display 10
started connceting
conenction problem, giving up
some problem

xrdp log: 

[20171013-07:33:21] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:25] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:28] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:32] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:35] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:39] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:42] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:46] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:49] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:53] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:33:56] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:00] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:03] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:07] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:10] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:14] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:17] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:21] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:24] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:28] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:31] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:35] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:38] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:42] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:45] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:49] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:52] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:56] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:34:59] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:03] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:06] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:10] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:13] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:17] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:20] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:24] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:27] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:31] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:34] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:38] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:41] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:45] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:48] [DEBUG] xrdp_wm_log_msg: connection problem, giving up
[20171013-07:35:48] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-07:35:48] [DEBUG] xrdp_wm_log_msg: some problem
[20171013-07:35:48] [DEBUG] xrdp_mm_module_cleanup
[20171013-07:35:48] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:36746)

Sesman log:

[20171013-07:37:22] [INFO ] A connection received from 127.0.0.1 port 36797
[20171013-07:37:23] [INFO ] ++ created session (access granted): username sethumadhave, ip 172.16.48.44:51567 - socket: 12
[20171013-07:37:23] [INFO ] starting Xorg session...
[20171013-07:37:23] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
[20171013-07:37:23] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6010)
[20171013-07:37:23] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6210)
[20171013-07:37:23] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20171013-07:37:23] [INFO ] calling auth_start_session from pid 16457
[20171013-07:37:23] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20171013-07:37:23] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20171013-07:37:23] [INFO ] setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20171013-07:37:23] [CORE ] waiting for window manager (pid 16458) to exit
[20171013-07:37:23] [CORE ] window manager (pid 16458) did exit, cleaning up session
[20171013-07:37:23] [INFO ] calling auth_stop_session and auth_end from pid 16457
[20171013-07:37:23] [DEBUG] cleanup_sockets:
[20171013-07:37:23] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_10
[20171013-07:37:23] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
[20171013-07:37:23] [INFO ] ++ terminated session:  username sethumadhave, display :10.0, session_pid 16457, ip 172.16.48.44:51567 - socket: 12
[20171013-08:01:21] [INFO ] A connection received from 127.0.0.1 port 37121
[20171013-08:01:21] [INFO ] ++ created session (access granted): username xc7239, ip 172.21                                                                                 .122.86:60612 - socket: 12
[20171013-08:01:21] [INFO ] starting Xvnc session...
[20171013-08:01:21] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
[20171013-08:01:21] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6010)
[20171013-08:01:21] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6210)
[20171013-08:01:21] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20171013-08:01:21] [INFO ] calling auth_start_session from pid 39451
[20171013-08:01:21] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20171013-08:01:21] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20171013-08:01:21] [WARN ] Removing insecure password file /home/xc7239/.vnc/sesman_xc7239                                                                                 _passwd
[20171013-08:01:21] [INFO ] Xvnc :10 -auth .Xauthority -geometry 2560x1600 -depth 32 -rfbau                                                                                 th /home/xc7239/.vnc/sesman_xc7239_passwd:10 -bs -nolisten tcp -localhost -dpi 96
[20171013-08:01:22] [CORE ] waiting for window manager (pid 39452) to exit

Can some one help me to fix this issue?

**Comment by metalefty** [comment] 2017-10-13 12:31
Run this command in the terminal (ex. logged in via ssh) and show me the result.

```
setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

**Comment by sureshkatukuri** [comment] 2017-10-13 12:48
I got below output:

(EE)
Fatal server error:
(EE) Server is already active for display 10
        If this server is no longer running, remove /tmp/.X10-lock
        and start again.
(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE)

**Comment by sureshkatukuri** [comment] 2017-10-13 13:04
tried with display 13

[20171013-09:02:39] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20171013-09:02:40] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20171013-09:02:40] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20171013-09:02:40] [DEBUG] return value from xrdp_mm_connect 0
[20171013-09:02:40] [INFO ] xrdp_wm_log_msg: login successful for display 13
[20171013-09:02:40] [DEBUG] xrdp_wm_log_msg: started connecting
[20171013-09:02:40] [INFO ] lib_mod_log_peer: xrdp_pid=46994 connected to X11rdp_pid=1226 X11rdp_uid=20154 X11rdp_gid=20105 client_ip=172.16.48.44 client_port=55182
[20171013-09:02:40] [DEBUG] xrdp_wm_log_msg: connected ok
[20171013-09:02:43] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:02:44] [ERROR] xrdp_mm_connect_chansrv: connect failed trying again...
[20171013-09:02:44] [DEBUG] Closed socket 20 (AF_UNIX)
[20171013-09:02:47] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:02:48] [ERROR] xrdp_mm_connect_chansrv: connect failed trying again...
[20171013-09:02:48] [DEBUG] Closed socket 20 (AF_UNIX)
[20171013-09:02:50] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:02:52] [ERROR] xrdp_mm_connect_chansrv: connect failed trying again...
[20171013-09:02:52] [DEBUG] Closed socket 20 (AF_UNIX)
[20171013-09:02:54] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:02:56] [ERROR] xrdp_mm_connect_chansrv: connect failed trying again...
[20171013-09:02:56] [ERROR] xrdp_mm_connect_chansrv: error in trans_connect chan
[20171013-09:02:56] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:38036)
[20171013-09:02:56] [DEBUG] Closed socket 12 (AF_INET 172.16.57.161:3389)
[20171013-09:02:56] [DEBUG] xrdp_mm_module_cleanup
[20171013-09:02:56] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:02:56] [DEBUG] Closed socket 20 (AF_UNIX)
[20171013-09:02:56] [ERROR] Listening socket is in wrong state, terminating listener
[20171013-09:02:56] [CORE ] shutting down log subsystem...
[20171013-09:02:57] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:01] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:04] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:08] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:11] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:15] [DEBUG] Closed socket 19 (AF_UNIX)
[20171013-09:03:18] [DEBUG] Closed socket 19 (AF_UNIX)
  
This time different error for above command

_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at ".xorgxrdp.10.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

**Comment by metalefty** [comment] 2017-10-13 13:14
No, do nothing with xrdp at this time. Please forget connecting via RDP right now. Just execute the above command via SSH and please show me result.

**Comment by metalefty** [comment] 2017-10-13 13:22
1. Reboot
2. Execute the above command via SSH but do nothing else

This process doesn't solve the issue but helps to know what's going wrong. This is not the solution but an investigation. We need to know Xorg is properly starting or not.

**Comment by sureshkatukuri** [comment] 2017-10-13 13:22
I am getting the same output

_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at ".xorgxrdp.10.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

**Comment by metalefty** [comment] 2017-10-13 13:23
Same for :20, :21, and else?

**Comment by sureshkatukuri** [comment] 2017-10-13 13:24
OK i will reboot the machine and come back with output for below command 

setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

**Comment by metalefty** [comment] 2017-10-13 13:25
Sorry, I mistakenly deleted my post. Waiting for the result after reboot :)

**Comment by sureshkatukuri** [comment] 2017-10-13 15:23
reboot is not possible at this time, is it possible to troubleshoot without reboot the machine?

**Comment by metalefty** [comment] 2017-10-14 02:44
You should at least show me the result of following command.  You need choose **UNUSED** display number. If you choose UNUSED display number, no need to reboot.

The reason why I told you to reboot is, make display number 10 unused again.  

`setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log`

**Comment by skalteis** [comment] 2017-10-17 07:37
Can confirm on Debian 9.1 and git HEAD. This seems to be a permission problem that comes up when the X server is started by sesman and appears to be related to the rootless X server approach modern distros are using.
A temporary workaround would be editing /etc/X11/Xwrapper.config to re-enable the root-running setup - which has potential security implications!

**Comment by moobyfr** [comment] 2017-10-18 19:58
feel free to close the issue if the problem is solved :)

**Comment by sureshkatukuri** [comment] 2017-10-20 12:37
Thank you very much !

**Closed** 2017-10-20 12:37 UTC

**Comment by SethuMadhavEde** [comment] 2017-10-25 12:41
Even i had same issue, but it doesn't worked for me.

I have installed xorgxrdp on rhel 7.3, When I put my credentials for Xorg session and click Ok I get blue screen and nothing happens and after some time i can see below screen

Connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
login successful for display 20
started connceting
conenction problem, giving up
some problem


[20171025-08:32:50] [DEBUG] xrdp_wm_log_msg: some problem
[20171025-08:32:50] [DEBUG] xrdp_mm_module_cleanup
[20171025-08:32:50] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:36298)
[20171025-08:39:22] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20171025-08:39:22] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20171025-08:39:22] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20171025-08:39:22] [DEBUG] return value from xrdp_mm_connect 0
[20171025-08:39:22] [INFO ] xrdp_wm_log_msg: login successful for display 20
[20171025-08:39:22] [DEBUG] xrdp_wm_log_msg: started connecting
[20171025-08:39:26] [DEBUG] Closed socket 19 (AF_UNIX)
[20171025-08:39:29] [DEBUG] Closed socket 19 (AF_UNIX)
[20171025-08:39:33] [DEBUG] Closed socket 19 (AF_UNIX)

Please help me to fix the issue.

**Comment by wangyouyan** [comment] 2020-01-17 06:35
@metalefty I encountered the same issue that I installed xrdp service with Xorg on CentOS 7.7.1908. I executed the above command and get result as below:
# setpriv --no-new-privs Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System:  3.10.0-957.1.3.el7.x86_64 
Current Operating System: Linux dev-centos7-wanglj21.novalocal 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-1062.9.1.el7.x86_64 root=/dev/mapper/rootvg-lv_root ro crashkernel=auto rd.lvm.lv=rootvg/lv_root rd.lvm.lv=rootvg/lv_swap quiet LANG=en_US.UTF-8
Build Date: 09 August 2019  03:27:09AM
Build ID: xorg-x11-server 1.20.4-7.el7 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Fri Jan 17 14:32:20 2020
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
pci id for fd 13: 1013:00b8, driver (null)
(II) modeset(0): Initializing kms color map for depth 16, 6 bpc.

Could you give me any suggestion？

**Comment by Yang-Richard** [comment] 2020-01-22 04:29
I'm getting the same issue after upgrading to Ubuntu 18.04. From other threads I've read, it seems that this new issue popping up is due to this specific version. I've tried the recommendation shown [here](https://catch22cats.blogspot.com/2018/05/xrdp-blank-screen-with-ubuntu-1804.html), but no luck.

Alas, I am also looking for any suggestions.
