### ISSUE TITLE
bluescreen when loggin in under non root user

### ISSUE THREAD

**Issue by alb2001** [neutrinolabs/xrdp#1371] opened 2019-07-10 16:14 UTC
Hello

My setup is as follows
Ubuntu Server 16.04 from Contabo
Ran dpkg-reconfigure to configure locales and tzdata

Followed these instructions here https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8
Replaced the file packages with xorgxrdp-0.2.10.tar.gz and xrdp-0.9.10.tar.gz instead (newest versions)

Ran dpkg-query --search to find out if I was using hwe suffixed packages

> linux-image-generic-hwe-16.04: /usr/share/doc/linux-image-generic-hwe-16.04/copyright
linux-generic-hwe-16.04: /usr/share/doc/linux-generic-hwe-16.04/changelog.gz
linux-headers-generic-hwe-16.04: /usr/share/doc/linux-headers-generic-hwe-16.04/copyright
linux-generic-hwe-16.04: /usr/share/doc/linux-generic-hwe-16.04/copyright
linux-headers-generic-hwe-16.04: /usr/share/doc/linux-headers-generic-hwe-16.04
linux-image-generic-hwe-16.04: /usr/share/doc/linux-image-generic-hwe-16.04/changelog.gz
linux-image-generic-hwe-16.04: /usr/share/doc/linux-image-generic-hwe-16.04
linux-generic-hwe-16.04: /usr/share/doc/linux-generic-hwe-16.04
linux-headers-generic-hwe-16.04: /usr/share/doc/linux-headers-generic-hwe-16.04/changelog.gz

So I installed xserver-xorg-core-hwe-16.04 and all its dependencies, then installed lubuntu-desktop, then rebooted server

Now all required packages are hwe-16.04 suffixed packages and installed xserver-xorg-dev-hwe-16.04

Compiled xrdp and xorgxrdp as the instructions say, enabled service. Created normal user and added to sudo group. Rebooted server

if I RDP into my server using the root user, the desktop works fine, althought after 10 minutes of inactivity the screen will go black and there's no way I can do anything except restarting the server. I assume it's an issue with the screen saver.

And now the next issue, which won't allow my newly created user to RDP into the server. As I get a blue screen, and the logs are like this:

xrdp.log
> [20190710-17:52:42] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:52:46] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:52:49] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:52:53] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:52:56] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:53:00] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:53:37] [DEBUG] Testing if xrdp can listen on 0.0.0.0 port 3389.
[20190710-17:53:37] [DEBUG] Closed socket 7 (AF_INET 0.0.0.0:3389)
[20190710-17:53:39] [INFO ] starting xrdp with pid 916
[20190710-17:53:39] [INFO ] listening to port 3389 on 0.0.0.0
[20190710-17:54:50] [INFO ] Socket 12: AF_INET connection received from clientip port 11523
[20190710-17:54:50] [DEBUG] Closed socket 12 (AF_INET serverip:3389)
[20190710-17:54:50] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
[20190710-17:54:50] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20190710-17:54:50] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20190710-17:54:50] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20190710-17:54:50] [DEBUG] TLSv1.2 enabled
[20190710-17:54:50] [DEBUG] Security layer: requested 11, selected 1
[20190710-17:54:50] [DEBUG] Closed socket 12 (AF_INET serverip:3389)
[20190710-17:54:51] [INFO ] Socket 12: AF_INET connection received from clientip port 11530
[20190710-17:54:51] [DEBUG] Closed socket 12 (AF_INET serverip:3389)
[20190710-17:54:51] [DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
[20190710-17:54:51] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20190710-17:54:51] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20190710-17:54:51] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20190710-17:54:51] [DEBUG] TLSv1.2 enabled
[20190710-17:54:51] [DEBUG] Security layer: requested 11, selected 1
[20190710-17:54:52] [INFO ] connected client computer name: DESKTOP-B4FA1H5
[20190710-17:54:52] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0x80800000
[20190710-17:54:52] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
[20190710-17:54:52] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
[20190710-17:54:52] [INFO ] adding channel item name drdynvc chan_id 1007 flags 0xc0800000
[20190710-17:54:52] [INFO ] TLS connection established from clientip port 11530: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20190710-17:54:52] [DEBUG] xrdp_00000705_wm_login_mode_event_00000001
[20190710-17:54:53] [INFO ] Loading keymap file /etc/xrdp/km-0000040a.ini
[20190710-17:54:53] [WARN ] local keymap file for 0x0000040a found and doesn't match built in keymap, using local keymap file
[20190710-17:54:58] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20190710-17:54:58] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20190710-17:54:58] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20190710-17:54:58] [DEBUG] return value from xrdp_mm_connect 0
[20190710-17:54:59] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20190710-17:54:59] [DEBUG] xrdp_wm_log_msg: started connecting
[20190710-17:55:02] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:06] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:09] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:13] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:16] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:20] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:23] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:27] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:30] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:34] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:37] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:41] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:44] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:48] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:51] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:55] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:55:58] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:02] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:05] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:09] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:12] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:16] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:19] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:23] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:26] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:30] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:33] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:37] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:40] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:44] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:47] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:51] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:54] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:56:58] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:01] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:05] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:08] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:12] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:15] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:19] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:22] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:26] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:29] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:33] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:36] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:40] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:43] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:47] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:50] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:54] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:57:57] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:01] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:04] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:08] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:11] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:15] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:18] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:22] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:25] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:28] [DEBUG] xrdp_wm_log_msg: connection problem, giving up
[20190710-17:58:28] [DEBUG] Closed socket 19 (AF_UNIX)
[20190710-17:58:28] [DEBUG] xrdp_wm_log_msg: some problem
[20190710-17:58:28] [DEBUG] xrdp_mm_module_cleanup
[20190710-17:58:28] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:44284)

sesman log

> [20190710-17:51:11] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpapi_10
[20190710-17:51:11] [INFO ] ++ terminated session:  username alberto, display :10.0, session_pid 2356, ip clientip:11457 - socket: 12
[20190710-17:53:00] [INFO ] shutting down sesman 1
[20190710-17:53:00] [INFO ] shutting down sesman 1
[20190710-17:53:00] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20190710-17:53:37] [DEBUG] libscp initialized
[20190710-17:53:37] [DEBUG] Testing if xrdp-sesman can listen on 127.0.0.1 port 3350.
[20190710-17:53:37] [DEBUG] Closed socket 1 (AF_INET 127.0.0.1:3350)
[20190710-17:53:37] [INFO ] starting xrdp-sesman with pid 899
[20190710-17:53:37] [INFO ] listening to port 3350 on 127.0.0.1
[20190710-17:54:58] [INFO ] A connection received from 127.0.0.1 port 44284
[20190710-17:54:59] [INFO ] ++ created session (access granted): username alberto, ip clientip:11530 - socket: 12
[20190710-17:54:59] [INFO ] starting Xorg session...
[20190710-17:54:59] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:5910)
[20190710-17:54:59] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6010)
[20190710-17:54:59] [DEBUG] Closed socket 9 (AF_INET 0.0.0.0:6210)
[20190710-17:54:59] [INFO ] calling auth_start_session from pid 1803
[20190710-17:54:59] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20190710-17:54:59] [DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
[20190710-17:54:59] [DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
[20190710-17:54:59] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20190710-17:55:08] [ERROR] X server for display 10 startup timeout
[20190710-17:55:08] [CORE ] waiting for window manager (pid 1823) to exit
[20190710-17:55:09] [ERROR] X server for display 10 startup timeout
[20190710-17:55:09] [ERROR] another Xserver might already be active on display 10 - see log
[20190710-17:55:09] [DEBUG] aborting connection...
[20190710-17:55:09] [CORE ] window manager (pid 1823) did exit, cleaning up session
[20190710-17:55:09] [INFO ] calling auth_stop_session and auth_end from pid 1803
[20190710-17:55:09] [DEBUG] cleanup_sockets:
[20190710-17:55:09] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_socket_10
[20190710-17:55:09] [DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
[20190710-17:55:09] [DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpapi_10
[20190710-17:55:09] [INFO ] ++ terminated session:  username alberto, display :10.0, session_pid 1803, ip clientip:11530 - socket: 12

tried running Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log and got this:
> X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Current Operating System: Linux blabla.server.net 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-4.15.0-54-generic root=UUID=0e4c08f8-d4c2-4b2f-9043-c46c55537275 ro nomodeset
Build Date: 25 October 2018  04:13:49PM
xorg-server 2:1.19.6-1ubuntu4.1~16.04.2 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Wed Jul 10 18:00:45 2019
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7f86d0a4b010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000306e4 bx 0x01020800 cx 0xffba2203 dx 0x1f8bfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpXvInit: depth 24
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpScreenInit: out
rdpmousePreInit: drv 0x561c2cdc57a0 info 0x561c2cf32710, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7f86d0e24cf0
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x561c2cdc5ee0 info 0x561c2d0bc290, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7f86d0c21600
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpSaveScreen:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off

I assume the issue is around here. But haven't been able to find a way to solve it
> [20190710-17:54:59] [INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20190710-17:55:08] [ERROR] X server for display 10 startup timeout
[20190710-17:55:08] [CORE ] waiting for window manager (pid 1823) to exit
[20190710-17:55:09] [ERROR] X server for display 10 startup timeout
[20190710-17:55:09] [ERROR] another Xserver might already be active on display 10 - see log
[20190710-17:55:09] [DEBUG] aborting connection...

All IP addresses and hostnames have been replaced. Thank you.

**Comment by moobyfr** [comment] 2019-07-10 16:50
Please, keep one issue open by problem

I comment here for the screensaver issue

> if I RDP into my server using the root user, the desktop works fine, althought after 10 minutes of inactivity the screen will go black and there's no way I can do anything except restarting the server. I assume it's an issue with the screen saver.


This is perhaps a duplicate of #871


(on debian, I remove now ``/etc/xdg/autostart/light-locker.desktop``)

**Comment by albertocastillo2001** [comment] 2019-07-10 16:53
Thanks

I think I solved one of the issues. I am able to login now using my username

DId so by editing sesman.ini
; Specify the path of non-suid Xorg executable. It might differ depending
; on your distribution and version. The typical path is shown as follows:
;
; Fedora 26 or later    :  param=/usr/libexec/Xorg
; Debian 9 or later     :  param=/usr/lib/xorg/Xorg
; Ubuntu 16.04 or later :  param=/usr/lib/xorg/Xorg
; Arch Linux            :  param=/usr/lib/xorg-server/Xorg
; CentOS 7              :  param=/usr/bin/Xorg or param=Xorg
;
**param=/usr/lib/xorg/Xorg** Default was Xorg

I disabled root login as well and will check if I still have issues with the screensaver. thank you. Will open a new one if needed.

**Comment by albertocastillo2001** [comment] 2019-07-10 18:15
And for the black screen issue after a few minutes (screen saver or locking) I followed this https://lnbu.jimdo.com/turorials/lubuntu/screen-lock-deactivation/

Seems to work for now.

**Comment by matt335672** [comment] 2023-06-15 09:59
This is pretty stale now, so I'm closing it. Feel free to open another issue if this is still a problem.

**Closed by matt335672** 2023-06-15 09:59 UTC
