### ISSUE TITLE
xrdp apt package doesn't work

### ISSUE THREAD

**Issue by chriskuech** [neutrinolabs/xrdp#927] opened 2017-10-29 17:23 UTC
There are known issues with the current apt package that were fixed in newer versions of xrdp; however, the apt package does not contain the latest version of xrdp.  Please release to apt when you publish a new version of xrdp. 

Ideally, xrdp's package should also depend on a working desktop environment, considering reading the GitHub issues, only one or a few desktop environments are expected to work.

Optimizing apt support would significantly ease xrdp adoption, especially considering the rate of unanswered stack exchange posts on xrdp.

**Comment by Natureshadow** [comment] 2017-10-29 17:58
Hi,

> There are known issues with the current apt package that were fixed in
> newer versions of xrdp; however, the apt package does not contain the
> latest version of xrdp. Please release to apt when you publish a new
> version of xrdp.

Yes it does: https://packages.debian.org/sid/xrdp

What is "release to apt" supposed to be, by the way?

Also, please report issues with the Debian package to the Debian BTS.

> Ideally, xrdp's package should also depend on a working desktop
> environment, considering reading the GitHub issues, only one or a few
> desktop environments are expected to work.

No. Also, I saw GNOME, KDE, LXDE, MATE, Cinnamon and icewem working.

> Optimizing apt support would significantly ease xrdp adoption,

Debian has a recent and working version of xrdp on all current releases.

**Comment by metalefty** [comment] 2017-10-29 23:31
> No. Also, I saw GNOME, KDE, LXDE, MATE, Cinnamon and icewem working.

In addition, Xfce, Lumina working.

**Comment by johnarnold** [comment] 2017-11-09 16:56
Until Ubuntu updates, a huge percentage of users are stuck on old versions or trying to build from source.  16.04 LTS, probably the most popular distro in the world has 0.6.1-2 currently ☹️

**Comment by metalefty** [comment] 2017-12-08 00:23
@johnarnold that's true but we, including you, should talk to Ubuntu maintainers.

**Comment by metalefty** [comment] 2017-12-08 00:24
No feedback from the reporter more than 1 month, the issue is not out issue. Closing.

**Closed by metalefty** 2017-12-08 00:24 UTC
Labels: not-our-issue, waiting-feedback
