### ISSUE TITLE
xrdp fails with black screen if pam_namespace is enabled

### ISSUE THREAD

**Issue by mjungowski** [neutrinolabs/xrdp#1482] opened 2020-01-16 22:46 UTC
Running XRDP 0.9.11 on CentOS 7 I am having issues with pam_namespace.so. Basically, as soon as I enable pam_namespace.so in /etc/pam.d/xrdp-sesman XRDP sessions (both Xorg and XVNC) fail with a black screen. After about 5 minutes or so this is what I see in /var/log/xrdp.log:

> [20200116-22:34:10] [DEBUG] xrdp_wm_log_msg: connection problem, giving up
> [20200116-22:34:10] [DEBUG] Closed socket 19 (AF_UNIX)
> [20200116-22:34:10] [DEBUG] xrdp_wm_log_msg: some problem
> [20200116-22:34:10] [DEBUG] xrdp_mm_module_cleanup
> [20200116-22:34:10] [DEBUG] Closed socket 18 (AF_INET 127.0.0.1:44860)

Uncommenting the pam_namespace.so line in my xrdp-sesman pam.d configfile and restarting XRDP immediately restores full XRDP functionality save for polyinstantiation, which is required on this multi-user Linux terminal server. It is working great when users log in via our thin clients using XDMCP and XDM and it's also working great for SSH logins, so I know for sure it's not a PAM issue per se but must be XRDP-related somehow.

I know that it is at least partly working because I can see the proper .X11-unix and .X10-lock files created in _/tmp-inst/system_u:object_r:tmp_t:s0_martin/_ instead of _/tmp_ with pam_namespace.so enabled. However, when logging in from a thin client via XDM or via SSH from a remote machine the polyinstantiated tmp-directory is a different one: _/tmp/system_u:object_r:tmp_t:s0-s0:c0.c1023_martin_. Not sure if that makes a difference or not but I thought I'd mention it either way.

My configuration:

```
[ root @ ebdlsa001 ] ~ > cat /etc/pam.d/xrdp-sesman 
#%PAM-1.0
# Generic Fedora config
auth       include      password-auth
auth	   required		pam_env.so
account    include      password-auth
password   include      password-auth
session    required     pam_selinux.so close
session    required     pam_selinux.so open
session    required     pam_loginuid.so
session    required     pam_namespace.so
session    include       password-auth
```

```
[ root @ ebdlsa001 ] ~ > ls -Z /usr/sbin/xrdp*
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/sbin/xrdp
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/sbin/xrdp-chansrv
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/sbin/xrdp-sesman
```

```
[ root @ ebdlsa001 ] ~ > cat /etc/security/namespace.conf 
# /etc/security/namespace.conf
#
# See /usr/share/doc/pam-*/txts/README.pam_namespace for more information.
/tmp     /tmp-inst/       	level      root,adm
/var/tmp /var/tmp/tmp-inst/   	level      root,adm
```

```
[ root @ ebdlsa001 ] ~ > cat /etc/sysconfig/selinux 
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=permissive
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted
```

Any hints?

**Comment by matt335672** [comment] 2020-01-25 11:55
Hi @mjungowski 
That sounds like a really interesting problem!
I've tried to reproduce it here on CentOS 7. I think the polyinstantiation is working, but it's not something I'm familiar with. I can create files in `/tmp` as a normal user and they're not visible to root's `/tmp` but that's all the testing I've done.

Originally I was getting delays on logging in with XRDP, but not as long as those you describe, and the log-in was successful.  So we've got an unaccounted-for difference which may or may not be a showstopper.

I can't account for a 5 minute delay in waiting for the X server. The code which generates your error above should try for about 30 secs before failing. Here are a couple of suggestions to look into this:-
- Try the other backend to see what happens. So if you're using Xvnc, try Xorg and vice-versa.
- While the 5 minute delay is happening, use 'ps' to see whether the X server is running, or has exited unexpectedly.
- Additional logging will be in the systemd journal. Use the following command to get the last 5 minutes of logging out of the journal:-
```
sudo journalctl -S -300
```

However, you'll need to do more work to get full functionality in any case. The two areas I'm aware of where xrdp uses `/tmp` by default are:-
- Checking if an X server is active by looking for the files the X server creates in `/tmp`
- Communicating between the sysem-level xrdp process and the session-level xrdp-chansrv process. This is done by a shared directory at `/tmp/.xrdp`.

The first of these doesn't look to be an issue, as all the code runs in the context of a PAM session.
The second of these is definitely an issue. As well as a delay while the connection is attempted, useful features like cut-and-paste and remote drives will not be available to you. However, by recompiling XRDP you can work around this. I've recompiled XRDP with `--with-socketdir=/run/xrdp-socks` , and I'm no longer getting delays on logging in. So changing this setting may well be necessary depending on your use cases. 

If you're compiling from scratch, just add `--with-socketdir=/run/xrdp-socks` to the configure command.

If you're using the EPEL RPM it's a bit more complicated, as you'll need to rebuild the RPM. An outline of the process would be:-
- Get the source RPM from an EPEL mirror.
- Install the source RPM on a CentOS machine with `rpm -i <src RPM>`
- `cd ~/rpmbuild`
- edit `SPECS/xrdp.spec` and add `--with-socketdir=/run/xrdp-socks` to the end of the %configure macro.
- build the RPM with `rpmbuild -bb SPECS/xrdp.spec`
- The above command will probably fail due to missing dependencies. Install the missing dependencies with `sudo yum install <whatever>` and retry

Apologies if the above is something you know all about anyway, and I hope this is useful. Please let us know how it goes.

**Comment by mjungowski** [comment] 2020-05-08 18:20
Matt, 

apologies for the late response. I was swamped and did not have the time to look into this any further.

I've already tried switching backends to no avail. I am using the EPEL RPM and will probably have to build xrdp myself in order to get it running properly. I'm assuming you used a self-compiled version when you successfully attempted to login via XRDP with polyinstantiation enabled, correct? It may just be something in the way the EPEL RPM is built and/or configured that prevents this from happening.

I'll keep you posted, thanks a lot for your suggestions and help.

**Comment by mjungowski** [comment] 2020-05-08 20:04
Matt, I can confirm that I was able to successfully enable polyinstantiation including copy & paste by building XRDP from source myself with aforementioned --with-socketdir parameter.

The only additional change I had to make was to adjust the method in /etc/security/namespace.conf from level to user as XRDP ran in a different context and thus the instantiated tmp-directory was different from the one when I logged in via SSH for example, or via XDMCP.

As far as I can tell it is now fully working, thank you very much.

**Comment by matt335672** [comment] 2020-05-11 08:57
That's great - thanks for the feedback.

I've posted bugzilla [BZ#1834178](https://bugzilla.redhat.com/show_bug.cgi?id=1834178) about this - I think it's important enough for downstream to fix.

**Comment by matt335672** [comment] 2020-05-25 08:20
An update which addresses this has been pushed out for Fedora and also for EPEL 7/8 in testing.

See the above link for details.

**Comment by matt335672** [comment] 2020-06-01 06:34
xrdp-0.9.13-2 which fixes this is now in EPEL 7/8 production

**Closed by matt335672** 2020-06-01 06:34 UTC
