### ISSUE TITLE
Have display, but cannot interact.

### ISSUE THREAD

**Issue by jerrywoo96** [neutrinolabs/xrdp#1555] opened 2020-04-22 03:41 UTC
Using Windows 10 RDC to connect to RPI3B (non plus) running Raspbian.
Login successful, Desktop visible, but cannot interact with desktop. Display is updating as time does change.

notes
using default ssh password
using en_sg utf locale
purged "pulseaudio*"
purged bluez

Steps to repoduce:
install raspbian buster desktop build 02-2020
install updates
install xrdp

**Comment by matt335672** [comment] 2021-11-20 08:32
@jerrywoo96  - sorry I didn't pick this up before.

This looks like a duplicate of neutrinolabs/xorgxrdp#164 or possibly #1701 if I'm misunderstanding how you're connecting.

This [post](/neutrinolabs/xorgxrdp/issues/164#issuecomment-784906241) may be significant.

**Closed** 2022-01-14 12:34 UTC
