### ISSUE TITLE
XRDP on Raspberry Pi 3A+ Very Slow/Not Connecting to Windows 10 Remote Desktop

### ISSUE THREAD

**Issue by anwarbashir** [neutrinolabs/xrdp#2303] opened 2022-07-04 22:37 UTC
Hi, 

Up until a few days ago I was using Windows 10 with Remote Desktop to connect to xRDP on my RPi. It was a bit slow but always worked :) I think Microsoft have recently pushed out an update, now I have to wait an about 5 mins before I can even get a login screen and the connection is not as stable. Any ideas on what to do?

**Comment by matt335672** [comment] 2022-07-05 08:12
5 min is way beyond anything reasonable.

Sounds like you need to look at the network between your Windows machine and the rPi. Have a look at tools like iperf which will let you examine bandwidth and packet loss. If you're using a wireless connection, try plugging a cable in instead and see if that helps - wireless is prone to unexpected interference being caused by other items in the home.

**Comment by matt335672** [comment] 2022-08-11 14:51
No further input - closing.

**Closed as completed by matt335672** 2022-08-11 14:51 UTC
