### ISSUE TITLE
various cppcheck findings

### ISSUE THREAD

**Issue by chipitsine** [neutrinolabs/xrdp#1473] opened 2020-01-07 14:35 UTC
```
sesman/chansrv/pcsc/xrdp_pcsc.c:1123:9: warning: Either the condition 'pioRecvPci==0' is redundant or there is possible null pointer dereference: pioRecvPci. [nullPointerRedundantCheck]
sesman/chansrv/pcsc/xrdp_pcsc.c:1125:9: warning: Either the condition 'pioRecvPci==0' is redundant or there is possible null pointer dereference: pioRecvPci. [nullPointerRedundantCheck]
sesman/chansrv/pcsc/xrdp_pcsc.c:1198:26: warning: Either the condition 'mszGroups==NULL' is redundant or there is possible null pointer dereference: mszGroups. [nullPointerRedundantCheck]
xrdp/xrdp_cache.c:366:13: warning: Either the condition 'bitmap!=0' is redundant or there is possible null pointer dereference: bitmap. [nullPointerRedundantCheck]
```

**Comment by matt335672** [comment] 2020-01-14 20:56
Hi @chipitsine 

I'm having problems reproducing exactly what you've got above.

In particular, if I check out v0.9.12 on Ubuntu 18.04.3 I get the following set of errors with `cppcheck -q --force  --enable=warning .`:-

```
[sesman/chansrv/chansrv_fuse.c:1719]: (error) Memory pointed to by 'full_path' is freed twice.
[sesman/chansrv/chansrv_xfs.c:390] -> [sesman/chansrv/chansrv_xfs.c:398]: (warning) Either the condition 'xfs!=NULL' is redundant or there is possible null pointer dereference: xfs.
[sesman/chansrv/chansrv_xfs.c:390] -> [sesman/chansrv/chansrv_xfs.c:399]: (warning) Either the condition 'xfs!=NULL' is redundant or there is possible null pointer dereference: xfs.
[sesman/chansrv/devredir.c:207]: (error) Uninitialized variable: s
[sesman/chansrv/pcsc/xrdp_pcsc.c:1183] -> [sesman/chansrv/pcsc/xrdp_pcsc.c:1198]: (warning) Either the condition 'mszGroups==NULL' is redundant or there is possible null pointer dereference: mszGroups.
[tests/tcp_proxy/main.c:40]: (error) Failed to parse #define
[vrplayer/decoderthread.cpp:33]: (warning) Member variable 'DecoderThread::pktTimer' is not initialized in the constructor.
[vrplayer/decoderthread.cpp:33]: (warning) Member variable 'DecoderThread::playVideo' is not initialized in the constructor.
[vrplayer/decoderthread.cpp:33]: (warning) Member variable 'DecoderThread::playVideoThread' is not initialized in the constructor.
[vrplayer/decoderthread.cpp:33]: (warning) Member variable 'DecoderThread::playAudio' is not initialized in the constructor.
[vrplayer/decoderthread.cpp:33]: (warning) Member variable 'DecoderThread::playAudioThread' is not initialized in the constructor.
[vrplayer/ourinterface.cpp:4]: (warning) Member variable 'OurInterface::demuxMediaThread' is not initialized in the constructor.
[xrdp/xrdp_cache.c:371] -> [xrdp/xrdp_cache.c:366]: (warning) Either the condition 'bitmap!=0' is redundant or there is possible null pointer dereference: bitmap.
[xrdpapi/xrdp-ssh-agent.c:270]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[xrdpvr/xrdpvr.c:918] -> [xrdpvr/xrdpvr.c:926]: (warning) Identical condition 'rv==0', second condition is always false
```
cppcheck is version 1.82

If I run on the latest devel commit I get much the same except the first error has been fixed by your earlier PR.

What platform, cppcheck version and commit are you using to get the above?

**Comment by chipitsine** [comment] 2020-01-14 21:02
Fedora 31. cppcheck-1.89

**Comment by metalefty** [comment] 2020-01-15 01:52
When fixing these findings, priority is roughly like this:
* xrdp/xrdp_cache
* sesman/chansrv/chansrv_{fuse,xfs}
* sesman/chansrv/devredir
* xrdpapi
* tests
* vrplayer
* xrdpvr

Because xr features are hardly used.

**Comment by matt335672** [comment] 2020-01-15 11:12
I've just built and installed cppcheck 1.90 on Ubuntu 18.04.3 with:-

```
make FILESDIR=/usr/local/cppcheck PREFIX=/usr/local
sudo make install FILESDIR=/usr/local/cppcheck PREFIX=/usr/local
```

This version of the program seems even more thorough, and error reporting is improved. Although interestingly, the errors in chansrv_xfs.c (if they are errors) are not reported by this version. This needs investigating in any case.

Run results (using the command above) are summarised below, using the suggested priority order above (xrdp_pcsc is extra). This is against commit ce3633b8076e5428735a72f2777d881bfbd9e458 which at the time of writing is the latest in devel.

I'm proposing to work down through these. When all the fixes are approved and committed to devel we can consider updating the CI to include cppcheck.

@chipitsine - I'm not clear how much you want to be involved with this from this point. I'm happy to just get on with analysing the results and raising the fixes, but if you'd like to contribute that's fine by me!

## xrdp/xrdp_cache.c
```
xrdp/xrdp_cache.c:366:13: warning: Either the condition 'bitmap!=0' is redundant or there is possible null pointer dereference: bitmap. [nullPointerRedundantCheck]
    crc16 = bitmap->crc16;
            ^
xrdp/xrdp_cache.c:371:13: note: Assuming that condition 'bitmap!=0' is not redundant
        if (COMPARE_WITH_CRC32
            ^
xrdp/xrdp_cache.c:366:13: note: Null pointer dereference
    crc16 = bitmap->crc16;
            ^
```
## sesman/chansrv/chansrv_{fuse,xfs}.c
```
sesman/chansrv/chansrv_fuse.c:2540:13: error: Memory pointed to by 'result' is freed twice. [doubleFree]
            free(result);
            ^
sesman/chansrv/chansrv_fuse.c:2536:29: note: Memory pointed to by 'result' is freed twice.
        char * p = (char *) realloc(result,
                            ^
sesman/chansrv/chansrv_fuse.c:2540:13: note: Memory pointed to by 'result' is freed twice.
            free(result);
            ^
```
(See note above regarding chansrv_xfs.c)
## sesman/chansrv/devredir.c
```
sesman/chansrv/devredir.c:207:40: error: Uninitialized variable: s [uninitvar]
        tui64 u64 = (tui64) (tintptr) &s;
                                       ^
```
## sesman/chansrv/pcsc/xrdp_pcsc.c
```
sesman/chansrv/pcsc/xrdp_pcsc.c:1123:9: warning: Either the condition 'pioRecvPci==0' is redundant or there is possible null pointer dereference: pioRecvPci. [nullPointerRedundantCheck]
        pioRecvPci->dwProtocol = GET_UINT32(msg, offset);
        ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1068:26: note: Assuming that condition 'pioRecvPci==0' is not redundant
    if (1 || (pioRecvPci == 0) || (pioRecvPci->cbPciLength < 8))
                         ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1123:9: note: Null pointer dereference
        pioRecvPci->dwProtocol = GET_UINT32(msg, offset);
        ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1125:9: warning: Either the condition 'pioRecvPci==0' is redundant or there is possible null pointer dereference: pioRecvPci. [nullPointerRedundantCheck]
        pioRecvPci->cbPciLength = GET_UINT32(msg, offset);
        ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1068:26: note: Assuming that condition 'pioRecvPci==0' is not redundant
    if (1 || (pioRecvPci == 0) || (pioRecvPci->cbPciLength < 8))
                         ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1125:9: note: Null pointer dereference
        pioRecvPci->cbPciLength = GET_UINT32(msg, offset);
        ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1198:26: warning: Either the condition 'mszGroups==NULL' is redundant or there is possible null pointer dereference: mszGroups. [nullPointerRedundantCheck]
    memcpy(msg + offset, mszGroups, bytes_groups);
                         ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1183:20: note: Assuming that condition 'mszGroups==NULL' is not redundant
    if ((mszGroups == NULL) && (mszReaders == NULL))
                   ^
sesman/chansrv/pcsc/xrdp_pcsc.c:1198:26: note: Null pointer dereference
    memcpy(msg + offset, mszGroups, bytes_groups);
                         ^
```
## xrdpapi/xrdp-ssh-agent.c
```
xrdpapi/xrdp-ssh-agent.c:270:9: warning: %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint]
        fprintf(stderr, "WTSVirtualChannelQuery() returned wrong length %d\n",
        ^
```
## tests/tcp_proxy/main.c
```
tests/tcp_proxy/main.c:40:0: error: Failed to parse #define [preprocessorErrorDirective]
#define
^
```
## vrplayer/decoderthread.cpp
```
vrplayer/decoderthread.cpp:33:16: warning: Member variable 'DecoderThread::pktTimer' is not initialized in the constructor. [uninitMemberVar]
DecoderThread::DecoderThread()
               ^
vrplayer/decoderthread.cpp:33:16: warning: Member variable 'DecoderThread::playVideo' is not initialized in the constructor. [uninitMemberVar]
DecoderThread::DecoderThread()
               ^
vrplayer/decoderthread.cpp:33:16: warning: Member variable 'DecoderThread::playVideoThread' is not initialized in the constructor. [uninitMemberVar]
DecoderThread::DecoderThread()
               ^
vrplayer/decoderthread.cpp:33:16: warning: Member variable 'DecoderThread::playAudio' is not initialized in the constructor. [uninitMemberVar]
DecoderThread::DecoderThread()
               ^
vrplayer/decoderthread.cpp:33:16: warning: Member variable 'DecoderThread::playAudioThread' is not initialized in the constructor. [uninitMemberVar]
DecoderThread::DecoderThread()
               ^
vrplayer/ourinterface.cpp:4:15: warning: Member variable 'OurInterface::demuxMediaThread' is not initialized in the constructor. [uninitMemberVar]
OurInterface::OurInterface(QObject *parent) :
              ^
```

**Comment by matt335672** [comment] 2020-01-16 12:56
Recommended cppcheck invocation is now:-
```
cppcheck -q --force --inline-suppr --enable=warning .
```
This addition of `--inline-suppr` allows current and future regressions of cppcheck to be commented inline, which will be necessary to maintain a cppcheck CI job in the future.

**Comment by matt335672** [comment] 2020-05-19 10:28
cppcheck now built into CI builds.

**Closed by matt335672** 2020-05-19 10:28 UTC
