### ISSUE TITLE
Screen session resize without reconnect

### ISSUE THREAD

**Issue by rootbdfy** [neutrinolabs/xrdp#982] opened 2017-12-22 08:54 UTC
Hello. I use XRDP (v. 0.9.4) + XORGXRDP (v. 0.2.5) with KDE as DE.
It is possible to resize session without  reconnect as it works in windows ?

**Comment by metalefty** [comment] 2017-12-22 08:57
Not implemented yet. Suggessted in #448.

**Comment by metalefty** [comment] 2017-12-22 09:08
Duplicate of #448.

**Closed by metalefty** 2017-12-22 09:08 UTC
Labels: duplicate
