### ISSUE TITLE
possible monitor resize state machine issue

### ISSUE THREAD

**Issue by akarl10** [neutrinolabs/xrdp#2440] opened 2022-11-29 13:29 UTC
As some of you may have already noted FreeRDP currently reworks its state machine.

now there is a regression with the dynamic resolution change (see https://github.com/FreeRDP/FreeRDP/issues/8458 for details)

it seems that xrdp still sends packets (namely pointer updates) after Deactivate All PDU/Demand Active PDU and before its own RDP PDU Type FontList. With the egfx branch applied also the graphics creation request is before the "FontList".

This is probably not in spec.

**Comment by Nexarian** [comment] 2022-11-30 02:25
I don't fully understand what the problem is.

**Comment by jsorg71** [comment] 2022-11-30 06:35
I think this means they don't want any updates between demand active and confirm active which ends with font list.  This makes sense to me and we can block them.
Sure spec does not say you can send updates before font list but does not say you can not.
When we have these unclear doc scenarios we usually fall back to what the MS implementation does.
Blocking the updated are easy but the delayed GFX will take a bit more.

**Comment by akarl10** [comment] 2022-11-30 16:47
yes, extactly what @jsorg71 says.
Now freerdp is more tolerant and logs a warning in such a case.

I personally have not read [MS-RDPBCGR](https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-RDPBCGR/5073f4ed-1e93-45e1-b039-6e30c385867c) spec in detail, but I've implemented some rdp gateway stuff. When implementing EXTAUTH_SSPI_NTLM the spec had some issues too (for example https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsgu/9b57a67a-cd79-41b8-9b0a-05c7d099eb0f says the header for the authentication scheme is Authorization, but in reality it is Rdg-Auth-Scheme, Authorization does not work, https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tsgu/186eb039-464d-416f-b4ff-932e09fce83b says this packet is from server to client where in reality it is used in both directions), so I feel the pain when deciding what to do in cases where the is room for interpretation or even the documentation does not what microsoft's own impementation does.

**Comment by Nexarian** [comment] 2022-11-30 17:51
I'll think about what to do here, then. It sounds like this is also a problem in the devel branch, and isn't unique to GFX. That's a good start to fix it there.

My "reference implementation" that I've been using has mostly been the Mac OS client, because it's the only one that supports resizing completely AND GFX (and they also update it regularly). MSTSC supports GFX and partial full-screen resizing, and the Microsoft App Store client supports resizing but not GFX (RemoteFX only, and hasn't been updated since early 2021). And, more importantly, I have access to Mac OS :). The thing that the Mac OS client was super picky about was the need to disconnect and reconnect the GFX session on every resize. Without that, it goes to a black screen and literally leaks a gigabyte of memory... It's very buggy when you go wrong :)

They also have an Azure specific one that only works if you configure a corporate domain that I don't know how to test, and I also haven't tested on the Android or iOS clients.

Anyway, the resizing workflow does now have a state machine. Most of the state machine manipulation seems to be guided by "this advances when a network request is received" so we don't usually have explicit management of the state machine, but I added that a few months back for resizing specifically.

It would be really nice to have someone on the Microsoft RDP team to talk to about some of this stuff so they can add clarifications to their protocol and/or fix bugs in their own implementation.

**Comment by akarl10** [comment] 2022-11-30 19:43
Agree. Now that the upcoming freerdp's will not have an issue with this I think this issue is not really that urgent anymore so you or anyone who has the knowledge and abilities may look into this with calm (it was never really urgent, but I think working reliably with microsoft rdp clients, rdesktop and freerdp is somewhat important)

**Comment by matt335672** [comment] 2024-03-22 17:55
This was fixed by commit 54acca43cfe85d60f8a8963fe7ac84cd293d5be2, so I'll close this now

**Closed as completed by matt335672** 2024-03-22 17:55 UTC
