### ISSUE TITLE
very small font logging from windows

### ISSUE THREAD

**Issue by gpau2022** [neutrinolabs/xrdp#2456] opened 2022-12-09 08:44 UTC
![image](https://user-images.githubusercontent.com/120170149/206661655-ad140fa3-ae0d-49f6-9198-2854e13d306e.png)

**Comment by metalefty** [comment] 2022-12-09 08:53
The issue is addressed in #2341.

**Comment by matt335672** [comment] 2022-12-09 10:43
I'll also add there's a lot of changes to get this to work. At present there are no plans to back-port these to v0.9.

**Closed as completed by matt335672** 2022-12-09 10:43 UTC
