### ISSUE TITLE
German keyboard's AltGr is not working

### ISSUE THREAD

**Issue by mpicjohn** [neutrinolabs/xrdp#864] opened 2017-09-06 19:32 UTC
Hi everybody,

I ran into a keyboard issue I seem not able to fix:

I'm connecting via freerdp from a Solaris Maschne to an xrdp server (debian 9, xrdp 0.9.1) with german keyboard setting. Keyboard mapping works as expected, but alt-gr is not working at all.

From stating xev on the xrdp server I could fiure out that presing alt-gr provides keycode 113 on the server side.

My  km-00000407.ini file shows Key113 mapped to 65027 which equals 0xfe03 (should match to alt-gr, I guess):

```
grep Key113 /etc/xrdp/km-00000407.ini
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0
```

any suggestions are really appreciated...

thx

Carsten

**Comment by metalefty** [comment] 2017-09-07 00:59
Confirmed your issue but I'm not familiar with German language or keyboard.  So I'm not sure how to confirm German keyboard working fine.  If AltGr+E shows euro sign and the key between T and U is Z (qwertz), it is working fine. Am I correct?

Anyway, I'll try to fix it.

**Comment by metalefty** [comment] 2017-09-07 01:30
Replacing 65027 with 65514 worked for me. Can you confirm?

**Comment by metalefty** [comment] 2017-09-07 05:16
@Natureshadow IIRC, you're in Germany. Can you confirm that too? Please consider backporting to Debian package if it is worth enough to backport.  I'm not sure how AltGr is important for German/European people. Ideally, I should check if AltGr works properly with other European keyboards but anyway let's fix German at this time.

**Comment by mpicjohn** [comment] 2017-09-07 07:53
Hi metalefty, thanks for the quick answer.

German keyboard is indeed qwertz and alt-gr + e should show the Euro sign.
I replaced the mapping for key113 with 65514 and rebooted the machine, but the change seems to not be honoured in any way.

Remote session is called like:

`/usr/local/bin/xfreerdp /u:test /p:test /kbd:0x00000407 /v:sunray-15`

Output from xev in the remote session when pressing alt-gr:

```
KeyPress event, serial 35, synthetic NO, window 0x2c00001,
    root 0x1b5, subw 0x0, time 1176204, (64,104), root:(916,179),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x2c00001,
    root 0x1b5, subw 0x0, time 1176205, (64,104), root:(916,179),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

```

Setting for Key 113 in mapping file:

```
grep Key113 /etc/xrdp/km-00000407.ini
Key113=65514:0
Key113=65514:0
Key113=65514:0
Key113=65514:0
Key113=65514:0
Key113=65514:0
```

**Comment by metalefty** [comment] 2017-09-07 08:22
If you get back to the original `Key113=65027:0`, what xev shows? `ISO_Level3_Shift`?

**Comment by metalefty** [comment] 2017-09-07 08:38
I missed this line. I understand you got keycode 113 on the server side.
> From stating xev on the xrdp server I could fiure out that presing alt-gr provides keycode 113 on the server side.

I misunderstood. Actually, I didn't reproduce your issue. It looks quite a similar situation but I didn't get keycode 113 on the server side because I don't have a true German keyboard.

**Comment by mpicjohn** [comment] 2017-09-07 09:01
Changed the km-00000407.ini file back to:

```
grep Key113 /etc/xrdp/km-00000407.ini
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0
Key113=65027:0

```
... and rebooted the machine, just in case.

xev on the xrdp server side now shows:

```
KeyPress event, serial 38, synthetic NO, window 0x2600001,
    root 0x1b5, subw 0x0, time 180400, (170,-15), root:(876,77),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x2600001,
    root 0x1b5, subw 0x0, time 180484, (170,-15), root:(876,77),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

so, finally no change. It looks like xrdp not accepting the changes in /etc/xrdp/km-00000407.ini

All other german keys (like the infamous Umlauts) ae working like expected.

**Comment by metalefty** [comment] 2017-09-07 09:02
I borrowed German Windows laptop. Finally, I can see the euro sign event by `xev` with km-00000407.ini `Key113=65027:0`. Please forget editing keymap file I commented before. Keep it original.

```
KeyPress event, serial 28, synthetic NO, window 0x800001,
    root 0x25e, subw 0x0, time 89910041, (68,122), root:(70,124),
    state 0x0, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 31, synthetic NO, window 0x800001,
    root 0x25e, subw 0x0, time 89910219, (68,122), root:(70,124),
    state 0x80, keycode 26 (keysym 0x20ac, EuroSign), same_screen YES,
    XLookupString gives 3 bytes: (e2 82 ac) "€"
    XmbLookupString gives 3 bytes: (e2 82 ac) "€"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x800001,
    root 0x25e, subw 0x0, time 89910328, (68,122), root:(70,124),
    state 0x80, keycode 26 (keysym 0x20ac, EuroSign), same_screen YES,
    XLookupString gives 3 bytes: (e2 82 ac) "€"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x800001,
    root 0x25e, subw 0x0, time 89916799, (68,122), root:(70,124),
    state 0x80, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

Also,  I successcully input "µ" with AltGr+m. 
```
KeyPress event, serial 28, synthetic NO, window 0x600001,
    root 0x25e, subw 0x0, time 90508909, (36,120), root:(38,122),
    state 0x0, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 31, synthetic NO, window 0x600001,
    root 0x25e, subw 0x0, time 90509122, (36,120), root:(38,122),
    state 0x80, keycode 58 (keysym 0xb5, mu), same_screen YES,
    XLookupString gives 2 bytes: (c2 b5) "µ"
    XmbLookupString gives 2 bytes: (c2 b5) "µ"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x600001,
    root 0x25e, subw 0x0, time 90509231, (36,120), root:(38,122),
    state 0x80, keycode 58 (keysym 0xb5, mu), same_screen YES,
    XLookupString gives 2 bytes: (c2 b5) "µ"
    XFilterEvent returns: False

KeyRelease event, serial 31, synthetic NO, window 0x600001,
    root 0x25e, subw 0x0, time 90510347, (36,120), root:(38,122),
    state 0x80, keycode 113 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

@Natureshadow Please forget my comment above. I misunderstood the issue. I still have a question to you. Is AltGr working fine for you, too?

**Comment by mpicjohn** [comment] 2017-09-07 09:07
`keycode 113 (keysym 0xfe03, ISO_Level3_Shift)`

is what I see when using xev on the client side

**Comment by mpicjohn** [comment] 2017-09-07 09:09
km-00000407.ini is back to original version...

**Comment by moobyfr** [comment] 2017-09-07 10:51
I use a french keyboard, with the AltGr key, we have several characters which need the AltGr ( @ [ { \ etc...) 
I've tried all combinations of AltGr, there are all working fine, except 
AltGr + j which causes an error on rdesktop side with "no translation for keysym 0xfe61, dead_hook"
AltGr + J -> no translation for keysym 0xfe62, dead_horn
AltGr + V -> no translation for keysym 0xad0, leftsinglequotemark
AltGr + B -> no translation for keysym 0xad1, rightsinglequotemark

(But we never need there chars so noone never complained about them)

**Comment by metalefty** [comment] 2017-09-14 00:17
If you got  `ISO_Level3_Shift` when you typed AltGr, the key properly passed trough by xrdp. I think it is out of area of xrdp responsibility.

**Comment by mpicjohn** [comment] 2017-09-20 13:56
ISO_Level3_Shift is only seen on the client side (where I start the RDP client Programm)...

**Comment by mpicjohn** [comment] 2017-09-20 14:31
OK, investigated further: seems to be related to the xfreerdp client. I will come back when I find the exact reason...

thx

**Comment by metalefty** [comment] 2017-10-10 08:32
Closing. If you find something new about this issue, please leave comments then I'll reopen.

**Closed by metalefty** 2017-10-10 08:32 UTC
Labels: keyboard, waiting-feedback
