### ISSUE TITLE
thinclient_drives and clipboard can't use

### ISSUE THREAD

**Issue by bensilea** [neutrinolabs/xrdp#2748] opened 2023-07-03 05:54 UTC
I decide to post the issue because it bothered me much times during this two years
I'm using xrdp 0.9.22 by xvnc on Gnome, CentOS 7.9.2009, VMWare virtual machine.I updated xrdp 0.9.18->0.9.21->0.9.22 during this two years to try to figure it out,but each version could happen.
It usually happens in this situation:
First day,I use mstsc.exe to start a totally new xrdp session and it works well including thinclient_drives and clipboard.At the end of the day,I keep the mstsc on all the night(It's inconvenient to power on PC every day)
On second day morning,when I power on my screen,I will find that xrdp(mstsc) become to blackscreen.And then I reopen it.This time it will reopen the last session but takes about 10~15 seconds with blankscreen(It's abnormal).And then the thinclient_drives and clipboard doesn't work.I have to close all the applications and log out and log in to recover it.Sometimes I have to reboot.

![image](https://github.com/neutrinolabs/xrdp/assets/12424281/28e5be76-096c-4acb-961c-2ab3f2fabb62)

I searched some issues.Once upon a time,I tried to modify according to https://github.com/neutrinolabs/xrdp/issues/1188#issuecomment-916832338

> echo 300 | sudo tee /proc/sys/net/ipv4/tcp_keepalive_time
echo 10 | sudo tee /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 3 | sudo tee /proc/sys/net/ipv4/tcp_keepalive_probes

It works a peroid of time.So I add it to the /etc/rc.d/rc.local so it will be set each time the centos system start.
But just a few days ago,after an update of the network bandwidth,the problem begin to happen again

Here is some detail:

> [root@localhost log]# systemctl status xrdp
● xrdp.service - xrdp daemon
   Loaded: loaded (/usr/lib/systemd/system/xrdp.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2023-06-30 15:34:55 CST; 2 days ago
     Docs: man:xrdp(8)
           man:xrdp.ini(5)
 Main PID: 2139 (xrdp)
    Tasks: 2
   CGroup: /system.slice/xrdp.service
           ├─ 2139 /usr/sbin/xrdp --nodaemon
           └─58911 /usr/sbin/xrdp --nodaemon
7月 03 10:47:59 localhost.localdomain xrdp[58911]: [INFO ] VNC sending cursor
7月 03 10:47:59 localhost.localdomain xrdp[58911]: [INFO ] VNC connection complete, connected ok
7月 03 10:47:59 localhost.localdomain xrdp[58911]: [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
7月 03 10:47:59 localhost.localdomain xrdp[58911]: [INFO ] connected ok
7月 03 10:48:03 localhost.localdomain xrdp[58911]: [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
7月 03 10:48:07 localhost.localdomain xrdp[58911]: [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
7月 03 10:48:11 localhost.localdomain xrdp[58911]: [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
7月 03 10:48:15 localhost.localdomain xrdp[58911]: [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
7月 03 10:48:15 localhost.localdomain xrdp[58911]: [ERROR] xrdp_mm_chansrv_connect: error in trans_connect chan
7月 03 10:48:15 localhost.localdomain xrdp[58911]: [INFO ] Layout from OldLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)

extract from /var/log/xrdp.log-20230702
> [20230630-15:31:56] [INFO ] starting xrdp with pid 12087
[20230630-15:31:56] [INFO ] address [0.0.0.0] port [3389] mode 1
[20230630-15:31:56] [INFO ] listening to port 3389 on 0.0.0.0
[20230630-15:31:56] [INFO ] xrdp_listen_pp done
[20230630-15:32:13] [INFO ] Received termination signal, stopping the server accept new connections thread
[20230630-15:34:55] [INFO ] starting xrdp with pid 2139
[20230630-15:34:55] [INFO ] address [0.0.0.0] port [3389] mode 1
[20230630-15:34:55] [INFO ] listening to port 3389 on 0.0.0.0
[20230630-15:34:55] [INFO ] xrdp_listen_pp done
[20230630-15:34:58] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.20.81.207 port 57289
[20230630-15:34:58] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230630-15:34:58] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230630-15:34:58] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230630-15:34:58] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20230630-15:34:58] [INFO ] Connected client computer name: PC1-HZ20036929
[20230630-15:34:58] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230630-15:34:58] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230630-15:34:58] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc008 is unknown (ignored)
[20230630-15:34:58] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000804]
[20230630-15:34:58] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20230630-15:34:58] [INFO ] TLS connection established from ::ffff:10.20.81.207 port 57289: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20230630-15:34:58] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230630-15:34:58] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20230630-15:34:58] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230630-15:34:58] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230630-15:34:58] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230630-15:34:58] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230630-15:34:58] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230630-15:34:58] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230630-15:34:58] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20230630-15:34:58] [INFO ] connecting to sesman on 127.0.0.1:3350
[20230630-15:34:58] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230630-15:34:58] [INFO ] sesman connect ok
[20230630-15:34:58] [INFO ] sending login info to session manager. Please wait...
[20230630-15:34:58] [INFO ] xrdp_wm_log_msg: login successful for user root on display 11
[20230630-15:34:58] [INFO ] login successful for user root on display 11
[20230630-15:34:58] [INFO ] loaded module 'libvnc.so' ok, interface size 4064, version 4
[20230630-15:34:58] [INFO ] VNC started connecting
[20230630-15:34:58] [INFO ] VNC connecting to 127.0.0.1 5911
[20230630-15:34:58] [INFO ] VNC tcp connected
[20230630-15:34:58] [INFO ] VNC security level is 2 (1 = none, 2 = standard)
[20230630-15:34:58] [INFO ] VNC password ok
[20230630-15:34:58] [INFO ] VNC sending share flag 
[20230630-15:34:58] [INFO ] VNC receiving server init
[20230630-15:34:58] [INFO ] VNC receiving pixel format
[20230630-15:34:58] [INFO ] VNC receiving name length
[20230630-15:34:58] [INFO ] VNC receiving name
[20230630-15:34:58] [INFO ] VNC sending pixel format
[20230630-15:34:58] [INFO ] VNC sending cursor
[20230630-15:34:58] [INFO ] VNC connection complete, connected ok
[20230630-15:34:58] [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
[20230630-15:34:58] [INFO ] connected ok
[20230630-15:34:59] [INFO ] Layout from OldLayout (geom=3840x1148 #screens=1) : 1804289383:(3840x1148+0+0)
[20230630-15:34:59] [INFO ] Layout from NewLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)
[20230630-18:58:08] [INFO ] Layout from OldLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)
[20230630-18:58:09] [INFO ] Layout from NewLayout (geom=1920x1080 #screens=1) : 0:(1920x1080+0+0)
[20230630-18:58:09] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230630-18:58:09] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20230630-18:58:09] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230630-18:58:09] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230630-18:58:09] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230701-22:59:17] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 24691
[20230701-22:59:17] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-22:59:17] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-22:59:17] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-22:59:23] [ERROR] libxrdp_force_read: bad header length 3
[20230701-22:59:23] [ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
[20230701-22:59:23] [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed
[20230701-22:59:23] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230701-22:59:23] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230701-22:59:23] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 25043
[20230701-22:59:23] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-22:59:23] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-22:59:23] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-22:59:23] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|RDP], selected [SSL]
[20230701-22:59:28] [ERROR] SSL_accept: I/O error
[20230701-22:59:28] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 25414
[20230701-22:59:28] [ERROR] trans_set_tls_mode: ssl_tls_accept failed
[20230701-22:59:28] [ERROR] xrdp_sec_incoming: trans_set_tls_mode failed
[20230701-22:59:28] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230701-22:59:28] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230701-22:59:28] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-22:59:28] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-22:59:28] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-22:59:28] [INFO ] Security protocol: configured [SSL|RDP], requested [RDP], selected [RDP]
[20230701-22:59:28] [ERROR] libxrdp_force_read: header read error
[20230701-22:59:28] [ERROR] Processing [ITU-T T.125] Connect-Initial failed
[20230701-22:59:28] [ERROR] [MCS Connection Sequence] receive connection request failed
[20230701-22:59:28] [ERROR] xrdp_sec_incoming: xrdp_mcs_incoming failed
[20230701-22:59:28] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230701-22:59:28] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230701-22:59:28] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20230701-22:59:28] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20230701-23:01:42] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 33730
[20230701-23:01:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-23:01:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-23:01:42] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-23:01:42] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 33735
[20230701-23:01:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-23:01:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-23:01:42] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-23:01:42] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 33739
[20230701-23:01:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-23:01:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-23:01:42] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-23:01:42] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 33759
[20230701-23:01:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-23:01:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-23:01:42] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-23:01:42] [ERROR] Unsupported [ITU-T T.123] TPKT header version: 129
[20230701-23:01:42] [ERROR] [ITU-T X.224] Connection Sequence: CR-TPDU (Connection Request) failed
[20230701-23:01:42] [ERROR] xrdp_sec_incoming: xrdp_iso_incoming failed
[20230701-23:01:42] [ERROR] xrdp_rdp_incoming: xrdp_sec_incoming failed
[20230701-23:01:42] [ERROR] xrdp_process_main_loop: libxrdp_process_incoming failed
[20230701-23:01:42] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.19.204.64 port 33765
[20230701-23:01:42] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230701-23:01:42] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230701-23:01:42] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230701-23:01:42] [ERROR] libxrdp_force_read: bad header length 3

It seems something went wrong on 2023-07-01 midnight while I didn't use my computer

extract from /var/log/xrdp.log,the time I back to my computer

> [20230703-09:35:25] [ERROR] xrdp_sec_recv: xrdp_mcs_recv failed
[20230703-09:35:25] [ERROR] xrdp_rdp_recv: xrdp_sec_recv failed
[20230703-09:35:25] [ERROR] libxrdp_process_data: xrdp_rdp_recv failed
[20230703-09:35:25] [ERROR] xrdp_process_data_in: xrdp_process_loop failed
[20230703-09:35:30] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.20.81.207 port 49427
[20230703-09:35:30] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230703-09:35:30] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230703-09:35:30] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230703-09:35:30] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20230703-09:35:30] [INFO ] Connected client computer name: PC1-HZ20036929
[20230703-09:35:30] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230703-09:35:30] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230703-09:35:30] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc008 is unknown (ignored)
[20230703-09:35:30] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000804]
[20230703-09:35:30] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20230703-09:35:30] [INFO ] TLS connection established from ::ffff:10.20.81.207 port 49427: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20230703-09:35:31] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230703-09:35:31] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20230703-09:35:31] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230703-09:35:31] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230703-09:35:31] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230703-09:35:31] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:35:31] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:35:31] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230703-09:35:31] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20230703-09:35:31] [INFO ] connecting to sesman on 127.0.0.1:3350
[20230703-09:35:31] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230703-09:35:31] [INFO ] sesman connect ok
[20230703-09:35:31] [INFO ] sending login info to session manager. Please wait...
[20230703-09:35:31] [INFO ] xrdp_wm_log_msg: login successful for user root on display 11
[20230703-09:35:31] [INFO ] login successful for user root on display 11
[20230703-09:35:31] [INFO ] loaded module 'libvnc.so' ok, interface size 4064, version 4
[20230703-09:35:31] [INFO ] VNC started connecting
[20230703-09:35:31] [INFO ] VNC connecting to 127.0.0.1 5911
[20230703-09:35:31] [INFO ] VNC tcp connected
[20230703-09:35:31] [INFO ] VNC security level is 2 (1 = none, 2 = standard)
[20230703-09:35:31] [INFO ] VNC password ok
[20230703-09:35:31] [INFO ] VNC sending share flag
[20230703-09:35:31] [INFO ] VNC receiving server init
[20230703-09:35:31] [INFO ] VNC receiving pixel format
[20230703-09:35:31] [INFO ] VNC receiving name length
[20230703-09:35:31] [INFO ] VNC receiving name
[20230703-09:35:31] [INFO ] VNC sending pixel format
[20230703-09:35:31] [INFO ] VNC receiving name length
[20230703-09:35:31] [INFO ] VNC receiving name
[20230703-09:35:31] [INFO ] VNC sending pixel format
[20230703-09:35:31] [INFO ] VNC sending cursor
[20230703-09:35:31] [INFO ] VNC connection complete, connected ok
[20230703-09:35:31] [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
[20230703-09:35:31] [INFO ] connected ok
[20230703-09:35:35] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:35:39] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:35:43] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:35:47] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:35:47] [ERROR] xrdp_mm_chansrv_connect: error in trans_connect chan
[20230703-09:35:47] [INFO ] Layout from OldLayout (geom=1920x1080 #screens=1) : 0:(1920x1080+0+0)
[20230703-09:35:47] [INFO ] Layout from NewLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)
[20230703-09:36:42] [ERROR] xrdp_sec_recv: xrdp_mcs_recv failed 
[20230703-09:36:42] [ERROR] xrdp_rdp_recv: xrdp_sec_recv failed 
[20230703-09:36:42] [ERROR] libxrdp_process_data: xrdp_rdp_recv failed
[20230703-09:36:42] [ERROR] xrdp_process_data_in: xrdp_process_loop failed
[20230703-09:36:42] [ERROR] SSL_write: I/O error
[20230703-09:36:42] [ERROR] xrdp_iso_send: trans_write_copy_s failed 
[20230703-09:36:42] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20230703-09:36:43] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.20.81.207 port 49438
[20230703-09:36:43] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230703-09:36:43] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230703-09:36:43] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230703-09:36:43] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20230703-09:36:43] [INFO ] Connected client computer name: PC1-HZ20036929
[20230703-09:36:43] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230703-09:36:43] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230703-09:36:43] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc008 is unknown (ignored)
[20230703-09:36:43] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000804]
[20230703-09:36:43] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20230703-09:36:43] [INFO ] TLS connection established from ::ffff:10.20.81.207 port 49438: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20230703-09:36:43] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230703-09:36:43] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20230703-09:36:43] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230703-09:36:43] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230703-09:36:43] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230703-09:36:43] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:36:43] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:36:43] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230703-09:36:43] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20230703-09:36:43] [INFO ] connecting to sesman on 127.0.0.1:3350
[20230703-09:36:43] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230703-09:36:43] [INFO ] sesman connect ok
[20230703-09:36:43] [INFO ] sending login info to session manager. Please wait...
[20230703-09:36:43] [INFO ] xrdp_wm_log_msg: login successful for user root on display 11
[20230703-09:36:43] [INFO ] login successful for user root on display 11
[20230703-09:36:43] [INFO ] loaded module 'libvnc.so' ok, interface size 4064, version 4
[20230703-09:36:43] [INFO ] VNC started connecting
[20230703-09:36:43] [INFO ] VNC connecting to 127.0.0.1 5911
[20230703-09:36:43] [INFO ] VNC tcp connected
[20230703-09:36:43] [INFO ] VNC security level is 2 (1 = none, 2 = standard)
[20230703-09:36:43] [INFO ] VNC password ok
[20230703-09:36:43] [INFO ] VNC sending share flag
[20230703-09:36:43] [INFO ] VNC receiving server init
[20230703-09:36:43] [INFO ] VNC receiving pixel format
[20230703-09:36:43] [INFO ] VNC receiving name length
[20230703-09:36:43] [INFO ] VNC receiving name
[20230703-09:36:43] [INFO ] VNC sending pixel format
[20230703-09:36:43] [INFO ] VNC sending cursor
[20230703-09:36:43] [INFO ] VNC connection complete, connected ok
[20230703-09:36:43] [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
[20230703-09:36:43] [INFO ] connected ok
[20230703-09:36:47] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:36:51] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:36:55] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:36:59] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:36:59] [ERROR] xrdp_mm_chansrv_connect: error in trans_connect chan
[20230703-09:36:59] [INFO ] Layout from OldLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)
[20230703-09:58:47] [ERROR] xrdp_sec_recv: xrdp_mcs_recv failed
[20230703-09:58:47] [ERROR] xrdp_rdp_recv: xrdp_sec_recv failed
[20230703-09:58:47] [ERROR] libxrdp_process_data: xrdp_rdp_recv failed
[20230703-09:58:47] [ERROR] xrdp_process_data_in: xrdp_process_loop failed
[20230703-09:58:47] [ERROR] SSL_write: I/O error
[20230703-09:58:47] [ERROR] xrdp_iso_send: trans_write_copy_s failed
[20230703-09:58:47] [ERROR] Sending [ITU T.125] DisconnectProviderUltimatum failed
[20230703-09:58:52] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:10.20.81.207 port 55182
[20230703-09:58:52] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20230703-09:58:52] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20230703-09:58:52] [WARN ] TLSv1.3 enabled by config, but not supported by system OpenSSL
[20230703-09:58:52] [INFO ] Security protocol: configured [SSL|RDP], requested [SSL|HYBRID|HYBRID_EX|RDP], selected [SSL]
[20230703-09:58:52] [INFO ] Connected client computer name: PC1-HZ20036929
[20230703-09:58:52] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc006 is unknown (ignored)
[20230703-09:58:52] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc00a is unknown (ignored)
[20230703-09:58:52] [WARN ] Received [MS-RDPBCGR] TS_UD_HEADER type 0xc008 is unknown (ignored)
[20230703-09:58:52] [INFO ] xrdp_load_keyboard_layout: Keyboard information sent by the RDP client, keyboard_type:[0x04], keyboard_subtype:[0x00], keylayout:[0x00000804]
[20230703-09:58:52] [INFO ] xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20230703-09:58:52] [INFO ] TLS connection established from ::ffff:10.20.81.207 port 55182: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384
[20230703-09:58:52] [INFO ] xrdp_caps_process_pointer: client supports new(color) cursor
[20230703-09:58:52] [INFO ] xrdp_process_offscreen_bmpcache: support level 1 cache size 10485760 MB cache entries 100
[20230703-09:58:52] [INFO ] xrdp_caps_process_codecs: nscodec, codec id 1, properties len 3
[20230703-09:58:52] [WARN ] xrdp_caps_process_codecs: unknown codec id 5
[20230703-09:58:52] [INFO ] xrdp_caps_process_codecs: RemoteFX, codec id 3, properties len 49
[20230703-09:58:52] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:58:52] [WARN ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20230703-09:58:52] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20230703-09:58:52] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20230703-09:58:58] [INFO ] connecting to sesman on 127.0.0.1:3350
[20230703-09:58:58] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20230703-09:58:58] [INFO ] sesman connect ok
[20230703-09:58:58] [INFO ] sending login info to session manager. Please wait...
[20230703-09:58:58] [INFO ] xrdp_wm_log_msg: login successful for user root on display 11
[20230703-09:58:58] [INFO ] login successful for user root on display 11
[20230703-09:58:58] [INFO ] loaded module 'libvnc.so' ok, interface size 4064, version 4
[20230703-09:58:58] [INFO ] VNC started connecting
[20230703-09:58:58] [INFO ] VNC connecting to 127.0.0.1 5911
[20230703-09:58:58] [INFO ] VNC tcp connected
[20230703-09:58:58] [INFO ] VNC security level is 2 (1 = none, 2 = standard)
[20230703-09:58:58] [INFO ] VNC password ok
[20230703-09:58:58] [INFO ] VNC sending share flag
[20230703-09:58:58] [INFO ] VNC receiving server init
[20230703-09:58:58] [INFO ] VNC receiving pixel format
[20230703-09:58:58] [INFO ] VNC receiving name length
[20230703-09:58:58] [INFO ] VNC receiving name
[20230703-09:58:58] [INFO ] VNC sending pixel format
[20230703-09:58:58] [INFO ] VNC sending cursor
[20230703-09:58:58] [INFO ] VNC connection complete, connected ok
[20230703-09:58:58] [INFO ] VNC: Clipboard (if available) is provided by chansrv facility
[20230703-09:58:58] [INFO ] connected ok
[20230703-09:59:02] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:59:06] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:59:10] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:59:14] [WARN ] xrdp_mm_chansrv_connect: connect failed trying again...
[20230703-09:59:14] [ERROR] xrdp_mm_chansrv_connect: error in trans_connect chan
[20230703-09:59:14] [INFO ] Layout from OldLayout (geom=3840x1148 #screens=2) : 0:(1920x1080+1920+68) 1:(1920x1080+0+0)

xrdp-sesman.log
> [20230703-09:35:31] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 42542
[20230703-09:35:31] [INFO ] ++ reconnected session: username root, display :11.0, session_pid 2151, ip ::ffff:10.20.81.207:49427 - socket: 12
[20230703-09:35:31] [ERROR] sesman_data_in: scp_process_msg failed
[20230703-09:35:31] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230703-09:35:31] [INFO ] Starting session reconnection script on display 11: /usr/libexec/xrdp/reconnectwm.sh
[20230703-09:35:31] [INFO ] Process 37675 has exited
[20230703-09:36:43] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 42580
[20230703-09:36:43] [INFO ] ++ reconnected session: username root, display :11.0, session_pid 2151, ip ::ffff:10.20.81.207:49438 - socket: 12
[20230703-09:36:43] [ERROR] sesman_data_in: scp_process_msg failed
[20230703-09:36:43] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230703-09:36:43] [INFO ] Starting session reconnection script on display 11: /usr/libexec/xrdp/reconnectwm.sh
[20230703-09:36:43] [INFO ] Process 38006 has exited
[20230703-09:48:18] [INFO ] starting xrdp-sesman with pid 41492
[20230703-09:58:58] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 43662
[20230703-09:58:58] [INFO ] ++ reconnected session: username root, display :11.0, session_pid 2151, ip ::ffff:10.20.81.207:55182 - socket: 12
[20230703-09:58:58] [ERROR] sesman_data_in: scp_process_msg failed
[20230703-09:58:58] [INFO ] Starting session reconnection script on display 11: /usr/libexec/xrdp/reconnectwm.sh
[20230703-09:58:58] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230703-09:58:58] [INFO ] Process 44662 has exited
[20230703-10:47:59] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 46078
[20230703-10:47:59] [INFO ] ++ reconnected session: username root, display :11.0, session_pid 2151, ip ::ffff:10.20.81.207:56214 - socket: 12
[20230703-10:47:59] [ERROR] sesman_data_in: scp_process_msg failed
[20230703-10:47:59] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230703-10:47:59] [INFO ] Starting session reconnection script on display 11: /usr/libexec/xrdp/reconnectwm.sh
[20230703-10:47:59] [INFO ] Process 58930 has exited

**Comment by matt335672** [comment] 2023-07-03 10:18
@bensilea - you are right. This is a duplicate of #1188 

It's not at all obvious though. I've added a [wiki page](/neutrinolabs/xrdp/wiki/Copy-Paste-and-network-drives-don't-work-on-a-reconnect) about this with a lot more detail, and linked from a couple of other places.

**Closed as completed by matt335672** 2023-07-03 10:18 UTC
