### ISSUE TITLE
Change deprecated constants in xrdpvr.c

### ISSUE THREAD

**Issue by hcoin** [neutrinolabs/xrdp#378] opened 2016-05-19 19:26 UTC
sed -i 's, CODEC_TYPE_VIDEO, AVMEDIA_TYPE_VIDEO,' xrdpvr/xrdpvr.c

sed -i 's, CODEC_TYPE_AUDIO, AVMEDIA_TYPE_AUDIO,' xrdpvr/xrdpvr.c

sed -i 's, PKT_FLAG_KEY, AV_PKT_FLAG_KEY,' xrdpvr/xrdpvr.c

The old constants now generate compile errors. (Ubuntu xenial LTS)

**Comment by metalefty** [comment] 2017-07-28 01:22
Duplicate of #293.

**Closed by metalefty** 2017-07-28 01:22 UTC
Labels: duplicate
