### ISSUE TITLE
clipboard issue

### ISSUE THREAD

**Issue by vamsheerudra** [neutrinolabs/xrdp#841] opened 2017-07-28 08:22 UTC
I am using xrdp ver 0.9.3 with xorgxrdp ver 0.2.3 on RHEL 6 and having issue with clip board.
copy/paste from and to the host machine (running windows 7) to Linux machine stops working when the Linux VM gets locked because of inactivity.

I am using xorg session for connectivity.

Please help.

**Comment by metalefty** [comment] 2017-07-31 04:57
When your clipboard stopped working, is xrdp-chansrv process living?

**Comment by vamsheerudra** [comment] 2017-08-02 04:31
It is:

[root@v5vrudra xrdp]# ps aux | grep xrdp-chansrv
vrudra    1959  0.0  0.0 228156  2212 pts/0    S    00:27   0:00 /usr/local/sbin/xrdp-chansrv
root      2363  0.0  0.0 105372   852 pts/0    S+   00:28   0:00 grep xrdp-chansrv

**Comment by metalefty** [comment] 2017-08-05 13:17
I mismarked duplicate, sorry.

**Comment by xiaocaovc** [comment] 2017-09-01 01:17
The same is true of this version v0.9.3.1

**Comment by Dvbnhbq** [comment] 2018-12-26 13:37
Clipboard seem not to work still. I have `xrdp-chansrc` process living.

**Comment by immae1** [comment] 2020-02-11 15:21
same here.  on ubuntu 16.04

**Comment by matt335672** [comment] 2021-09-09 14:32
This looks like a duplicate of #1188 

It's possible to confirm this by working through [this post](https://github.com/neutrinolabs/xrdp/issues/1188#issuecomment-896743561)

There are some workarounds in the linked thread. Please comment here if appropriate, and we can re-open this if necessary.

**Closed by matt335672** 2021-09-09 14:32 UTC
Labels: clipboard

**Comment by matt335672** [comment] 2021-09-09 14:34
Duplicate of #1188
