### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by shh230** [neutrinolabs/xrdp#1718] opened 2020-11-10 09:37 UTC
[20201110-17:18:50] [INFO ] Socket 11: AF_INET connection received from 10.242.25.190 port 62373
[20201110-17:18:50] [DEBUG] Closed socket 11 (AF_INET 10.242.48.203:3389)
[20201110-17:18:50] [DEBUG] Closed socket 10 (AF_INET 0.0.0.0:3389)
[20201110-17:18:50] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20201110-17:18:50] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20201110-17:18:50] [DEBUG] TLSv1.3 enabled
[20201110-17:18:50] [DEBUG] TLSv1.2 enabled
[20201110-17:18:50] [DEBUG] Security layer: requested 3, selected 1
[20201110-17:18:50] [INFO ] connected client computer name: HIH-L-4407.loca
[20201110-17:18:50] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000
[20201110-17:18:50] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
[20201110-17:18:50] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
[20201110-17:18:51] [INFO ] TLS connection established from 10.242.25.190 port 62373: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
[20201110-17:18:51] [DEBUG] xrdp_0000fcd5_wm_login_mode_event_00000001
[20201110-17:18:51] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:18:51] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:18:51] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20201110-17:18:51] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20201110-17:19:03] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
[20201110-17:19:03] [INFO ] xrdp_wm_log_msg: sesman connect ok
[20201110-17:19:03] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
[20201110-17:19:03] [DEBUG] return value from xrdp_mm_connect 0
[20201110-17:19:03] [INFO ] xrdp_wm_log_msg: login successful for display 10
[20201110-17:19:03] [DEBUG] xrdp_wm_log_msg: started connecting
[20201110-17:19:07] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:11] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:14] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:18] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:21] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:25] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:28] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:32] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:35] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:38] [INFO ] Socket 11: AF_INET connection received from 10.242.25.190 port 62494
[20201110-17:19:38] [DEBUG] Closed socket 11 (AF_INET 10.242.48.203:3389)
[20201110-17:19:38] [DEBUG] Closed socket 10 (AF_INET 0.0.0.0:3389)
[20201110-17:19:38] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20201110-17:19:38] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20201110-17:19:38] [DEBUG] TLSv1.3 enabled
[20201110-17:19:38] [DEBUG] TLSv1.2 enabled
[20201110-17:19:38] [DEBUG] Security layer: requested 3, selected 1
[20201110-17:19:38] [INFO ] connected client computer name: HIH-L-4407.loca
[20201110-17:19:38] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000
[20201110-17:19:38] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
[20201110-17:19:38] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
[20201110-17:19:39] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:39] [INFO ] TLS connection established from 10.242.25.190 port 62494: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
[20201110-17:19:39] [DEBUG] xrdp_0000fcf7_wm_login_mode_event_00000001
[20201110-17:19:39] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:19:39] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:19:39] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20201110-17:19:39] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20201110-17:19:42] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:43] [DEBUG] Closed socket 11 (AF_INET 10.242.48.203:3389)
[20201110-17:19:43] [DEBUG] xrdp_mm_module_cleanup
[20201110-17:19:46] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:49] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:53] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:19:53] [INFO ] Socket 11: AF_INET connection received from 10.242.25.190 port 62534
[20201110-17:19:53] [DEBUG] Closed socket 11 (AF_INET 10.242.48.203:3389)
[20201110-17:19:53] [DEBUG] Closed socket 10 (AF_INET 0.0.0.0:3389)
[20201110-17:19:53] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20201110-17:19:53] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20201110-17:19:53] [DEBUG] TLSv1.3 enabled
[20201110-17:19:53] [DEBUG] TLSv1.2 enabled
[20201110-17:19:53] [DEBUG] Security layer: requested 3, selected 1
[20201110-17:19:53] [INFO ] connected client computer name: HIH-L-4407.loca
[20201110-17:19:53] [INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800000
[20201110-17:19:53] [INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc0000000
[20201110-17:19:53] [INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a00000
[20201110-17:19:54] [INFO ] TLS connection established from 10.242.25.190 port 62534: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
[20201110-17:19:55] [DEBUG] xrdp_0000fd02_wm_login_mode_event_00000001
[20201110-17:19:55] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:19:55] [INFO ] Cannot find keymap file /etc/xrdp/km-00000804.ini
[20201110-17:19:55] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20201110-17:19:55] [WARN ] local keymap file for 0x00000804 found and doesn't match built in keymap, using local keymap file
[20201110-17:19:56] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:00] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: VNC started connecting
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: VNC connecting to 127.0.0.1 5900
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: VNC tcp connected
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: VNC security level is 0 (1 = none, 2 = standard)
[20201110-17:20:02] [DEBUG] VNC Server will disconnect
[20201110-17:20:02] [DEBUG] VNC error 1 after security negotiation
[20201110-17:20:02] [DEBUG] VNC error before sending share flag
[20201110-17:20:02] [DEBUG] VNC error before receiving server init
[20201110-17:20:02] [DEBUG] VNC error before receiving pixel format
[20201110-17:20:02] [DEBUG] VNC error before receiving name length
[20201110-17:20:02] [DEBUG] VNC error before receiving name
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: VNC error - problem connecting
[20201110-17:20:02] [DEBUG] Closed socket 17 (AF_INET 127.0.0.1:62930)
[20201110-17:20:02] [DEBUG] xrdp_wm_log_msg: some problem
[20201110-17:20:02] [ERROR] xrdp_wm_log_msg: Error connecting to: 127.0.0.1
[20201110-17:20:02] [DEBUG] xrdp_mm_module_cleanup
[20201110-17:20:02] [DEBUG] VNC mod_exit
[20201110-17:20:02] [DEBUG] return value from xrdp_mm_connect 1
[20201110-17:20:03] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:07] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:10] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:14] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:17] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:21] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:25] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:28] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:32] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:35] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:39] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:42] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:46] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:49] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:53] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:20:56] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:00] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:03] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:07] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:10] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:14] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:17] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:21] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:24] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:28] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:32] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:35] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:39] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:42] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:46] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:49] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:53] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:21:56] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:00] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:03] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:07] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:10] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:14] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:17] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:21] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:24] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:28] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:31] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:34] [DEBUG] xrdp_wm_log_msg: connection problem, giving up
[20201110-17:22:34] [DEBUG] Closed socket 18 (AF_UNIX)
[20201110-17:22:34] [DEBUG] xrdp_wm_log_msg: some problem
[20201110-17:22:34] [DEBUG] xrdp_mm_module_cleanup
[20201110-17:22:34] [DEBUG] Closed socket 17 (AF_INET 127.0.0.1:62908)
[20201110-17:22:34] [DEBUG] Closed socket 11 (AF_INET 10.242.48.203:3389)
[20201110-17:22:35] [DEBUG] xrdp_mm_module_cleanup

![image](https://user-images.githubusercontent.com/38716757/98654863-cd75da80-2379-11eb-885e-bfd9262e43d3.png)

[xrdp.log](https://github.com/neutrinolabs/xrdp/files/5516207/xrdp.log)

**Comment by matt335672** [comment] 2020-11-10 11:03
The VNC module currently only supports the "VNC authentication" method, or no authentication at all. This message indicates the VNC module and the VNC server could not agree on a security type:-

```
VNC Server will disconnect
```

How are you starting the VNC server? Are you able to change the security type it's using?

**Comment by shh230** [comment] 2020-11-11 01:42
sudo /usr/local/sbin/xrdp

**Comment by matt335672** [comment] 2020-11-11 10:24
@shh230 - the problem seems to be a mismatch between the security types provided by these items:-
- The VNC server. Looking at the information you've presented above, this is something out of the scope of XRDP.
- The VNC module provided by XRDP.

You'll need to reconfigure your VNC server to support the standard "VNC authentication" security type. Until you do this, XRDP will not be able to connect to it.

**Comment by shh230** [comment] 2020-11-11 12:46
I use connect to other RDP server with freeRDP. How to set up RDP server?

**Comment by matt335672** [comment] 2020-11-12 10:41
To use XRDP you need to configure a VNC server on the Mac and then connect to that. It looks like that's what you're trying to do.

However, the server and XRDP must agree on a "security type". XRDP does not support many of these at the moment.

I'm afraid I don't have access to a Mac so I can't tell you what you need to do to make this work. Maybe someone else can help.

**Comment by matt335672** [comment] 2021-01-05 11:54
There's been no movement on this for a couple of months so I'm closing it. Anyone who has more Mac knowledge or experience can still comment here.

**Closed by matt335672** 2021-01-05 11:54 UTC
Labels: question or troubleshoot

**Comment by redragerover** [comment] 2022-12-15 21:21
I believe the issue is the `security level is 0` part.

 I got around this by going into System Preferences -> Sharing
1. make sure Remote Management is checked
2. click Computer Settings in the Remote Management menu
3.  Check "VNC viewers may control screen with password" and set a password
