### ISSUE TITLE
Upgrade to 0.9.22 missing libvnc.so/libxup.so? (xrdp-0.9.22-3.el8.x86_64.rpm)

### ISSUE THREAD

**Issue by jacktar283** [neutrinolabs/xrdp#2680] opened 2023-05-17 08:11 UTC
After upgrading from xrdp-0.9.21-1 to 0.9.22-3 from the Epel repos in Centos8 Streams, it's no longer possible to login via Xorgxrdp or VNC

The xrdp-0.9.22-3.el8.x86_64 rpm package from EPEL does not ship with the files

- /usr/lib64/xrdp/libxup.so
- /usr/lib64/xrdp/libvnc.so

Both of those files are included in the xrdp-0.9.21-1.el8.x86_64 rpm package

The xrdp.ini file contains lib references to libxup.so and libvnc.so under the respective [Xorg] and [Xvnc] configuration blocks (where used)

Have these libs been made redundant in 0.9.22-3 and should those lines now be removed from the configuration block? 
Is the absence of the /usr/lib64/xrdp/libxup.so and /usr/lib64/xrdp/libvnc.so intentional? Are other dependencies now needed in order to use xorgxrdp and/or VNC connections to the xrdp service?

Thanks

**Comment by jjasoncool** [comment] 2023-05-17 08:15
same issue here, but my distro is fedora 38

![圖片](https://github.com/neutrinolabs/xrdp/assets/24731867/ef8156fb-3148-494e-baa1-0e7665400bc8)

**Comment by matt335672** [comment] 2023-05-17 09:07
Duplicate of #2678 

This is an EPEL packaging issue which is fixed in 0.9.22-4

I'm closing this one. Add any other comments to #2678

**Closed as completed by matt335672** 2023-05-17 09:07 UTC
